'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports DevExpress.Xpo

Public Structure INCENUNFUKey
    <Persistent("CODCENATE")>
    Public Property CODCENATE As String

    <Persistent("UFUCODIGO")>
    Public Property UFUCODIGO As String
End Structure

<Persistent("dbo.INCENUNFU")>
Partial Public Class INCENUNFUXpo
    Inherits XPLiteObject

    <Key(), Persistent()>
    Public Property Key As INCENUNFUKey

    <PersistentAlias("ADCENATEN.CODCENATE")>
    Public ReadOnly Property CODCENATE() As String
        Get
            Return Convert.ToString(EvaluateAlias("CODCENATE"))
        End Get
    End Property

    <PersistentAlias("INUNIFUNC.UFUCODIGO")>
    Public ReadOnly Property UFUCODIGO() As String
        Get
            Return Convert.ToString(EvaluateAlias("UFUCODIGO"))
        End Get
    End Property

    Dim fINDAUDFOR As Decimal
    Public Property INDAUDFOR() As Decimal
        Get
            Return fINDAUDFOR
        End Get
        Set(ByVal value As Decimal)
            SetPropertyValue(Of Decimal)("INDAUDFOR", fINDAUDFOR, value)
        End Set
    End Property

    Dim fADCENATEN As CentersXpo
    <Persistent("CODCENATE")>
    <Association("INCENUNFU_References_ADCENATEN")>
    Public Property ADCENATEN() As CentersXpo
        Get
            Return fADCENATEN
        End Get
        Set(ByVal value As CentersXpo)
            SetPropertyValue(Of CentersXpo)("ADCENATEN", fADCENATEN, value)
        End Set
    End Property

    Dim fINUNIFUNC As INUNIFUNCXpo
    <Persistent("UFUCODIGO")>
    <Association("INCENUNFU_References_INUNIFUNC")>
    Public Property INUNIFUNC() As INUNIFUNCXpo
        Get
            Return fINUNIFUNC
        End Get
        Set(ByVal value As INUNIFUNCXpo)
            SetPropertyValue(Of INUNIFUNCXpo)("INUNIFUNC", fINUNIFUNC, value)
        End Set
    End Property

    Public Sub New(ByVal session As Session)
        MyBase.New(session)
    End Sub
End Class
