
--CREATE PROCEDURE [Billing].[SP_ESTADISTICO_INGRESOS]
--	@OperatingUnitCode VARCHAR(20),
--DECLARE	@DateStart DATETIME='2024-05-01'
--DECLARE	@DateEnd DATETIME='2024-05-31';
--AS

CREATE view [Report].[UploadCubeVieRCMAdmissionsStatistician] as

	SELECT DISTINCT CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY,
	CASE p.iptipodoc 
		WHEN 1 THEN 'CC'
		WHEN 2 THEN 'CE'
		WHEN 3 THEN 'TI'
		WHEN 4 THEN 'RC'
		WHEN 5 THEN 'PA'
		WHEN 6 THEN 'AS'
		WHEN 7 THEN 'MS'
		WHEN 8 THEN 'NU'
		WHEN 9 THEN 'CN'
		WHEN 10 THEN 'CD'
		WHEN 11 THEN 'SC' 
		WHEN 12 THEN 'PE' 
		WHEN 13 THEN 'PT'
		WHEN 14 THEN 'DE'
		WHEN 15 THEN 'SI' END AS 'TIPO DOCUMENTO',--[TipoDocumento],
		CASE
			WHEN I.IPCODPACI IS NULL THEN '0'
			ELSE I.IPCODPACI
		END AS 'NRO IDENTIFICACIN',--[NroIdentificacion],
		CASE
			WHEN P.GENEXPEDITIONCITY IS NULL
				AND CI.NAME IS NULL THEN '0 - DESCONOCIDO'
			ELSE CAST(P.GENEXPEDITIONCITY AS VARCHAR(20)) + ' - ' + ISNULL(CI.NAME, '')
		END AS 'LUGAR EXPEDICION',--[LugarExpedicion],
		CASE
			WHEN P.IPNOMCOMP IS NULL THEN 'DESCONOCIDO'
			ELSE P.IPNOMCOMP
		END AS 'PACIENTE',--[Paciente],
		CASE
			WHEN UBINOMBRE IS NULL THEN 'DESCONOCIDO'
			ELSE UBINOMBRE
		END AS 'UBICACION',--[Ubicacion],
		CASE
			WHEN MUNNOMBRE IS NULL THEN 'DESCONOCIDO'
			ELSE MUNNOMBRE
		END AS 'MUNICIPIO',--[Municipio],
		CASE
			WHEN P.IPTELEFON IS NULL
				OR P.IPTELEFON LIKE '' THEN '0'
			ELSE P.IPTELEFON
		END AS 'TELEFONO PRINCIPAL',--[TelefonoPrincipal],
		CASE
			WHEN P.IPTELMOVI IS NULL
				OR P.IPTELMOVI LIKE '' THEN '0'
			ELSE P.IPTELMOVI
		END AS 'TELEFONO ALTERNTIVO',--[TelefonoAlternativo],
		IIF(GA.CODE IS NULL, ISNULL(EA.CODE, '0'), ISNULL(GA.CODE, '0')) AS 'CODIGO GRUPO ATENCION',--[CodigoGrupoAtencion],
		IIF(GA.NAME IS NULL, ISNULL(EA.NAME, 'DESCONOCIDO'), ISNULL(GA.NAME, 'DESCONOCIDO')) AS 'GRUPO ATENCION',--[GrupoAtencion],
		CASE
			WHEN EA.NAME IS NULL THEN 'DESCONOCIDO'
			ELSE EA.NAME
		END AS 'ENTIDAD',--[Entidad],

		CASE
			WHEN I.CODCENATE IS NULL THEN '0'
			ELSE I.CODCENATE
		END AS 'CODIGO CENTRO ATENCION',--[CodigoCentroAtencion],
		CASE
			WHEN AD.NOMCENATE IS NULL THEN 'DESCONOCIDO'
			ELSE AD.NOMCENATE
		END AS 'CENTRO ATENCION',--[CentroAtencion],
		CASE
			WHEN UF.UFUDESCRI IS NULL THEN 'DESCONOCIDO'
			ELSE UF.UFUDESCRI
		END AS 'UNIDAD FUNCIONAL',--[UnidadFuncional],
		I.NUMINGRES AS 'NRO INGRESO',--[NroIngreso],
		ISNULL(I.IFECHAING, TRY_CONVERT(DATETIME, '1900-12-31', 121)) AS 'FECHA INGRESO',--[FechaIngreso],
		CASE MONTH(I.IFECHAING)
			WHEN 1 THEN 'ENERO'
			WHEN 2 THEN 'FEBRERO'
			WHEN 3 THEN 'MARZO'
			WHEN 4 THEN 'ABRIL'
			WHEN 5 THEN 'MAYO'
			WHEN 6 THEN 'JUNIO'
			WHEN 7 THEN 'JULIO'
			WHEN 8 THEN 'AGOSTO'
			WHEN 9 THEN 'SEPTIEMBRE'
			WHEN 10 THEN 'OCTUBRE'
			WHEN 11 THEN 'NOVIEMBRE'
			WHEN 12 THEN 'DICIEMBRE'
			ELSE 'DESCONOCIDO'
		END 'MES INGRESO',--[MesIngreso],
		MONTH(I.IFECHAING) AS 'NRO MES INGRESO',--[NroMesIngreso],
		CASE I.IESTADOIN
			WHEN '  ' THEN 'SIN CONFIRMAR HOJA DE TRABAJO'
			WHEN 'F' THEN 'CONFIRMADA HOJA DE TRABAJO'
			WHEN 'A' THEN 'ANULADO'
			WHEN 'C' THEN 'CERRADO'
			WHEN 'P' THEN 'FACTURADO PARCIAL'
			ELSE 'DESCONOCIDO'
		END AS 'ESTADO INGRESO',--[EstadoIngreso],
		CASE I.TIPOINGRE
			WHEN 1 THEN 'AMBULATORIO'
			WHEN 2 THEN 'HOSPITALARIO'
		END AS 'TIPO INGRESO',--[TipoIngreso],
		CASE I.ICAUSAING
			WHEN '1' THEN 'HERIDOS EN COMBATE'
			WHEN '2' THEN 'ENFERMEDAD PROFESIONAL'
			WHEN '3' THEN 'ENFERMEDAD GENERAL ADULTO'
			WHEN '4' THEN 'ENFERMEDAD GENERAL PEDIATRIA'
			WHEN '5' THEN 'ODONTOLOGÍA'
			WHEN '6' THEN 'ACCIDENTE DE TRANSITO'
			WHEN '7' THEN 'CATASTROFE/FISALUD'
			WHEN '8' THEN 'QUEMADOS'
			WHEN '9' THEN 'MATERNIDAD'
			WHEN '10' THEN 'ACCIDENTE LABORAL'
			WHEN '11' THEN 'CIRUGIA PROGRAMADA'
			ELSE 'DESCONOCIDO'
		END AS 'CAUSA INGRESO',--[CausaIngreso],
		ISNULL(EM.FECALTPAC, TRY_CONVERT(DATETIME, '1900-12-31', 121)) AS 'FECHA ALTA MEDICA',--[FechaAltaMedica],
		CASE
			WHEN I.CODDIAING IS NULL THEN '0'
			ELSE I.CODDIAING
		END AS 'CIE10 INGRESO',--[CIE10Ingreso],
		CASE
			WHEN CIE10.NOMDIAGNO IS NULL THEN 'DESCONOCIDO'
			ELSE CIE10.NOMDIAGNO
		END AS 'DIAGNOSTICO INGRESO',--[DiagnosticoIngreso],
		CASE
			WHEN I.CODDIAEGR IS NULL THEN 'DESCONOCIDO'
			ELSE I.CODDIAEGR
		END AS 'CIE10 EGRESO',--[CIE10Egreso],
		CASE
			WHEN DI.NOMDIAGNO IS NULL THEN 'DESCONOCIDO'
			ELSE DI.NOMDIAGNO
		END AS 'DIAGNOSTICO EGRESO',--[DiagnosticoEgreso],
		ISNULL(SEG2.CODUSUARI, UU.CODUSUARI) 'CODIGO USUARIO CREA INGRESO',--[CodigoUsuarioCreaIngreso],
		ISNULL(SEG2.NOMUSUARI, UU.NOMUSUARI) 'USUARIO CREA INGRESO',--[UsuarioCreaIngreso],
		ISNULL(I.FECREGCRE, TRY_CONVERT(DATETIME, '1900-12-31', 121)) 'FECHA CREACION',--[FechaCreacion],
		CASE
			WHEN I.CODUSUMOD IS NULL THEN '0'
			ELSE I.CODUSUMOD
		END AS 'CODIGO USUARIO MODIFICO',--[CodigoUsuarioModifico],
		CASE
			WHEN UU2.NOMUSUARI IS NULL THEN 'DESCONOCIDO'
			ELSE UU2.NOMUSUARI
		END AS 'USUARIO MODIFICO',--[UsuarioModifico],
		ISNULL(I.FECREGMOD, TRY_CONVERT(DATETIME, '1900-12-31', 121)) AS 'FECHA MODIFICACION',--[FechaModificacion],
		CASE
			WHEN D.UFUDESCRI IS NULL THEN 'DESCONOCIDO'
			ELSE D.UFUDESCRI
		END AS 'UNIDADA FUNCIONAL ACTUAL',--[UnidadFuncionalActual],
		CASE
			WHEN I.IOBSERVAC IS NULL
				OR I.IOBSERVAC LIKE '' THEN 'NO APLICA'
			ELSE I.IOBSERVAC
		END AS 'OBSERVACIONES',--[Observaciones],
		CASE
			WHEN CIE10_ac.NOMDIAGNO IS NULL THEN 'DESCONOCIDO'
			ELSE UPPER(CIE10_ac.NOMDIAGNO)
		END AS 'ENFERMEDAD ACTUAL',--[EnfermedadActual],
		CASE I.ITIPORIES
			WHEN 1 THEN 'ENFERMEDAD GENERAL Y MATERNIDAD'
			WHEN 2 THEN 'ACCIDENTE DE TRANSITO'
			WHEN 3 THEN 'CATASTROFE'
			ELSE 'DESCONOCIDO'
		END AS 'TIPO RIESGO',--[TipoRiesgo],
		CASE
			WHEN EM.FECALTPAC IS NULL THEN 'SIN ALTA MEDICA'
			ELSE 'CON ALTA MEDICA'
		END AS 'INGRESO ALTA MEDICA',--[IngresoAltaMedica],
		--CASE
		--    WHEN EM.FECALTPAC IS NULL THEN 0
		--    ELSE DATEDIFF(DAY, EM.FECALTPAC, GETDATE())
		--END AS 'DIAS_ALTA_MEDICA', --20201127 Regla modificada de acuerdo a reunión con la Dra. Lina Maria Agudelo
		CASE I.IESTADOIN
			WHEN '  ' THEN DATEDIFF(DAY, EM.FECALTPAC, GETDATE())
			WHEN 'F' THEN 0
			WHEN 'A' THEN 0
			WHEN 'C' THEN 0
			WHEN 'P' THEN DATEDIFF(DAY, EM.FECALTPAC, GETDATE())
			ELSE 0
		END AS 'DIAS ALTA MEDICA',--[DiasAltaMedica]
		CAST(I.IFECHAING AS DATE) 'FECHA BUSQUEDA',
		CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUA
	FROM DBO.ADINGRESO AS I WITH (NOLOCK)
	LEFT JOIN DBO.INUNIFUNC AS UF WITH (NOLOCK) ON UF.UFUCODIGO = I.UFUCODIGO
	LEFT JOIN CONTRACT.CAREGROUP AS GA WITH (NOLOCK) ON GA.ID = I.GENCAREGROUP
	LEFT JOIN [Security].[UserINT] AS U WITH (NOLOCK) ON U.USERCODE = I.CODUSUCRE
	LEFT JOIN DBO.SEGUSUARU AS U2 WITH (NOLOCK) ON U2.CODUSUARI = I.CODUSUCRE
	LEFT JOIN [Security].[UserINT] AS UM WITH (NOLOCK) ON UM.USERCODE = I.CODUSUMOD
	LEFT JOIN SECURITY.PERSONINT AS PER WITH (NOLOCK) ON PER.ID = U.IDPERSON
	LEFT JOIN SECURITY.PERSONINT AS PERM WITH (NOLOCK) ON PERM .ID = UM.IDPERSON
	LEFT JOIN DBO.INPACIENT AS P WITH (NOLOCK) ON P.IPCODPACI = I.IPCODPACI
	LEFT JOIN CONTRACT.HEALTHADMINISTRATOR AS EA WITH (NOLOCK) ON EA.ID = I.GENCONENTITY
	LEFT JOIN COMMON.CITY AS CI WITH (NOLOCK) ON CI.ID = P.GENEXPEDITIONCITY
	LEFT JOIN
	( 
		SELECT 
			HC.NUMEFOLIO, HC.NUMINGRES, HC.IPCODPACI, CODDIAGNO FROM DBO.HCHISPACA HC INNER JOIN (SELECT MAX(NUMEFOLIO) NUMEFOLIO, NUMINGRES, IPCODPACI 
		FROM DBO.HCHISPACA GROUP BY NUMINGRES, IPCODPACI ) HC1 ON HC.NUMINGRES=HC1.NUMINGRES AND  HC.NUMEFOLIO=HC1.NUMEFOLIO AND HC.IPCODPACI=HC1.IPCODPACI

	) DA ON I.NUMINGRES=DA.NUMINGRES AND I.IPCODPACI=DA.IPCODPACI --DIAGNOSTICO ACTUAL
	LEFT JOIN DBO.INDIAGNOS AS CIE10 WITH (NOLOCK) ON CIE10.CODDIAGNO = I.CODDIAING
	LEFT JOIN DBO.INDIAGNOS AS CIE10_ac WITH (NOLOCK) ON CIE10_ac.CODDIAGNO = DA.CODDIAGNO
	LEFT JOIN DBO.ADINGRESO AS I2 WITH (NOLOCK) ON I2.NUMINGRES = I.NUMINGRES
	LEFT JOIN DBO.INUNIFUNC AS D WITH (NOLOCK) ON I2.UFUAACTHOS = D .UFUCODIGO
	LEFT JOIN DBO.HCREGEGRE AS EM WITH (NOLOCK) ON EM.IPCODPACI = I.IPCODPACI
	AND EM.NUMINGRES = I.NUMINGRES
	LEFT JOIN (

		SELECT 
			MIN(TRIANUMER) TRIANUMER,
			NUMINGRES,
			MIN(CODCONCEC) CODCONCEC
	   FROM DBO.ADTRIAGEU
	   WHERE CODCONCEC IS NOT NULL
	   GROUP BY NUMINGRES

	) AS ADT ON ADT.NUMINGRES = I.NUMINGRES
	LEFT JOIN DBO.ADCONTURG AS ADCO ON ADT.CODCONCEC = ADCO.CODCONCEC
	LEFT JOIN DBO.SEGUSUARU AS SEG2 ON SEG2.CODUSUARI = ADCO.CODUSUARI
	LEFT JOIN DBO.SEGUSUARU AS UU WITH (NOLOCK) ON UU.CODUSUARI = I.CODUSUCRE
	LEFT JOIN DBO.SEGUSUARU AS UU2 WITH (NOLOCK) ON UU2.CODUSUARI = I.CODUSUMOD
	LEFT JOIN DBO.INUBICACI AS BB WITH (NOLOCK) ON BB.AUUBICACI = P.AUUBICACI
	LEFT JOIN DBO.INMUNICIP AS EE WITH (NOLOCK) ON EE.DEPMUNCOD = BB.DEPMUNCOD
	LEFT JOIN DBO.INDIAGNOS AS DI WITH (NOLOCK) ON I.CODDIAEGR = DI.CODDIAGNO
	LEFT JOIN DBO.ADCENATEN AS AD WITH (NOLOCK) ON I.CODCENATE = AD.CODCENATE 
	--WHERE CAST(I.IFECHAING AS DATE)  BETWEEN @DateStart AND @DateEnd

GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_Purpose', @value=N'Expone un dataset consolidado de ingresos asistenciales (admisiones) con datos demográficos del paciente, entidad/grupo de atención, diagnósticos, estado y tiempos de alta, para alimentar un cubo analítico de RCM.', @level0type=N'SCHEMA', @level0name=N'Report', @level1type=N'VIEW', @level1name=N'UploadCubeVieRCMAdmissionsStatistician';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_Preconditions', @value=N'Existe un ingreso en ADINGRESO con identificadores NUMINGRES e IPCODPACI consistentes en las tablas relacionadas; La base de datos actual (DB_NAME) representa la compañía/instancia a reportar; Las tablas catálogo (INDIAGNOS, INUNIFUNC, ADCENATEN, COMMON.CITY, CONTRACT.CAREGROUP, CONTRACT.HEALTHADMINISTRATOR) están pobladas para resolver descripciones', @level0type=N'SCHEMA', @level0name=N'Report', @level1type=N'VIEW', @level1name=N'UploadCubeVieRCMAdmissionsStatistician';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_Invariants', @value=N'Toda columna de texto sin dato se normaliza a ''DESCONOCIDO'', ''NO APLICA'' o ''0''; Las fechas nulas se sustituyen por ''1900-12-31''; La marca de tiempo de actualización (ULT_ACTUA) se calcula convirtiendo GETDATE() a la zona ''Pakistan Standard Time''; ID_COMPANY se deriva de DB_NAME() truncado a 9 caracteres; El diagnóstico actual del paciente se obtiene siempre del folio más reciente (MAX(NUMEFOLIO)) en HCHISPACA por ingreso; Si el grupo de atención específico no existe, se hereda del administrador de salud (entidad); Las uniones se hacen con NOLOCK, aceptando lecturas sucias para fines analíticos', @level0type=N'SCHEMA', @level0name=N'Report', @level1type=N'VIEW', @level1name=N'UploadCubeVieRCMAdmissionsStatistician';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_DomainConcepts', @value=N'Ingreso/Admisión; Paciente; Tipo de documento; Entidad/Administrador de salud (EPS); Grupo de atención; Centro de atención; Unidad funcional; Diagnóstico CIE-10 (ingreso, egreso, actual); Causa de ingreso; Tipo de riesgo; Alta médica; Triage; Historia clínica (folio); Estado del ingreso (facturación parcial, anulado, cerrado)', @level0type=N'SCHEMA', @level0name=N'Report', @level1type=N'VIEW', @level1name=N'UploadCubeVieRCMAdmissionsStatistician';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_SideEffects', @value=N'[RETURN_RESULT] Report.UploadCubeVieRCMAdmissionsStatistician: Devuelve un registro DISTINCT por ingreso enriquecido con descripciones, tomando el último folio de historia clínica (MAX(NUMEFOLIO)) por NUMINGRES+IPCODPACI para el diagnóstico actual y el menor TRIANUMER/CODCONCEC con CODCONCEC NOT NULL para el usuario que creó el ingreso desde triage.', @level0type=N'SCHEMA', @level0name=N'Report', @level1type=N'VIEW', @level1name=N'UploadCubeVieRCMAdmissionsStatistician';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_Decisions', @value=N'si p.iptipodoc entre 1..15 → Mapea a códigos de tipo de documento: 1=CC, 2=CE, 3=TI, 4=RC, 5=PA, 6=AS, 7=MS, 8=NU, 9=CN, 10=CD, 11=SC, 12=PE, 13=PT, 14=DE, 15=SI; si I.IESTADOIN → Traduce estado del ingreso: ''  ''=SIN CONFIRMAR HOJA DE TRABAJO, ''F''=CONFIRMADA, ''A''=ANULADO, ''C''=CERRADO, ''P''=FACTURADO PARCIAL; otros=DESCONOCIDO else DESCONOCIDO; si I.TIPOINGRE = 1 / 2 → 1=AMBULATORIO, 2=HOSPITALARIO; si I.ICAUSAING entre ''1''..''11'' → Traduce causa de ingreso (HERIDOS EN COMBATE, ENFERMEDAD PROFESIONAL, ENF. GENERAL ADULTO/PEDIATRIA, ODONTOLOGÍA, ACCIDENTE DE TRANSITO, CATASTROFE/FISALUD, QUEMADOS, MATERNIDAD, ACCIDENTE LABORAL, CIRUGIA PROGRAMADA) else DESCONOCIDO; si I.ITIPORIES = 1/2/3 → 1=ENFERMEDAD GENERAL Y MATERNIDAD, 2=ACCIDENTE DE TRANSITO, 3=CATASTROFE else DESCONOCIDO; si EM.FECALTPAC IS NULL → Marca ''SIN ALTA MEDICA'' else Marca ''CON ALTA MEDICA''; si I.IESTADOIN IN (''  '',''P'') → Calcula DIAS ALTA MEDICA = DATEDIFF(DAY, EM.FECALTPAC, GETDATE()) else DIAS ALTA MEDICA = 0 (estados F, A, C u otros); si GA.CODE/NAME IS NULL → Usa código/nombre de la entidad EA (HEALTHADMINISTRATOR) como grupo de atención else Usa el código/nombre del grupo de atención (CAREGROUP); si P.GENEXPEDITIONCITY IS NULL AND CI.NAME IS NULL → Lugar de expedición = ''0 - DESCONOCIDO'' else Concatena código de ciudad + nombre', @level0type=N'SCHEMA', @level0name=N'Report', @level1type=N'VIEW', @level1name=N'UploadCubeVieRCMAdmissionsStatistician';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_Consumes', @value=N'DBO.ADINGRESO; DBO.INUNIFUNC; CONTRACT.CAREGROUP; Security.UserINT; DBO.SEGUSUARU; SECURITY.PERSONINT; DBO.INPACIENT; CONTRACT.HEALTHADMINISTRATOR; COMMON.CITY; DBO.HCHISPACA; DBO.INDIAGNOS; DBO.HCREGEGRE; DBO.ADTRIAGEU; DBO.ADCONTURG; DBO.INUBICACI; DBO.INMUNICIP; DBO.ADCENATEN', @level0type=N'SCHEMA', @level0name=N'Report', @level1type=N'VIEW', @level1name=N'UploadCubeVieRCMAdmissionsStatistician';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_Source', @value=N'ai_claude-opus-4-7_tier-c_2026-05-06', @level0type=N'SCHEMA', @level0name=N'Report', @level1type=N'VIEW', @level1name=N'UploadCubeVieRCMAdmissionsStatistician';
GO
