

CREATE VIEW [Report].[ViewPathologiesRequests] AS

WITH 
CTE_GRUPO AS
(
SELECT CG.CODE AS CODGRUPO, 
CG.NAME AS GRUPOATENCION, 
CON.CODE AS CODCONTRATO, 
CON.CONTRACTNAME AS NOMBRECONTRATO, 
PT.CODE AS CODPLANTIPROCE, 
PT.NAME AS PLANTILLAPROCEDIMIENTO, 
CGR.CODE AS CODIGOGRUPO, 
CGR.NAME AS GRUPO, 
CSG.CODE AS CODSUBGRUPO, 
CSG.NAME AS SUBGRUPO, 
CE.CODE AS CUPS, 
CE.DESCRIPTION AS DESCRIPCIONCUPS, 
CD.CODE AS CODRELACION, 
CD.NAME AS DESCRIPCIONRELACIONADA,
CASE PC.CONTRACTED WHEN 1 THEN 'SI' ELSE 'NO' END AS CONTRATADO,
CASE PC.QUOTED WHEN 1 THEN 'SI' ELSE 'NO' END AS COTIZADO, 
CECD.ID AS IDRELACION
FROM CONTRACT.CAREGROUP AS CG WITH(NOLOCK)
INNER JOIN CONTRACT.CONTRACT AS CON WITH(NOLOCK) ON CG.CONTRACTID = CON.ID
INNER JOIN CONTRACT.PROCEDURETEMPLATE AS PT WITH(NOLOCK) ON CG.PROCEDURETEMPLATEID = PT.ID
INNER JOIN CONTRACT.PROCEDURECUPS AS PC WITH(NOLOCK) ON PT.ID = PC.PROCEDURESTEMPLATEID
INNER JOIN CONTRACT.CUPSENTITY AS CE WITH(NOLOCK) ON PC.CUPSID = CE.ID
LEFT OUTER JOIN CONTRACT.CUPSENTITYCONTRACTDESCRIPTIONS AS CECD WITH(NOLOCK) ON PC.CUPSENTITYCONTRACTDESCRIPTIONID = CECD.ID
LEFT JOIN CONTRACT.CONTRACTDESCRIPTIONS AS CD WITH(NOLOCK) ON CECD.CONTRACTDESCRIPTIONID = CD.ID
LEFT OUTER JOIN CONTRACT.CUPSSUBGROUP CSG WITH(NOLOCK) ON CE.CUPSSUBGROUPID = CSG.ID
LEFT OUTER JOIN CONTRACT.CUPSGROUP CGR WITH(NOLOCK) ON CSG.CUPSGROUPID = CGR.ID
),

CTE_ORDENAMIENTO_PATOLOGIA
AS (
---****PATOLOGIAS******
SELECT RTRIM(E.NOMCENATE) [CENTRO ATENCION], 
A.UFUCODIGO + ' - ' + RTRIM(D.UFUDESCRI) AS [UNIDAD FUNCIONAL], 
CG.CODE + '-' + CG.NAME [GRUPO], 
CSG.CODE + '-' + CSG.NAME [SUBGRUPO], 
A.CODSERIPS [CODIGO CUPS], 
RTRIM(B.DESSERIPS) AS [DESCRIPCION SERVICIO], 
ISNULL(CD.CODE + ' - ' + CD.NAME, '') [DESCRIPCION RELACIONADA], 
A.FECORDMED AS [FECHA SOLICITUD],
CASE I.IPTIPODOC WHEN '1' THEN 'CC'
				 WHEN '2' THEN 'CE'
				 WHEN '3' THEN 'TI'
				 WHEN '4' THEN 'RC'
				 WHEN '5' THEN 'PA'
				 WHEN '6' THEN 'AS'
				 WHEN '7' THEN 'MS'
				 WHEN '8' THEN 'NU'
				 WHEN '9' THEN 'NV'
				 WHEN '10' THEN 'CD'
				 WHEN '11' THEN 'SC'
				 WHEN '12' THEN 'PE' END AS [TIPO IDENTIFICACION], 
A.IPCODPACI AS [IDENTIFICACION], 
I.IPTELEFON AS [TELEFONO FIJO], 
I.IPTELMOVI AS [TELEFONO MOVIL], 
I.IPNOMCOMP AS [PACIENTE], 
A.NUMINGRES AS [INGRESO],
A.NUMEFOLIO AS FOLIO, 
CASE WHEN SERREASIT = '1' THEN 'ESTUDIOS REALIZADOS EN SITIO'
	 WHEN ESTSERIPS IN('2', '3', '4')THEN 'ESTUDIOS REALIZADOS'
	 WHEN ESTSERIPS = '6' THEN 'ANULADO' ELSE 'ESTUDIOS NO REALIZADOS' END AS ESTADO, 
SUM(A.CANSERIPS) AS CANTIDAD, 
PRO.CODPROSAL [ID PROFESIONAL], 
PRO.NOMMEDICO AS PROFESIONAL, 
ESPMED.DESESPECI ESPECIALIDAD, 
DIAG.CODDIAGNO CIE10, 
DIAG.NOMDIAGNO DIAGNOSTICO,
CASE ESTA.ESTADIO WHEN 0 THEN 'ESTADIO CLÍNICO (EC) 0 (TUMOR IN SITU)'
				  WHEN 1 THEN 'EC I O 1'
				  WHEN 2 THEN 'EC IA O 1A'
				  WHEN 3 THEN 'EC IA1'
				  WHEN 4 THEN 'EC IA2'
				  WHEN 5 THEN 'EC IB O 1B'
				  WHEN 6 THEN 'EC IB1'
				  WHEN 7 THEN 'EC IB2'
				  WHEN 8 THEN 'EC IC O 1C'
				  WHEN 9 THEN 'EC IS O 1S'
				  WHEN 10 THEN 'EC II O 2'
				  WHEN 11 THEN 'EC IIA O 2A'
				  WHEN 12 THEN 'EC IIA1'
				  WHEN 13 THEN 'EC IIA2'
				  WHEN 14 THEN 'EC IIB O 2B'
				  WHEN 15 THEN 'EC IIC O 2C'
				  WHEN 16 THEN 'EC III O 3'
				  WHEN 17 THEN 'EC IIIA O 3A'
				  WHEN 18 THEN 'EC IIIB O 3B'
				  WHEN 19 THEN 'EC IIIC O 3C'
				  WHEN 20 THEN 'EC IV O 4'
				  WHEN 21 THEN 'EC IVA O 4A'
				  WHEN 22 THEN 'EC IVB O 4B'
				  WHEN 23 THEN 'EC IVC O 4C'
				  WHEN 24 THEN 'EC 4S (PARA NEUROBLASTOMA)'
				  WHEN 25 THEN 'EC  V O 5'
				  WHEN 26 THEN 'EC ESTADIO IAB'
				  WHEN 55 THEN 'PERSONA CON ASEGURAMIENTO (RÉGIMEN SUBSIDIADO O CONTRIBUTIVO Y QUE NO SON PPNA) QUE RECIBIÓ SERVICIOS DE SALUD POR PARTE DEL ENTE TERRITORIALDURANTE EL PERIODO DE REPORTE'
				  WHEN 93 THEN 'SIN INFORMACIÓN DE ESTADIFICACIÓN EN HISTORIA CLÍNICA'
				  WHEN 98 THEN 'NO APLICA (ES CÁNCER DE PIEL BASOCELULAR, ES CÁNCER HEMATOLÓGICO O ES CÁNCER EN SNC, EXCEPTO NEUROBLASTOMA)'
				  WHEN 99 THEN 'DESCONOCIDO, EL DATO DE ESTA VARIABLE NO SE ENCUENTRA DESCRITO EN LOS SOPORTES CLÍNICOS' ELSE '' END ESTADIO,
CASE WHEN MANEXTPRO = 0 THEN 'HOSPITALARIO' ELSE 'AMBULATORIO' END AS [TIPO SOLICITUD], 
EA.CODE + ' - ' + EA.NAME AS [ENTIDAD ADMINISTRADORA], 
GA.CODE + ' - ' + GA.NAME [GRUPO ATENCION],
CASE GA.LIQUIDATIONTYPE WHEN 1 THEN 'PAGO POR SERVICIOS'
						WHEN 2 THEN 'PGP'
						WHEN 3 THEN 'FACTURA GLOBAL'
						WHEN 4 THEN 'CAPITACION GLOBAL'
						WHEN 5 THEN 'CONTROL' END [TIPO CONTRATO], 
'PATOLOGIAS' [TIPO ORDEN], 
IIF(G.CODGRUPO IS NULL, 'NO', 'SI') CUBIERTO, 
ISNULL(G.CONTRATADO, 'NO') CONTRATADO, 
ISNULL(G.COTIZADO, 'NO') COTIZADO, 
GA.CODE [CODIGO GRUPO], 
A.IDDESCRIPCIONRELACIONADA, 
FAC.InvoiceNumber AS FACTURA,
CAST(A.FECORDMED AS DATE) [FECHA BUSQUEDA]
FROM DBO.ADINGRESO ING WITH(NOLOCK)
JOIN DBO.HCORDPATO A WITH(NOLOCK) ON ING.NUMINGRES = A.NUMINGRES
JOIN DBO.INCUPSIPS B WITH(NOLOCK) ON A.CODSERIPS = B.CODSERIPS
JOIN DBO.INPACIENT I WITH(NOLOCK) ON A.IPCODPACI = I.IPCODPACI
JOIN DBO.INUNIFUNC D WITH(NOLOCK) ON A.UFUCODIGO = D.UFUCODIGO
JOIN DBO.ADCENATEN E WITH(NOLOCK) ON A.CODCENATE = E.CODCENATE
JOIN DBO.INPROFSAL PRO WITH(NOLOCK) ON A.CODPROSAL = PRO.CODPROSAL
JOIN CONTRACT.CUPSENTITY AS CUPS WITH(NOLOCK) ON CUPS.CODE = B.CODSERIPS
JOIN CONTRACT.CUPSSUBGROUP AS CSG WITH(NOLOCK) ON CSG.ID = CUPS.CUPSSUBGROUPID
JOIN CONTRACT.CUPSGROUP AS CG WITH(NOLOCK) ON CG.ID = CSG.CUPSGROUPID
JOIN DBO.HCHISPACA HIS WITH(NOLOCK) ON A.NUMINGRES = HIS.NUMINGRES
                            AND A.NUMEFOLIO = HIS.NUMEFOLIO
JOIN DBO.INESPECIA AS ESPMED WITH(NOLOCK) ON ESPMED.CODESPECI = HIS.CODESPTRA
JOIN DBO.INDIAGNOS AS DIAG WITH(NOLOCK) ON DIAG.CODDIAGNO = HIS.CODDIAGNO
JOIN CONTRACT.CAREGROUP AS GA WITH(NOLOCK) ON GA.ID = ING.GENCAREGROUP
JOIN CONTRACT.HEALTHADMINISTRATOR AS EA WITH(NOLOCK) ON EA.ID = ING.GENCONENTITY
LEFT JOIN CONTRACT.CUPSENTITYCONTRACTDESCRIPTIONS CECD WITH(NOLOCK) ON CECD.ID = A.IDDESCRIPCIONRELACIONADA
LEFT JOIN CONTRACT.CONTRACTDESCRIPTIONS CD WITH(NOLOCK) ON CD.ID = CECD.CONTRACTDESCRIPTIONID LEFT JOIN
Billing.ServiceOrder ORD ON ORD.Id=A.GENSERVICEORDER LEFT JOIN
Billing.ServiceOrderDetail ORDD ON ORD.Id=ORDD.ServiceOrderId LEFT JOIN
Billing.InvoiceDetail FACD ON ORDD.ID=FACD.ServiceOrderDetailId LEFT JOIN
Billing.Invoice FAC ON FACD.InvoiceId=FAC.Id
LEFT JOIN DBO.INDIAGNOP AS EST WITH(NOLOCK) ON A.IPCODPACI = EST.IPCODPACI
                                    AND A.NUMINGRES = EST.NUMINGRES
                                    AND EST.NUMEFOLIO = A.NUMEFOLIO
                                    AND EST.ESTADIO IS NOT NULL LEFT JOIN
CTE_GRUPO AS G ON G.CODGRUPO = GA.CODE
AND G.CUPS = A.CODSERIPS
AND A.IDDESCRIPCIONRELACIONADA = G.IDRELACION
LEFT JOIN
(
SELECT EST.NUMEFOLIO, 
EST.IPCODPACI PACIENTE, 
ESTADIO
FROM DBO.INDIAGNOH AS EST WITH(NOLOCK)
INNER JOIN
(
SELECT MIN(NUMEFOLIO) NUMEFOLIO, 
IPCODPACI
FROM DBO.INDIAGNOH
WHERE ESTADIO IS NOT NULL
AND ESTADIO NOT IN(93, 98, 99)
GROUP BY IPCODPACI
) FE ON EST.NUMEFOLIO = FE.NUMEFOLIO
AND EST.IPCODPACI = FE.IPCODPACI --CONSULTA DE PRIMER ESTADIO 20201123
WHERE ESTADIO IS NOT NULL
) ESTA ON ING.IPCODPACI = ESTA.PACIENTE
GROUP BY A.CODSERIPS, B.DESSERIPS, SERREASIT, ESTSERIPS, A.IPCODPACI, A.NUMINGRES, I.IPNOMCOMP, CECD.ID, CD.ID, CD.CODE, CD.NAME, E.NOMCENATE, 
A.UFUCODIGO, D.UFUDESCRI, A.NUMEFOLIO, PRO.CODPROSAL, PRO.NOMMEDICO, MANEXTPRO, A.FECORDMED, CG.CODE + '-' + CG.NAME, CSG.CODE + '-' + CSG.NAME, 
ESPMED.DESESPECI, DIAG.CODDIAGNO, DIAG.NOMDIAGNO, EA.CODE + ' - ' + EA.NAME, GA.CODE + ' - ' + GA.NAME, GA.LIQUIDATIONTYPE,EST.ESTADIO, 
GA.CODE, A.IDDESCRIPCIONRELACIONADA, G.CONTRATADO, G.COTIZADO, IIF(G.CODGRUPO IS NULL, 'NO', 'SI'), ESTA.ESTADIO, I.IPTIPODOC, I.IPTELEFON, 
I.IPTELMOVI,FAC.InvoiceNumber

UNION ALL

SELECT RTRIM(E.NOMCENATE) [CENTRO ATENCION], 
A.UFUCODIGO + ' - ' + RTRIM(D.UFUDESCRI) AS [UNIDAD FUNCIONAL], 
CG.CODE + '-' + CG.NAME [GRUPO], 
CSG.CODE + '-' + CSG.NAME [SUBGRUPO], 
A.CODSERIPS [CODIGO CUPS], 
RTRIM(B.DESSERIPS) AS [DESCRIPCION SERVICIO], 
ISNULL(CD.CODE + ' - ' + CD.NAME, '') [DESCRIPCION RELACIONADA], 
A.FECORDMED AS [FECHA SOLICITUD],
CASE I.IPTIPODOC WHEN '1' THEN 'CC'
				 WHEN '2' THEN 'CE'
				 WHEN '3' THEN 'TI'
				 WHEN '4' THEN 'RC'
				 WHEN '5' THEN 'PA'
				 WHEN '6' THEN 'AS'
				 WHEN '7' THEN 'MS'
				 WHEN '8' THEN 'NU'
				 WHEN '9' THEN 'NV'
				 WHEN '10' THEN 'CD'
				 WHEN '11' THEN 'SC'
				 WHEN '12' THEN 'PE' END AS [TIPO IDENTIFICACION], 
A.IPCODPACI AS [IDENTIFICACION], 
I.IPTELEFON AS [TELEFONO FIJO], 
I.IPTELMOVI AS [TELEFONO MOVIL], 
'HIJO ' + CAST(RN.NUMHIJREG AS VARCHAR(20)) AS [PACIENTE], 
INGMH.NUMINGRES AS [INGRESO],
A.NUMEFOLIO AS FOLIO, 
CASE WHEN SERREASIT = '1' THEN 'ESTUDIOS REALIZADOS EN SITIO'
	 WHEN ESTSERIPS IN('2', '3', '4') THEN 'ESTUDIOS REALIZADOS'
	 WHEN ESTSERIPS = '6' THEN 'ANULADO' ELSE 'ESTUDIOS NO REALIZADOS' END AS ESTADO, 
SUM(A.CANSERIPS) AS CANTIDAD, 
PRO.CODPROSAL [ID PROFESIONAL], 
PRO.NOMMEDICO AS PROFESIONAL, 
ESPMED.DESESPECI ESPECIALIDAD, 
DIAG.CODDIAGNO CIE10, 
DIAG.NOMDIAGNO DIAGNOSTICO,
CASE ESTA.ESTADIO WHEN 0 THEN 'ESTADIO CLÍNICO (EC) 0 (TUMOR IN SITU)'
				  WHEN 1 THEN 'EC I O 1'
				  WHEN 2 THEN 'EC IA O 1A'
				  WHEN 3 THEN 'EC IA1'
				  WHEN 4 THEN 'EC IA2'
				  WHEN 5 THEN 'EC IB O 1B'
				  WHEN 6 THEN 'EC IB1'
				  WHEN 7 THEN 'EC IB2'
				  WHEN 8 THEN 'EC IC O 1C'
				  WHEN 9 THEN 'EC IS O 1S'
				  WHEN 10 THEN 'EC II O 2' 
				  WHEN 11 THEN 'EC IIA O 2A'
				  WHEN 12 THEN 'EC IIA1'
				  WHEN 13 THEN 'EC IIA2'
				  WHEN 14 THEN 'EC IIB O 2B'
				  WHEN 15 THEN 'EC IIC O 2C'
				  WHEN 16 THEN 'EC III O 3'
				  WHEN 17 THEN 'EC IIIA O 3A'
				  WHEN 18 THEN 'EC IIIB O 3B'
				  WHEN 19 THEN 'EC IIIC O 3C'
				  WHEN 20 THEN 'EC IV O 4'
				  WHEN 21 THEN 'EC IVA O 4A'
				  WHEN 22 THEN 'EC IVB O 4B'
				  WHEN 23 THEN 'EC IVC O 4C'
				  WHEN 24 THEN 'EC 4S (PARA NEUROBLASTOMA)'
				  WHEN 25 THEN 'EC  V O 5'
				  WHEN 26 THEN 'EC ESTADIO IAB'
				  WHEN 55 THEN 'PERSONA CON ASEGURAMIENTO (RÉGIMEN SUBSIDIADO O CONTRIBUTIVO Y QUE NO SON PPNA) QUE RECIBIÓ SERVICIOS DE SALUD POR PARTE DEL ENTE TERRITORIALDURANTE EL PERIODO DE REPORTE'
				  WHEN 93 THEN 'SIN INFORMACIÓN DE ESTADIFICACIÓN EN HISTORIA CLÍNICA'
				  WHEN 98 THEN 'NO APLICA (ES CÁNCER DE PIEL BASOCELULAR, ES CÁNCER HEMATOLÓGICO O ES CÁNCER EN SNC, EXCEPTO NEUROBLASTOMA)'
				  WHEN 99 THEN 'DESCONOCIDO, EL DATO DE ESTA VARIABLE NO SE ENCUENTRA DESCRITO EN LOS SOPORTES CLÍNICOS' ELSE '' END ESTADIO,
CASE WHEN MANEXTPRO = 0 THEN 'HOSPITALARIO' ELSE 'AMBULATORIO' END AS [TIPO SOLICITUD], 
EA.CODE + ' - ' + EA.NAME AS [ENTIDAD ADMINISTRADORA], 
GA.CODE + ' - ' + GA.NAME [GRUPO ATENCION],
CASE GA.LIQUIDATIONTYPE WHEN 1 THEN 'PAGO POR SERVICIOS'
						WHEN 2 THEN 'PGP'
						WHEN 3 THEN 'FACTURA GLOBAL'
						WHEN 4 THEN 'CAPITACION GLOBAL'
						WHEN 5 THEN 'CONTROL' END [TIPO CONTRATO], 
'PATOLOGIAS' [TIPO ORDEN], 
IIF(G.CODGRUPO IS NULL, 'NO', 'SI') CUBIERTO, 
ISNULL(G.CONTRATADO, 'NO') CONTRATADO, 
ISNULL(G.COTIZADO, 'NO') COTIZADO, 
GA.CODE [CODIGO GRUPO], 
A.IDDESCRIPCIONRELACIONADA, 
FAC.InvoiceNumber AS FACTURA,
CAST(A.FECORDMED AS DATE) [FECHA BUSQUEDA]
FROM DBO.HCORDPATO A WITH(NOLOCK)
JOIN DBO.INCUPSIPS B WITH(NOLOCK) ON A.CODSERIPS = B.CODSERIPS
JOIN DBO.HCINGRESORECNAC INGMH WITH(NOLOCK) ON A.NUMINGRES = INGMH.NUMINGRESHIJO
JOIN DBO.HCRECINAC RN WITH(NOLOCK) ON INGMH.NUMINGRESHIJO = RN.NUMINGRESHIJO
JOIN DBO.ADINGRESO AS ING WITH(NOLOCK) ON ING.NUMINGRES = INGMH.NUMINGRESHIJO
JOIN DBO.INPACIENT I WITH(NOLOCK) ON A.IPCODPACI = I.IPCODPACI
JOIN DBO.INUNIFUNC D WITH(NOLOCK) ON A.UFUCODIGO = D.UFUCODIGO
JOIN DBO.ADCENATEN E WITH(NOLOCK) ON A.CODCENATE = E.CODCENATE
JOIN DBO.INPROFSAL PRO WITH(NOLOCK) ON A.CODPROSAL = PRO.CODPROSAL
JOIN CONTRACT.CUPSENTITY AS CUPS WITH(NOLOCK) ON CUPS.CODE = B.CODSERIPS
JOIN CONTRACT.CUPSSUBGROUP AS CSG WITH(NOLOCK) ON CSG.ID = CUPS.CUPSSUBGROUPID
JOIN CONTRACT.CUPSGROUP AS CG WITH(NOLOCK) ON CG.ID = CSG.CUPSGROUPID
JOIN DBO.HCHISPACA HIS WITH(NOLOCK) ON A.NUMINGRES = HIS.NUMINGRES AND A.NUMEFOLIO = HIS.NUMEFOLIO
JOIN DBO.INESPECIA AS ESPMED WITH(NOLOCK) ON ESPMED.CODESPECI = HIS.CODESPTRA
JOIN DBO.INDIAGNOS AS DIAG WITH(NOLOCK) ON DIAG.CODDIAGNO = HIS.CODDIAGNO
JOIN CONTRACT.CAREGROUP AS GA WITH(NOLOCK) ON GA.ID = ING.GENCAREGROUP
JOIN CONTRACT.HEALTHADMINISTRATOR AS EA WITH(NOLOCK) ON EA.ID = ING.GENCONENTITY LEFT JOIN 
CONTRACT.CUPSENTITYCONTRACTDESCRIPTIONS CECD WITH(NOLOCK) ON CECD.ID = A.IDDESCRIPCIONRELACIONADA LEFT JOIN 
CONTRACT.CONTRACTDESCRIPTIONS CD WITH(NOLOCK) ON CD.ID = CECD.CONTRACTDESCRIPTIONID LEFT JOIN
Billing.ServiceOrder ORD ON ORD.Id=A.GENSERVICEORDER LEFT JOIN
Billing.ServiceOrderDetail ORDD ON ORD.Id=ORDD.ServiceOrderId LEFT JOIN
Billing.InvoiceDetail FACD ON ORDD.ID=FACD.ServiceOrderDetailId LEFT JOIN
Billing.Invoice FAC ON FACD.InvoiceId=FAC.Id
LEFT JOIN DBO.INDIAGNOP AS EST WITH(NOLOCK) ON A.IPCODPACI = EST.IPCODPACI AND A.NUMINGRES = EST.NUMINGRES
																		   AND EST.NUMEFOLIO = A.NUMEFOLIO
																		   AND EST.ESTADIO IS NOT NULL LEFT JOIN
CTE_GRUPO AS G ON G.CODGRUPO = GA.CODE
AND G.CUPS = A.CODSERIPS
AND A.IDDESCRIPCIONRELACIONADA = G.IDRELACION
LEFT JOIN
(
SELECT EST.NUMEFOLIO, 
EST.IPCODPACI PACIENTE, 
ESTADIO
FROM DBO.INDIAGNOH AS EST WITH(NOLOCK)
INNER JOIN
(
SELECT MIN(NUMEFOLIO) NUMEFOLIO, 
IPCODPACI
FROM DBO.INDIAGNOH WITH(NOLOCK)
WHERE ESTADIO IS NOT NULL
AND ESTADIO NOT IN(93, 98, 99)
GROUP BY IPCODPACI
) FE ON EST.NUMEFOLIO = FE.NUMEFOLIO
AND EST.IPCODPACI = FE.IPCODPACI --CONSULTA DE PRIMER ESTADIO 20201123
WHERE ESTADIO IS NOT NULL
) ESTA ON ING.IPCODPACI = ESTA.PACIENTE
GROUP BY A.CODSERIPS, B.DESSERIPS, SERREASIT, ESTSERIPS, A.IPCODPACI, INGMH.NUMINGRES, RN.NUMHIJREG, CECD.ID, CD.ID, CD.CODE, CD.NAME, 
E.NOMCENATE, A.UFUCODIGO, D.UFUDESCRI, A.NUMEFOLIO, PRO.CODPROSAL, PRO.NOMMEDICO, MANEXTPRO, A.FECORDMED, CG.CODE + '-' + CG.NAME, 
CSG.CODE + '-' + CSG.NAME, ESPMED.DESESPECI, DIAG.CODDIAGNO, DIAG.NOMDIAGNO, EA.CODE + ' - ' + EA.NAME, GA.CODE + ' - ' + GA.NAME, 
GA.LIQUIDATIONTYPE, EST.ESTADIO, GA.CODE, A.IDDESCRIPCIONRELACIONADA, G.CONTRATADO, G.COTIZADO, IIF(G.CODGRUPO IS NULL, 'NO', 'SI'), 
ESTA.ESTADIO, I.IPTIPODOC, I.IPTELEFON, I.IPTELMOVI,FAC.InvoiceNumber
)

SELECT CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
*,
YEAR([FECHA BUSQUEDA]) AS 'AÑO FECHA BUSQUEDA',
MONTH([FECHA BUSQUEDA]) AS 'MES AÑO FECHA BUSQUEDA',
CASE MONTH([FECHA BUSQUEDA]) WHEN 1 THEN 'ENERO'
							 WHEN 2 THEN 'FEBRERO'
							 WHEN 3 THEN 'MARZO'
							 WHEN 4 THEN 'ABRIL'
							 WHEN 5 THEN 'MAYO'
							 WHEN 6 THEN 'JUNIO'
							 WHEN 7 THEN 'JULIO'
							 WHEN 8 THEN 'AGOSTO'
							 WHEN 9 THEN 'SEPTIEMBRE'
							 WHEN 10 THEN 'OCTUBRE'
							 WHEN 11 THEN 'NOVIEMBRE'
							 WHEN 12 THEN 'DICIEMBRE' END AS 'MES NOMBRE FECHA BUSQUEDA', 
FORMAT(DAY([FECHA BUSQUEDA]), '00') AS 'DIA FECHA BUSQUEDA',
CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM CTE_ORDENAMIENTO_PATOLOGIA;
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Vista de reporte que consolida las órdenes de patología solicitadas a pacientes (incluyendo recién nacidos vinculados por ingreso madre-hijo), aplanando información clínica, contractual y de facturación para consumo en reporting. Cruza datos de ingreso, profesional solicitante, diagnóstico CIE-10, estadio oncológico (codificado 0-99), código CUPS con su grupo/subgrupo, cobertura contractual (contratado/cotizado) y número de factura asociada. También expone el estado de ejecución del estudio, tipo de solicitud (hospitalario/ambulatorio) y entidad administradora con su modalidad de contratación.', @level0type=N'SCHEMA', @level0name=N'Report', @level1type=N'VIEW', @level1name=N'ViewPathologiesRequests';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DescriptionSource', @value=N'ai_claude-sonnet-4-6_2026-05-05', @level0type=N'SCHEMA', @level0name=N'Report', @level1type=N'VIEW', @level1name=N'ViewPathologiesRequests';
GO
GO
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_Purpose', @value=N'Vista de reporte que consolida las solicitudes de patología (incluyendo las generadas para recién nacidos), enriqueciéndolas con datos de paciente, profesional, diagnóstico, estadio oncológico, contrato, cobertura, factura asociada y dimensiones de fecha de búsqueda.', @level0type=N'SCHEMA', @level0name=N'Report', @level1type=N'VIEW', @level1name=N'ViewPathologiesRequests';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_Preconditions', @value=N'Cada orden de patología (HCORDPATO) debe tener ingreso (ADINGRESO o HCINGRESORECNAC) válido, paciente (INPACIENT), CUPS IPS (INCUPSIPS) y unidad funcional (INUNIFUNC) existentes, ya que los JOIN son INNER.; El ingreso debe tener grupo de atención (CAREGROUP) y entidad administradora (HEALTHADMINISTRATOR) asignados (GENCAREGROUP, GENCONENTITY).; Debe existir registro de historia (HCHISPACA) por NUMINGRES+NUMEFOLIO con especialidad (INESPECIA) y diagnóstico (INDIAGNOS) válidos.; El CUPS solicitado debe estar registrado en CONTRACT.CUPSENTITY con subgrupo y grupo de CUPS asociados.; Para la rama de recién nacidos, debe existir vínculo en HCINGRESORECNAC y HCRECINAC con NUMINGRESHIJO.', @level0type=N'SCHEMA', @level0name=N'Report', @level1type=N'VIEW', @level1name=N'ViewPathologiesRequests';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_Invariants', @value=N'Solo considera estadios oncológicos significativos para la subconsulta de ''primer estadio'' del paciente: excluye 93, 98 y 99 (sin información, no aplica y desconocido) y toma el MIN(NUMEFOLIO) por paciente como primer estadio registrado.; TIPO ORDEN siempre es la constante ''PATOLOGIAS''.; La cobertura (CUBIERTO/CONTRATADO/COTIZADO) se determina haciendo match triple en CTE_GRUPO por código de grupo de atención + código CUPS + IDRELACION (descripción contractual relacionada).; FECHA BUSQUEDA es la fecha de orden médica (FECORDMED) truncada a DATE y se usa para derivar año, mes y día.; ULT_ACTUAL siempre se calcula convirtiendo GETDATE() a la zona horaria ''Pakistan Standard Time''.; ID_COMPANY se obtiene de DB_NAME() truncado a VARCHAR(9), identificando la base de datos de la compañía donde se ejecuta la vista.; El estadio listado en la columna ESTADIO corresponde al primer estadio histórico del paciente (INDIAGNOH) y no al del folio actual.', @level0type=N'SCHEMA', @level0name=N'Report', @level1type=N'VIEW', @level1name=N'ViewPathologiesRequests';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_SideEffects', @value=N'[RETURN_RESULT] Report.ViewPathologiesRequests: Devuelve la unión (UNION ALL) de solicitudes de patología asociadas a ingresos normales y a ingresos de recién nacidos (HCINGRESORECNAC), agregando ID_COMPANY=DB_NAME(), año/mes/día de FECHA BUSQUEDA y ULT_ACTUAL en zona horaria ''Pakistan Standard Time''.', @level0type=N'SCHEMA', @level0name=N'Report', @level1type=N'VIEW', @level1name=N'ViewPathologiesRequests';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_Decisions', @value=N'si SERREASIT = ''1'' → ESTADO = ''ESTUDIOS REALIZADOS EN SITIO'' else Se evalúa siguiente rama según ESTSERIPS; si ESTSERIPS IN (''2'',''3'',''4'') → ESTADO = ''ESTUDIOS REALIZADOS'' else Se evalúa ESTSERIPS = ''6''; si ESTSERIPS = ''6'' → ESTADO = ''ANULADO'' else ESTADO = ''ESTUDIOS NO REALIZADOS''; si MANEXTPRO = 0 → TIPO SOLICITUD = ''HOSPITALARIO'' else TIPO SOLICITUD = ''AMBULATORIO''; si G.CODGRUPO IS NULL (no hay match en CTE_GRUPO por código de grupo + CUPS + IDRELACION) → CUBIERTO = ''NO'', y CONTRATADO/COTIZADO toman ''NO'' por ISNULL else CUBIERTO = ''SI'' y se toman valores reales de contratado/cotizado del contrato; si GA.LIQUIDATIONTYPE → Mapea TIPO CONTRATO a ''PAGO POR SERVICIOS'' (1), ''PGP'' (2), ''FACTURA GLOBAL'' (3), ''CAPITACION GLOBAL'' (4), ''CONTROL'' (5); si I.IPTIPODOC entre ''1'' y ''12'' → Mapea TIPO IDENTIFICACION a CC, CE, TI, RC, PA, AS, MS, NU, NV, CD, SC, PE respectivamente; si ESTA.ESTADIO (estadio oncológico) entre 0 y 99 → Traduce a etiqueta clínica (EC 0..IV, 4S neuroblastoma, 55 aseguramiento territorial, 93 sin información, 98 no aplica, 99 desconocido); si Origen de la fila: ingreso del paciente vs. ingreso de recién nacido (HCINGRESORECNAC) → En la rama recién nacido, PACIENTE se sustituye por ''HIJO '' + NUMHIJREG y el INGRESO es el del hijo (NUMINGRESHIJO)', @level0type=N'SCHEMA', @level0name=N'Report', @level1type=N'VIEW', @level1name=N'ViewPathologiesRequests';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_Source', @value=N'ai_claude-opus-4-7_tier-c_2026-05-06', @level0type=N'SCHEMA', @level0name=N'Report', @level1type=N'VIEW', @level1name=N'ViewPathologiesRequests';
GO
