

/*********************************************************************************
Modificaciones
_____________________________________________________________________________
Version 1
Persona que modifico: Amira Esperanza Gil Meneses
Fecha: 12-07-2023
Observaciones:Se Ingresa campo para el código de la Unidad Funcional - Solicitud HSJ. 
--------------------------------------
Version 2
Persona que modifico:Nilsson Miguel Galindo Lopez
Fecha:23-11-2023
Observacion:Se cambia las fechas de busqueda, de la de ingreso a la fecha de alta medica, esto solicitado por San Jose
--------------------------------------
Version 3
Persona que modifico:Nilsson Miguel Galindo Lopez
Fecha:20-05-2024
Observacion:Se Adiciona el campo de boleta de salida del paciente.
--***********************************************************************************************************************************/

CREATE VIEW [Report].[ViewEgresosHospitalarios] as

WITH CTE_PRIMER_INGRESO AS

 (
  SELECT 
   EST.NUMINGRES,
   EST.IPCODPACI,
   MIN(EST.IFECHAING) AS [FECHA INGRESO],
   EST.CODESPTRA,
   ESPMED.DESESPECI
  FROM 
   DBO.ADINGRESO EST
   LEFT JOIN dbo.INESPECIA AS ESPMED ON EST.CODESPTRA = ESPMED.CODESPECI
  GROUP BY 
   EST.NUMINGRES,
   EST.IPCODPACI,
   EST.CODESPTRA,
   ESPMED.DESESPECI
),

CTE_ULTIMO_INGRESO AS
(
     SELECT 
	  EST.NUMINGRES,
	  EST.IPCODPACI,
	  MAX(EST.FECHEGRESO) 'FECHA EGRESO'
	 FROM 
	  DBO.ADINGRESO EST
	 GROUP BY 
	  EST.NUMINGRES,
	  EST.IPCODPACI
),

INGRESO_INICIAL AS
 (
  SELECT 
   ES.IPCODPACI, 
   ES.NUMINGRES,  
   ES.FECINIEST 'FECHA HOSPITALIZACION', 
   ES.CODTIPEST,
   UNF.Name 'UnidadIngreso'
  FROM 
   CHREGESTA AS ES
   INNER JOIN (SELECT EST.IPCODPACI,  EST.NUMINGRES,  MIN(ID) ID FROM CHREGESTA AS EST GROUP BY EST.IPCODPACI, EST.NUMINGRES) AS G ON G.ID = ES.ID
   INNER JOIN CHCAMASHO CAMD ON CAMD.CODICAMAS = ES.CODICAMAS
   LEFT JOIN Payroll.FunctionalUnit UNF ON CAMD.UFUCODIGO=UNF.Code
 ),

----CTE PARA IDENTIFICAR LA ULTIMA CAMA ACTIVA DE ESE INGRESO
 CTE_ULTIMA_CAMAS_OCUPADA AS
 (
   SELECT 
	EGR.NUMINGRES,
	EGR.FECINIEST,
	EGR.FECFINEST,
	EGR.CODICAMAS,
	CAM.NUMCAMHOS,
	FUN.UFUDESCRI,
	FUN.UFUTIPUNI,
	FUN.UFUCODIGO,
	'EGRESO' AS TIPINGEST, 
	EGR.CODTIPEST, 
	TIP.DESTIPEST, EGR.GENESTLIQ,EGR.ID
   FROM 
    CHREGESTA EGR 
    INNER JOIN
     (
       SELECT EGR.IPCODPACI ,EGR.NUMINGRES,MAX(EGR.ID) ID  FROM CHREGESTA EGR 
	   GROUP BY EGR.IPCODPACI ,EGR.NUMINGRES
	 ) AS G ON G.ID =EGR.ID
    INNER JOIN CHCAMASHO AS CAM  ON CAM.CODICAMAS =EGR.CODICAMAS
    INNER JOIN DBO.INUNIFUNC AS FUN  ON CAM.UFUCODIGO =FUN.UFUCODIGO
	INNER JOIN CHTIPESTA TIP ON TIP.CODTIPEST=EGR.CODTIPEST 
   WHERE 
    EGR.FECFINEST>'1989-01-01 00:00:00.000'
)

SELECT  --COUNT(*) 
 CAST(DB_NAME() AS VARCHAR(9)) AS ID_COMPANY, 
 CEN.NOMCENATE AS [CENTRO DE ATENCION],
 HEA.HealthEntityCode AS [CODIGO EPS/ENTIDAD TERRITORIAL],
 HEA.CODE AS [CODIGO ENTIDAD], 
 RTRIM(HEA.NAME) AS ENTIDAD, 
 RTRIM(CGR.NAME) AS [GRUPO DE ATENCION],
 CASE PAC.IPTIPOPAC WHEN 1 THEN 'CONTRIBUTIVO' 
					WHEN 2 THEN 'SUBSIDIADO' 
					WHEN 3 THEN 'VINCULADO' 
					WHEN 4 THEN 'PARTICULAR' 
					WHEN 5 THEN 'OTRO' 
					WHEN 6 THEN 'DESPLAZADO REG. CONTRIBUTIVO' 	 
					WHEN 7 THEN 'DESPLAZADO REG. SUBSIDIADO' ELSE 'DESPLAZADO NO ASEGURADO' END AS RÉGIMEN,
 NIV.NIVDESCRI AS [NIVEL O ESTRACTO],
 CASE PAC.IPTIPOAFI WHEN 0 THEN 'No Aplica'
					WHEN 1 THEN 'Cotizante' 
					WHEN 2 THEN 'Beneficiario'
					WHEN 3 THEN 'Adicional'
					WHEN 4 THEN 'Jub/Retirado'
					WHEN 5 THEN 'Pensionado' END AS [TIPO DE AFILIACIÓN],
 CASE PAC.IPTIPODOC WHEN '1'  THEN 'CC'
					WHEN '2'  THEN 'CE'	 
					WHEN '3'  THEN 'TI'
					WHEN '4'  THEN 'RC'
					WHEN '5'  THEN 'PA'
					WHEN '6'  THEN 'AS'
					WHEN '7'  THEN 'MS'
					WHEN '8'  THEN 'NU'
					WHEN '9'  THEN 'NV'
					WHEN '10' THEN 'CD'
					WHEN '11' THEN 'SC'
					WHEN '12' THEN 'PE' END AS [TIPO IDENTIFICACION],
 CASE PAC.IPTIPODOC WHEN '1'  THEN 'CEDULA DE CIUDADANIA'
					WHEN '2'  THEN 'CEDULA DE EXTRANJERIA'
					WHEN '3'  THEN 'TARJETA DE IDENTIDAD'
					WHEN '4'  THEN 'REGISTRO CIVIL'
					WHEN '5'  THEN 'PASAPORTE'
					WHEN '6'  THEN 'ADULTO SIN IDENTIFICACION'
					WHEN '7'  THEN 'MENOR SIN IDENTIFICACION'
					WHEN '8'  THEN 'NUMERO UNICO DE IDENTIFICACIÒN'
					WHEN '9'  THEN 'CERTIFICADO NACIDO VIVO'
					WHEN '10' THEN 'CARNET DIPLOMATICO'
					WHEN '11' THEN 'SALVOCONDUCTO'
					WHEN '12' THEN 'PERMISO ESPECIAL DE PERMANENCIA' END AS [DESCRIPCION IDENTIFICACION], 
 HC.IPCODPACI AS IDENTIFICACION, 
 RTRIM(PAC.IPPRINOMB) AS [PRIMER NOMBRE], 
 RTRIM(PAC.IPSEGNOMB) AS [SEGUNDO NOMBRE], 
 RTRIM(PAC.IPPRIAPEL) AS [PRIMER APELLIDO], 
 RTRIM(PAC.IPSEGAPEL) AS [SEGUNDO APELLIDO], 
 RTRIM(PAC.IPNOMCOMP) AS [NOMBRE COMPLETO PACIENTE], 
 CAST(PAC.IPFECNACI AS DATE) AS [FECHA NACIMIENTO], 
 FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECALTPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000) AS EDAD,
 CASE WHEN FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECALTPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<=5 THEN '0-5 Años' 
	  WHEN FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECALTPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>=6 AND FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECALTPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<=11 THEN '6-11 Años' 
	  WHEN FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECALTPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>=12 AND FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECALTPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<=17 THEN '12-17 Años' 
	  WHEN FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECALTPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>=18 AND FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECALTPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<=28 THEN '18-28 Años' 
	  WHEN FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECALTPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>=29 AND FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECALTPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)<=59 THEN '29-59 Años' 
	  WHEN FLOOR((CAST(CONVERT(VARCHAR(8), HC.FECALTPAC, 112) AS INT) - CAST(CONVERT(VARCHAR(8), PAC.IPFECNACI, 112) AS INT)) / 10000)>=60 THEN 'Mayor 60 Años' END AS [RANGO DE EDAD],
 CASE WHEN PAC.IPSEXOPAC = '1' THEN 'M' ELSE 'F' END AS SEXO,
 PAC.IPDIRECCI AS DIRECCION,
 PAC.IPTELEFON AS [TELEFONO FIJO],
 PAC.IPTELMOVI AS [TELEFONO MOVIL],
 CASE PAC.CODGRUPOE WHEN '000' THEN 'OTRO'
					WHEN '001' THEN 'INDIGENAS'
					WHEN '002' THEN 'AFROCOLOMBIANOS NEGROS MULATOS O AFRODESCENDIENTES'
					WHEN '003' THEN 'RAIZALES SAN ANDRES Y PROVIDENCIA'
					WHEN '004' THEN 'PUEBLO ROM GITANOS'
					WHEN '999' THEN 'NO SABE  NO INFORMA  NO APLICA' ELSE 'NO REGISTRA' END AS [ETNIA PACIENTE], 
 DEP.depcodigo AS [CODIGO DEPARTEMENTO],
 DEP.nomdepart AS DEPARTAMENTO,
 MUN.DEPMUNCOD AS [CODIGO MUNICIPIO],
 MUN.MUNNOMBRE AS MUNICIPIO,
 CASE UNI.UFUTIPUNI WHEN 1 THEN 'URGENCIAS' 
					WHEN 2 THEN 'HOSPITALIZACION'
					WHEN 3 THEN 'APOYO DIAGNOSTICO'
					WHEN 4 THEN 'APOYO TERAPEUTICO'
					WHEN 5 THEN 'UCI'
					WHEN 6 THEN 'UCI'
					WHEN 7 THEN 'UCI'
					WHEN 8 THEN 'UCI'
					WHEN 9 THEN 'UCI'
					WHEN 10 THEN 'UCI'
					WHEN 11 THEN 'UCI'
					WHEN 12 THEN 'UNIDAD RENAL'
					WHEN 13 THEN 'UNIDAD ONCOLOGICA' 
					WHEN 14 THEN 'UNIDAD MEDICINA NUCLEAR'
					WHEN 15 THEN 'CONSULTA EXTERNA'
					WHEN 16 THEN 'UNIDAD MENTAL'
					WHEN 17 THEN 'UNIDAD DE QUEMADOS'
					WHEN 18 THEN 'UNIDAD DE CUIDADOS PALATIVOS'
					WHEN 19 THEN 'CIRUGIA'
					WHEN 20 THEN 'LABORATORIOS'
					WHEN 21 THEN 'CARDIOLOGIA NO INVASIVA'
					WHEN 22 THEN 'CARDIOLOGIA INVASIVA'
					WHEN 23 THEN 'GINECO OBSTETRICIA'
					WHEN 24 THEN 'CONSULTA EXTERNA GINOCO OBSTETRICIA'
					WHEN 30 THEN 'OTRAS'
					WHEN 31 THEN 'CONSULTA PRIORITARIA' END AS [TIPO UNIDAD], 
 UNI.UFUCODIGO AS [CODIGO UNIDAD FUNCIONAL DE INGRESO],
 RTRIM(UNI.UFUDESCRI) AS [UNIDAD FUNCIONAL DE INGRESO],
 CING.[CODESPTRA] AS [COD. ESPECIALIDAD TRATANTE INGRESO], 
 CING.[DESESPECI] AS [ESPECIALIDAD TRATANTE INGRESO], 
 RTRIM(CAM.NUMCAMHOS) AS [CAMA ACTUAL],
 HC.NUMINGRES AS INGRESO, 
 ING.CODDIAING AS [CODIGO DX INGRESO], 
 RTRIM(DIA.NOMDIAGNO) AS [DX INGRESO],  
 CASE EI.CODTIPEST WHEN '001' THEN 'GENERAL' 
				   WHEN '002' THEN 'CUIDADO BASICO' 
				   WHEN '003' THEN 'CUIDADO INTERMEDIO' ELSE 'CUIDADO INTENSIVO' END AS [TIPO ESTANCIA],
 CAST (CING.[FECHA INGRESO] as date) AS [FECHA INGRESO],
 CONVERT(NVARCHAR, CAST (CING.[FECHA INGRESO] as time),8) AS [HORA INGRESO],
 EI.[UnidadIngreso] AS [UNIDAD FUNCIONAL HOSPITALIZACION], 
 CAST (EI.[FECHA HOSPITALIZACION] as date) AS [FECHA HOSPITALIZACION], 
 CONVERT(NVARCHAR, CAST (EI.[FECHA HOSPITALIZACION] as time), 8) AS [HORA HOSPITALIZACION], 
 PRO.CODPROSAL AS [CODIGO PROFESIONAL EGRESO],
 PRO.NOMMEDICO AS [PROFESIONAL EGRESO], 
 ESP.DESESPECI AS [ESPECIALIDAD EGRESO],
 ING.CODDIAEGR AS [CODIGO DX EGRESO], 
 RTRIM(DIAE.NOMDIAGNO) AS [DX EGRESO], 
 CO.UFUDESCRI AS [UNIDAD DE EGRESO],
 CO.NUMCAMHOS AS [CAMA DE EGRESO],
 CASE HC.ESTPACEGR WHEN 1 THEN 'MEJOR'
				   WHEN 2 THEN 'IGUAL Y PEOR'
				   WHEN 3 THEN 'FALLECIDO'
				   WHEN 4 THEN 'REMITIDO'
				   WHEN 5 THEN 'HOSPITALIZACION EN CASA' END AS [ESTADO AL EGRESO], 
 CASE HIS.INDICAPAC WHEN 1 THEN 'Trasladar a Urgencias: Solo consulta externa'
                    WHEN 2 THEN  'Trasladar a Observacion Urgencias: solo Urgencias' 
                    WHEN 3 THEN 'Trasladar a Hospitalizacion: Dif Misma Unidad' 
                    WHEN 4 THEN 'Trasladar a UCI Adulto: Dif Misma Unidad' 
				    WHEN 5 THEN 'Trasladar a UCI Pediatrica: Dif Misma Unidad' 
					WHEN 6 THEN 'Trasladar a UCI Neonatal: Dif Misma Unidad' 
					WHEN 7 THEN 'Trasladar a Consulta Externa: Dif Misma Unidad'
					WHEN 8 THEN 'Trasladar a Cirugia: Dif Misma Unidad' 
					WHEN 9 THEN 'Hospitalizacion en Casa' 
					WHEN 10 THEN 'Referencia' 
					WHEN 11 THEN 'Morgue' 
					WHEN 12 THEN 'Salida' 
					WHEN 13 THEN 'Continua en la Unidad' 
					WHEN 14 THEN 'Paciente en Tratamiento' 
					WHEN 15 THEN 'Retiro Voluntario' 
					WHEN 16 THEN 'Fuga' 
					WHEN 17 THEN 'Salida Parcial' 
					WHEN 18 THEN 'Estancia Con la Madre' 
					WHEN 19 THEN 'U.Cuidado Intermedio' 
					WHEN 20 THEN 'U.Basica' END AS [DESTINO PACIENTE],
 CAST(HC.FECALTPAC as date) AS [FECHA ALTA MEDICA], 
 CONVERT(NVARCHAR, CAST(HC.FECALTPAC as time), 8) AS [HORA ALTA MEDICA], 
 CAST(CTUE.[FECHA EGRESO] as date) 'FECHA EGRESO', 
 CONVERT(NVARCHAR, CAST(CTUE.[FECHA EGRESO] as time), 8) 'HORA EGRESO', 
 --CONVERT(VARCHAR,DATEDIFF(MINUTE,CING.[FECHA INGRESO],HC.FECALTPAC)/60)+','+CONVERT(VARCHAR,DATEDIFF(MINUTE,CING.[FECHA INGRESO],HC.FECALTPAC)%60) AS [FECHA INGRESO VS FECHA DE ALTA EN HORAS],
 CONVERT(VARCHAR,DATEDIFF(MINUTE,CING.[FECHA INGRESO],HC.FECALTPAC)/60)+','+REPLACE(CONVERT(VARCHAR,CONVERT(INT,ROUND((DATEDIFF(MINUTE,CING.[FECHA INGRESO],HC.FECALTPAC)%60)/0.60,0))),'-','') AS [FECHA INGRESO VS FECHA DE ALTA EN HORAS],
 CONVERT(VARCHAR,DATEDIFF(HOUR,CING.[FECHA INGRESO],HC.FECALTPAC)/24)+','+REPLACE(CONVERT(VARCHAR,CONVERT(INT,ROUND((DATEDIFF(HOUR,CING.[FECHA INGRESO],HC.FECALTPAC)%24)/0.24,0))),'-','') AS [FECHA INGRESO VS FECHA DE ALTA EN DIAS],
 CONVERT(VARCHAR,DATEDIFF(MINUTE,HC.FECALTPAC,CTUE.[FECHA EGRESO])/60)+','+REPLACE(CONVERT(VARCHAR,CONVERT(INT,ROUND((DATEDIFF(MINUTE,HC.FECALTPAC,CTUE.[FECHA EGRESO])%60)/0.60,0))),'-','') AS [FECHA ALTA MEDICA VS FECHA DE EGRESO EN HORAS],
 SAL.Code AS [CODIGO BOLETA DE SALIDA],
 HC.FECMUEPAC AS [FECHA DE MUERTE],
 CASE HC.CODCAUMUE  WHEN 001 THEN 'MUERTE NATURAL'
                    WHEN 002 THEN 'MUERTE VIOLENTA'
                    WHEN 003 THEN 'MUERTE EN ESTUDIO' END AS [CAUSA DE MUERTE],
 HC.NUMCERDEF AS [NO_CERT_DEFUNCION],
 IIF(DATEDIFF(MINUTE,CING.[FECHA INGRESO],HC.FECMUEPAC)/60<=48,'SI','NO') AS [MUERTE < 48 HORAS],
 IIF(DATEDIFF(MINUTE,CING.[FECHA INGRESO],HC.FECMUEPAC)/60>=48,'SI','NO') AS [MUERTE > 48 HORAS],
 1 as 'CANTIDAD',
 CAST(HC.FECALTPAC AS date) AS 'FECHA BUSQUEDA',
 YEAR(HC.FECALTPAC) AS 'AÑO BUSQUEDA',
 MONTH(HC.FECALTPAC) AS 'MES BUSQUEDA',
 CONCAT(FORMAT(MONTH(HC.FECALTPAC), '00') ,' - ', 
	   CASE MONTH(HC.FECALTPAC) 
	    WHEN 1 THEN 'ENERO'
   	    WHEN 2 THEN 'FEBRERO'
	    WHEN 3 THEN 'MARZO'
	    WHEN 4 THEN 'ABRIL'
	    WHEN 5 THEN 'MAYO'
	    WHEN 6 THEN 'JUNIO'
	    WHEN 7 THEN 'JULIO'
	    WHEN 8 THEN 'AGOSTO'
	    WHEN 9 THEN 'SEPTIEMBRE'
	    WHEN 10 THEN 'OCTUBRE'
	    WHEN 11 THEN 'NOVIEMBRE'
	    WHEN 12 THEN 'DICIEMBRE' END) 'MES NOMBRE BUSQUEDA',
 CONVERT(DATETIME,GETDATE() AT TIME ZONE 'Pakistan Standard Time',1) AS ULT_ACTUAL
FROM 
 HCREGEGRE HC
 INNER JOIN ADINGRESO AS ING ON HC.NUMINGRES=ING.NUMINGRES
 LEFT JOIN dbo.CHCAMASHO CAM ON ING.CODCAMACT=CAM.CODICAMAS
 INNER JOIN INGRESO_INICIAL EI ON HC.NUMINGRES = EI.NUMINGRES
 INNER JOIN CTE_ULTIMO_INGRESO CTUE ON HC.NUMINGRES = CTUE.NUMINGRES
 LEFT JOIN CTE_PRIMER_INGRESO CING ON CING.NUMINGRES =HC.NUMINGRES 
 INNER JOIN HCHISPACA HIS ON HC.NUMINGRES = HIS.NUMINGRES AND HC.NUMEFOLIO = HIS.NUMEFOLIO
 INNER JOIN INPACIENT AS PAC ON PAC.IPCODPACI = HC.IPCODPACI
 INNER JOIN ADCENATEN AS CEN ON HC.CODCENATE = CEN.CODCENATE
 INNER JOIN INUNIFUNC UNI ON HC.UFUCODIGO = UNI.UFUCODIGO
 INNER JOIN.CONTRACT.HEALTHADMINISTRATOR HEA ON ING.GENCONENTITY = HEA.ID
 INNER JOIN.CONTRACT.CAREGROUP AS CGR ON ING.GENCAREGROUP = CGR.ID
 LEFT JOIN INPROFSAL PRO ON HIS.CODPROSAL = PRO.CODPROSAL
 LEFT JOIN INESPECIA AS ESP ON ESP.CODESPECI = HIS.CODESPTRA
 LEFT JOIN INDIAGNOS AS DIA ON ING.CODDIAING = DIA.CODDIAGNO
 LEFT JOIN INDIAGNOS AS DIAE ON ING.CODDIAEGR = DIAE.CODDIAGNO
 LEFT JOIN dbo.INUBICACI UBI on pac.AUUBICACI=UBI.AUUBICACI
LEFT JOIN dbo.INMUNICIP MUN ON UBI.DEPMUNCOD=MUN.DEPMUNCOD 
LEFT JOIN dbo.INDEPARTA DEP ON MUN.DEPCODIGO=DEP.depcodigo
LEFT JOIN CTE_ULTIMA_CAMAS_OCUPADA CO ON HC.NUMINGRES=CO.NUMINGRES
LEFT JOIN Billing.SlipOut SAL ON HC.NUMINGRES=SAL.AdmissionNumber
LEFT JOIN dbo.ADNIVELES NIV ON PAC.NIVCODIGO=NIV.NIVCODIGO
--where HC.FECALTPAC is null
--WHERE CAST(ING.IFECHAING as date) BETWEEN '2023-09-01' AND '2023-09-30'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Vista de reporting para egresos hospitalarios que consolida, por ingreso de paciente, datos demográficos, de aseguramiento (EPS, régimen, tipo de afiliación), trayectoria de cama (unidad funcional de ingreso y egreso), diagnósticos de ingreso y egreso, fechas y horas de hospitalización, alta médica y egreso administrativo, estado y destino al egreso, causa de muerte si aplica, y boleta de salida. Está orientada a informes de gestión hospitalaria y auditoría de estancias.', @level0type=N'SCHEMA', @level0name=N'Report', @level1type=N'VIEW', @level1name=N'ViewEgresosHospitalarios';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DescriptionSource', @value=N'ai_claude-sonnet-4-6_2026-05-05', @level0type=N'SCHEMA', @level0name=N'Report', @level1type=N'VIEW', @level1name=N'ViewEgresosHospitalarios';
GO
GO
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_DomainConcepts', @value=N'Egreso hospitalario; Ingreso/Admisión hospitalaria; Alta médica; Estancia (cama, unidad funcional); Diagnóstico de ingreso y egreso; Régimen de afiliación (contributivo/subsidiado/vinculado/particular/desplazado); Tipo de afiliación (cotizante/beneficiario/...); Tipo de documento de identidad; Etnia del paciente; Tipo de unidad funcional (UCI, urgencias, hospitalización, etc.); Estado del paciente al egreso; Destino del paciente al egreso; Causa y certificado de defunción; Mortalidad < 48 horas / > 48 horas; Boleta de salida (SlipOut) de facturación; Ubicación geográfica (departamento/municipio); EPS / Entidad administradora de salud; Grupo de atención del contrato; Especialidad tratante; Profesional de la salud responsable del egreso; Nivel SISBEN/estrato', @level0type=N'SCHEMA', @level0name=N'Report', @level1type=N'VIEW', @level1name=N'ViewEgresosHospitalarios';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_Decisions', @value=N'si PAC.IPTIPOPAC entre 1 y 7 (o distinto) → Mapea el tipo de paciente a régimen de afiliación: 1=CONTRIBUTIVO, 2=SUBSIDIADO, 3=VINCULADO, 4=PARTICULAR, 5=OTRO, 6=DESPLAZADO REG. CONTRIBUTIVO, 7=DESPLAZADO REG. SUBSIDIADO else DESPLAZADO NO ASEGURADO; si PAC.IPTIPOAFI 0..5 → Mapea tipo de afiliación: 0=No Aplica, 1=Cotizante, 2=Beneficiario, 3=Adicional, 4=Jub/Retirado, 5=Pensionado; si PAC.IPTIPODOC 1..12 → Mapea código de tipo de documento a sigla (CC, CE, TI, RC, PA, AS, MS, NU, NV, CD, SC, PE) y a su descripción larga; si Edad calculada (FECALTPAC - IPFECNACI)/10000 → Clasifica en rangos: 0-5, 6-11, 12-17, 18-28, 29-59, Mayor 60 Años; si PAC.IPSEXOPAC = ''1'' → Sexo = ''M'' else Sexo = ''F''; si PAC.CODGRUPOE en (000,001,002,003,004,999) → Mapea etnia: 000=OTRO, 001=INDIGENAS, 002=AFROCOLOMBIANOS..., 003=RAIZALES SAN ANDRES Y PROVIDENCIA, 004=PUEBLO ROM GITANOS, 999=NO SABE NO INFORMA NO APLICA else NO REGISTRA; si UNI.UFUTIPUNI 1..31 → Clasifica el tipo de unidad funcional (URGENCIAS, HOSPITALIZACION, APOYO DIAGNOSTICO/TERAPEUTICO, UCI [valores 5..11], UNIDAD RENAL, ONCOLOGICA, MEDICINA NUCLEAR, CONSULTA EXTERNA, MENTAL, QUEMADOS, CUIDADOS PALIATIVOS, CIRUGIA, LABORATORIOS, CARDIOLOGIA, GINECO OBSTETRICIA, OTRAS, CONSULTA PRIORITARIA); si EI.CODTIPEST en (001,002,003) → Tipo de estancia: 001=GENERAL, 002=CUIDADO BASICO, 003=CUIDADO INTERMEDIO else CUIDADO INTENSIVO; si HC.ESTPACEGR 1..5 → Estado al egreso: 1=MEJOR, 2=IGUAL Y PEOR, 3=FALLECIDO, 4=REMITIDO, 5=HOSPITALIZACION EN CASA; si HIS.INDICAPAC 1..20 → Mapea destino del paciente (traslado a urgencias/observación/hospitalización/UCI adulto/pediátrica/neonatal/consulta externa/cirugía, hospitalización en casa, referencia, morgue, salida, continúa en unidad, tratamiento, retiro voluntario, fuga, salida parcial, estancia con la madre, U.Cuidado Intermedio, U.Básica); si HC.CODCAUMUE en (1,2,3) → Causa de muerte: 1=MUERTE NATURAL, 2=MUERTE VIOLENTA, 3=MUERTE EN ESTUDIO; si DATEDIFF(MINUTE, FECHA INGRESO, HC.FECMUEPAC)/60 <= 48 → [MUERTE < 48 HORAS] = ''SI'', sino ''NO''; si DATEDIFF(MINUTE, FECHA INGRESO, HC.FECMUEPAC)/60 >= 48 → [MUERTE > 48 HORAS] = ''SI'', sino ''NO''; si CTE_ULTIMA_CAMAS_OCUPADA: EGR.FECFINEST > ''1989-01-01'' → Solo se considera estancia válida (con cama de egreso) si la fecha fin de estancia es posterior a 1989-01-01', @level0type=N'SCHEMA', @level0name=N'Report', @level1type=N'VIEW', @level1name=N'ViewEgresosHospitalarios';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_Consumes', @value=N'dbo.ADINGRESO; dbo.INESPECIA; dbo.CHREGESTA; dbo.CHCAMASHO; Payroll.FunctionalUnit; dbo.INUNIFUNC; dbo.CHTIPESTA; dbo.HCREGEGRE; dbo.HCHISPACA; dbo.INPACIENT; dbo.ADCENATEN; CONTRACT.HEALTHADMINISTRATOR; CONTRACT.CAREGROUP; dbo.INPROFSAL; dbo.INDIAGNOS; dbo.INUBICACI; dbo.INMUNICIP; dbo.INDEPARTA; Billing.SlipOut; dbo.ADNIVELES', @level0type=N'SCHEMA', @level0name=N'Report', @level1type=N'VIEW', @level1name=N'ViewEgresosHospitalarios';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_Source', @value=N'ai_claude-opus-4-7_tier-c_2026-05-06', @level0type=N'SCHEMA', @level0name=N'Report', @level1type=N'VIEW', @level1name=N'ViewEgresosHospitalarios';
GO
