/****** OBJECT:  DATABASE LOGGING    SCRIPT DATE: 8/22/2005 ******/
USE [GENESIS]
GO
 
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[CATEGORY]') AND OBJECTPROPERTY(ID, N'ISUSERTABLE') = 1)
BEGIN
CREATE TABLE [DBO].[CATEGORY](
	[CATEGORYID] [INT] IDENTITY(1,1) NOT NULL,
	[CATEGORYNAME] [NVARCHAR](64) NOT NULL,
 CONSTRAINT [PK_CATEGORIES] PRIMARY KEY CLUSTERED 
(
	[CATEGORYID] ASC
) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[CATEGORYLOG]') AND OBJECTPROPERTY(ID, N'ISUSERTABLE') = 1)
BEGIN
CREATE TABLE [DBO].[CATEGORYLOG](
	[CATEGORYLOGID] [INT] IDENTITY(1,1) NOT NULL,
	[CATEGORYID] [INT] NOT NULL,
	[LOGID] [INT] NOT NULL,
 CONSTRAINT [PK_CATEGORYLOG] PRIMARY KEY CLUSTERED 
(
	[CATEGORYLOGID] ASC
) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM DBO.SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[LOG]') AND OBJECTPROPERTY(ID, N'ISUSERTABLE') = 1)
BEGIN
CREATE TABLE [DBO].[LOG](
	[LOGID] [INT] IDENTITY(1,1) NOT NULL,
	[EVENTID] [INT] NULL,
	[PRIORITY] [INT] NOT NULL,
	[SEVERITY] [NVARCHAR](32) NOT NULL,
	[TITLE] [NVARCHAR](256) NOT NULL,
	[TIMESTAMP] [DATETIME] NOT NULL,
	[MACHINENAME] [NVARCHAR](32) NOT NULL,
	[APPDOMAINNAME] [NVARCHAR](512) NOT NULL,
	[PROCESSID] [NVARCHAR](256) NOT NULL,
	[PROCESSNAME] [NVARCHAR](512) NOT NULL,
	[THREADNAME] [NVARCHAR](512) NULL,
	[WIN32THREADID] [NVARCHAR](128) NULL,
	[MESSAGE] [NVARCHAR](1500) NULL,
	[FORMATTEDMESSAGE] [NTEXT] NULL,
 CONSTRAINT [PK_LOG] PRIMARY KEY CLUSTERED 
(
	[LOGID] ASC
) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[INSERTCATEGORYLOG]') AND TYPE IN (N'P', N'PC'))
BEGIN
EXEC DBO.SP_EXECUTESQL @STATEMENT = N'CREATE PROCEDURE INSERTCATEGORYLOG
	@CATEGORYID INT,
	@LOGID INT
AS
BEGIN
	SET NOCOUNT ON;
 
	DECLARE @CATLOGID INT
	SELECT @CATLOGID FROM CATEGORYLOG WHERE CATEGORYID=@CATEGORYID AND LOGID = @LOGID
	IF @CATLOGID IS NULL
	BEGIN
		INSERT INTO CATEGORYLOG (CATEGORYID, LOGID) VALUES(@CATEGORYID, @LOGID)
		RETURN @@IDENTITY
	END
	ELSE RETURN @CATLOGID
END
' 
END
GO
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[ADDCATEGORY]') AND TYPE IN (N'P', N'PC'))
BEGIN
EXEC DBO.SP_EXECUTESQL @STATEMENT = N'
 
CREATE PROCEDURE [DBO].[ADDCATEGORY]
	-- ADD THE PARAMETERS FOR THE FUNCTION HERE
	@CATEGORYNAME NVARCHAR(64),
	@LOGID INT
AS
BEGIN
	SET NOCOUNT ON;
	DECLARE @CATID INT
	SELECT @CATID = CATEGORYID FROM CATEGORY WHERE CATEGORYNAME = @CATEGORYNAME
	IF @CATID IS NULL
	BEGIN
		INSERT INTO CATEGORY (CATEGORYNAME) VALUES(@CATEGORYNAME)
		SELECT @CATID = @@IDENTITY
	END
 
	EXEC INSERTCATEGORYLOG @CATID, @LOGID 
 
	RETURN @CATID
END
 
' 
END
GO
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[CLEARLOGS]') AND TYPE IN (N'P', N'PC'))
BEGIN
EXEC DBO.SP_EXECUTESQL @STATEMENT = N'CREATE PROCEDURE CLEARLOGS
AS
BEGIN
	SET NOCOUNT ON;
 
	DELETE FROM CATEGORYLOG
	DELETE FROM [LOG]
	DELETE FROM CATEGORY
END
' 
END
GO
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID(N'[DBO].[WRITELOG]') AND TYPE IN (N'P', N'PC'))
BEGIN
EXEC DBO.SP_EXECUTESQL @STATEMENT = N'
 
 
 
/****** OBJECT:  STORED PROCEDURE DBO.WRITELOG    SCRIPT DATE: 10/1/2004 3:16:36 PM ******/
 
CREATE PROCEDURE [DBO].[WRITELOG]
(
	@EVENTID INT, 
	@PRIORITY INT, 
	@SEVERITY NVARCHAR(32), 
	@TITLE NVARCHAR(256), 
	@TIMESTAMP DATETIME,
	@MACHINENAME NVARCHAR(32), 
	@APPDOMAINNAME NVARCHAR(512),
	@PROCESSID NVARCHAR(256),
	@PROCESSNAME NVARCHAR(512),
	@THREADNAME NVARCHAR(512),
	@WIN32THREADID NVARCHAR(128),
	@MESSAGE NVARCHAR(1500),
	@FORMATTEDMESSAGE NTEXT,
	@LOGID INT OUTPUT
)
AS 
 
	INSERT INTO [LOG] (
		EVENTID,
		PRIORITY,
		SEVERITY,
		TITLE,
		[TIMESTAMP],
		MACHINENAME,
		APPDOMAINNAME,
		PROCESSID,
		PROCESSNAME,
		THREADNAME,
		WIN32THREADID,
		MESSAGE,
		FORMATTEDMESSAGE
	)
	VALUES (
		@EVENTID, 
		@PRIORITY, 
		@SEVERITY, 
		@TITLE, 
		@TIMESTAMP,
		@MACHINENAME, 
		@APPDOMAINNAME,
		@PROCESSID,
		@PROCESSNAME,
		@THREADNAME,
		@WIN32THREADID,
		@MESSAGE,
		@FORMATTEDMESSAGE)
 
	SET @LOGID = @@IDENTITY
	RETURN @LOGID
 
 
 
' 
END
GO
SET ANSI_NULLS OFF
GO
SET QUOTED_IDENTIFIER OFF
GO
IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID(N'FK_CATEGORYLOG_CATEGORY') AND PARENT_OBJ = OBJECT_ID(N'[DBO].[CATEGORYLOG]'))
ALTER TABLE [DBO].[CATEGORYLOG]  WITH CHECK ADD  CONSTRAINT [FK_CATEGORYLOG_CATEGORY] FOREIGN KEY(	[CATEGORYID])
REFERENCES [DBO].[CATEGORY] (	[CATEGORYID])
GO
IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE ID = OBJECT_ID(N'FK_CATEGORYLOG_LOG') AND PARENT_OBJ = OBJECT_ID(N'[DBO].[CATEGORYLOG]'))
ALTER TABLE [DBO].[CATEGORYLOG]  WITH CHECK ADD  CONSTRAINT [FK_CATEGORYLOG_LOG] FOREIGN KEY(	[LOGID])
REFERENCES [DBO].[LOG] (	[LOGID])
GO
 
SET QUOTED_IDENTIFIER ON 
SET ARITHABORT ON 
SET CONCAT_NULL_YIELDS_NULL ON 
SET ANSI_NULLS ON 
SET ANSI_PADDING ON 
SET ANSI_WARNINGS ON 
SET NUMERIC_ROUNDABORT OFF 
GO
 
DECLARE @BERRORS AS BIT
 
BEGIN TRANSACTION
SET @BERRORS = 0
 
CREATE NONCLUSTERED INDEX [IXCATEGORYLOG] ON [DBO].[CATEGORYLOG] ([LOGID] ASC, [CATEGORYID] ASC )
IF( @@ERROR <> 0 ) SET @BERRORS = 1
 
IF( @BERRORS = 0 )
  COMMIT TRANSACTION
ELSE
  ROLLBACK TRANSACTION
