'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Namespace GENESISDOCUMENTAL01

    Partial Public Class Metadata
        Inherits XPLiteObject
        Dim fId As Integer
        <Key(True)> _
        Public Property Id() As Integer
            Get
                Return fId
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Id", fId, value)
            End Set
        End Property
        Dim fIdFileContainer As FileContainer
        <Association("MetadataReferencesFileContainer")> _
        Public Property IdFileContainer() As FileContainer
            Get
                Return fIdFileContainer
            End Get
            Set(ByVal value As FileContainer)
                SetPropertyValue(Of FileContainer)("IdFileContainer", fIdFileContainer, value)
            End Set
        End Property
        Dim fName As String
        <Size(50)> _
        Public Property Name() As String
            Get
                Return fName
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("Name", fName, value)
            End Set
        End Property
        Dim fDataType As String
        <Size(20)> _
        Public Property DataType() As String
            Get
                Return fDataType
            End Get
            Set(ByVal value As String)
                SetPropertyValue(Of String)("DataType", fDataType, value)
            End Set
        End Property
        Dim fLong1 As Integer
        <Persistent("Long")> _
        Public Property Long1() As Integer
            Get
                Return fLong1
            End Get
            Set(ByVal value As Integer)
                SetPropertyValue(Of Integer)("Long1", fLong1, value)
            End Set
        End Property
        Dim fState As Boolean
        Public Property State() As Boolean
            Get
                Return fState
            End Get
            Set(ByVal value As Boolean)
                SetPropertyValue(Of Boolean)("State", fState, value)
            End Set
        End Property
    End Class

End Namespace
