'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel


Partial Public Class INDIAGNOP
    Inherits XPLiteObject
    Dim fIDETIPHIS As String
    <Size(9)> _
    Public Property IDETIPHIS() As String
        Get
            Return fIDETIPHIS
        End Get
        Set(ByVal value As String)
            SetPropertyValue(Of String)("IDETIPHIS", fIDETIPHIS, value)
        End Set
    End Property

    Dim fCODDIAGNO As String
    <Size(4)> _
    Public Property CODDIAGNO() As String
        Get
            Return fCODDIAGNO
        End Get
        Set(ByVal value As String)
            SetPropertyValue(Of String)("CODDIAGNO", fCODDIAGNO, value)
        End Set
    End Property

    Dim fNUMEFOLIO As String
    <Size(10)> _
    Public Property NUMEFOLIO() As String
        Get
            Return fNUMEFOLIO
        End Get
        Set(ByVal value As String)
            SetPropertyValue(Of String)("NUMEFOLIO", fNUMEFOLIO, value)
        End Set
    End Property

    Dim fCODCENATE As String
    <Size(10)> _
    Public Property CODCENATE() As String
        Get
            Return fCODCENATE
        End Get
        Set(ByVal value As String)
            SetPropertyValue(Of String)("CODCENATE", fCODCENATE, value)
        End Set
    End Property
    Dim fUFUCODIGO As String
    <Size(10)> _
    Public Property UFUCODIGO() As String
        Get
            Return fUFUCODIGO
        End Get
        Set(ByVal value As String)
            SetPropertyValue(Of String)("UFUCODIGO", fUFUCODIGO, value)
        End Set
    End Property
    Dim fCODPROSAL As String
    <Size(20)> _
    Public Property CODPROSAL() As String
        Get
            Return fCODPROSAL
        End Get
        Set(ByVal value As String)
            SetPropertyValue(Of String)("CODPROSAL", fCODPROSAL, value)
        End Set
    End Property
    Dim fDIAINGEGR As Char
    Public Property DIAINGEGR() As Char
        Get
            Return fDIAINGEGR
        End Get
        Set(ByVal value As Char)
            SetPropertyValue(Of Char)("DIAINGEGR", fDIAINGEGR, value)
        End Set
    End Property
    Dim fTIPDIAGNO As Char
    Public Property TIPDIAGNO() As Char
        Get
            Return fTIPDIAGNO
        End Get
        Set(ByVal value As Char)
            SetPropertyValue(Of Char)("TIPDIAGNO", fTIPDIAGNO, value)
        End Set
    End Property
    Dim fCLADIAGNO As String
    <Size(2)> _
    Public Property CLADIAGNO() As String
        Get
            Return fCLADIAGNO
        End Get
        Set(ByVal value As String)
            SetPropertyValue(Of String)("CLADIAGNO", fCLADIAGNO, value)
        End Set
    End Property
    Dim fOBSDIAGNO As String
    <Size(250)> _
    Public Property OBSDIAGNO() As String
        Get
            Return fOBSDIAGNO
        End Get
        Set(ByVal value As String)
            SetPropertyValue(Of String)("OBSDIAGNO", fOBSDIAGNO, value)
        End Set
    End Property
    Dim fFECDIAGNO As DateTime
    Public Property FECDIAGNO() As DateTime
        Get
            Return fFECDIAGNO
        End Get
        Set(ByVal value As DateTime)
            SetPropertyValue(Of DateTime)("FECDIAGNO", fFECDIAGNO, value)
        End Set
    End Property
    Dim fFOLDIAGNO As Integer
    Public Property FOLDIAGNO() As Integer
        Get
            Return fFOLDIAGNO
        End Get
        Set(ByVal value As Integer)
            SetPropertyValue(Of Integer)("FOLDIAGNO", fFOLDIAGNO, value)
        End Set
    End Property
    Dim fDIAESTADO As Integer
    Public Property DIAESTADO() As Integer
        Get
            Return fDIAESTADO
        End Get
        Set(ByVal value As Integer)
            SetPropertyValue(Of Integer)("DIAESTADO", fDIAESTADO, value)
        End Set
    End Property
    Dim fINDAUDFOR As Decimal
    Public Property INDAUDFOR() As Decimal
        Get
            Return fINDAUDFOR
        End Get
        Set(ByVal value As Decimal)
            SetPropertyValue(Of Decimal)("INDAUDFOR", fINDAUDFOR, value)
        End Set
    End Property
    Dim fPLANTDIAG As String
    <Size(SizeAttribute.Unlimited)> _
    Public Property PLANTDIAG() As String
        Get
            Return fPLANTDIAG
        End Get
        Set(ByVal value As String)
            SetPropertyValue(Of String)("PLANTDIAG", fPLANTDIAG, value)
        End Set
    End Property
    Dim fTRATA4505 As Integer
    Public Property TRATA4505() As Integer
        Get
            Return fTRATA4505
        End Get
        Set(ByVal value As Integer)
            SetPropertyValue(Of Integer)("TRATA4505", fTRATA4505, value)
        End Set
    End Property
    Dim fFECHLEISH As DateTime
    Public Property FECHLEISH() As DateTime
        Get
            Return fFECHLEISH
        End Get
        Set(ByVal value As DateTime)
            SetPropertyValue(Of DateTime)("FECHLEISH", fFECHLEISH, value)
        End Set
    End Property
    Public Structure CompoundKey1Struct
        <Size(10)> _
        <Persistent("NUMINGRES")> _
        Public Property NUMINGRES As String
        <Size(15)> _
        <Persistent("IPCODPACI")> _
        Public Property IPCODPACI As String
        <Size(4)> _
        <Persistent("CODDIAGNO")> _
        Public Property CODDIAGNO As String
        <Persistent("CODDIAPRI")> _
        Public Property CODDIAPRI As Boolean
    End Structure
    <Key(), Persistent()> _
    Public CompoundKey1 As CompoundKey1Struct
    Public Sub New(ByVal session As Session)
        MyBase.New(session)
    End Sub
End Class


