'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel

<Persistent("dbo.ViewGetAdmission")>
Partial Public Class ViewGetAdmissionXpo
    Inherits XPLiteObject

#Region "Members"

    Dim fAdmissionCode As String
    <Key(True)>
    Public Property AdmissionCode() As String
        Get
            Return fAdmissionCode
        End Get
        Set(ByVal value As String)
            SetPropertyValue(Of String)("AdmissionCode", fAdmissionCode, value)
        End Set
    End Property

    Dim fPatientCode As String
    Public Property PatientCode() As String
        Get
            Return fPatientCode
        End Get
        Set(ByVal value As String)
            SetPropertyValue(Of String)("PatientCode", fPatientCode, value)
        End Set
    End Property

    Dim fPatientName As String
    Public Property PatientName() As String
        Get
            Return fPatientName
        End Get
        Set(ByVal value As String)
            SetPropertyValue(Of String)("PatientName", fPatientName, value)
        End Set
    End Property

    Dim fPatientDateBirth As DateTime
    Public Property PatientDateBirth() As DateTime
        Get
            Return fPatientDateBirth
        End Get
        Set(ByVal value As DateTime)
            SetPropertyValue(Of DateTime)("PatientDateBirth", fPatientDateBirth, value)
        End Set
    End Property

    Dim fPatientGenus As Integer
    Public Property PatientGenus() As Integer
        Get
            Return fPatientGenus
        End Get
        Set(ByVal value As Integer)
            SetPropertyValue(Of Integer)("PatientGenus", fPatientGenus, value)
        End Set
    End Property

    Dim fAdmissionDate As DateTime
    Public Property AdmissionDate() As DateTime
        Get
            Return fAdmissionDate
        End Get
        Set(ByVal value As DateTime)
            SetPropertyValue(Of DateTime)("AdmissionDate", fAdmissionDate, value)
        End Set
    End Property

    Dim fAdmissionType As Integer
    Public Property AdmissionType() As Integer
        Get
            Return fAdmissionType
        End Get
        Set(ByVal value As Integer)
            SetPropertyValue(Of Integer)("AdmissionType", fAdmissionType, value)
        End Set
    End Property

    Dim fBedStay As String
    Public Property BedStay() As String
        Get
            Return fBedStay
        End Get
        Set(ByVal value As String)
            SetPropertyValue(Of String)("BedStay", fBedStay, value)
        End Set
    End Property

    Dim fPlaceEntry As Integer
    Public Property PlaceEntry() As Integer
        Get
            Return fPlaceEntry
        End Get
        Set(ByVal value As Integer)
            SetPropertyValue(Of Integer)("PlaceEntry", fPlaceEntry, value)
        End Set
    End Property

    Dim fLiquidationType As Integer
    Public Property LiquidationType() As Integer
        Get
            Return fLiquidationType
        End Get
        Set(ByVal value As Integer)
            SetPropertyValue(Of Integer)("LiquidationType", fLiquidationType, value)
        End Set
    End Property

    Dim fBenefitPlan As String
    Public Property BenefitPlan() As String
        Get
            Return fBenefitPlan
        End Get
        Set(ByVal value As String)
            SetPropertyValue(Of String)("BenefitPlan", fBenefitPlan, value)
        End Set
    End Property

    Dim fEntityCode As String
    Public Property EntityCode() As String
        Get
            Return fEntityCode
        End Get
        Set(ByVal value As String)
            SetPropertyValue(Of String)("EntityCode", fEntityCode, value)
        End Set
    End Property

    Dim fEntityName As String
    Public Property EntityName() As String
        Get
            Return fEntityName
        End Get
        Set(ByVal value As String)
            SetPropertyValue(Of String)("EntityName", fEntityName, value)
        End Set
    End Property

    Dim fAuthorizationNumber As String
    Public Property AuthorizationNumber() As String
        Get
            Return fAuthorizationNumber
        End Get
        Set(ByVal value As String)
            SetPropertyValue(Of String)("AuthorizationNumber", fAuthorizationNumber, value)
        End Set
    End Property

    Dim fResponsibleName As String
    Public Property ResponsibleName() As String
        Get
            Return fResponsibleName
        End Get
        Set(ByVal value As String)
            SetPropertyValue(Of String)("ResponsibleName", fResponsibleName, value)
        End Set
    End Property

    Dim fResponsiblePhone As String
    Public Property ResponsiblePhone() As String
        Get
            Return fResponsiblePhone
        End Get
        Set(ByVal value As String)
            SetPropertyValue(Of String)("ResponsiblePhone", fResponsiblePhone, value)
        End Set
    End Property

    Dim fCareGroupId As Integer
    Public Property CareGroupId() As Integer
        Get
            Return fCareGroupId
        End Get
        Set(ByVal value As Integer)
            SetPropertyValue(Of Integer)("CareGroupId", fCareGroupId, value)
        End Set
    End Property

    Dim fHealthAdministratorId As Integer
    Public Property HealthAdministratorId() As Integer
        Get
            Return fHealthAdministratorId
        End Get
        Set(ByVal value As Integer)
            SetPropertyValue(Of Integer)("HealthAdministratorId", fHealthAdministratorId, value)
        End Set
    End Property

    Dim fStatus As String
    Public Property Status() As String
        Get
            Return fStatus
        End Get
        Set(ByVal value As String)
            SetPropertyValue(Of String)("Status", fStatus, value)
        End Set
    End Property

    Dim fTRATAESPECIA As Integer
    Public Property TRATAESPECIA() As Integer
        Get
            Return fTRATAESPECIA
        End Get
        Set(ByVal value As Integer)
            SetPropertyValue(Of Integer)("TRATAESPECIA", fTRATAESPECIA, value)
        End Set
    End Property

    Dim fFullNameAdmission As String
    Public Property FullNameAdmission() As String
        Get
            Return fFullNameAdmission
        End Get
        Set(ByVal value As String)
            SetPropertyValue(Of String)("FullNameAdmission", fFullNameAdmission, value)
        End Set
    End Property

    Dim fCenterAttentionCode As String
    Public Property CenterAttentionCode() As String
        Get
            Return fCenterAttentionCode
        End Get
        Set(ByVal value As String)
            SetPropertyValue(Of String)("CenterAttentionCode", fCenterAttentionCode, value)
        End Set
    End Property

#End Region

#Region "Builders"

    Public Sub New(ByVal session As Session)
        MyBase.New(session)
    End Sub

#End Region

End Class