Partial Class ImageCollectionManager
    Inherits System.ComponentModel.Component

    <System.Diagnostics.DebuggerNonUserCode()> _
    Public Sub New(ByVal container As System.ComponentModel.IContainer)
        MyClass.New()

        'Required for System.Windows.Forms Class Composition Designer support
        If (container IsNot Nothing) Then
            container.Add(Me)
        End If

    End Sub

    <System.Diagnostics.DebuggerNonUserCode()> _
    Public Sub New()
        MyBase.New()

        'This call is required by the Component Designer.
        InitializeComponent()

    End Sub

    'Component overrides dispose to clean up the component list.
    <System.Diagnostics.DebuggerNonUserCode()> _
    Protected Overrides Sub Dispose(ByVal disposing As Boolean)
        Try
            If disposing AndAlso components IsNot Nothing Then
                components.Dispose()
            End If
        Finally
            MyBase.Dispose(disposing)
        End Try
    End Sub

    'Required by the Component Designer
    Private components As System.ComponentModel.IContainer

    'NOTE: The following procedure is required by the Component Designer
    'It can be modified using the Component Designer.
    'Do not modify it using the code editor.
    <System.Diagnostics.DebuggerStepThrough()> _
    Private Sub InitializeComponent()
        Me.components = New System.ComponentModel.Container()
        Dim resources As System.ComponentModel.ComponentResourceManager = New System.ComponentModel.ComponentResourceManager(GetType(ImageCollectionManager))
        Me.ToolBarIconsBrownLarge = New DevExpress.Utils.ImageCollection(Me.components)
        Me.ImageIconsOtherBlue = New DevExpress.Utils.ImageCollection(Me.components)
        Me.ToolBarIconsGreenLarge = New DevExpress.Utils.ImageCollection(Me.components)
        Me.ToolBarIconsLilaLarge = New DevExpress.Utils.ImageCollection(Me.components)
        Me.ToolBarIconsFucsiaLarge = New DevExpress.Utils.ImageCollection(Me.components)
        Me.ToolBarIconsWhiteLarge = New DevExpress.Utils.ImageCollection(Me.components)
        Me.ToolBarIconsBlueLarge = New DevExpress.Utils.ImageCollection(Me.components)
        Me.ImageIconsOtherWhite = New DevExpress.Utils.ImageCollection(Me.components)
        Me.ToolBarIconsBlueSmall = New DevExpress.Utils.ImageCollection(Me.components)
        Me.ToolBarIconsWhiteSmall = New DevExpress.Utils.ImageCollection(Me.components)
        Me.ToolBarIconsBrownSmall = New DevExpress.Utils.ImageCollection(Me.components)
        Me.ToolBarIconsFucsiaSmall = New DevExpress.Utils.ImageCollection(Me.components)
        Me.ToolBarIconsGreenSmall = New DevExpress.Utils.ImageCollection(Me.components)
        Me.ToolBarIconsLilaSmall = New DevExpress.Utils.ImageCollection(Me.components)
        Me.ImageIconsOtherBrown = New DevExpress.Utils.ImageCollection(Me.components)
        Me.ImageIconsOtherFucsia = New DevExpress.Utils.ImageCollection(Me.components)
        Me.ImageIconsOtherLila = New DevExpress.Utils.ImageCollection(Me.components)
        Me.ImageIconsOtherGreen = New DevExpress.Utils.ImageCollection(Me.components)
        Me.ImageIconMessageIndigo = New DevExpress.Utils.ImageCollection(Me.components)
        Me.ImageIconMessageErrorIndigo = New DevExpress.Utils.ImageCollection(Me.components)
        CType(Me.ToolBarIconsBrownLarge, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ImageIconsOtherBlue, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ToolBarIconsGreenLarge, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ToolBarIconsLilaLarge, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ToolBarIconsFucsiaLarge, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ToolBarIconsWhiteLarge, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ToolBarIconsBlueLarge, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ImageIconsOtherWhite, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ToolBarIconsBlueSmall, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ToolBarIconsWhiteSmall, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ToolBarIconsBrownSmall, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ToolBarIconsFucsiaSmall, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ToolBarIconsGreenSmall, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ToolBarIconsLilaSmall, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ImageIconsOtherBrown, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ImageIconsOtherFucsia, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ImageIconsOtherLila, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ImageIconsOtherGreen, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ImageIconMessageIndigo, System.ComponentModel.ISupportInitialize).BeginInit()
        CType(Me.ImageIconMessageErrorIndigo, System.ComponentModel.ISupportInitialize).BeginInit()
        '
        'ToolBarIconsBrownLarge
        '
        Me.ToolBarIconsBrownLarge.ImageSize = New System.Drawing.Size(32, 32)
        Me.ToolBarIconsBrownLarge.ImageStream = CType(resources.GetObject("ToolBarIconsBrownLarge.ImageStream"), DevExpress.Utils.ImageCollectionStreamer)
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(0, "0.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(1, "1.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(2, "2.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(3, "3.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(4, "4.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(5, "5.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(6, "6.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(7, "7.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(8, "8.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(9, "9.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(10, "10.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(11, "11.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(12, "12.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(13, "13.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(14, "14.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(15, "15.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(16, "16.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(17, "17.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(18, "18.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(19, "19.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(20, "20.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(21, "21.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(22, "22.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(23, "23.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(24, "24.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(25, "25.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(26, "26.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(27, "27.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(28, "28.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(29, "29.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(30, "30.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(31, "31.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(32, "32.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(33, "33.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(34, "34.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(35, "35.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(36, "36.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(37, "37.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(38, "38.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(39, "39.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(40, "40.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(41, "41.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(42, "42.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(43, "43.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(44, "44.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(45, "45.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(46, "46.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(47, "47.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(48, "48.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(49, "49.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(50, "50.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(51, "51.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(52, "52.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(53, "53.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(54, "54.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(55, "55.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(56, "56.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(57, "57.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(58, "58.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(59, "59.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(60, "60.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(61, "61.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(62, "62.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(63, "63.png")
        Me.ToolBarIconsBrownLarge.Images.SetKeyName(64, "64.png")
        '
        'ImageIconsOtherBlue
        '
        Me.ImageIconsOtherBlue.ImageStream = CType(resources.GetObject("ImageIconsOtherBlue.ImageStream"), DevExpress.Utils.ImageCollectionStreamer)
        Me.ImageIconsOtherBlue.Images.SetKeyName(0, "ajustes 16x16_a.png")
        Me.ImageIconsOtherBlue.Images.SetKeyName(1, "Notification24_1.png")
        Me.ImageIconsOtherBlue.Images.SetKeyName(2, "Vituel24.png")
        Me.ImageIconsOtherBlue.Images.SetKeyName(3, "21.png")
        Me.ImageIconsOtherBlue.Images.SetKeyName(4, "22.png")
        Me.ImageIconsOtherBlue.Images.SetKeyName(5, "23.png")
        Me.ImageIconsOtherBlue.Images.SetKeyName(6, "24.png")
        Me.ImageIconsOtherBlue.Images.SetKeyName(7, "25.png")
        Me.ImageIconsOtherBlue.Images.SetKeyName(8, "26.png")
        Me.ImageIconsOtherBlue.Images.SetKeyName(9, "27.png")
        Me.ImageIconsOtherBlue.Images.SetKeyName(10, "28.png")
        '
        'ToolBarIconsGreenLarge
        '
        Me.ToolBarIconsGreenLarge.ImageSize = New System.Drawing.Size(32, 32)
        Me.ToolBarIconsGreenLarge.ImageStream = CType(resources.GetObject("ToolBarIconsGreenLarge.ImageStream"), DevExpress.Utils.ImageCollectionStreamer)
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(0, "0.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(1, "1.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(2, "2.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(3, "3.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(4, "4.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(5, "5.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(6, "6.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(7, "7.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(8, "8.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(9, "9.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(10, "10.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(11, "11.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(12, "12.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(13, "13.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(14, "14.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(15, "15.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(16, "16.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(17, "17.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(18, "18.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(19, "19.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(20, "20.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(21, "21.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(22, "22.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(23, "23.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(24, "24.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(25, "25.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(26, "26.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(27, "27.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(28, "28.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(29, "29.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(30, "30.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(31, "31.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(32, "32.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(33, "33.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(34, "34.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(35, "35.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(36, "36.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(37, "37.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(38, "38.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(39, "39.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(40, "40.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(41, "41.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(42, "42.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(43, "43.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(44, "44.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(45, "45.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(46, "46.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(47, "47.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(48, "48.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(49, "49.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(50, "50.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(51, "51.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(52, "52.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(53, "53.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(54, "54.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(55, "55.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(56, "56.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(57, "57.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(58, "58.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(59, "59.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(60, "60.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(61, "61.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(62, "62.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(63, "63.png")
        Me.ToolBarIconsGreenLarge.Images.SetKeyName(64, "64.png")
        '
        'ToolBarIconsLilaLarge
        '
        Me.ToolBarIconsLilaLarge.ImageSize = New System.Drawing.Size(32, 32)
        Me.ToolBarIconsLilaLarge.ImageStream = CType(resources.GetObject("ToolBarIconsLilaLarge.ImageStream"), DevExpress.Utils.ImageCollectionStreamer)
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(0, "0.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(1, "1.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(2, "2.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(3, "3.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(4, "4.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(5, "5.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(6, "6.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(7, "7.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(8, "8.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(9, "9.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(10, "10.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(11, "11.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(12, "12.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(13, "13.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(14, "14.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(15, "15.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(16, "16.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(17, "17.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(18, "18.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(19, "19.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(20, "20.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(21, "21.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(22, "22.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(23, "23.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(24, "24.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(25, "25.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(26, "26.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(27, "27.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(28, "28.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(29, "29.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(30, "30.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(31, "31.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(32, "32.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(33, "33.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(34, "34.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(35, "35.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(36, "36.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(37, "37.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(38, "38.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(39, "39.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(40, "40.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(41, "41.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(42, "42.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(43, "43.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(44, "44.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(45, "45.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(46, "46.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(47, "47.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(48, "48.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(49, "49.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(50, "50.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(51, "51.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(52, "52.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(53, "53.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(54, "54.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(55, "55.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(56, "56.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(57, "57.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(58, "58.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(59, "59.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(60, "60.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(61, "61.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(62, "62.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(63, "63.png")
        Me.ToolBarIconsLilaLarge.Images.SetKeyName(64, "64.png")
        '
        'ToolBarIconsFucsiaLarge
        '
        Me.ToolBarIconsFucsiaLarge.ImageSize = New System.Drawing.Size(32, 32)
        Me.ToolBarIconsFucsiaLarge.ImageStream = CType(resources.GetObject("ToolBarIconsFucsiaLarge.ImageStream"), DevExpress.Utils.ImageCollectionStreamer)
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(0, "0.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(1, "1.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(2, "2.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(3, "3.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(4, "4.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(5, "5.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(6, "6.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(7, "7.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(8, "8.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(9, "9.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(10, "10.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(11, "11.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(12, "12.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(13, "13.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(14, "14.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(15, "15.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(16, "16.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(17, "17.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(18, "18.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(19, "19.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(20, "20.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(21, "21.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(22, "22.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(23, "23.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(24, "24.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(25, "25.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(26, "26.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(27, "27.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(28, "28.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(29, "29.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(30, "30.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(31, "31.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(32, "32.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(33, "33.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(34, "34.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(35, "35.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(36, "36.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(37, "37.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(38, "38.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(39, "39.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(40, "40.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(41, "41.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(42, "42.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(43, "43.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(44, "44.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(45, "45.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(46, "46.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(47, "47.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(48, "48.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(49, "49.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(50, "50.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(51, "51.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(52, "52.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(53, "53.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(54, "54.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(55, "55.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(56, "56.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(57, "57.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(58, "58.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(59, "59.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(60, "60.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(61, "61.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(62, "62.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(63, "63.png")
        Me.ToolBarIconsFucsiaLarge.Images.SetKeyName(64, "64.png")
        '
        'ToolBarIconsWhiteLarge
        '
        Me.ToolBarIconsWhiteLarge.ImageSize = New System.Drawing.Size(32, 32)
        Me.ToolBarIconsWhiteLarge.ImageStream = CType(resources.GetObject("ToolBarIconsWhiteLarge.ImageStream"), DevExpress.Utils.ImageCollectionStreamer)
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(0, "0.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(1, "1.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(2, "2.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(3, "3.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(4, "4.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(5, "5.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(6, "6.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(7, "7.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(8, "8.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(9, "9.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(10, "10.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(11, "11.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(12, "12.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(13, "13.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(14, "14.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(15, "15.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(16, "16.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(17, "17.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(18, "18.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(19, "19.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(20, "20.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(21, "21.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(22, "22.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(23, "23.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(24, "24.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(25, "25.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(26, "26.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(27, "27.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(28, "28.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(29, "29.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(30, "30.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(31, "31.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(32, "32.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(33, "33.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(34, "34.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(35, "35.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(36, "36.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(37, "37.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(38, "38.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(39, "39.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(40, "40.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(41, "41.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(42, "42.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(43, "43.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(44, "44.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(45, "45.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(46, "46.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(47, "47.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(48, "48.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(49, "49.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(50, "50.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(51, "51.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(52, "52.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(53, "53.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(54, "54.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(55, "55.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(56, "56.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(57, "57.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(58, "58.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(59, "59.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(60, "60.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(61, "61.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(62, "62.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(63, "63.png")
        Me.ToolBarIconsWhiteLarge.Images.SetKeyName(64, "64.png")
        '
        'ToolBarIconsBlueLarge
        '
        Me.ToolBarIconsBlueLarge.ImageSize = New System.Drawing.Size(32, 32)
        Me.ToolBarIconsBlueLarge.ImageStream = CType(resources.GetObject("ToolBarIconsBlueLarge.ImageStream"), DevExpress.Utils.ImageCollectionStreamer)
        Me.ToolBarIconsBlueLarge.Images.SetKeyName(63, "Icon Navegar(1).png")
        Me.ToolBarIconsBlueLarge.Images.SetKeyName(64, "64.png")
        '
        'ImageIconsOtherWhite
        '
        Me.ImageIconsOtherWhite.ImageStream = CType(resources.GetObject("ImageIconsOtherWhite.ImageStream"), DevExpress.Utils.ImageCollectionStreamer)
        Me.ImageIconsOtherWhite.Images.SetKeyName(0, "0.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(1, "1.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(2, "2.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(3, "3.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(4, "4.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(5, "5.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(6, "6.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(7, "7.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(8, "8.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(9, "9.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(10, "10.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(11, "11.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(12, "12.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(13, "13.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(14, "14.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(15, "15.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(16, "16.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(17, "17.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(18, "18.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(19, "20.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(20, "21.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(21, "22.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(22, "23.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(23, "24.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(24, "25.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(25, "26.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(26, "27.png")
        Me.ImageIconsOtherWhite.Images.SetKeyName(27, "28.png")
        '
        'ToolBarIconsBlueSmall
        '
        Me.ToolBarIconsBlueSmall.ImageStream = CType(resources.GetObject("ToolBarIconsBlueSmall.ImageStream"), DevExpress.Utils.ImageCollectionStreamer)
        '
        'ToolBarIconsWhiteSmall
        '
        Me.ToolBarIconsWhiteSmall.ImageStream = CType(resources.GetObject("ToolBarIconsWhiteSmall.ImageStream"), DevExpress.Utils.ImageCollectionStreamer)
        Me.ToolBarIconsWhiteSmall.Images.SetKeyName(0, "0.png")
        Me.ToolBarIconsWhiteSmall.Images.SetKeyName(1, "1.png")
        Me.ToolBarIconsWhiteSmall.Images.SetKeyName(2, "2.png")
        Me.ToolBarIconsWhiteSmall.Images.SetKeyName(3, "3.png")
        Me.ToolBarIconsWhiteSmall.Images.SetKeyName(4, "4.png")
        Me.ToolBarIconsWhiteSmall.Images.SetKeyName(5, "5.png")
        Me.ToolBarIconsWhiteSmall.Images.SetKeyName(6, "6.png")
        Me.ToolBarIconsWhiteSmall.Images.SetKeyName(7, "7.png")
        Me.ToolBarIconsWhiteSmall.Images.SetKeyName(8, "8.png")
        '
        'ToolBarIconsBrownSmall
        '
        Me.ToolBarIconsBrownSmall.ImageStream = CType(resources.GetObject("ToolBarIconsBrownSmall.ImageStream"), DevExpress.Utils.ImageCollectionStreamer)
        Me.ToolBarIconsBrownSmall.Images.SetKeyName(0, "0.png")
        Me.ToolBarIconsBrownSmall.Images.SetKeyName(1, "1.png")
        Me.ToolBarIconsBrownSmall.Images.SetKeyName(2, "2.png")
        Me.ToolBarIconsBrownSmall.Images.SetKeyName(3, "3.png")
        Me.ToolBarIconsBrownSmall.Images.SetKeyName(4, "4.png")
        Me.ToolBarIconsBrownSmall.Images.SetKeyName(5, "5.png")
        Me.ToolBarIconsBrownSmall.Images.SetKeyName(6, "6.png")
        Me.ToolBarIconsBrownSmall.Images.SetKeyName(7, "7.png")
        Me.ToolBarIconsBrownSmall.Images.SetKeyName(8, "8.png")
        '
        'ToolBarIconsFucsiaSmall
        '
        Me.ToolBarIconsFucsiaSmall.ImageStream = CType(resources.GetObject("ToolBarIconsFucsiaSmall.ImageStream"), DevExpress.Utils.ImageCollectionStreamer)
        Me.ToolBarIconsFucsiaSmall.Images.SetKeyName(0, "0.png")
        Me.ToolBarIconsFucsiaSmall.Images.SetKeyName(1, "1.png")
        Me.ToolBarIconsFucsiaSmall.Images.SetKeyName(2, "2.png")
        Me.ToolBarIconsFucsiaSmall.Images.SetKeyName(3, "3.png")
        Me.ToolBarIconsFucsiaSmall.Images.SetKeyName(4, "4.png")
        Me.ToolBarIconsFucsiaSmall.Images.SetKeyName(5, "5.png")
        Me.ToolBarIconsFucsiaSmall.Images.SetKeyName(6, "6.png")
        Me.ToolBarIconsFucsiaSmall.Images.SetKeyName(7, "7.png")
        Me.ToolBarIconsFucsiaSmall.Images.SetKeyName(8, "8.png")
        '
        'ToolBarIconsGreenSmall
        '
        Me.ToolBarIconsGreenSmall.ImageStream = CType(resources.GetObject("ToolBarIconsGreenSmall.ImageStream"), DevExpress.Utils.ImageCollectionStreamer)
        Me.ToolBarIconsGreenSmall.Images.SetKeyName(0, "0.png")
        Me.ToolBarIconsGreenSmall.Images.SetKeyName(1, "1.png")
        Me.ToolBarIconsGreenSmall.Images.SetKeyName(2, "2.png")
        Me.ToolBarIconsGreenSmall.Images.SetKeyName(3, "3.png")
        Me.ToolBarIconsGreenSmall.Images.SetKeyName(4, "4.png")
        Me.ToolBarIconsGreenSmall.Images.SetKeyName(5, "5.png")
        Me.ToolBarIconsGreenSmall.Images.SetKeyName(6, "6.png")
        Me.ToolBarIconsGreenSmall.Images.SetKeyName(7, "7.png")
        Me.ToolBarIconsGreenSmall.Images.SetKeyName(8, "8.png")
        '
        'ToolBarIconsLilaSmall
        '
        Me.ToolBarIconsLilaSmall.ImageStream = CType(resources.GetObject("ToolBarIconsLilaSmall.ImageStream"), DevExpress.Utils.ImageCollectionStreamer)
        Me.ToolBarIconsLilaSmall.Images.SetKeyName(0, "0.png")
        Me.ToolBarIconsLilaSmall.Images.SetKeyName(1, "1.png")
        Me.ToolBarIconsLilaSmall.Images.SetKeyName(2, "2.png")
        Me.ToolBarIconsLilaSmall.Images.SetKeyName(3, "3.png")
        Me.ToolBarIconsLilaSmall.Images.SetKeyName(4, "4.png")
        Me.ToolBarIconsLilaSmall.Images.SetKeyName(5, "5.png")
        Me.ToolBarIconsLilaSmall.Images.SetKeyName(6, "6.png")
        Me.ToolBarIconsLilaSmall.Images.SetKeyName(7, "7.png")
        Me.ToolBarIconsLilaSmall.Images.SetKeyName(8, "8.png")
        '
        'ImageIconsOtherBrown
        '
        Me.ImageIconsOtherBrown.ImageStream = CType(resources.GetObject("ImageIconsOtherBrown.ImageStream"), DevExpress.Utils.ImageCollectionStreamer)
        Me.ImageIconsOtherBrown.Images.SetKeyName(0, "0.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(1, "1.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(2, "2.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(3, "3.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(4, "4.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(5, "5.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(6, "6.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(7, "7.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(8, "8.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(9, "9.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(10, "10.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(11, "11.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(12, "12.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(13, "13.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(14, "14.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(15, "15.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(16, "16.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(17, "17.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(18, "18.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(19, "20.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(20, "21.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(21, "22.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(22, "23.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(23, "24.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(24, "25.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(25, "26.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(26, "27.png")
        Me.ImageIconsOtherBrown.Images.SetKeyName(27, "28.png")
        '
        'ImageIconsOtherFucsia
        '
        Me.ImageIconsOtherFucsia.ImageStream = CType(resources.GetObject("ImageIconsOtherFucsia.ImageStream"), DevExpress.Utils.ImageCollectionStreamer)
        Me.ImageIconsOtherFucsia.Images.SetKeyName(0, "0.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(1, "1.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(2, "2.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(3, "3.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(4, "4.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(5, "5.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(6, "6.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(7, "7.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(8, "8.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(9, "9.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(10, "10.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(11, "11.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(12, "12.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(13, "13.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(14, "14.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(15, "15.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(16, "16.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(17, "17.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(18, "18.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(19, "20.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(20, "21.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(21, "22.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(22, "23.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(23, "24.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(24, "25.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(25, "26.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(26, "27.png")
        Me.ImageIconsOtherFucsia.Images.SetKeyName(27, "28.png")
        '
        'ImageIconsOtherLila
        '
        Me.ImageIconsOtherLila.ImageStream = CType(resources.GetObject("ImageIconsOtherLila.ImageStream"), DevExpress.Utils.ImageCollectionStreamer)
        Me.ImageIconsOtherLila.Images.SetKeyName(0, "0.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(1, "1.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(2, "2.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(3, "3.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(4, "4.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(5, "5.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(6, "6.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(7, "7.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(8, "8.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(9, "9.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(10, "10.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(11, "11.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(12, "12.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(13, "13.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(14, "14.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(15, "15.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(16, "16.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(17, "17.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(18, "18.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(19, "20.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(20, "21.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(21, "22.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(22, "23.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(23, "24.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(24, "25.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(25, "26.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(26, "27.png")
        Me.ImageIconsOtherLila.Images.SetKeyName(27, "28.png")
        '
        'ImageIconsOtherGreen
        '
        Me.ImageIconsOtherGreen.ImageStream = CType(resources.GetObject("ImageIconsOtherGreen.ImageStream"), DevExpress.Utils.ImageCollectionStreamer)
        Me.ImageIconsOtherGreen.Images.SetKeyName(0, "0.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(1, "1.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(2, "2.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(3, "3.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(4, "4.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(5, "5.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(6, "6.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(7, "7.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(8, "8.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(9, "9.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(10, "10.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(11, "11.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(12, "12.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(13, "13.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(14, "14.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(15, "15.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(16, "16.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(17, "17.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(18, "18.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(19, "20.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(20, "21.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(21, "22.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(22, "23.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(23, "24.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(24, "25.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(25, "26.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(26, "27.png")
        Me.ImageIconsOtherGreen.Images.SetKeyName(27, "28.png")
        '
        'ImageIconMessageIndigo
        '
        Me.ImageIconMessageIndigo.ImageSize = New System.Drawing.Size(397, 397)
        Me.ImageIconMessageIndigo.ImageStream = CType(resources.GetObject("ImageIconMessageIndigo.ImageStream"), DevExpress.Utils.ImageCollectionStreamer)
        Me.ImageIconMessageIndigo.Images.SetKeyName(0, "AVerde.png")
        Me.ImageIconMessageIndigo.Images.SetKeyName(1, "EVerde.png")
        Me.ImageIconMessageIndigo.Images.SetKeyName(2, "IVerde.png")
        Me.ImageIconMessageIndigo.Images.SetKeyName(3, "PVerde.png")
        Me.ImageIconMessageIndigo.Images.SetKeyName(4, "ALila.png")
        Me.ImageIconMessageIndigo.Images.SetKeyName(5, "ELila.png")
        Me.ImageIconMessageIndigo.Images.SetKeyName(6, "ILila.png")
        Me.ImageIconMessageIndigo.Images.SetKeyName(7, "PLila.png")
        Me.ImageIconMessageIndigo.Images.SetKeyName(8, "AFucsia.png")
        Me.ImageIconMessageIndigo.Images.SetKeyName(9, "EFucsia.png")
        Me.ImageIconMessageIndigo.Images.SetKeyName(10, "IFucsia.png")
        Me.ImageIconMessageIndigo.Images.SetKeyName(11, "PFucsia.png")
        Me.ImageIconMessageIndigo.Images.SetKeyName(12, "ACafe.png")
        Me.ImageIconMessageIndigo.Images.SetKeyName(13, "ECafe.png")
        Me.ImageIconMessageIndigo.Images.SetKeyName(14, "ICafe.png")
        Me.ImageIconMessageIndigo.Images.SetKeyName(15, "PCafe.png")
        Me.ImageIconMessageIndigo.Images.SetKeyName(16, "ABlanco.png")
        Me.ImageIconMessageIndigo.Images.SetKeyName(17, "EBlanco.png")
        Me.ImageIconMessageIndigo.Images.SetKeyName(18, "IBlanco.png")
        Me.ImageIconMessageIndigo.Images.SetKeyName(19, "PBlanco.png")
        '
        'ImageIconMessageErrorIndigo
        '
        Me.ImageIconMessageErrorIndigo.ImageSize = New System.Drawing.Size(180, 180)
        Me.ImageIconMessageErrorIndigo.ImageStream = CType(resources.GetObject("ImageIconMessageErrorIndigo.ImageStream"), DevExpress.Utils.ImageCollectionStreamer)
        Me.ImageIconMessageErrorIndigo.Images.SetKeyName(0, "Blanco.png")
        Me.ImageIconMessageErrorIndigo.Images.SetKeyName(1, "Cafe.png")
        Me.ImageIconMessageErrorIndigo.Images.SetKeyName(2, "Fucsia.png")
        Me.ImageIconMessageErrorIndigo.Images.SetKeyName(3, "Lila.png")
        Me.ImageIconMessageErrorIndigo.Images.SetKeyName(4, "Verde.png")
        CType(Me.ToolBarIconsBrownLarge, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ImageIconsOtherBlue, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ToolBarIconsGreenLarge, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ToolBarIconsLilaLarge, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ToolBarIconsFucsiaLarge, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ToolBarIconsWhiteLarge, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ToolBarIconsBlueLarge, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ImageIconsOtherWhite, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ToolBarIconsBlueSmall, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ToolBarIconsWhiteSmall, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ToolBarIconsBrownSmall, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ToolBarIconsFucsiaSmall, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ToolBarIconsGreenSmall, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ToolBarIconsLilaSmall, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ImageIconsOtherBrown, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ImageIconsOtherFucsia, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ImageIconsOtherLila, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ImageIconsOtherGreen, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ImageIconMessageIndigo, System.ComponentModel.ISupportInitialize).EndInit()
        CType(Me.ImageIconMessageErrorIndigo, System.ComponentModel.ISupportInitialize).EndInit()

    End Sub
    Public WithEvents ToolBarIconsBrownLarge As DevExpress.Utils.ImageCollection
    Public WithEvents ImageIconsOtherBlue As DevExpress.Utils.ImageCollection
    Public WithEvents ToolBarIconsGreenLarge As DevExpress.Utils.ImageCollection
    Public WithEvents ToolBarIconsLilaLarge As DevExpress.Utils.ImageCollection
    Public WithEvents ToolBarIconsFucsiaLarge As DevExpress.Utils.ImageCollection
    Public WithEvents ToolBarIconsWhiteLarge As DevExpress.Utils.ImageCollection
    Public WithEvents ToolBarIconsBlueLarge As DevExpress.Utils.ImageCollection
    Public WithEvents ImageIconsOtherWhite As DevExpress.Utils.ImageCollection
    Public WithEvents ToolBarIconsBlueSmall As DevExpress.Utils.ImageCollection
    Public WithEvents ToolBarIconsWhiteSmall As DevExpress.Utils.ImageCollection
    Public WithEvents ToolBarIconsBrownSmall As DevExpress.Utils.ImageCollection
    Public WithEvents ToolBarIconsFucsiaSmall As DevExpress.Utils.ImageCollection
    Public WithEvents ToolBarIconsGreenSmall As DevExpress.Utils.ImageCollection
    Public WithEvents ToolBarIconsLilaSmall As DevExpress.Utils.ImageCollection
    Friend WithEvents ImageIconsOtherBrown As DevExpress.Utils.ImageCollection
    Friend WithEvents ImageIconsOtherFucsia As DevExpress.Utils.ImageCollection
    Friend WithEvents ImageIconsOtherLila As DevExpress.Utils.ImageCollection
    Friend WithEvents ImageIconsOtherGreen As DevExpress.Utils.ImageCollection
    Public WithEvents ImageIconMessageIndigo As DevExpress.Utils.ImageCollection
    Friend WithEvents ImageIconMessageErrorIndigo As DevExpress.Utils.ImageCollection

End Class
