

CREATE view [Billing].[A_Tocanc_Fact_Costos]
AS

SELECT       RTRIM(CEN.NOMCENATE) AS CENTRO_ATENCION, BILLING.REVENUECONTROLDETAIL.CAREGROUPID, BILLING.REVENUECONTROLDETAIL.ID, ING.IESTADOIN AS ESTADO_INGRESO, SO.ADMISSIONNUMBER AS INGRESO, ING.IFECHAING AS FECHA_INGRESO, 
                         BILLING.REVENUECONTROL.PATIENTCODE AS IDENTIFICACIÓN, P.IPNOMCOMP AS PACIENTE, P.IPFECNACI AS FECHA_NACIMIENTO, 
						 DATEDIFF(YEAR,P.IPFECNACI,ING.IFECHAING) AS EDAD_EN_CONSULTA , 
						 T .NAME AS ENTIDAD, BILLING.REVENUECONTROLDETAIL.FOLIOORDER AS FOLIOS_A_FACTURAR, 
                         CASE BILLING.REVENUECONTROLDETAIL.FOLIOTYPE WHEN '1' THEN 'EAPB CON CONTRATO' WHEN '2' THEN 'EAPB SIN CONTRATO' WHEN '3' THEN 'PARTICULARES' WHEN '4' THEN 'ASEGURADORAS' END AS TIPO, 
                         CASE BILLING.REVENUECONTROLDETAIL.LIQUIDATIONTYPE WHEN '1' THEN 'PAGO POR SERVICIOS' WHEN '2' THEN 'CAPITACION' WHEN '3' THEN 'FACTURA GLOBAL' WHEN '4' THEN 'CAPITACION GLOBAL' END AS TIPO_LIQUIDACION,
                          EA.HEALTHENTITYCODE AS ENTIDAD_ADMINISTRADORA, T .NIT AS NIT_ENTIDAD, GA.CODE AS GRUPO_ATENCIÓN, GA.NAME AS DESCRIPCIÓN_GRUPO_ATENCIÓN, 
                         BILLING.REVENUECONTROLDETAIL.TOTALFOLIO AS [VR TOTAL FOLIO PENDIENTE FACTURAR], DQ.INVOICEDQUANTITY AS [CANTIDAD QX], DQ.TOTALSALESPRICE AS [TOTAL FACTURADO QX], 
                         DQ.PERFORMSHEALTHPROFESSIONALCODE AS [CÓD PROFESIONAL QX], RTRIM(MEDQX.CODPROSAL) + ' - ' + LTRIM(MEDQX.NOMMEDICO) AS [PROFESIONAL QX], 
                         CASE BILLING.REVENUECONTROLDETAIL.RESPONSIBLERECOVERYFEE WHEN '1' THEN 'NINGUNO' WHEN '2' THEN 'PACIENTE' WHEN '3' THEN 'TERCERO' END AS [RESPONSABLE CUOTA RECUPERACIÓN], 
						 CASE P.TIPCOBSAL
						 WHEN '1' THEN 'CONTRIBUTIVO'
					     WHEN '2' THEN 'SUBSIDIADO TOTAL'
					     WHEN '3' THEN 'SUBSIDIADO PARCIAL'
					     WHEN '4' THEN 'POBLACION POBRE SIN ASEGURAR CON SISBEN'
					     WHEN '5' THEN 'POBLACION POBRE SIN ASEGURAR SIN SISBEN'
					     WHEN '6' THEN 'DESPLAZADOS'
					     WHEN '7' THEN 'PLAN DE SALUD ADICIONAL'
					     WHEN '8' THEN 'OTROS'
						 ELSE 'DESCONOCIDO' END AS TIPO_PACIENTE,
                         BILLING.REVENUECONTROLDETAIL.TOTALPATIENTWITHDISCOUNT AS [VR COBRADO A PACIENTE], BILLING.REVENUECONTROLDETAIL.VALUECOPAY AS [VR CUOTA RECUPERACIÓN FOLIO], 
                         BILLING.REVENUECONTROLDETAIL.VALUEFEEMODERATOR AS [VR CUOTA MODERADORA FOLIO], BILLING.REVENUECONTROLDETAIL.OBSERVATION AS [OBSERVACIONES], CAT.NAME AS [CATEGORÍA PARA RIPS], 
                         CASE BILLING.REVENUECONTROLDETAIL.STATUS WHEN '1' THEN 'REGISTRADO' WHEN '2' THEN 'FACTURADO' WHEN '3' THEN 'BLOQUEADO' END AS 'ESTADO', --PER.FULLNAME AS [USUARIO CREA], 
                         BILLING.REVENUECONTROLDETAIL.CREATIONDATE AS [FECHA CREACIÓN], ---PERM .FULLNAME AS [USUARIO MODIFICA], 
						 BILLING.REVENUECONTROLDETAIL.MODIFICATIONDATE AS [FECHA MODIFICACIÓN], 
                         CASE BILLING.SERVICEORDERDETAIL.SERVICETYPE WHEN '1' THEN 'SOAT' WHEN '2' THEN 'ISS' WHEN '3' THEN 'CUPS' END AS [TIPO SERVICIO], 
                         CASE BILLING.SERVICEORDERDETAIL.RECORDTYPE WHEN '1' THEN 'SERVICIOS' WHEN '2' THEN 'MEDICAMENTOS' END AS [SERVICIOS/MEDICAMENTOS], CUPS.CODE AS [CÓDIGO CUPS], 
                         CUPS.DESCRIPTION AS [DESCRIPCIÓN CUPS], SERVICIOSIPS.CODE AS [CÓDIGO SERVICIO], SERVICIOSIPS.NAME AS [DESCRIPCIÓN SERVICIO], BILLING.SERVICEORDERDETAIL.PACKAGING AS [SERVICIO INCLUIDO EN PAQUETE], 
                         CASE BILLING.SERVICEORDERDETAIL.PRESENTATION WHEN '1' THEN 'NO QUIRÚRGICO' WHEN '2' THEN 'QUIRÚRGICO' WHEN '3' THEN 'PAQUETE' END AS [PRESENTACIÓN SERVICIO], PR.CODE AS [CÓD PRODUCTO], 
                         PR.NAME AS [DESCRIPCIÓN PRODUCTO], BILLING.SERVICEORDERDETAIL.SUPPLYQUANTITY AS [CANTIDAD ENTREGADA], BILLING.SERVICEORDERDETAIL.DEVOLUTIONQUANTITY AS [CANTIDAD DEVUELTA], 
                         BILLING.SERVICEORDERDETAIL.INVOICEDQUANTITY AS [CANTIDAD A FACTURAR], BILLING.SERVICEORDERDETAIL.RATEMANUALSALEPRICE AS [VALOR UNITARIO  A FACTURAR ], (BILLING.SERVICEORDERDETAIL.INVOICEDQUANTITY) 
                         * (BILLING.SERVICEORDERDETAIL.RATEMANUALSALEPRICE) AS [TOTAL A FACTURAR], BILLING.REVENUECONTROLDETAIL.TOTALPATIENTSALESPRICE AS [TOTAL CUOTA RECUPERACIÓN], 
                         BILLING.SERVICEORDERDETAIL.SERVICEDATE AS [FECHA SERVICIO], BILLING.SERVICEORDERDETAIL.AUTHORIZATIONNUMBER AS [AUTORIZACIÓN], UF.CODE AS CODIGO_UNIDAD_FUNCIONAL_INGRESO, 
                         UF.NAME AS UNIDAD_FUNCIONAL_INGRESO, SALIDA.FECALTPAC AS FECHA_ALTA_MEDICA, 
						 YEAR(SALIDA.FECALTPAC) AS  AÑO_FECHA_ALTA_MEDICA,
						 MONTH(SALIDA.FECALTPAC) AS MES_FECHA_ALTA_MEDICA,
						 DAY(SALIDA.FECALTPAC) AS  DIA_FECHA_ALTA_MEDICA,
						 CASE MONTH(SALIDA.FECALTPAC)
							WHEN 1 THEN 'ENERO'
							WHEN 2 THEN 'FEBRERO'
							WHEN 3 THEN 'MARZO'
							WHEN 4 THEN 'ABRIL'
							WHEN 5 THEN 'MAYO'
							WHEN 6 THEN 'JUNIO'
							WHEN 7 THEN 'JULIO'
							WHEN 8 THEN 'AGOSTO'
							WHEN 9 THEN 'SEPTIEMBRE'
							WHEN 10 THEN 'OCTUBRE'
							WHEN 11 THEN 'NOVIEMBRE'
							WHEN 12 THEN 'DICIEMBRE'
							ELSE 'DESCONOCIDO'
						 END MES_NOMBRE_FECHA_ALTA_MEDICA,
						 YEAR(ING.IFECHAING) AS  AÑO_FECHA_INGRESO,
						 MONTH(ING.IFECHAING) AS MES_FECHA_INGRESO,
						 DAY(ING.IFECHAING) AS  DIA_FECHA_INGRESO,
						 CASE MONTH(ING.IFECHAING)
							WHEN 1 THEN 'ENERO'
							WHEN 2 THEN 'FEBRERO'
							WHEN 3 THEN 'MARZO'
							WHEN 4 THEN 'ABRIL'
							WHEN 5 THEN 'MAYO'
							WHEN 6 THEN 'JUNIO'
							WHEN 7 THEN 'JULIO'
							WHEN 8 THEN 'AGOSTO'
							WHEN 9 THEN 'SEPTIEMBRE'
							WHEN 10 THEN 'OCTUBRE'
							WHEN 11 THEN 'NOVIEMBRE'
							WHEN 12 THEN 'DICIEMBRE'
							ELSE 'DESCONOCIDO'
						 END MES_NOMBRE_FECHA_INGRESO,
						  CASE WHEN SALIDA.FECALTPAC IS NULL THEN 'SIN ALTA MÉDICA'
                          ELSE 'CON ALTA MÉDICA' END AS 'INGRESO_ALTA_MEDICA',
						 --BILLING.REVENUECONTROLDETAIL.TIMESTAMP, 
						 ING.UFUEGRMED AS CODIGO_UNIDAD_FUNCIONAL_EGRESO, UFE.UFUDESCRI AS UNIDAD_FUNCIONAL_EGRESO, CAMA.DESCCAMAS AS CAMA_EGRESO,
						CASE  CEN.NOMCENATE WHEN 'CLINICA DE ALTA TECNOLOGIA MARAYA' THEN '4.812775'
						 WHEN 'CIRCUNVALAR' THEN '4.808665'
						 WHEN 'SAN MARCEL' THEN '5.036220'
						 WHEN 'HOSPITALIZACION INFANTIL' THEN '5.064226'
						 WHEN 'CENTENARIO' THEN '4.542379'
						 WHEN 'SAN JUAN DE DIOS' THEN '4.557683'
						 WHEN 'CLINICA ARTURO LOPEZ CARDONA' THEN '4.545148'
						 WHEN 'CARTAGO UNIDAD ONCOLOGICA' THEN '4.754317'
						 END UBICACION_LATITUD,
						CASE  CEN.NOMCENATE WHEN 'CLINICA DE ALTA TECNOLOGIA MARAYA' THEN '-75.721576'
						 WHEN 'CIRCUNVALAR' THEN '-75.680038'
						 WHEN 'SAN MARCEL' THEN '-75.469270'
						 WHEN 'HOSPITALIZACION INFANTIL' THEN '-75.498604'
						 WHEN 'CENTENARIO' THEN '-75.658726'
						 WHEN 'SAN JUAN DE DIOS' THEN '-75.656878'
						 WHEN 'CLINICA ARTURO LOPEZ CARDONA' THEN '-75.661106'
						 WHEN 'CARTAGO UNIDAD ONCOLOGICA' THEN '-75.926218'
						 END UBICACION_LONGITUD
--INTO [PBI].[STG_PENDIENTE_FACTURACION]
FROM            BILLING.REVENUECONTROLDETAIL WITH (NOLOCK) INNER JOIN
                         BILLING.SERVICEORDERDETAILDISTRIBUTION WITH (NOLOCK) ON BILLING.REVENUECONTROLDETAIL.ID = BILLING.SERVICEORDERDETAILDISTRIBUTION.REVENUECONTROLDETAILID AND 
                         BILLING.REVENUECONTROLDETAIL.STATUS IN ('1', '3') INNER JOIN
                         BILLING.SERVICEORDERDETAIL WITH (NOLOCK) ON BILLING.SERVICEORDERDETAILDISTRIBUTION.SERVICEORDERDETAILID = BILLING.SERVICEORDERDETAIL.ID INNER JOIN
                         BILLING.REVENUECONTROL WITH (NOLOCK) ON BILLING.REVENUECONTROLDETAIL.REVENUECONTROLID = BILLING.REVENUECONTROL.ID LEFT  JOIN
                         DBO.INPACIENT AS P WITH (NOLOCK) ON P.IPCODPACI = BILLING.REVENUECONTROL.PATIENTCODE LEFT  JOIN
                         CONTRACT.CONTRACTENTITY AS E WITH (NOLOCK) ON E.ID = BILLING.REVENUECONTROLDETAIL.CONTRACTENTITYID LEFT  JOIN
                         CONTRACT.CAREGROUP AS GA WITH (NOLOCK) ON GA.ID = BILLING.REVENUECONTROLDETAIL.CAREGROUPID LEFT  JOIN
                         BILLING.INVOICECATEGORIES AS CAT WITH (NOLOCK) ON CAT.ID = BILLING.REVENUECONTROLDETAIL.INVOICECATEGORYID LEFT  JOIN
                         --INDIGOSEC.SECURITY.[USER] AS U WITH (NOLOCK) ON U.USERCODE = BILLING.REVENUECONTROLDETAIL.CREATIONUSER LEFT  JOIN
                         --INDIGOSEC.SECURITY.PERSON AS PER WITH (NOLOCK) ON PER.ID = U.IDPERSON LEFT  JOIN
                         --INDIGOSEC.SECURITY.[USER] AS UM WITH (NOLOCK) ON UM.USERCODE = BILLING.REVENUECONTROLDETAIL.MODIFICATIONUSER LEFT  JOIN
                         --INDIGOSEC.SECURITY.PERSON AS PERM WITH (NOLOCK) ON PERM .ID = UM.IDPERSON LEFT  JOIN
                         CONTRACT.CUPSENTITY AS CUPS WITH (NOLOCK) ON CUPS.ID = BILLING.SERVICEORDERDETAIL.CUPSENTITYID LEFT  JOIN
                         CONTRACT.IPSSERVICE AS SERVICIOSIPS WITH (NOLOCK) ON SERVICIOSIPS.ID = BILLING.SERVICEORDERDETAIL.IPSSERVICEID LEFT  JOIN
                         INVENTORY.INVENTORYPRODUCT AS PR WITH (NOLOCK) ON PR.ID = BILLING.SERVICEORDERDETAIL.PRODUCTID LEFT  JOIN
                         PAYROLL.FUNCTIONALUNIT AS UF WITH (NOLOCK) ON UF.ID = BILLING.SERVICEORDERDETAIL.PERFORMSFUNCTIONALUNITID LEFT  JOIN
                         DBO.HCREGEGRE AS SALIDA WITH (NOLOCK) ON SALIDA.NUMINGRES = BILLING.REVENUECONTROL.ADMISSIONNUMBER LEFT JOIN
						 DBO.HCREGEST AS CAME WITH (NOLOCK) ON SALIDA.NUMEFOLIO=CAME.NUMEFOLIO AND SALIDA.IPCODPACI=CAME.IPCODPACI AND SALIDA.NUMINGRES=CAME.NUMINGRES  AND SALIDA.UFUCODIGO=CAME.UFUCODIGO LEFT JOIN
						 DBO.CHCAMASHO AS CAMA WITH (NOLOCK) ON CAME.UFUCODIGO=CAMA.UFUCODIGO AND CAME.CODICAMAS = CAMA.CODICAMAS LEFT JOIN
                         CONTRACT.HEALTHADMINISTRATOR AS EA WITH (NOLOCK) ON EA.ID = BILLING.REVENUECONTROLDETAIL.HEALTHADMINISTRATORID LEFT  JOIN
                         COMMON.THIRDPARTY AS T WITH (NOLOCK) ON T .ID = BILLING.SERVICEORDERDETAIL.THIRDPARTYID LEFT  JOIN
                         DBO.ADINGRESO AS ING WITH (NOLOCK) ON ING.NUMINGRES = BILLING.REVENUECONTROL.ADMISSIONNUMBER INNER JOIN
                         .ADCENATEN AS CEN ON CEN.CODCENATE = ING.CODCENATE LEFT  JOIN
						 DBO.INUNIFUNC AS UFE WITH (NOLOCK) ON ING.UFUEGRMED = UFE.UFUCODIGO LEFT  JOIN
                         BILLING.SERVICEORDERDETAILSURGICAL AS DQ WITH (NOLOCK) ON DQ.SERVICEORDERDETAILID = BILLING.SERVICEORDERDETAIL.ID LEFT  JOIN
                         CONTRACT.IPSSERVICE AS SERVICIOSIPSQ WITH (NOLOCK) ON SERVICIOSIPSQ.ID = DQ.IPSSERVICEID LEFT  JOIN
                         DBO.INPROFSAL AS MEDQX WITH (NOLOCK) ON MEDQX.CODPROSAL = DQ.PERFORMSHEALTHPROFESSIONALCODE LEFT  JOIN
                         BILLING.SERVICEORDER AS SO WITH (NOLOCK) ON SO.ID = BILLING.SERVICEORDERDETAIL.SERVICEORDERID 
WHERE        ---BILLING.REVENUECONTROLDETAIL.STATUS IN ('1', '3') 
--AND 
BILLING.SERVICEORDERDETAIL.ISDELETE = '0' AND ING.IESTADOIN <> 'A' 
--AND ING.IESTADOIN <> 'F' 
AND ING.IESTADOIN <> 'C'
GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Vista que consolida el detalle de costos y facturación pendiente por folio de atención, integrando información del paciente (cédula, nombre, fecha de nacimiento, edad al ingreso, tipo de afiliación), del ingreso hospitalario (número de ingreso, fecha, estado, unidad funcional, fecha de alta médica), de la entidad pagadora (EPS, aseguradora, NIT, grupo de atención, tipo de folio y tipo de liquidación) y del detalle de cada servicio o medicamento a facturar (código CUPS, código de servicio IPS, producto de inventario, cantidades entregadas y devueltas, valor unitario, total a facturar, profesional quirúrgico, número de autorización). Combina los controles de ingresos y sus folios (RevenueControl / RevenueControlDetail) con el detalle de órdenes de servicio y su distribución financiera (ServiceOrderDetail / ServiceOrderDetailDistribution), enriqueciendo con catálogos de CUPS, servicios IPS, productos de inventario, categorías RIPS y datos maestros del paciente. Se utiliza principalmente para reportes de pre-facturación, análisis de costos por ingreso, control de folios pendientes de facturar, cuotas moderadoras, copagos y cuotas de recuperación, así como para auditoría de servicios quirúrgicos y no quirúrgicos por centro de atención y período de alta médica o ingreso.', @level0type = N'SCHEMA', @level0name = N'Billing', @level1type = N'VIEW', @level1name = N'A_Tocanc_Fact_Costos';
GO
EXECUTE sp_addextendedproperty @name = N'MS_DescriptionSource', @value = N'backport_from_v25.47c_2026-05-05', @level0type = N'SCHEMA', @level0name = N'Billing', @level1type = N'VIEW', @level1name = N'A_Tocanc_Fact_Costos';
GO
GO
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_Purpose', @value=N'Consolida los folios pendientes de facturación (registrados o bloqueados) con datos del ingreso, paciente, entidad responsable, servicios/medicamentos, profesional quirúrgico y ubicación geográfica del centro de atención, para análisis y costeo.', @level0type=N'SCHEMA', @level0name=N'Billing', @level1type=N'VIEW', @level1name=N'A_Tocanc_Fact_Costos';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_Preconditions', @value=N'El detalle del control de ingresos (REVENUECONTROLDETAIL) debe estar en estado ''1'' (REGISTRADO) o ''3'' (BLOQUEADO).; El detalle de la orden de servicio (SERVICEORDERDETAIL.ISDELETE) no debe estar marcado como eliminado (''0'').; El ingreso (ADINGRESO.IESTADOIN) no debe estar en estado ''A'' ni ''C'' (anulado/cancelado).; Debe existir relación entre REVENUECONTROLDETAIL, SERVICEORDERDETAILDISTRIBUTION, SERVICEORDERDETAIL y REVENUECONTROL (INNER JOIN).', @level0type=N'SCHEMA', @level0name=N'Billing', @level1type=N'VIEW', @level1name=N'A_Tocanc_Fact_Costos';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_Invariants', @value=N'Solo se incluyen folios pendientes de facturar: STATUS distinto de ''2'' (FACTURADO).; Excluye ingresos anulados (''A'') y cancelados (''C''); los demás estados sí se incluyen (incluido ''F'').; Excluye líneas de orden de servicio marcadas como eliminadas (ISDELETE=''0'' es el filtro positivo retenido).; TOTAL A FACTURAR se calcula siempre como INVOICEDQUANTITY * RATEMANUALSALEPRICE de SERVICEORDERDETAIL.; EDAD_EN_CONSULTA se calcula con DATEDIFF en años entre fecha de nacimiento del paciente y fecha de ingreso.; Las coordenadas geográficas de los centros están cableadas en la vista (no provienen de tabla maestra).', @level0type=N'SCHEMA', @level0name=N'Billing', @level1type=N'VIEW', @level1name=N'A_Tocanc_Fact_Costos';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_SideEffects', @value=N'[RETURN_RESULT] Billing.A_Tocanc_Fact_Costos: Devuelve filas decodificando catálogos (FOLIOTYPE, LIQUIDATIONTYPE, STATUS, SERVICETYPE, RECORDTYPE, PRESENTATION, RESPONSIBLERECOVERYFEE, TIPCOBSAL) a etiquetas legibles en español, y calcula edad en consulta, descomposición de fechas (año/mes/día/nombre del mes) y bandera INGRESO_ALTA_MEDICA según SALIDA.FECALTPAC sea NULL o no.', @level0type=N'SCHEMA', @level0name=N'Billing', @level1type=N'VIEW', @level1name=N'A_Tocanc_Fact_Costos';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_Decisions', @value=N'si REVENUECONTROLDETAIL.FOLIOTYPE IN (''1'',''2'',''3'',''4'') → Clasifica el folio como EAPB CON CONTRATO / EAPB SIN CONTRATO / PARTICULARES / ASEGURADORAS; si REVENUECONTROLDETAIL.LIQUIDATIONTYPE IN (''1'',''2'',''3'',''4'') → Asigna tipo de liquidación: PAGO POR SERVICIOS / CAPITACION / FACTURA GLOBAL / CAPITACION GLOBAL; si REVENUECONTROLDETAIL.STATUS = ''1'' o ''3'' → Reporta el folio como REGISTRADO o BLOQUEADO (los FACTURADOS ''2'' quedan excluidos por el filtro del JOIN); si REVENUECONTROLDETAIL.RESPONSIBLERECOVERYFEE IN (''1'',''2'',''3'') → Identifica responsable de cuota de recuperación: NINGUNO / PACIENTE / TERCERO; si INPACIENT.TIPCOBSAL IN (''1''..''8'') → Asigna tipo de paciente (CONTRIBUTIVO, SUBSIDIADO TOTAL/PARCIAL, POBLACION POBRE SIN ASEGURAR CON/SIN SISBEN, DESPLAZADOS, PLAN DE SALUD ADICIONAL, OTROS) else Etiqueta el tipo de paciente como DESCONOCIDO; si SALIDA.FECALTPAC IS NULL → Marca el ingreso como ''SIN ALTA MÉDICA'' else Marca el ingreso como ''CON ALTA MÉDICA''; si CEN.NOMCENATE coincide con uno de los 8 centros listados (MARAYA, CIRCUNVALAR, SAN MARCEL, HOSPITALIZACION INFANTIL, CENTENARIO, SAN JUAN DE DIOS, ARTURO LOPEZ CARDONA, CARTAGO UNIDAD ONCOLOGICA) → Asigna coordenadas fijas (latitud/longitud) cableadas en el SQL para georreferenciar el centro de atención else UBICACION_LATITUD y UBICACION_LONGITUD quedan en NULL; si SERVICEORDERDETAIL.RECORDTYPE = ''1'' o ''2'' → Distingue si la línea corresponde a SERVICIOS o MEDICAMENTOS; si SERVICEORDERDETAIL.PRESENTATION IN (''1'',''2'',''3'') → Clasifica la presentación del servicio: NO QUIRÚRGICO / QUIRÚRGICO / PAQUETE', @level0type=N'SCHEMA', @level0name=N'Billing', @level1type=N'VIEW', @level1name=N'A_Tocanc_Fact_Costos';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_Consumes', @value=N'BILLING.REVENUECONTROLDETAIL; BILLING.SERVICEORDERDETAILDISTRIBUTION; BILLING.SERVICEORDERDETAIL; BILLING.REVENUECONTROL; DBO.INPACIENT; CONTRACT.CONTRACTENTITY; CONTRACT.CAREGROUP; BILLING.INVOICECATEGORIES; CONTRACT.CUPSENTITY; CONTRACT.IPSSERVICE; INVENTORY.INVENTORYPRODUCT; PAYROLL.FUNCTIONALUNIT; DBO.HCREGEGRE; DBO.HCREGEST; DBO.CHCAMASHO; CONTRACT.HEALTHADMINISTRATOR; COMMON.THIRDPARTY; DBO.ADINGRESO; DBO.ADCENATEN; DBO.INUNIFUNC; BILLING.SERVICEORDERDETAILSURGICAL; DBO.INPROFSAL; BILLING.SERVICEORDER', @level0type=N'SCHEMA', @level0name=N'Billing', @level1type=N'VIEW', @level1name=N'A_Tocanc_Fact_Costos';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_Source', @value=N'ai_claude-opus-4-7_tier-c_2026-05-06', @level0type=N'SCHEMA', @level0name=N'Billing', @level1type=N'VIEW', @level1name=N'A_Tocanc_Fact_Costos';
GO
