CREATE EXTERNAL TABLE [Treasury].[VoucherTransaction_19] (
    [Id] INT NOT NULL,
    [Code] VARCHAR (20) NOT NULL,
    [IdThirdParty] INT NULL,
    [IdMainAccount] INT NOT NULL,
    [IdCostCenter] INT NULL,
    [VoucherClass] INT NOT NULL,
    [ExpenseType] TINYINT NOT NULL,
    [Detail] VARCHAR (MAX) NOT NULL,
    [DocumentDate] DATETIME NOT NULL,
    [IdCashRegister] INT NULL,
    [IdEntityBankAccount] INT NULL,
    [Value] DECIMAL (18, 2) NOT NULL,
    [PaymentMethod] TINYINT NULL,
    [NoteNumber] VARCHAR (50) NULL,
    [IdChecks] INT NULL,
    [CheckNumber] BIGINT NULL,
    [TransactionDate] DATETIME NULL,
    [TaxByMil] BIT NOT NULL,
    [TaxByMilValue] DECIMAL (18, 2) NULL,
    [CashRegisterExpense] BIT NOT NULL,
    [RefundCashRegisterExpense] BIT NOT NULL,
    [SchedulePaymentId] INT NULL,
    [BeneficiaryIdentification] VARCHAR (20) NULL,
    [Beneficiary] VARCHAR (100) NULL,
    [TransactionRelationship] BIT NULL,
    [CheckReconciled] BIT NULL,
    [IdPaymentOrder] INT NULL,
    [Printed] BIT NULL,
    [RTEValue] DECIMAL (18, 2) NULL,
    [IVAValue] DECIMAL (18, 2) NULL,
    [ICAValue] DECIMAL (18, 2) NULL,
    [OtherValue] DECIMAL (18, 2) NULL,
    [BankAccountNumber] VARCHAR (50) NULL,
    [BankName] VARCHAR (100) NULL,
    [DetailsInterfaceBudget] VARCHAR (100) NULL,
    [IdUnitOperative] INT NOT NULL,
    [IdRefund] INT NULL,
    [Status] TINYINT NOT NULL,
    [CreationUser] VARCHAR (20) NOT NULL,
    [CreationDate] DATETIME NOT NULL,
    [ModificationUser] VARCHAR (20) NULL,
    [ModificationDate] DATETIME NULL,
    [ConfirmationUser] VARCHAR (20) NULL,
    [ConfirmationDate] DATETIME NULL,
    [AnnulmentUser] VARCHAR (20) NULL,
    [AnnulmentDate] DATETIME NULL,
    [ReversedUser] VARCHAR (20) NULL,
    [ReversedDate] DATETIME NULL,
    [TimeStamp] ROWVERSION NOT NULL,
    [EmailSent] BIT NOT NULL,
    [IdCheckCashingStatus] TINYINT NULL,
    [HandlesDocumentSupport] BIT NOT NULL,
    [CurrencyId] INT NULL,
    [SupplierBankAccountId] INT NULL
)
    WITH (
    DATA_SOURCE = [INDIGO999_19],
    SCHEMA_NAME = N'Treasury',
    OBJECT_NAME = N'VoucherTransaction'
    );

