CREATE TABLE [Payroll].[VerifyAutoliquidationFileCR] (
    [Id]                                                INT            IDENTITY (1, 1) NOT NULL,
    [RegisterStatus]                                    BIT            NOT NULL,
    [PayrollDateLiquidated]                             DATE           NOT NULL,
    [EmployeeId]                                        INT            NOT NULL,
    [TypeContractEmployee]                              VARCHAR (5)    NOT NULL,
    [SubTypeEmployee]                                   VARCHAR (5)    NOT NULL,
    [ForeignNotBound]                                   VARCHAR (5)    NOT NULL,
    [ColombianForeignResident]                          VARCHAR (5)    NOT NULL,
    [CodeCityBranchOffice]                              VARCHAR (10)   NOT NULL,
    [Entry]                                             VARCHAR (1)    NOT NULL,
    [Retirement]                                        VARCHAR (1)    NOT NULL,
    [TDE]                                               VARCHAR (1)    NOT NULL,
    [TAE]                                               VARCHAR (1)    NOT NULL,
    [TDP]                                               VARCHAR (1)    NOT NULL,
    [TAP]                                               VARCHAR (1)    NOT NULL,
    [VSP]                                               VARCHAR (1)    NOT NULL,
    [Correcciones]                                      VARCHAR (1)    NOT NULL,
    [VST]                                               VARCHAR (1)    NOT NULL,
    [SLN]                                               VARCHAR (1)    NOT NULL,
    [IGE]                                               VARCHAR (1)    NOT NULL,
    [LMA]                                               VARCHAR (1)    NOT NULL,
    [VAC]                                               VARCHAR (1)    NOT NULL,
    [AVP]                                               VARCHAR (1)    NOT NULL,
    [VCT]                                               VARCHAR (1)    NOT NULL,
    [IRL]                                               VARCHAR (2)    NOT NULL,
    [PensionAdministratorCode]                          VARCHAR (20)   NOT NULL,
    [TransferPensionAdministratorCode]                  VARCHAR (20)   NOT NULL,
    [EPSCode]                                           VARCHAR (20)   NOT NULL,
    [TransferEPSCode]                                   VARCHAR (20)   NOT NULL,
    [CCFCode]                                           VARCHAR (20)   NOT NULL,
    [PensionDays]                                       INT            NOT NULL,
    [HealthDays]                                        INT            NOT NULL,
    [ProfessionalRiskDays]                              INT            NOT NULL,
    [CompensationFundDays]                              INT            NOT NULL,
    [BasicSalary]                                       NUMERIC (18)   NOT NULL,
    [IntegralSalary]                                    VARCHAR (1)    NOT NULL,
    [IBCPension]                                        NUMERIC (18)   NOT NULL,
    [IBCHealth]                                         NUMERIC (18)   NOT NULL,
    [IBCProfessionalRisk]                               NUMERIC (18)   NOT NULL,
    [IBCCompensationFund]                               NUMERIC (18)   NOT NULL,
    [RateContributionPension]                           NUMERIC (6, 3) NOT NULL,
    [ValuePension]                                      NUMERIC (18)   NOT NULL,
    [VoluntaryContributionPensionValue]                 NUMERIC (18)   NOT NULL,
    [VoluntaryContributionPensionValuePatron]           NUMERIC (18)   NOT NULL,
    [TotalPensionContribution]                          NUMERIC (18)   NOT NULL,
    [PensionSolidarityFundValueContribution]            NUMERIC (18)   NOT NULL,
    [PensionSolidarityFundValueContributionSubsistence] NUMERIC (18)   NOT NULL,
    [ValueNotRetainedByVoluntaryContributions]          NUMERIC (18)   NOT NULL,
    [RateContributionHealth]                            NUMERIC (6, 3) NOT NULL,
    [ValueHealth]                                       NUMERIC (18)   NOT NULL,
    [ValueAditionalUPC]                                 NUMERIC (18)   NOT NULL,
    [AuthorizationNumberDisability]                     VARCHAR (50)   NOT NULL,
    [ValueGeneralDisability]                            NUMERIC (18)   NOT NULL,
    [AuthorizationNumberMaternityLicense]               VARCHAR (50)   NOT NULL,
    [ValueMaternityLicense]                             NUMERIC (18)   NOT NULL,
    [RateContributionProfessionalRisk]                  NUMERIC (6, 3) NOT NULL,
    [WorkCenter]                                        VARCHAR (50)   NOT NULL,
    [ValueContributionProfessionalRisk]                 NUMERIC (18)   NOT NULL,
    [RateContributorCCF]                                NUMERIC (6, 3) NOT NULL,
    [ValueContributionCCF]                              NUMERIC (18)   NOT NULL,
    [RateContributorSENA]                               NUMERIC (6, 3) NOT NULL,
    [ValueSena]                                         NUMERIC (18)   NOT NULL,
    [RateContributionICBF]                              NUMERIC (6, 3) NOT NULL,
    [ValueICBF]                                         NUMERIC (18)   NOT NULL,
    [RateContributorESAP]                               NUMERIC (6, 3) NOT NULL,
    [RateContributorEducationMinistry]                  NUMERIC (6, 3) NOT NULL,
    [MinistryCodeRiskFound]                             VARCHAR (50)   NOT NULL,
    [ProfessionalRiskCode]                              VARCHAR (20)   NOT NULL,
    [TarifaEspecialPensiones]                           INT            NOT NULL,
    [IngressDate]                                       DATE           NULL,
    [DateRetirement]                                    DATE           NULL,
    [SanctionInitialDate]                               DATE           NULL,
    [SanctionEndDate]                                   DATE           NULL,
    [AmbulatoryDisabilityInitialDate]                   DATE           NULL,
    [AmbulatoryDisabiltyEndDate]                        DATE           NULL,
    [MaternityLeaveInitialDate]                         DATE           NULL,
    [MaternityLeaveEndDate]                             DATE           NULL,
    [VacationInitialDate]                               DATE           NULL,
    [VacationEndDate]                                   DATE           NULL,
    [FechaInicioVCT]                                    DATE           NULL,
    [FechaFinVCT]                                       DATE           NULL,
    [FechaInicioIRL]                                    DATE           NULL,
    [FechaFinIRL]                                       DATE           NULL,
    [IBCOtrosParafiscales]                              NUMERIC (18)   NOT NULL,
    [TotalHours]                                        INT            NOT NULL,
    [FechaEmpleadoExterior]                             DATE           NULL,
    [Observations]                                      VARCHAR (500)  NULL,
    [IBCSLN]                                            NUMERIC (18)   NULL,
    [BaseIGE]                                           NUMERIC (18)   NULL,
    [BaseVAC]                                           NUMERIC (18)   NULL,
    [BaseIRL]                                           NUMERIC (18)   NULL,
    [ConfirmationDate]                                  DATETIME       NULL,
    [ConfirmationUser]                                  VARCHAR (20)   NULL,
    [DisconfirmationDate]                               DATETIME       NULL,
    [DisconfirmationUser]                               VARCHAR (20)   NULL,
    [BaseLMA]                                           NUMERIC (18)   NULL,
    [BaseLiquidacionSLN]                                NUMERIC (18)   NULL,
    [BaseLiquidacionIGE]                                NUMERIC (18)   NULL,
    [BaseLiquidacionLMA]                                NUMERIC (18)   NULL,
    [BaseLiquidacionVAC]                                NUMERIC (18)   NULL,
    [BaseLiquidacionIRL]                                NUMERIC (18)   NULL,
    [VSTValue]                                          NUMERIC (18)   NULL,
    [EconomicActivityARL]                               VARCHAR (7)    NULL,
    [ContractId]                                        INT            NULL,
    [ConceptClass]                                      VARCHAR (4)    NULL,
    CONSTRAINT [PK_VerifyAutoliquidationFileCR] PRIMARY KEY CLUSTERED ([Id] ASC)
);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Tabla de verificación del archivo de autoliquidación de aportes a seguridad social (formato PILA) para empleados en Colombia. Almacena por período de nómina liquidada los datos de cada empleado: bases de cotización (IBC), tarifas y valores aportados a pensión, salud, riesgos profesionales, CCF, SENA e ICBF, junto con novedades (ingreso, retiro, incapacidades, licencias, vacaciones). Registra también el estado de confirmación/desconfirmación del registro con usuario y fecha responsable.', @level0type=N'SCHEMA', @level0name=N'Payroll', @level1type=N'TABLE', @level1name=N'VerifyAutoliquidationFileCR';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DescriptionSource', @value=N'backport_from_v25.47c_2026-05-05', @level0type=N'SCHEMA', @level0name=N'Payroll', @level1type=N'TABLE', @level1name=N'VerifyAutoliquidationFileCR';
GO
