'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel
Imports System.Globalization
Imports System.IO
Imports System.Reflection
Imports System.Runtime.Serialization.Formatters.Binary
Imports System.Runtime.Serialization
Imports System.Runtime.CompilerServices
Imports Domain.Base.Entities
Imports System.Data.Entity.ModelConfiguration

<DataContract(IsReference:=True), Serializable(), KnownType(GetType(ScheduleDetailHour))>
<KnownType(GetType(ScheduleDetail))>
<KnownType(GetType(ScheduleDetailConcept))>
Partial Public Class ScheduleDetailHour
	Inherits Entity(Of ScheduleDetailHour)
    Implements IObjectWithChangeTracker
    Implements INotifyPropertyChanged

#Region "Aux Property"

	Private _ScheduleDetailHourAux As ScheduleDetailHour

	<DataMember()>
    Public Property ScheduleDetailHourAux As ScheduleDetailHour
        Get
            Return Me._ScheduleDetailHourAux
        End Get
        Set(value As ScheduleDetailHour)
            Me._ScheduleDetailHourAux = value
        End Set
    End Property


#End Region

#Region "Simple Properties"

	Private _id As Integer
	<DataMember()>
	Public Property Id() As Integer
        Get
            Return _id
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_id, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'Id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _id = value
                OnPropertyChanged("Id")
            End If
        End Set
    End Property

	Private _scheduleDetailId As Integer
	<DataMember()>
	Public Property ScheduleDetailId() As Integer
        Get
            Return _scheduleDetailId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_scheduleDetailId, value) Then
                ChangeTracker.RecordOriginalValue("ScheduleDetailId", _scheduleDetailId)
                If Not IsDeserializing Then
                    If ScheduleDetail IsNot Nothing AndAlso Not Equals(ScheduleDetail.Id, value) Then
                        ScheduleDetail = Nothing
                    End If
                End If
                _scheduleDetailId = value
                OnPropertyChanged("ScheduleDetailId")
            End If
        End Set
    End Property

	Private _dateTimeInitial As Date
	<DataMember()>
	Public Property DateTimeInitial() As Date
        Get
            Return _dateTimeInitial
        End Get
        Set(ByVal value As Date)
            If Not Equals(_dateTimeInitial, value) Then
                _dateTimeInitial = value
                OnPropertyChanged("DateTimeInitial")
            End If
        End Set
    End Property

	Private _dateTimeEnding As Date
	<DataMember()>
	Public Property DateTimeEnding() As Date
        Get
            Return _dateTimeEnding
        End Get
        Set(ByVal value As Date)
            If Not Equals(_dateTimeEnding, value) Then
                _dateTimeEnding = value
                OnPropertyChanged("DateTimeEnding")
            End If
        End Set
    End Property

	Private _totalNumberHours As Decimal
	<DataMember()>
	Public Property TotalNumberHours() As Decimal
        Get
            Return _totalNumberHours
        End Get
        Set(ByVal value As Decimal)
            If Not Equals(_totalNumberHours, value) Then
                _totalNumberHours = value
                OnPropertyChanged("TotalNumberHours")
            End If
        End Set
    End Property

	Private _nextDay As Boolean
	<DataMember()>
	Public Property NextDay() As Boolean
        Get
            Return _nextDay
        End Get
        Set(ByVal value As Boolean)
            If Not Equals(_nextDay, value) Then
                _nextDay = value
                OnPropertyChanged("NextDay")
            End If
        End Set
    End Property

	Private _event As Boolean
	<DataMember()>
	Public Property [Event]() As Boolean
        Get
            Return _event
        End Get
        Set(ByVal value As Boolean)
            If Not Equals(_event, value) Then
                _event = value
                OnPropertyChanged("Event")
            End If
        End Set
    End Property

	Private _approved As Boolean
	<DataMember()>
	Public Property Approved() As Boolean
        Get
            Return _approved
        End Get
        Set(ByVal value As Boolean)
            If Not Equals(_approved, value) Then
                _approved = value
                OnPropertyChanged("Approved")
            End If
        End Set
    End Property

	Private _appliedLiquidationConcept As Boolean
	<DataMember()>
	Public Property AppliedLiquidationConcept() As Boolean
        Get
            Return _appliedLiquidationConcept
        End Get
        Set(ByVal value As Boolean)
            If Not Equals(_appliedLiquidationConcept, value) Then
                _appliedLiquidationConcept = value
                OnPropertyChanged("AppliedLiquidationConcept")
            End If
        End Set
    End Property

	Private _state As Boolean
	<DataMember()>
	Public Property State() As Boolean
        Get
            Return _state
        End Get
        Set(ByVal value As Boolean)
            If Not Equals(_state, value) Then
                _state = value
                OnPropertyChanged("State")
            End If
        End Set
    End Property

	Private _eventLastMonth As Boolean
	<DataMember()>
	Public Property EventLastMonth() As Boolean
        Get
            Return _eventLastMonth
        End Get
        Set(ByVal value As Boolean)
            If Not Equals(_eventLastMonth, value) Then
                _eventLastMonth = value
                OnPropertyChanged("EventLastMonth")
            End If
        End Set
    End Property

	Private _paidEventLastMonth As Nullable(Of Date)
	<DataMember()>
	Public Property PaidEventLastMonth() As Nullable(Of Date)
        Get
            Return _paidEventLastMonth
        End Get
        Set(ByVal value As Nullable(Of Date))
            If Not Equals(_paidEventLastMonth, value) Then
                _paidEventLastMonth = value
                OnPropertyChanged("PaidEventLastMonth")
            End If
        End Set
    End Property

#End Region

#Region "Navigation Properties"

    <DataMember()>
    Public Property ScheduleDetail() As ScheduleDetail
        Get
            Return _scheduleDetail
        End Get
        Set(ByVal value As ScheduleDetail)
            If _scheduleDetail IsNot value Then
                Dim previousValue As ScheduleDetail = _scheduleDetail
                _scheduleDetail = value
                FixupScheduleDetail(previousValue)
                OnNavigationPropertyChanged("ScheduleDetail")
            End If
        End Set
    End Property

    Private _scheduleDetail As ScheduleDetail


    <DataMember()>
	Public Property ScheduleDetailConcept() As TrackableCollection(Of ScheduleDetailConcept)
		Get
            If _scheduleDetailConcept Is Nothing Then
                _scheduleDetailConcept = New TrackableCollection(Of ScheduleDetailConcept)
                AddHandler _scheduleDetailConcept.CollectionChanged, AddressOf FixupScheduleDetailConcept
            End If
            Return _scheduleDetailConcept
        End Get
        Set(ByVal value As TrackableCollection(Of ScheduleDetailConcept))
            If _scheduleDetailConcept IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _scheduleDetailConcept IsNot Nothing Then
                    RemoveHandler _scheduleDetailConcept.CollectionChanged, AddressOf FixupScheduleDetailConcept
                    ' This is the principal end in an association that performs cascade deletes.
                    ' Remove the cascade delete event handler for any entities in the current collection.
                    For Each item As ScheduleDetailConcept In _scheduleDetailConcept
                        RemoveHandler ChangeTracker.ObjectStateChanging, AddressOf item.HandleCascadeDelete
                    Next
                End If
                _scheduleDetailConcept = value
                If _scheduleDetailConcept IsNot Nothing Then
                    AddHandler _scheduleDetailConcept.CollectionChanged, AddressOf FixupScheduleDetailConcept
                    ' This is the principal end in an association that performs cascade deletes.
                    ' Add the cascade delete event handler for any entities that are already in the new collection.
                    For Each item As ScheduleDetailConcept In _scheduleDetailConcept
                        AddHandler ChangeTracker.ObjectStateChanging, AddressOf item.HandleCascadeDelete
                    Next
                End If
                OnNavigationPropertyChanged("ScheduleDetailConcept")
            End If
        End Set
    End Property

    Private _scheduleDetailConcept As TrackableCollection(Of ScheduleDetailConcept)

#End Region

#Region "ChangeTracking"

    Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
        If ChangeTracker.State <> ObjectState.Added AndAlso ChangeTracker.State <> ObjectState.Deleted Then
            ChangeTracker.State = ObjectState.Modified
        End If
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Protected Overridable Sub OnNavigationPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Private _changeTracker As ObjectChangeTracker

    <DataMember()>
    Public Property ChangeTracker() As ObjectChangeTracker Implements IObjectWithChangeTracker.ChangeTracker
        Get
            If _changeTracker Is Nothing Then
                _changeTracker = New ObjectChangeTracker()
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            Return _changeTracker
        End Get
        Set(ByVal value As ObjectChangeTracker)
            If _changeTracker IsNot Nothing Then
                RemoveHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            _changeTracker = value
            If _changeTracker IsNot Nothing Then
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
        End Set
    End Property

    Private Sub HandleObjectStateChanging(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.ClearNavigationProperties()
        End If
    End Sub

    Private _isDeserializing As Boolean
    Protected Property IsDeserializing() As Boolean
        Get
            Return _isDeserializing
        End Get
        Private Set(ByVal value As Boolean)
            _isDeserializing = value
        End Set
    End Property

    <OnDeserializing()>
    Public Sub OnDeserializingMethod(ByVal context As StreamingContext)
        IsDeserializing = True
    End Sub

    <OnDeserialized()>
    Public Sub OnDeserializedMethod(ByVal context As StreamingContext)
        IsDeserializing = False
        ChangeTracker.ChangeTrackingEnabled = True
    End Sub

    Protected Overridable Sub ClearNavigationProperties()
        ScheduleDetail = Nothing
        ScheduleDetailConcept.Clear()
    End Sub

#End Region

#Region "Association Fixup"

    Private Sub FixupScheduleDetail(ByVal previousValue As ScheduleDetail)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.ScheduleDetailHour.Contains(Me) Then
            previousValue.ScheduleDetailHour.Remove(Me)
        End If

        If ScheduleDetail IsNot Nothing Then
            ScheduleDetail.ScheduleDetailHour.Add(Me)

            ScheduleDetailId = ScheduleDetail.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("ScheduleDetail") AndAlso
                ChangeTracker.OriginalValues("ScheduleDetail") Is ScheduleDetail Then
                ChangeTracker.OriginalValues.Remove("ScheduleDetail")
            Else
                ChangeTracker.RecordOriginalValue("ScheduleDetail", previousValue)
            End If
            If ScheduleDetail IsNot Nothing AndAlso Not ScheduleDetail.ChangeTracker.ChangeTrackingEnabled Then
                ScheduleDetail.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupScheduleDetailConcept(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As ScheduleDetailConcept In e.NewItems
                item.ScheduleDetailHour = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("ScheduleDetailConcept", item)
                End If
                ' This is the principal end in an association that performs cascade deletes.
                ' Update the event listener to refer to the new dependent.
                AddHandler ChangeTracker.ObjectStateChanging, AddressOf item.HandleCascadeDelete
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As ScheduleDetailConcept In e.OldItems
                If item.ScheduleDetailHour Is Me Then
                    item.ScheduleDetailHour = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("ScheduleDetailConcept", item)
                End If
                ' This is the principal end in an association that performs cascade deletes.
                ' Remove the previous dependent from the event listener.
                RemoveHandler ChangeTracker.ObjectStateChanging, AddressOf item.HandleCascadeDelete
            Next
        End If
    End Sub

#End Region

End Class

