'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel
Imports System.Globalization
Imports System.IO
Imports System.Reflection
Imports System.Runtime.Serialization.Formatters.Binary
Imports System.Runtime.Serialization
Imports System.Runtime.CompilerServices
Imports Domain.Base.Entities
Imports System.Data.Entity.ModelConfiguration

<DataContract(IsReference:=True), Serializable(), KnownType(GetType(VacationRequest))>
<KnownType(GetType(Employee))>
Partial Public Class VacationRequest
	Inherits Entity(Of VacationRequest)
    Implements IObjectWithChangeTracker
    Implements INotifyPropertyChanged

#Region "Aux Property"

	Private _VacationRequestAux As VacationRequest

	<DataMember()>
    Public Property VacationRequestAux As VacationRequest
        Get
            Return Me._VacationRequestAux
        End Get
        Set(value As VacationRequest)
            Me._VacationRequestAux = value
        End Set
    End Property


#End Region

#Region "Simple Properties"

	Private _id As Integer
	<DataMember()>
	Public Property Id() As Integer
        Get
            Return _id
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_id, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'Id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _id = value
                OnPropertyChanged("Id")
            End If
        End Set
    End Property

	Private _employeeId As Integer
	<DataMember()>
	Public Property EmployeeId() As Integer
        Get
            Return _employeeId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_employeeId, value) Then
                ChangeTracker.RecordOriginalValue("EmployeeId", _employeeId)
                If Not IsDeserializing Then
                    If Employee IsNot Nothing AndAlso Not Equals(Employee.Id, value) Then
                        Employee = Nothing
                    End If
                End If
                _employeeId = value
                OnPropertyChanged("EmployeeId")
            End If
        End Set
    End Property

	Private _vacationType As Byte
	<DataMember()>
	Public Property VacationType() As Byte
        Get
            Return _vacationType
        End Get
        Set(ByVal value As Byte)
            If Not Equals(_vacationType, value) Then
                _vacationType = value
                OnPropertyChanged("VacationType")
            End If
        End Set
    End Property

	Private _days As Integer
	<DataMember()>
	Public Property Days() As Integer
        Get
            Return _days
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_days, value) Then
                _days = value
                OnPropertyChanged("Days")
            End If
        End Set
    End Property

	Private _initialDate As Date
	<DataMember()>
	Public Property InitialDate() As Date
        Get
            Return _initialDate
        End Get
        Set(ByVal value As Date)
            If Not Equals(_initialDate, value) Then
                _initialDate = value
                OnPropertyChanged("InitialDate")
            End If
        End Set
    End Property

	Private _endDate As Date
	<DataMember()>
	Public Property EndDate() As Date
        Get
            Return _endDate
        End Get
        Set(ByVal value As Date)
            If Not Equals(_endDate, value) Then
                _endDate = value
                OnPropertyChanged("EndDate")
            End If
        End Set
    End Property

	Private _incorporationDate As Date
	<DataMember()>
	Public Property IncorporationDate() As Date
        Get
            Return _incorporationDate
        End Get
        Set(ByVal value As Date)
            If Not Equals(_incorporationDate, value) Then
                _incorporationDate = value
                OnPropertyChanged("IncorporationDate")
            End If
        End Set
    End Property

	Private _enjoyDay As Integer
	<DataMember()>
	Public Property EnjoyDay() As Integer
        Get
            Return _enjoyDay
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_enjoyDay, value) Then
                _enjoyDay = value
                OnPropertyChanged("EnjoyDay")
            End If
        End Set
    End Property

	Private _status As Byte
	<DataMember()>
	Public Property Status() As Byte
        Get
            Return _status
        End Get
        Set(ByVal value As Byte)
            If Not Equals(_status, value) Then
                _status = value
                OnPropertyChanged("Status")
            End If
        End Set
    End Property

	Private _cancellationReason As String
	<DataMember()>
	Public Property CancellationReason() As String
        Get
            Return _cancellationReason
        End Get
        Set(ByVal value As String)
            If Not Equals(_cancellationReason, value) Then
                _cancellationReason = value
                OnPropertyChanged("CancellationReason")
            End If
        End Set
    End Property

	Private _creationUser As String
	<DataMember()>
	Public Property CreationUser() As String
        Get
            Return _creationUser
        End Get
        Set(ByVal value As String)
            If Not Equals(_creationUser, value) Then
                _creationUser = value
                OnPropertyChanged("CreationUser")
            End If
        End Set
    End Property

	Private _creationDate As Date
	<DataMember()>
	Public Property CreationDate() As Date
        Get
            Return _creationDate
        End Get
        Set(ByVal value As Date)
            If Not Equals(_creationDate, value) Then
                _creationDate = value
                OnPropertyChanged("CreationDate")
            End If
        End Set
    End Property

	Private _modificationUser As String
	<DataMember()>
	Public Property ModificationUser() As String
        Get
            Return _modificationUser
        End Get
        Set(ByVal value As String)
            If Not Equals(_modificationUser, value) Then
                _modificationUser = value
                OnPropertyChanged("ModificationUser")
            End If
        End Set
    End Property

	Private _modificationDate As Nullable(Of Date)
	<DataMember()>
	Public Property ModificationDate() As Nullable(Of Date)
        Get
            Return _modificationDate
        End Get
        Set(ByVal value As Nullable(Of Date))
            If Not Equals(_modificationDate, value) Then
                _modificationDate = value
                OnPropertyChanged("ModificationDate")
            End If
        End Set
    End Property

	Private _approvalUser As String
	<DataMember()>
	Public Property ApprovalUser() As String
        Get
            Return _approvalUser
        End Get
        Set(ByVal value As String)
            If Not Equals(_approvalUser, value) Then
                _approvalUser = value
                OnPropertyChanged("ApprovalUser")
            End If
        End Set
    End Property

	Private _approvalDate As Nullable(Of Date)
	<DataMember()>
	Public Property ApprovalDate() As Nullable(Of Date)
        Get
            Return _approvalDate
        End Get
        Set(ByVal value As Nullable(Of Date))
            If Not Equals(_approvalDate, value) Then
                _approvalDate = value
                OnPropertyChanged("ApprovalDate")
            End If
        End Set
    End Property

	Private _cancellationUser As String
	<DataMember()>
	Public Property CancellationUser() As String
        Get
            Return _cancellationUser
        End Get
        Set(ByVal value As String)
            If Not Equals(_cancellationUser, value) Then
                _cancellationUser = value
                OnPropertyChanged("CancellationUser")
            End If
        End Set
    End Property

	Private _cancellationDate As Nullable(Of Date)
	<DataMember()>
	Public Property CancellationDate() As Nullable(Of Date)
        Get
            Return _cancellationDate
        End Get
        Set(ByVal value As Nullable(Of Date))
            If Not Equals(_cancellationDate, value) Then
                _cancellationDate = value
                OnPropertyChanged("CancellationDate")
            End If
        End Set
    End Property

#End Region

#Region "Navigation Properties"

    <DataMember()>
    Public Property Employee() As Employee
        Get
            Return _employee
        End Get
        Set(ByVal value As Employee)
            If _employee IsNot value Then
                Dim previousValue As Employee = _employee
                _employee = value
                FixupEmployee(previousValue)
                OnNavigationPropertyChanged("Employee")
            End If
        End Set
    End Property

    Private _employee As Employee


#End Region

#Region "ChangeTracking"

    Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
        If ChangeTracker.State <> ObjectState.Added AndAlso ChangeTracker.State <> ObjectState.Deleted Then
            ChangeTracker.State = ObjectState.Modified
        End If
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Protected Overridable Sub OnNavigationPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Private _changeTracker As ObjectChangeTracker

    <DataMember()>
    Public Property ChangeTracker() As ObjectChangeTracker Implements IObjectWithChangeTracker.ChangeTracker
        Get
            If _changeTracker Is Nothing Then
                _changeTracker = New ObjectChangeTracker()
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            Return _changeTracker
        End Get
        Set(ByVal value As ObjectChangeTracker)
            If _changeTracker IsNot Nothing Then
                RemoveHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            _changeTracker = value
            If _changeTracker IsNot Nothing Then
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
        End Set
    End Property

    Private Sub HandleObjectStateChanging(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.ClearNavigationProperties()
        End If
    End Sub

    Private _isDeserializing As Boolean
    Protected Property IsDeserializing() As Boolean
        Get
            Return _isDeserializing
        End Get
        Private Set(ByVal value As Boolean)
            _isDeserializing = value
        End Set
    End Property

    <OnDeserializing()>
    Public Sub OnDeserializingMethod(ByVal context As StreamingContext)
        IsDeserializing = True
    End Sub

    <OnDeserialized()>
    Public Sub OnDeserializedMethod(ByVal context As StreamingContext)
        IsDeserializing = False
        ChangeTracker.ChangeTrackingEnabled = True
    End Sub

    Protected Overridable Sub ClearNavigationProperties()
        Employee = Nothing
    End Sub

#End Region

#Region "Association Fixup"

    Private Sub FixupEmployee(ByVal previousValue As Employee)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.VacationRequest.Contains(Me) Then
            previousValue.VacationRequest.Remove(Me)
        End If

        If Employee IsNot Nothing Then
            Employee.VacationRequest.Add(Me)

            EmployeeId = Employee.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("Employee") AndAlso
                ChangeTracker.OriginalValues("Employee") Is Employee Then
                ChangeTracker.OriginalValues.Remove("Employee")
            Else
                ChangeTracker.RecordOriginalValue("Employee", previousValue)
            End If
            If Employee IsNot Nothing AndAlso Not Employee.ChangeTracker.ChangeTrackingEnabled Then
                Employee.StartTracking()
            End If
        End If
    End Sub

#End Region

End Class

