CREATE EXTERNAL TABLE [FixedAsset].[FixedAssetPhysicalAsset_temp] (
    [Id] INT NOT NULL,
    [ItemId] INT NOT NULL,
    [MainAccountId] INT NOT NULL,
    [Serie] VARCHAR (50) NOT NULL,
    [Plate] VARCHAR (50) NOT NULL,
    [LocationId] INT NOT NULL,
    [ResponsibleId] INT NOT NULL,
    [SupplierId] INT NULL,
    [HistoricalValue] DECIMAL (18, 2) NOT NULL,
    [FairValue] DECIMAL (18, 2) NOT NULL,
    [TrademarkId] INT NOT NULL,
    [Model] VARCHAR (100) NOT NULL,
    [PolicyId] INT NULL,
    [HandlesWarranty] BIT NOT NULL,
    [WarrantyExpirationDate] DATE NULL,
    [AdquisitionDate] DATE NOT NULL,
    [InstallationDate] DATE NULL,
    [Depreciate] BIT NOT NULL,
    [HasOutput] BIT NOT NULL,
    [OutputDate] DATE NULL,
    [OutputRefund] BIT NOT NULL,
    [Observation] VARCHAR (1000) NULL,
    [StatusAssetId] INT NOT NULL,
    [Status] BIT NOT NULL,
    [TimeStamp] ROWVERSION NOT NULL,
    [AdquisitionType] TINYINT NOT NULL,
    [NumberContractLeasing] VARCHAR (50) NULL,
    [InitialDateLeasing] DATE NULL,
    [EndDateLeasing] DATE NULL,
    [ApplyMinimunAmount] BIT NOT NULL,
    [AdquisitionTypeReal] TINYINT NOT NULL,
    [PurchaseDate] DATE NULL,
    [EntryNumber] VARCHAR (20) NULL,
    [VoucherTransactionNumber] VARCHAR (20) NULL,
    [HasReclassified] BIT NOT NULL,
    [EndDateLeasingExecuted] DATE NULL,
    [RecoverableValue] DECIMAL (18, 2) NOT NULL,
    [HasHighTech] BIT NOT NULL,
    [NetHistoricalValue] DECIMAL (18, 2) NOT NULL,
    [FinancialDiscount] DECIMAL (18, 2) NOT NULL,
    [Amortize] BIT NOT NULL
)
    WITH (
    DATA_SOURCE = [INDIGO999_temp]
    );

