<ServiceModel.ServiceContract()>
Public Interface IFixedAssetService
    Inherits IFixedAssetSequense, IFixedAssetBlockRecordFixedAsset, IFixedAssetFixedAssetLocation, IFixedAssetTrademarkService, IFixedAssetPolicyTypeService, IFixedAssetPolicyService
    Inherits IFixedAssetInsuranceService, IFixedAssetPartsAccesoriesConsumablesService, ISettingFixedAssetService, IFixedAssetItemCatalogService, IFixedAssetInventoryTypeService
    Inherits IFixedAssetItemTypeService, IFixedAssetResponsibleTypeService, IFixedAssetVinculationTypeService, IFixedAssetResponsibleService, IFixedAssetFixedAssetRemissionEntranceService
    Inherits IFixedAssetItemTypePartsAccesoriesConsumablesService, IFixedAssetEntryService, IFixedAssetPurchaseOrderService, IFixedAssetItemService, IFixedAssetValorizationService
    Inherits IFixedAssetLocationTypeService, IFixedAssetInitialBalanceService, IFixedAssetTransferService, IFixedAssetActiveOutputService, IFixedAssetPhysicalAssetService, IFixedAssetChangePlateService
    Inherits IFixedAssetStatusService, IFixedAssetDepreciationService, IFixedAssetEntryDevolutionService, IFixedAssetReclassificationService, IFixedAssetDeteriorationIndicationService
    Inherits IFixedAssetPhysicalAssetPartService, IFixedAssetServiceReports, IFixedAssetRetirementTypesService, IFixedAssetCatalogOfPropertyandServicesService
End Interface
