CREATE FUNCTION [dbo].[InterpretacionEscala] 
(
@IDHCESCALAS AS int, 
@CodigoEscala AS varchar(500), 
@Resultado AS varchar(500),
@ResultadoDecimal AS decimal,
@Sexo AS int
)

RETURNS varchar(500)
AS
BEGIN

declare @InterpretacionEscala varchar(500)

SELECT @InterpretacionEscala = CASE @CodigoEscala
			WHEN 1 THEN CASE @Resultado WHEN 0 THEN '0-Bebedor social' WHEN 1 THEN '1-Bebedor social' WHEN 2 THEN '2-Consumo de riesgo' WHEN 3 THEN '3-Consumo perjudicial' WHEN 4 THEN '4-Dependencia alcohólica' END 
			WHEN 2 THEN CASE WHEN @Resultado in(18,19,20) THEN CONVERT(varchar, @Resultado) +'-'+ 'Buena función familiar' WHEN @Resultado in(14,15,16,17) THEN CONVERT(varchar, @Resultado) +'-'+ 'Disfunción familiar leve' WHEN @Resultado IN(10,11,12,13) THEN CONVERT(varchar, @Resultado) +'-'+ 'Disfunción familiar moderada' ELSE CONVERT(varchar, @Resultado) +'-'+ 'Disfunción familiar severa' END
			WHEN 3 THEN CASE WHEN @Resultado in(0,1,2,3,4,5,6,7,8,9) THEN CONVERT(varchar, @Resultado) +'-'+ 'Sin riesgo de depresión' WHEN @Resultado in(10,11,12) THEN CONVERT(varchar, @Resultado) +'-'+ 'En riesgo de depresión' ELSE CONVERT(varchar, @Resultado) +'-'+ 'Sospecha de depresión'  END
			WHEN 4 THEN CASE WHEN @Resultado < 3  THEN CONVERT(varchar, @Resultado) +'-'+ 'Bajo riesgo' WHEN @Resultado >= 3 THEN CONVERT(varchar, @Resultado) +'-'+ 'Alto riesgo' END
			WHEN 5 THEN CASE WHEN @Resultado in(0) THEN CONVERT(varchar, @Resultado) +'-'+ 'No violencia doméstica.' WHEN @Resultado >= 1 THEN CONVERT(varchar, @Resultado) +'-'+ 'Violencia doméstica.' END
			WHEN 6 THEN CASE WHEN @Resultado < 10 THEN CONVERT(varchar, @Resultado) +'-'+ 'Riesgo bajo.' WHEN @Resultado IN(10,11,12,13,14,15,16,17,18,19,20) THEN CONVERT(varchar, @Resultado) +'-'+ 'Riesgo moderado.' WHEN @Resultado > 20 THEN CONVERT(varchar, @Resultado) +'-'+ 'Riesgo alto.' END
			WHEN 7 THEN CASE WHEN @Resultado in(0,1,2,3) THEN CONVERT(varchar, @Resultado) +'-'+ 'No adherente al tratamiento' WHEN @Resultado = 4 THEN CONVERT(varchar, @Resultado) +'-'+ 'Adherente al tratamiento.' END
			WHEN 8 THEN CASE WHEN @Resultado < 12 THEN CONVERT(varchar, @Resultado) +'-'+ 'Baja probabilidad de diabetes.' WHEN @Resultado >= 12 THEN CONVERT(varchar, @Resultado) +'-'+ 'Alta probabilidad de diabetes mellitus tipo II.' END
			WHEN 9 THEN CASE WHEN @Resultado in(25,26,27,28,29) THEN CONVERT(varchar, @Resultado) +'-'+ 'Probablemente sin deterioro.' WHEN @Resultado in(20,21,22,23,24) THEN CONVERT(varchar, @Resultado) +'-'+ 'Probablemente con deterioro leve.' WHEN @Resultado in(15,16,17,18,19) THEN CONVERT(varchar, @Resultado) +'-'+ 'Deterioro moderado.' WHEN @Resultado < 14 THEN CONVERT(varchar, @Resultado) +'-'+ 'Deterioro Grave.' END
			WHEN 10 THEN CASE WHEN @Resultado in(0,1,2) THEN CONVERT(varchar, @Resultado) +'-'+ 'Dependencia muy baja.' WHEN @Resultado in(3,4) THEN CONVERT(varchar, @Resultado) +'-'+ 'Dependencia baja.' WHEN @Resultado in(5) THEN CONVERT(varchar, @Resultado) +'-'+ 'Dependencia moderada.' WHEN @Resultado in(6,7) THEN CONVERT(varchar, @Resultado) +'-'+ 'Dependencia alta.' WHEN @Resultado in(8,9,10) THEN CONVERT(varchar, @Resultado) +'-'+ 'Dependencia muy alta.' END
			WHEN 11 THEN CASE WHEN @Resultado = 1 THEN CONVERT(varchar, @Resultado) +'-'+ 'Estadio I' WHEN @Resultado = 2 THEN CONVERT(varchar, @Resultado) +'-'+ 'Estadio II' WHEN @Resultado = 3 THEN CONVERT(varchar, @Resultado) +'-'+ 'Estadio III' WHEN @Resultado = 4 THEN CONVERT(varchar, @Resultado) +'-'+ 'Estadio IV' WHEN @Resultado = 5 THEN CONVERT(varchar, @Resultado) +'-'+ 'Estadio V' END
			WHEN 12 THEN CASE WHEN @Resultado = 1 THEN CONVERT(varchar, @Resultado) +'-'+ 'Estadio I' WHEN @Resultado = 2 THEN CONVERT(varchar, @Resultado) +'-'+ 'Estadio II' WHEN @Resultado = 3 THEN CONVERT(varchar, @Resultado) +'-'+ 'Estadio III' WHEN @Resultado = 4 THEN CONVERT(varchar, @Resultado) +'-'+ 'Estadio IV' WHEN @Resultado = 5 THEN CONVERT(varchar, @Resultado) +'-'+ 'Estadio V' END
			WHEN 13 THEN CASE WHEN @Resultado = 1 THEN CONVERT(varchar, @Resultado) +'-'+ 'Estadio I' WHEN @Resultado = 2 THEN CONVERT(varchar, @Resultado) +'-'+ 'Estadio II' WHEN @Resultado = 3 THEN CONVERT(varchar, @Resultado) +'-'+ 'Estadio III' WHEN @Resultado = 4 THEN CONVERT(varchar, @Resultado) +'-'+ 'Estadio IV' WHEN @Resultado = 5 THEN CONVERT(varchar, @Resultado) +'-'+ 'Estadio V' END
			WHEN 14 THEN CASE WHEN @Resultado = 1 THEN CONVERT(varchar, @Resultado) +'-'+ 'Estadio I' WHEN @Resultado = 2 THEN CONVERT(varchar, @Resultado) +'-'+ 'Estadio II' WHEN @Resultado = 3 THEN CONVERT(varchar, @Resultado) +'-'+ 'Estadio III' WHEN @Resultado = 4 THEN CONVERT(varchar, @Resultado) +'-'+ 'Estadio IV' WHEN @Resultado = 5 THEN CONVERT(varchar, @Resultado) +'-'+ 'Estadio V' END
			WHEN 15 THEN CASE WHEN @Resultado = 0 THEN CONVERT(varchar, @Resultado) +'-'+ 'Sin úlcera' WHEN @Resultado = 1 THEN CONVERT(varchar, @Resultado) +'-'+ 'Úlcera superficial' WHEN @Resultado = 2 THEN CONVERT(varchar, @Resultado) +'-'+ 'Úlcera profunda' WHEN @Resultado = 3 THEN CONVERT(varchar, @Resultado) +'-'+ 'Úlcera profunda con formación de absceso' WHEN @Resultado = 4 THEN CONVERT(varchar, @Resultado) +'-'+ 'Gangrena localizada' WHEN @Resultado = 5 THEN CONVERT(varchar, @Resultado) +'-'+ 'Gangrena extensa' END
			WHEN 16 THEN CASE WHEN @Resultado = 0 THEN CONVERT(varchar, @Resultado) +'-'+ 'Grado 0' WHEN @Resultado = 1 THEN CONVERT(varchar, @Resultado) +'-'+ 'Grado 1' WHEN @Resultado = 2 THEN CONVERT(varchar, @Resultado) +'-'+ 'Grado 2' WHEN @Resultado = 3 THEN CONVERT(varchar, @Resultado) +'-'+ 'Grado 3' WHEN @Resultado = 4 THEN CONVERT(varchar, @Resultado) +'-'+ 'Grado 4' WHEN @Resultado = 5 THEN CONVERT(varchar, @Resultado) +'-'+ 'Grado 5' END
			WHEN 17 THEN CASE WHEN @Resultado < 10 THEN CONVERT(varchar, @Resultado) +'-'+ 'Impacto bajo de la EPOC' WHEN @Resultado >= 10 THEN CONVERT(varchar, @Resultado) +'-'+ 'Impacto medio / alto de la EPOC' END
			WHEN 18 THEN CASE WHEN @Resultado = 1 THEN CONVERT(varchar, @Resultado) +'-'+ '≥ 2 exacerbaciones en el año o ≥ 1 causante de hospitalización.' WHEN @Resultado = 2 THEN CONVERT(varchar, @Resultado) +'-'+ '0 o 1 exacerbación en el año sin ingreso hospitalario' END
			WHEN 19 THEN CASE WHEN @Resultado = 1 THEN 'Clasificación EPOC: GRUPO A' WHEN @Resultado = 2 THEN 'Clasificación EPOC: GRUPO B' WHEN @Resultado = 3 THEN 'Clasificación EPOC: GRUPO C' WHEN @Resultado = 4 THEN 'Clasificación EPOC: GRUPO D' END
			WHEN 20 THEN CASE WHEN @Resultado = 15 THEN CONVERT(varchar, @Resultado) +'-'+ 'Genialidad' WHEN (@Resultado >= 140 AND @Resultado <= 149)  THEN CONVERT(varchar, @Resultado) +'-'+ 'Casi genialidad' WHEN (@Resultado >= 120 AND @Resultado <= 139)  THEN CONVERT(varchar, @Resultado) +'-'+ 'Inteligencia muy superior' WHEN (@Resultado >= 110 AND @Resultado <= 119)  THEN CONVERT(varchar, @Resultado) +'-'+ 'Inteligencia superior' WHEN (@Resultado >= 90 AND @Resultado <= 109)  THEN CONVERT(varchar, @Resultado) +'-'+ 'Inteligencia normal o mediana' WHEN (@Resultado >= 80 AND @Resultado <= 89)  THEN CONVERT(varchar, @Resultado) +'-'+ 'Inteligencia lenta' WHEN (@Resultado >= 70 AND @Resultado <= 79)  THEN CONVERT(varchar, @Resultado) +'-'+ 'Limítrofe (bordeline o fronterizo)' WHEN (@Resultado >= 50 AND @Resultado <= 69)  THEN CONVERT(varchar, @Resultado) +'-'+ 'Deficiencia mental superficial' WHEN (@Resultado >= 30 AND @Resultado <= 49)  THEN CONVERT(varchar, @Resultado) +'-'+ 'Deficiencia mental media' WHEN @Resultado < 30  THEN CONVERT(varchar, @Resultado) +'-'+ 'Deficiencia mental profunda' END
			WHEN 21 THEN CASE WHEN @Resultado = 1 THEN 'Clasificación EPOC: GRUPO A' WHEN @Resultado = 2 THEN 'Clasificación EPOC: GRUPO B' WHEN @Resultado = 3 THEN 'Clasificación EPOC: GRUPO C' WHEN @Resultado = 4 THEN 'Clasificación EPOC: GRUPO D' END
			WHEN 22 THEN @Resultado --'Abreviada Desarrollo'
			WHEN 23 THEN CASE WHEN @Resultado in(1, 2, 3, 4, 5, 6, 7, 8, 9) THEN CONVERT(varchar, @Resultado) +'-'+ 'Clase I: Enfermos con menos de 10 puntos. No requieren de UCI' WHEN @Resultado in(10, 11, 12, 13, 14, 15, 16, 17, 18, 19) THEN CONVERT(varchar, @Resultado) +'-'+ 'Clase II: Enfermos con 10-19 puntos' WHEN @Resultado IN(20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39) THEN CONVERT(varchar, @Resultado) +'-'+ 'Clase III: Enfermos con 20-39 puntos' ELSE CONVERT(varchar, @Resultado) +'-'+ 'Clase IV: Enfermos con 40 o más puntos' END
			WHEN 24 THEN CASE WHEN @Resultado <= 12 THEN CONVERT(varchar, @Resultado) +'-'+ 'ALTO RIESGO: Puntuación total < 12' WHEN @Resultado in(13, 14) THEN CONVERT(varchar, @Resultado) +'-'+ 'RIESGO MODERADO: Puntuación total 13 – 14 puntos' WHEN @Resultado IN(15,16,17,18) THEN CONVERT(varchar, @Resultado) +'-'+ 'RIESGO BAJO: Puntuación total 15 – 16 si menor de 75 años o de 15 – 18 si mayor o igual a 75 años' WHEN @Resultado > 18 THEN CONVERT(varchar, @Resultado) +'-'+ 'Sin Riesgo' END
			WHEN 25 THEN CASE WHEN @Resultado in(0, 1, 2, 3, 4) THEN CONVERT(varchar, @Resultado) +'-'+ 'Mortalidad esperada: 4%' WHEN @Resultado in(5, 6, 7, 8, 9) THEN CONVERT(varchar, @Resultado) +'-'+ 'Mortalidad esperada: 8%' WHEN @Resultado IN(10, 11, 12, 13, 14) THEN CONVERT(varchar, @Resultado) +'-'+ 'Mortalidad esperada: 15%' WHEN @Resultado IN(15, 16, 17, 18, 19) THEN CONVERT(varchar, @Resultado) +'-'+ 'Mortalidad esperada: 25%' WHEN @Resultado IN(20, 21, 22, 23, 24) THEN CONVERT(varchar, @Resultado) +'-'+ 'Mortalidad esperada: 40%' WHEN @Resultado IN(25, 26, 27, 28, 29) THEN CONVERT(varchar, @Resultado) +'-'+ 'Mortalidad esperada: 55%' WHEN @Resultado IN(30,31,32,33,34) THEN CONVERT(varchar, @Resultado) +'-'+ 'Mortalidad esperada: 73%' ELSE CONVERT(varchar, @Resultado) +'-'+ 'Mortalidad esperada: >85%' END
			WHEN 26 THEN CASE WHEN @Resultado >= 80 AND  @Resultado <= 100 THEN CONVERT(varchar, @Resultado) +'-'+ 'Capaz de realizar actividades normales' WHEN @Resultado >= 50 AND @Resultado <= 70 THEN CONVERT(varchar, @Resultado) +'-'+ 'Incapaz de trabajar' WHEN @Resultado >= 0 AND @Resultado <= 40 THEN CONVERT(varchar, @Resultado) +'-'+ 'Incapaz de autocuidarse' END
			WHEN 27 THEN CASE WHEN @Resultado = 0 THEN CONVERT(varchar, @Resultado) +'-'+ 'Asintomático, actividad normal' WHEN @Resultado = 1 THEN CONVERT(varchar, @Resultado) +'-'+ 'Sintomático, ambulatorio y realiza las actividades cotidianas' WHEN @Resultado = 2 THEN CONVERT(varchar, @Resultado) +'-'+ 'Sintomático, en cama menos del 50% del día' WHEN @Resultado = 3 THEN CONVERT(varchar, @Resultado) +'-'+ 'Sintomático, en cama más del 50% del día' WHEN @Resultado = 4 THEN CONVERT(varchar, @Resultado) +'-'+ 'No se levanta y puede necesitar internación' WHEN @Resultado = 5 THEN CONVERT(varchar, @Resultado) +'-'+ 'Muerto' END
			WHEN 28 THEN CASE WHEN @Resultado < 17 THEN CONVERT(varchar, @Resultado) +'-'+ 'Clase I: No requieren de UCI' WHEN @Resultado >= 18 and @Resultado <= 30 THEN CONVERT(varchar, @Resultado) +'-'+ 'Clase II: Estables con monitorización invasiva o no y vigilancia intensiva .La evolución más probable es la mejoría.' WHEN @Resultado >= 31 THEN CONVERT(varchar, @Resultado) +'-'+ 'Clase III: Inestables que requieren cuidados médicos y de enfermería intensiva con frecuentes valoraciones y cambios de órdenes de tratamiento' END
			WHEN 29 THEN (SELECT CONCAT('Apertura Ocular: ' + CASE APERTURAOCULAR WHEN 4 THEN CONVERT(varchar, APERTURAOCULAR) +'-'+ 'Espontánea' WHEN 3 THEN CONVERT(varchar, APERTURAOCULAR) +'-'+ 'A la orden' WHEN 2 THEN CONVERT(varchar, APERTURAOCULAR) +'-'+ 'Ante un estímulo doloroso' WHEN 1 THEN CONVERT(varchar, APERTURAOCULAR) +'-'+ 'Ausencia de apertura ocular' END, + ' Respuesta Verbal: ' + CASE RESPUESTAVERVAL WHEN 5 THEN CONVERT(varchar, RESPUESTAVERVAL) +'-'+ 'Orientado correctamente' WHEN 4 THEN CONVERT(varchar, RESPUESTAVERVAL) +'-'+ 'Paciente confuso' WHEN 3 THEN CONVERT(varchar, RESPUESTAVERVAL) +'-'+ 'Lenguaje inapropiado' WHEN 1 THEN CONVERT(varchar, RESPUESTAVERVAL) +'-'+ 'Carencia de actividad verbal' END, + ' Respuesta Motora: ' + CASE RESPUESTAMOTORA WHEN 6 THEN CONVERT(varchar, RESPUESTAMOTORA) +'-'+ 'Obedece órdenes' WHEN 5 THEN CONVERT(varchar, RESPUESTAMOTORA) +'-'+ 'Localiza estímulos dolorosos' WHEN 4 THEN CONVERT(varchar, RESPUESTAMOTORA) +'-'+ 'Se retira al dolor' WHEN 3 THEN CONVERT(varchar, RESPUESTAMOTORA) +'-'+ 'Respuesta con flexión anormal de los miembros' WHEN 2 THEN CONVERT(varchar, RESPUESTAMOTORA) +'-'+ 'Respuesta con extensión anormal de los miembros' WHEN 1 THEN CONVERT(varchar, RESPUESTAMOTORA) +'-'+ 'Ausencia de respuesta motora' END) FROM ESCALAGLASGOW WHERE IDHCESCALAS = @IDHCESCALAS)
			WHEN 30 THEN (SELECT CONCAT('Apertura Ocular: ' + CASE APERTURAOCULAR WHEN 4 THEN CONVERT(varchar, APERTURAOCULAR) +'-'+ 'Espontánea' WHEN 3 THEN CONVERT(varchar, APERTURAOCULAR) +'-'+ 'A la orden' WHEN 2 THEN CONVERT(varchar, APERTURAOCULAR) +'-'+ 'Ante un estímulo doloroso' WHEN 1 THEN CONVERT(varchar, APERTURAOCULAR) +'-'+ 'Ausencia de apertura ocular' END, + ' Respuesta Verbal: ' + CASE RESPUESTAVERVAL WHEN 5 THEN CONVERT(varchar, RESPUESTAVERVAL) +'-'+ 'Palabras adecuadas' WHEN 4 THEN CONVERT(varchar, RESPUESTAVERVAL) +'-'+ 'Palabras inadecuadas' WHEN 3 THEN CONVERT(varchar, RESPUESTAVERVAL) +'-'+ 'Llora o grita' WHEN 1 THEN CONVERT(varchar, RESPUESTAVERVAL) +'-'+ 'Sin respuesta' END, + ' Respuesta Motora: ' + CASE RESPUESTAMOTORA WHEN 6 THEN CONVERT(varchar, RESPUESTAMOTORA) +'-'+ 'Obedece órdenes' WHEN 5 THEN CONVERT(varchar, RESPUESTAMOTORA) +'-'+ 'Localiza estímulos dolorosos' WHEN 4 THEN CONVERT(varchar, RESPUESTAMOTORA) +'-'+ 'Se retira al dolor' WHEN 3 THEN CONVERT(varchar, RESPUESTAMOTORA) +'-'+ 'Respuesta con flexión anormal de los miembros' WHEN 2 THEN CONVERT(varchar, RESPUESTAMOTORA) +'-'+ 'Respuesta con extensión anormal de los miembros' WHEN 1 THEN CONVERT(varchar, RESPUESTAMOTORA) +'-'+ 'Ausencia de respuesta motora' END) FROM ESCALAGLASGOW WHERE IDHCESCALAS = @IDHCESCALAS)
			WHEN 31 THEN (SELECT CONCAT('Apertura Ocular: ' + CASE APERTURAOCULAR WHEN 4 THEN CONVERT(varchar, APERTURAOCULAR) +'-'+ 'Espontánea' WHEN 3 THEN CONVERT(varchar, APERTURAOCULAR) +'-'+ 'A la voz' WHEN 2 THEN CONVERT(varchar, APERTURAOCULAR) +'-'+ 'Ante un estímulo doloroso' WHEN 1 THEN CONVERT(varchar, APERTURAOCULAR) +'-'+ 'Ausencia de apertura ocular' END, + ' Respuesta Verbal: ' + CASE RESPUESTAVERVAL WHEN 5 THEN CONVERT(varchar, RESPUESTAVERVAL) +'-'+ 'Sonríe, balbucea' WHEN 4 THEN CONVERT(varchar, RESPUESTAVERVAL) +'-'+ 'Llanto consolable' WHEN 3 THEN CONVERT(varchar, RESPUESTAVERVAL) +'-'+ 'Llora ante el dolor' WHEN 1 THEN CONVERT(varchar, RESPUESTAVERVAL) +'-'+ 'Sin respuesta' END, + ' Respuesta Motora: ' + CASE RESPUESTAMOTORA WHEN 6 THEN CONVERT(varchar, RESPUESTAMOTORA) +'-'+ 'Movimientos espontáneos' WHEN 5 THEN CONVERT(varchar, RESPUESTAMOTORA) +'-'+ 'Se retira al contacto' WHEN 4 THEN CONVERT(varchar, RESPUESTAMOTORA) +'-'+ 'Se retira al dolor' WHEN 3 THEN CONVERT(varchar, RESPUESTAMOTORA) +'-'+ 'Flexión al dolor' WHEN 2 THEN CONVERT(varchar, RESPUESTAMOTORA) +'-'+ 'Extensión al dolor' WHEN 1 THEN CONVERT(varchar, RESPUESTAMOTORA) +'-'+ 'Ausencia de respuesta motora' END) FROM ESCALAGLASGOW WHERE IDHCESCALAS = @IDHCESCALAS)
			WHEN 32 THEN CASE WHEN @Resultado >= 0 AND  @Resultado <= 6 THEN CONVERT(varchar, @Resultado) +' ptos - '+ 'probabilidad Mortalidad: < 10%' WHEN @Resultado >= 7 AND @Resultado <= 9 THEN CONVERT(varchar, @Resultado) +' ptos - '+ 'probabilidad Mortalidad: 15 - 20%' WHEN @Resultado >= 10 AND @Resultado <= 14 THEN CONVERT(varchar, @Resultado) +' ptos - '+ 'probabilidad Mortalidad: 50 - 60%' WHEN @Resultado = 15 THEN CONVERT(varchar, @Resultado) +' ptos - '+ 'probabilidad Mortalidad: > 80%' WHEN @Resultado > 15 AND @Resultado <= 24 THEN CONVERT(varchar, @Resultado) +' ptos - '+ 'probabilidad Mortalidad: > 90%' END
			WHEN 33 THEN CASE WHEN @Resultado >= 5 THEN CONVERT(varchar, @Resultado) +' ptos - '+ 'probabilidad Mortalidad: 85%' WHEN @Resultado in(3,4) THEN CONVERT(varchar, @Resultado) +' ptos - '+ 'probabilidad Mortalidad: 52%' WHEN @Resultado IN(0,1,2) THEN CONVERT(varchar, @Resultado) +' ptos - '+ 'probabilidad Mortalidad: < 26%' END
			WHEN 34 THEN CASE WHEN @Resultado <= 21 THEN CONVERT(varchar, @Resultado) +' ptos - '+ 'probabilidad Mortalidad: 0%' WHEN @Resultado in(2,23) THEN CONVERT(varchar, @Resultado) +' ptos - '+ 'probabilidad Mortalidad: 1-10%' WHEN @Resultado >= 44 and @Resultado <= 52 THEN CONVERT(varchar, @Resultado) +' ptos - '+ 'probabilidad Mortalidad: 10-20%' WHEN @Resultado >= 53 and @Resultado <= 57 THEN CONVERT(varchar, @Resultado) +' ptos - '+ 'probabilidad Mortalidad: 20-30%' WHEN @Resultado >= 58 and @Resultado <= 62 THEN CONVERT(varchar, @Resultado) +' ptos - '+ 'probabilidad Mortalidad: 30-40%' WHEN @Resultado >= 63 and @Resultado <= 67 THEN CONVERT(varchar, @Resultado) +' ptos - '+ 'probabilidad Mortalidad: 40-50%' WHEN @Resultado >= 68 and @Resultado <= 72 THEN CONVERT(varchar, @Resultado) +' ptos - '+ 'probabilidad Mortalidad: 50-60%' WHEN @Resultado >= 73 and @Resultado <= 78 THEN CONVERT(varchar, @Resultado) +' ptos - '+ 'probabilidad Mortalidad: 60-70%' WHEN @Resultado >= 79 and @Resultado <= 86 THEN CONVERT(varchar, @Resultado) +' ptos - '+ 'probabilidad Mortalidad: 70-80%' WHEN @Resultado >= 87 and @Resultado <= 96 THEN CONVERT(varchar, @Resultado) +' ptos - '+ 'probabilidad Mortalidad: 80-90%' WHEN @Resultado >= 91 and @Resultado <= 112 THEN CONVERT(varchar, @Resultado) +' ptos - '+ 'probabilidad Mortalidad: 90-95%' WHEN @Resultado >= 113 and @Resultado <= 159 THEN CONVERT(varchar, @Resultado) +' ptos - '+ 'probabilidad Mortalidad: 95-99%' WHEN @Resultado >= 160  THEN CONVERT(varchar, @Resultado) +' ptos - '+ 'probabilidad Mortalidad: 100%' END
			WHEN 35 THEN CASE WHEN @Resultado < 20 THEN CONVERT(varchar, @Resultado) +'-'+ 'Dependencia total' WHEN @Resultado >= 21 and @Resultado <= 60 THEN CONVERT(varchar, @Resultado) +'-'+ 'Dependencia severa' WHEN @Resultado >= 61 AND @Resultado <= 90 THEN CONVERT(varchar, @Resultado) +'-'+ 'Dependencia moderada' WHEN @Resultado >= 91 AND @Resultado <= 99 THEN CONVERT(varchar, @Resultado) +'-'+ 'Dependencia leve' WHEN @Resultado >= 100 THEN CONVERT(varchar, @Resultado) +'-'+ 'independencia'  END
			WHEN 36 THEN CASE WHEN @Resultado <= 24 THEN CONVERT(varchar, @Resultado) +'-'+ 'Cuidados básicos de enfermería.' WHEN @Resultado >= 25 and @Resultado <= 50 THEN CONVERT(varchar, @Resultado) +'-'+ 'Implementar plan de prevención de caídas estándar.' WHEN @Resultado >= 51 THEN CONVERT(varchar, @Resultado) +'-'+ 'Implemntar medidas especiales' END
			WHEN 37 THEN CASE WHEN @Resultado <= 1 THEN CONVERT(varchar, @Resultado) +'-'+ 'Bajo Riesgo.' WHEN @Resultado >= 2 and @Resultado <= 3 THEN CONVERT(varchar, @Resultado) +'-'+ 'mediano Riesgo.' WHEN @Resultado >= 4 THEN CONVERT(varchar, @Resultado) +'-'+ 'Alto Riesgo' END
			WHEN 38 THEN CASE WHEN @Resultado <= 13 THEN CONVERT(varchar, @Resultado) +'-'+ 'Riesgo Alto' WHEN @Resultado > 13 THEN CONVERT(varchar, @Resultado) +'-'+ 'Sin Riesgo' END
			WHEN 39 THEN CASE WHEN @Resultado in(0,1) THEN CONVERT(varchar, @Resultado) +'-'+ 'Sin Riesgo.' WHEN @Resultado >= 2 THEN CONVERT(varchar, @Resultado) +'-'+ 'Riesgo de desnutrición.' END
			WHEN 40 THEN CASE WHEN @Resultado IN(0,1,2) THEN CONVERT(varchar, @Resultado) +'-'+ 'Bajo riesgo - Alta médica con seguimiento ambulatorio.' WHEN @Resultado IN(3,4) THEN CONVERT(varchar, @Resultado) +'-'+ 'Riesgo moderado - Seguimiento ambulatorio intensivo, considerar internación según criterio médico.' WHEN @Resultado IN(5,6) THEN CONVERT(varchar, @Resultado) +'-'+ 'Riesgo alto - Se recomienda internación, principalmente en pacientes con apoyo social precario.' WHEN @Resultado IN(7,8,9,10) THEN CONVERT(varchar, @Resultado) +'-'+ 'Riesgo muy alto - Internación, incluso en contra de la voluntad del paciente.' END
			WHEN 41 THEN CASE WHEN @Resultado <= 9 THEN CONVERT(varchar, @Resultado) +'-'+ 'No depresión' WHEN @Resultado >= 10 and @Resultado <= 18 THEN CONVERT(varchar, @Resultado) +'-'+ 'Depresión Leve' WHEN @Resultado >= 19 and @Resultado <= 29 THEN CONVERT(varchar, @Resultado) +'-'+ 'Depresión Moderada' WHEN @Resultado >= 30 THEN CONVERT(varchar, @Resultado) +'-'+ 'Depresión Severa' END
			WHEN 42 THEN CASE WHEN @Resultado <= 46 THEN CONVERT(varchar, @Resultado) +'-'+ 'Ausencia de sobrecarga' WHEN @Resultado >= 47 and @Resultado <= 55 THEN CONVERT(varchar, @Resultado) +'-'+ 'Sobrecarga ligera'  WHEN @Resultado >= 56 THEN CONVERT(varchar, @Resultado) +'-'+ 'Sobrecarga intensa' END
			WHEN 43 THEN CASE WHEN @Resultado = 0 THEN CONVERT(varchar, @Resultado) +'-'+ 'Normal'  WHEN @Resultado >= 1 THEN CONVERT(varchar, @Resultado) +'-'+ 'Realizar una visita de seguimiento para el niño y su familia'  END
			WHEN 44 THEN CASE WHEN @Resultado >= 0 and @Resultado <= 15 THEN CONVERT(varchar, @Resultado) +'% - '+ 'Higiene oral buena' WHEN @Resultado >= 16 and @Resultado <= 33 THEN CONVERT(varchar, @Resultado) +'% - '+ 'Higiene oral regular' WHEN @Resultado >= 34 and @Resultado <= 100 THEN CONVERT(varchar, @Resultado) +'% - '+ 'Higiene oral deficiente' END
			WHEN 45 THEN CASE WHEN @Resultado = 1 THEN CONVERT(varchar, @Resultado) +'-'+ 'Se considera en Riesgo mayor y su remisión es Urgente' WHEN @Resultado = 0 THEN CONVERT(varchar, @Resultado) +'-'+ 'Se considera en Riesgo menor y su remisión no es urgente' END
			WHEN 46 THEN CASE WHEN @Resultado IN (1,2,3,4) THEN CONVERT(varchar, @Resultado) +' -Observar si el paciente etá inquieto o agitado. -No haga ningún estímulo físico.' WHEN @Resultado = 0 THEN CONVERT(varchar, @Resultado) +' Realice nueva valoración si lo considera necesario.' WHEN @Resultado IN (-1,-2,-3) THEN CONVERT(varchar, @Resultado) +' -Llame al paciente por su nombre. -Puede repetir el nombre, pero no estimular físicamente. -Cuantifique el tiempo de contacto ocular.' WHEN @Resultado IN (-4,-5) THEN CONVERT(varchar, @Resultado) +' -Estimular al paciente, sacudiendo su hombro o frotando sobre la región esternal. -Podría ser necesario intentar evaluar de nuevo más tarde.' END
			WHEN 47 THEN CASE WHEN @Resultado < 3 THEN CONVERT(varchar, @Resultado) +' - '+ 'Bajo riesgo de caídas' WHEN @Resultado >= 3 THEN CONVERT(varchar, @Resultado) +' - '+ 'Alto riesgo de caídas' END
			WHEN 48 THEN @Resultado --'Norton'
			WHEN 49 THEN @Resultado --'Vass'
			WHEN 51 THEN (SELECT CONCAT('Resultado 1: ' + CASE WHEN RESULTADO1 >= 11 THEN 'Alta probabilidad de sufrir un trastorno depresivo o ansioso' WHEN RESULTADO1 < 11 THEN 'Baja probabilidad de sufrir un trastorno depresivo o ansioso' END, + ' Resultado 2: ' + CASE WHEN RESULTADO2 >= 1 THEN 'Presencia de trastorno psicótico' WHEN RESULTADO2 <= 0 THEN 'No presencia de trastorno psicótico' END, + ' Resultado 3: ' + CASE WHEN RESULTADO3 >= 1 THEN 'Caso de trastorno convulsivo'  WHEN RESULTADO3 <= 0 THEN 'No caso de trastorno convulsivo' END, + ' Resultado 4: ' + CASE WHEN RESULTADO4 >= 1 THEN 'Presencia de  consumo problemático de alcohol'  WHEN RESULTADO4 <= 0 THEN 'No presencia de  consumo problemático de alcohol' END) AS 'Resultado' FROM dbo.HCESCALADSQR WHERE IDHCESCALAS = @IDHCESCALAS)
			WHEN 52 THEN CASE WHEN @Resultado in(0,1,2) THEN CONVERT(varchar, @Resultado) +'-'+ 'Bajo riesgo' WHEN @Resultado in(3, 4, 5, 6, 7) THEN CONVERT(varchar, @Resultado) +'-'+ 'Mediano riesgo' WHEN @Resultado IN(8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20) THEN CONVERT(varchar, @Resultado) +'-'+ 'Alto riesgo'  END
			WHEN 53 THEN CASE WHEN @Resultado in(0) THEN CONVERT(varchar, @Resultado) +'-'+ 'Sin riesgo' WHEN @Resultado in(1,2) THEN CONVERT(varchar, @Resultado) +'-'+ 'Riesgo de depresión' END 
			WHEN 54 THEN CASE WHEN @Resultado IN(0,1,2,3,4,5,6,7) THEN CONVERT(varchar, @Resultado) +'-'+ 'Sin riesgo de alcoholismo.' WHEN @Resultado IN(8,9,10,11,12,13,14,15) THEN CONVERT(varchar, @Resultado) +'-'+ 'Consumo de riesgo.' WHEN @Resultado IN(16,17,18,19) THEN CONVERT(varchar, @Resultado) +'-'+ 'Consumo perjudicial de alcohol.' WHEN @Resultado >= 20 THEN CONVERT(varchar, @Resultado) +'-'+ 'Dependencia de alcohol.' END
			WHEN 55 THEN CASE WHEN @Resultado IN(0) THEN CONVERT(varchar, @Resultado) +'-'+ 'Sin riesgo de fragilidad.' WHEN @Resultado IN(1,2) THEN CONVERT(varchar, @Resultado) +'-'+ 'Pre frágil.' WHEN @Resultado >= 3 THEN CONVERT(varchar, @Resultado) +'-'+ 'Frágil' END
			WHEN 56 THEN CASE WHEN @Resultado IN(0,1) THEN CONVERT(varchar, @Resultado) +'-'+ 'Máxima dependencia.' WHEN @Resultado IN(2,3) THEN CONVERT(varchar, @Resultado) +'-'+ 'Dependencia severa.' WHEN @Resultado IN(4,5) THEN CONVERT(varchar, @Resultado) +'-'+ 'Dependencia moderada.' WHEN @Resultado IN(6,7) THEN CONVERT(varchar, @Resultado) +'-'+ 'Dependencia ligera.' WHEN @Resultado >= 8 THEN CONVERT(varchar, @Resultado) +'-'+ 'Independencia total.' END
			WHEN 57 THEN CASE WHEN @Resultado IN(0,1,2,3,4) THEN CONVERT(varchar, @Resultado) +'-'+ 'No se aprecia ansiedad.' WHEN @Resultado IN(5,6,7,8,9) THEN CONVERT(varchar, @Resultado) +'-'+ 'Síntomas de ansiedad leve.' WHEN @Resultado IN(10,11,12,13,14) THEN CONVERT(varchar, @Resultado) +'-'+ 'Síntomas de ansiedad moderada.'  WHEN @Resultado >= 15 THEN CONVERT(varchar, @Resultado) +'-'+ 'Síntomas de ansiedad severa.' END
			WHEN 58 THEN CASE WHEN @Resultado >= 0 and @Resultado < 17  THEN CONVERT(varchar, @Resultado) +'-'+ 'Malnutrición.' WHEN @Resultado >= 17 and @Resultado < 24  THEN CONVERT(varchar, @Resultado) +'-'+ 'Riesgo de malnutrición.'  WHEN @Resultado >= 24 THEN CONVERT(varchar, @Resultado) +'-'+ 'Estado nutricional normal.' END
			WHEN 59 THEN CASE WHEN @Resultado IN(0,1,2,3,4,5,6,7) THEN CONVERT(varchar, @Resultado) +'-'+ 'Malnutrición.' WHEN @Resultado IN(8,9,10,11) THEN CONVERT(varchar, @Resultado) +'-'+ 'Riesgo de malnutrición.'  WHEN @Resultado >= 12 THEN CONVERT(varchar, @Resultado) +'-'+ 'Estado nutricional normal.' END
			WHEN 60 THEN (SELECT STUFF(( SELECT CONCAT(CASE WHEN TAGPREGUNTA = 001 THEN ' Tabaco: ' WHEN TAGPREGUNTA = 002 THEN ' Alcohol: ' WHEN TAGPREGUNTA = 003 THEN ' Cannabis: ' WHEN TAGPREGUNTA = 004 THEN ' Cocaina: ' WHEN TAGPREGUNTA = 005 THEN ' Anfetaminas: ' WHEN TAGPREGUNTA = 006 THEN ' Inhalantes: ' WHEN TAGPREGUNTA = 007 THEN ' Sedantes: ' WHEN TAGPREGUNTA = 008 THEN ' Alucinógenos: ' WHEN TAGPREGUNTA = 009 THEN ' Opiaceos: ' WHEN TAGPREGUNTA = 010 THEN ' Otras drogas: ' END, + VALORITEMSELECCIONADO, + ' ' +TEXTOITEMSELECCIONADO) FROM HCESCALASRESULTITEMS WHERE IDHCESCALAS = @IDHCESCALAS FOR XML PATH('')),1,1, ''))
			WHEN 61 THEN CASE WHEN @Resultado = 0 THEN CONVERT(varchar, @Resultado) +'-'+ 'Riesgo Bajo' WHEN @Resultado in (1,2,3,4) THEN CONVERT(varchar, @Resultado) +'-'+ 'Riesgo Bajo' WHEN @Resultado in (5,6) THEN CONVERT(varchar, @Resultado) +'-'+ 'Riesgo Medio' WHEN @Resultado >= 7 THEN CONVERT(varchar, @Resultado) +'-'+ 'Riesgo Alto' END
			WHEN 62 THEN CASE @Sexo WHEN 1 THEN CONCAT(@Resultado,+ ' ' +CASE @Resultado WHEN  0 THEN 'Riesgo bajo'  WHEN  1 THEN 'Riesgo moderado' WHEN 2 THEN 'Riesgo moderado/alto' WHEN 3 THEN 'Riesgo moderado/alto'  WHEN 4 THEN 'Riesgo moderado/alto' WHEN  5 THEN 'Riesgo moderado/alto' WHEN 6 THEN 'Riesgo moderado/alto' WHEN 7 THEN 'Riesgo moderado/alto'  WHEN 8 THEN 'Riesgo alto' WHEN 9 THEN 'No Aplica' END) ELSE CONCAT(@Resultado,+ ' ' +CASE @Resultado WHEN  0 THEN 'No aplica'  WHEN  1 THEN 'Riesgo bajo' WHEN 2 THEN 'Riesgo moderado' WHEN 3 THEN 'Riesgo moderado/alto'  WHEN 4 THEN 'Riesgo moderado/alto' WHEN  5 THEN 'Riesgo moderado/alto' WHEN 6 THEN 'Riesgo moderado/alto' WHEN 7 THEN 'Riesgo moderado/alto'  WHEN 8 THEN 'Riesgo moderado/alto' WHEN 9 THEN 'Riesgo Alto' END) END
			WHEN 63 THEN CONCAT(@Resultado,+ ' ' +CASE WHEN @Resultado <= 20  THEN 'Muy bajo riesgo' WHEN  @Resultado > 20 and @Resultado <= 30 THEN 'Bajo riesgo' WHEN @Resultado > 30 and @Resultado <= 40 THEN  'Moderado riesgo' WHEN @Resultado > 40 and @Resultado <= 50 THEN 'Alto riesgo' WHEN  @Resultado > 50 THEN 'Muy alto riesgo' END)
			WHEN 64 THEN CONCAT(@Resultado, + ' ' + CASE @Resultado WHEN  0 THEN 'Bajo riesgo (0,6 - 1,13%)' WHEN  1 THEN 'Riesgo intermedio (1,88 - 3,2%)' WHEN 2 THEN 'Riesgo intermedio (1,88 - 3,2%)' Else 'Alto riesgo	(4,9 - 19,6%)'  END)
			WHEN 65 THEN CONCAT(@Resultado,+ ' ' + CASE WHEN @Resultado = 0 THEN 'Bajo riesgo (1.9%)' WHEN @Resultado = 1 THEN 'Bajo riesgo (2.5%)' WHEN @Resultado = 2 THEN 'Riesgo intermedio (5.3%)' WHEN @Resultado = 3 THEN 'Riesgo intermedio (8.4%)' WHEN @Resultado = 4 THEN 'Alto riesgo (10.4%)' WHEN @Resultado >= 5 THEN 'Alto riesgo (12.3%)' END)
			WHEN 66 THEN CONCAT( @ResultadoDecimal, + '% ' + 'Predicted Mortality By EuroSCOPEII')
			WHEN 67 THEN CASE @Resultado WHEN  1 THEN 'Clase I - Pacientes sin limitación de actividades; No sufren síntomas de las actividades ordinarias' WHEN  2 THEN 'Clase II - Pacientes con ligera y leve limitación de actividad; Se sienten cómodos con el descanso o con un esfuerzo leve' WHEN 3 THEN 'Clase III - Pacientes con marcada limitación de actividad; Sólo se sienten cómodos en reposo' Else 'Clase IV - Pacientes que deben estar en reposo completo, confinados a la cama o la silla; Cualquier actividad física provoca molestias y los síntomas ocurren en reposo' END
			WHEN 68 THEN CASE @Resultado WHEN  1 THEN '0 - 5%'+' \ '+'Mortalidad' WHEN  2 THEN '10 - 20%'+' \ '+'Mortalidad' WHEN 3 THEN '35 - 45%'+' \ '+' Mortalidad' Else '85 - 95%'+' \ '+' Mortalidad' END
			WHEN 69 THEN CONCAT(@Resultado, + ' ' +CASE WHEN @Resultado < 4  THEN 'Bajo riesgo' WHEN @Resultado >= 4 THEN 'Alto riesgo' END)
			WHEN 70 THEN CONCAT(@Resultado, + ' ' +CASE WHEN @Resultado = 0  THEN 'Riesgo mínimo' WHEN @Resultado in (1,2) THEN 'Bajo riesgo' WHEN @Resultado in (3,4) THEN 'Riesgo moderado (0,7%)' WHEN @Resultado in (5,6) THEN 'Riesgo alto (1,8%)' WHEN @Resultado in (7,8) THEN 'Riesgo alto (4%)' Else 'Riesgo muy alto (10,7%)' END)
			WHEN 71 THEN CASE WHEN @Resultado = 0 THEN CONVERT(varchar, @Resultado) +'-'+ 'Riesgo bajo (Asistencia clínica rutinaria)' WHEN @Resultado = 1 THEN CONVERT(varchar, @Resultado) +'-'+ 'Riesgo moderado (Monitorización por 3 días)' WHEN @Resultado >= 2 THEN CONVERT(varchar, @Resultado) +'-'+ 'Riesgo alto (Inicie tratamiento)' END
			WHEN 72 THEN CASE WHEN @Resultado = 0 THEN CONVERT(varchar, @Resultado) +'-'+ 'Riesgo bajo' WHEN @Resultado Between 1 And 3 THEN CONVERT(varchar, @Resultado) +'-'+ 'Riesgo moderado' WHEN @Resultado = 4 Or @Resultado = 5 THEN CONVERT(varchar, @Resultado) +'-'+ 'Riesgo alto' END
			WHEN 73 THEN CASE WHEN @Resultado Between 0 And 3 THEN CONVERT(varchar, @Resultado) +'-'+ 'Bien nutrido' WHEN @Resultado Between 4 And 9 THEN CONVERT(varchar, @Resultado) +'-'+ 'Moderadamente malnutrido' WHEN @Resultado > 9 THEN CONVERT(varchar, @Resultado) +'-'+ 'Severamente malnutrido' END 
			WHEN 74 THEN CASE WHEN @Resultado = 0 THEN CONVERT(varchar, @Resultado) + ' - ' +  '0,8% ' + 'Riesgo de mortalidad a 30 dias' WHEN @Resultado = 1 THEN CONVERT(varchar, @Resultado) + ' - ' +  '1,6% ' + 'Riesgo de mortalidad a 30 dias' WHEN @Resultado = 2 THEN CONVERT(varchar, @Resultado) + ' - ' +  '2,2% ' + 'Riesgo de mortalidad a 30 dias' WHEN @Resultado = 3 THEN CONVERT(varchar, @Resultado) + ' - ' +  '4,4% ' + 'Riesgo de mortalidad a 30 dias' WHEN @Resultado = 4 THEN CONVERT(varchar, @Resultado) + ' - ' +  '7,3% ' + 'Riesgo de mortalidad a 30 dias' WHEN @Resultado = 5 THEN CONVERT(varchar, @Resultado) + ' - ' +  '12% ' + 'Riesgo de mortalidad a 30 dias' WHEN @Resultado = 6 THEN CONVERT(varchar, @Resultado) + ' - ' +  '16% ' + 'Riesgo de mortalidad a 30 dias' WHEN @Resultado = 7 THEN CONVERT(varchar, @Resultado) + ' - ' +  '23% ' + 'Riesgo de mortalidad a 30 dias' WHEN @Resultado = 8 THEN CONVERT(varchar, @Resultado) + ' - ' +  '27% ' + 'Riesgo de mortalidad a 30 dias' WHEN @Resultado Between 9 And 14 THEN CONVERT(varchar, @Resultado) + ' - ' +  '36% ' + 'Riesgo de mortalidad a 30 dias' END
			WHEN 75 THEN CASE WHEN @Resultado <= 0 THEN CONVERT(varchar, @Resultado) + ' - ' + 'Riesgo bajo' WHEN @Resultado = 1 Or @Resultado = 2 THEN CONVERT(varchar, @Resultado) + ' - ' + 'Riesgo intermedio' WHEN @Resultado >= 3 THEN CONVERT(varchar, @Resultado) + ' - ' + 'Riesgo alto' END
			WHEN 76 THEN CASE WHEN @ResultadoDecimal < 2 THEN CONVERT(varchar, @ResultadoDecimal) + ' - ' + 'Riesgo bajo' WHEN @ResultadoDecimal Between 2 And 6 THEN CONVERT(varchar, @ResultadoDecimal) + ' - ' + 'Riesgo intermedio' WHEN @ResultadoDecimal > 6 THEN CONVERT(varchar, @ResultadoDecimal) + ' - ' + 'Riesgo alto' END
			WHEN 77 THEN CASE WHEN @Resultado <= 5 THEN CONVERT(varchar, @Resultado) + ' - ' + '7.5% Riesgo de incremento de creatinina y/o 0.04% Riesgo de diálisis.' WHEN @Resultado Between 6 And 10 THEN CONVERT(varchar, @Resultado) + ' - ' + '14% Riesgo de incremento de creatinina y/o 0.12% Riesgo de diálisis.' WHEN @Resultado Between 11 And 15 THEN CONVERT(varchar, @Resultado) + ' - ' + '26.1% Riesgo de incremento de creatinina y/o 1.09% Riesgo de diálisis.' WHEN @Resultado >= 16 THEN CONVERT(varchar, @Resultado) + ' - ' +  '57.3% Riesgo de incremento de creatinina y/o 12.6% Riesgo de diálisis.' END
			WHEN 78 THEN CASE WHEN @Resultado <= 87 THEN CONVERT(varchar, @Resultado) + '. - ' + '(0.2%) Riesgo de mortalidad a 6 meses.' WHEN @Resultado Between 88 And 128 THEN CONVERT(varchar, @Resultado) + '. - ' + '(3-10%) Riesgo de mortalidad a 6 meses.' WHEN @Resultado Between 129 And 149 THEN CONVERT(varchar, @Resultado) + '. - ' + '(10-20%) Riesgo de mortalidad a 6 meses.' WHEN @Resultado Between 150 And 173 THEN CONVERT(varchar, @Resultado) + '. - ' + '(20-30%) Riesgo de mortalidad a 6 meses.' WHEN @Resultado Between 174 And 182 THEN CONVERT(varchar, @Resultado) + '. - ' + '(40%) Riesgo de mortalidad a 6 meses.' WHEN @Resultado Between 183 And 190 THEN CONVERT(varchar, @Resultado) + '. - ' + '(50%) Riesgo de mortalidad a 6 meses.' WHEN @Resultado Between 191 And 199 THEN CONVERT(varchar, @Resultado) + '. - ' + '(60%) Riesgo de mortalidad a 6 meses.' WHEN @Resultado Between 200 And 207 THEN CONVERT(varchar, @Resultado) + '. - ' + '(70%) Riesgo de mortalidad a 6 meses.' WHEN @Resultado Between 208 And 218 THEN CONVERT(varchar, @Resultado) + '. - ' + '(80%) Riesgo de mortalidad a 6 meses.' WHEN @Resultado Between 219 And 284 THEN CONVERT(varchar, @Resultado) + '. - ' + '(90%) Riesgo de mortalidad a 6 meses.' WHEN @Resultado >= 285 THEN CONVERT(varchar, @Resultado) + '. - ' + '(99%) Riesgo de mortalidad a 6 meses.' END
			WHEN 79 THEN CASE WHEN @Resultado = 0 Or @Resultado = 1 THEN CONVERT(varchar, @Resultado) + '. - ' + '(5%) Riesgo a los 14 días de mortalidad por todas las causas, IM nuevo o recurrente, isquemia recurrente severa que requiere revascularización urgente.' WHEN @Resultado = 2 THEN CONVERT(varchar, @Resultado) + '. - ' + '(8%) Riesgo a los 14 días de mortalidad por todas las causas, IM nuevo o recurrente, isquemia recurrente severa que requiere revascularización urgente.' WHEN @Resultado = 3 THEN CONVERT(varchar, @Resultado) + '. - ' + '(13%) Riesgo a los 14 días de mortalidad por todas las causas, IM nuevo o recurrente, isquemia recurrente severa que requiere revascularización urgente.' WHEN @Resultado = 4 THEN CONVERT(varchar, @Resultado) + '. - ' + '(20%) Riesgo a los 14 días de mortalidad por todas las causas, IM nuevo o recurrente, isquemia recurrente severa que requiere revascularización urgente.' WHEN @Resultado = 5 THEN CONVERT(varchar, @Resultado) + '. - ' + '(26%) Riesgo a los 14 días de mortalidad por todas las causas, IM nuevo o recurrente, isquemia recurrente severa que requiere revascularización urgente.' WHEN @Resultado = 6 Or @Resultado = 7 THEN CONVERT(varchar, @Resultado) + '. - ' + '(41%) Riesgo a los 14 días de mortalidad por todas las causas, IM nuevo o recurrente, isquemia recurrente severa que requiere revascularización urgente.' END
			WHEN 80 THEN CASE WHEN @Resultado in(0) THEN CONVERT(varchar, @Resultado) +'-'+ 'Sin riesgo.' WHEN @Resultado = 1 THEN CONVERT(varchar, @Resultado) +'-'+ 'Tipo I: Leve - No requiere antibiótico, manejo ambulatorio' WHEN @Resultado = 2 THEN CONVERT(varchar, @Resultado) +'-'+ 'Tipo II: Moderado - Verifique la necesidad de antibiótico y el ingreso a urgencias' WHEN @Resultado = 3 THEN CONVERT(varchar, @Resultado) +'-'+ 'Tipo III: Severa - Hospitalizar e iniciar antibiótico' END
			WHEN 81 THEN CASE WHEN @ResultadoDecimal < 2.6 THEN CONVERT(varchar, @ResultadoDecimal) +'-'+ 'Remisión de la enfermedad' WHEN @ResultadoDecimal >= 2.6 AND @ResultadoDecimal <= 3.2 THEN CONVERT(varchar, @ResultadoDecimal) +'-'+ 'Actividad de la enfermedad BAJA' WHEN @ResultadoDecimal > 3.2 AND @ResultadoDecimal < 5.1 THEN CONVERT(varchar, @ResultadoDecimal) +'-'+ 'Actividad de la enfermedad MODERADA' WHEN @ResultadoDecimal >= 5.1 THEN CONVERT(varchar, @ResultadoDecimal) +'-'+ 'Actividad de la enfermedad ALTA' END
			WHEN 82 THEN CASE WHEN @Resultado = 0 THEN CONVERT(varchar, @Resultado) +'-'+ 'Asintomático' WHEN @Resultado = 1 THEN CONVERT(varchar, @Resultado) +'-'+ 'Sin discapacidad significativa' WHEN @Resultado = 2 THEN CONVERT(varchar, @Resultado) +'-'+ 'Discapacidad leve' WHEN @Resultado = 3 THEN CONVERT(varchar, @Resultado) +'-'+ 'Discapacidad moderada' WHEN @Resultado = 4 THEN CONVERT(varchar, @Resultado) +'-'+ 'Discapacidad moderadamente grave' WHEN @Resultado = 5 THEN CONVERT(varchar, @Resultado) +'-'+ 'Discapacidad grave' WHEN @Resultado = 6 THEN CONVERT(varchar, @Resultado) +'-'+ 'Muerte' END
			WHEN 83 THEN CASE WHEN @ResultadoDecimal = 0 THEN CONVERT(varchar, @ResultadoDecimal) +'-'+ 'Sin dificultad'  WHEN @ResultadoDecimal >= 0.1 AND @ResultadoDecimal <= 0.9 THEN CONVERT(varchar, @ResultadoDecimal) +'-'+ 'Leve dificultad' WHEN @ResultadoDecimal >= 1.0 AND @ResultadoDecimal <= 1.9 THEN CONVERT(varchar, @ResultadoDecimal) +'-'+ 'Moderada dificultad' WHEN @ResultadoDecimal >= 2.0 AND @ResultadoDecimal <= 2.9 THEN CONVERT(varchar, @ResultadoDecimal) +'-'+ 'Severa dificultad' WHEN @ResultadoDecimal = 3.0 THEN CONVERT(varchar, @ResultadoDecimal) +'-'+ 'Muy severa dificultad' END
			WHEN 84 THEN CASE WHEN @Resultado <8 THEN CONVERT(varchar, @Resultado) +'-'+ 'Mayor riesgo de sangrado con terapia trombolítica. Peor pronóstico funcional' WHEN @Resultado =8 Or @Resultado =9 THEN CONVERT(varchar, @Resultado) +'-'+ '40% de los pacientes tendrán mRS 0-1 a los 90 días' WHEN @Resultado =10 THEN CONVERT(varchar, @Resultado) +'-'+ 'Tomografía computarizada normal' END
			WHEN 85 THEN CASE WHEN @Resultado = 1 THEN 'Desarrollo esperado' WHEN @Resultado = 2 THEN 'Sospecha de problema del desarrollo' WHEN @Resultado = 3 THEN 'Riesgo de problema del desarrollo' END
			WHEN 86 THEN CASE WHEN @Resultado <13 THEN CONVERT(varchar, @Resultado) +' % -'+ 'Aceptable' WHEN @Resultado > 12 AND @Resultado <24 THEN CONVERT(varchar, @Resultado) +' % -'+ 'Cuestionable' WHEN @Resultado > 23 THEN CONVERT(varchar, @Resultado) +' % -'+ 'Deficiente' END
			WHEN 87 THEN CASE WHEN @Resultado =0 THEN CONVERT(varchar, @Resultado) +'-'+ 'Normal' WHEN @Resultado >0 AND @Resultado <4 THEN CONVERT(varchar, @Resultado) +'-'+ 'Déficit leve' WHEN @Resultado >3 AND @Resultado <17 THEN CONVERT(varchar, @Resultado) +'-'+ 'Déficit moderada - Se recomienda la terapia de trombólisis' WHEN @Resultado >16 AND @Resultado <26 THEN CONVERT(varchar, @Resultado) +'-'+ 'Déficit grave  - Se recomienda la terapia de trombólisis' WHEN @Resultado >25 THEN CONVERT(varchar, @Resultado) +'-'+ 'Déficit muy grave' END
			WHEN 88 THEN CASE WHEN @Resultado > 11 THEN CONVERT(varchar, @Resultado) +' - '+ 'Riesgo alto de caídas' WHEN @Resultado < 12 THEN CONVERT(varchar, @Resultado) +' - '+ 'Riesgo bajo de caídas' END 
			WHEN 89 THEN CASE WHEN @Resultado = 0 THEN CONVERT(varchar, @Resultado) +' - '+ 'Sin riesgo de enfermedad potencialmente transmisible.' WHEN @Resultado = 1 THEN CONVERT(varchar, @Resultado) +' - '+ 'Prueba negativa: Manejar con medidas estándar si se descartan procesos infecciosos.' WHEN @Resultado > 1 THEN CONVERT(varchar, @Resultado) +' - '+ 'Prueba positiva: Coloque al paciente en un consultorio cerrado, indique al médico la priorización de la atención y entregue tapabocas al paciente.'END
			WHEN 90 THEN CASE WHEN @Resultado Between 0 And 6 THEN CONVERT(varchar, @Resultado) + '. - ' + 'Dolor leve' WHEN @Resultado Between 7 And 11 THEN CONVERT(varchar, @Resultado) + '. - ' + 'Dolor moderado' WHEN @Resultado >= 12 THEN CONVERT(varchar, @Resultado) + '. - ' + 'Dolor intenso' END
			WHEN 91 THEN CASE WHEN @Resultado = 0 THEN CONVERT(varchar, @Resultado) + '. - ' + 'Relajado y confortable' WHEN @Resultado Between 1 And 3 THEN CONVERT(varchar, @Resultado) + '. - ' + 'Disconfort leve' WHEN @Resultado Between 4 And 6 THEN CONVERT(varchar, @Resultado) + '. - ' + 'Disconfort moderado' WHEN @Resultado Between 7 And 10 THEN CONVERT(varchar, @Resultado) + '. - ' + 'Disconfort severo, dolor o ambos' END
			WHEN 92 THEN CASE WHEN @Resultado >= 0 or @Resultado<=2 THEN  Concat(@Resultado,'-Riesgo de caídas bajo') WHEN @Resultado = 3 or @Resultado=4 THEN  Concat(@Resultado,'-Riesgo de caídas moderado') WHEN @Resultado >= 5  THEN Concat(@Resultado,'-Riesgo de caídas alto') END
			WHEN 93 THEN CASE WHEN @Resultado = 0 THEN  Concat(@Resultado,'-Sin dolor') WHEN @Resultado = 2 THEN  Concat(@Resultado,'-Dolor leve') WHEN @Resultado = 4  THEN Concat(@Resultado,'-Dolor moderado') WHEN @Resultado = 6  THEN Concat(@Resultado,'-Dolor intenso') WHEN @Resultado = 8  THEN Concat(@Resultado,'-Dolor muy intenso') WHEN @Resultado = 10  THEN Concat(@Resultado,'-Muchísimo dolor') END
			WHEN 94 THEN CASE WHEN @Resultado = 0 THEN  Concat(@Resultado,'- Sin dolor') WHEN @Resultado BETWEEN 1 AND 3 then  Concat(@Resultado,' - Dolor suave')WHEN @Resultado BETWEEN 4 AND 6 then Concat(@Resultado,'- Dolor moderado') WHEN @Resultado BETWEEN 7 AND 10 then Concat(@Resultado,'- Dolor intenso') END
			WHEN 95 THEN CASE WHEN @Resultado Between 0 And 7 Then CONVERT(varchar, @Resultado) + '. - ' + 'Situación social buena (bajo riesgo social)' WHEN @Resultado Between 8 And 9 Then CONVERT(varchar, @Resultado) + '. - ' + 'Riesgo social intermedio' WHEN @Resultado Between 10 And 15 Then CONVERT(varchar, @Resultado) + '. - ' + 'Deterioro social severo (alto riesgo social)' END
			WHEN 96 THEN CASE WHEN @Resultado BETWEEN 0 AND 1 then CONCAT(@Resultado, ' - Ausencia de delírium.') WHEN @Resultado BETWEEN 2 AND 4 then CONCAT(@Resultado, ' - Sospecha de síndrome confusional (delírium).') END
			WHEN 97 THEN CASE WHEN @Resultado BETWEEN 0 AND 1 then  Concat(@Resultado,' - Bajo riesgo de infección') WHEN @Resultado BETWEEN 2 AND 4 then Concat(@Resultado,' - Alto riesgo de infección') END
			WHEN 98 THEN CASE WHEN @Resultado Between 0 And 1 then  Concat(@Resultado,' - Bajo riesgo farmacológico') WHEN @Resultado Between 2 And 3 Then Concat(@Resultado,' - Alto riesgo farmacológico') END
			WHEN 99 THEN CASE WHEN CAST(@Resultado AS INT) = 0 THEN  Concat(@Resultado,' - Bajo riesgo psicosocial') WHEN CAST(@Resultado AS INT) IN (1, 2) THEN  Concat(@Resultado,' - Alto riesgo psicosocial') END
			WHEN 100 THEN CASE WHEN @Resultado Between 0 And 9 Then CONVERT(varchar, @Resultado) + '. - ' + 'Riesgo social bajo (normal)' WHEN @Resultado Between 10 And 16 Then CONVERT(varchar, @Resultado) + '. - ' + 'Riesgo social intermedio' WHEN @Resultado Between 17 And 25 Then CONVERT(varchar, @Resultado) + '. - ' + 'Riesgo social elevado (problema social)' END
			WHEN 101 THEN CASE WHEN @Resultado = '0'  then  Concat(@Resultado,' - Observación de rutina')  WHEN @Resultado BETWEEN 1 And 3 then Concat(@Resultado,' - Observación: mínimo cada 4 horas') WHEN @Resultado BETWEEN 4 And 5 then Concat(@Resultado,' - Observación: mínimo cada  hora') WHEN @Resultado >= 6 then Concat(@Resultado,' - monitoreo contínuo de signos vitales') END
			WHEN 102 THEN CASE WHEN @Resultado Between 0 And 1 THEN CONCAT(@Resultado,' -',' Bajo riesgo')  WHEN @Resultado Between 2 And 4 THEN CONCAT(@Resultado,' -',' Riesgo intermedio- Requiere apoyo respiratorio o circulatorio') WHEN @Resultado Between 5 And 7 THEN CONCAT(@Resultado,' -',' Riesgo alto - requiere una combinación de apoyo respiratorio y circulatorio') WHEN @Resultado > 7 THEN CONCAT(@Resultado,' -',' Riesgo alto Indica reanimación cardiopulmonar o muerte') END
			WHEN 103 THEN CASE WHEN @Resultado Between 0 And 1 THEN CONCAT(@Resultado,' -',' Bajo riesgo')  WHEN @Resultado Between 2 And 4 THEN CONCAT(@Resultado,' -',' Riesgo intermedio - requiere apoyo respiratorio o circulatorio') WHEN @Resultado Between 5 And 7 THEN CONCAT(@Resultado,' -',' Riesgo alto - requiere una combinación de apoyo respiratorio y circulatorio') WHEN @Resultado > 7 THEN CONCAT(@Resultado,' -',' Riesgo alto - indica reanimación cardiopulmonar o muerte') END
			WHEN 104 THEN CASE WHEN @Resultado Between 0 And 1 THEN CONCAT(@Resultado,' -',' Bajo riesgo')  WHEN @Resultado Between 2 And 4 THEN CONCAT(@Resultado,' -',' Riesgo intermedio - requiere apoyo respiratorio o circulatorio') WHEN @Resultado Between 5 And 7 THEN CONCAT(@Resultado,' -',' Riesgo alto - requiere una combinación de apoyo respiratorio y circulatorio') WHEN @Resultado > 7 THEN CONCAT(@Resultado,' -',' Riesgo alto - indica reanimación cardiopulmonar o muerte') END
			WHEN 105 THEN CONCAT(@Resultado, '- puntos') 
			WHEN 106 THEN CASE WHEN (@Resultado BETWEEN 0 AND 7) THEN CONCAT(@Resultado, ' - No síndrome de abstinencia') WHEN (@Resultado BETWEEN 8 AND 12) THEN CONCAT(@Resultado, ' - Síndrome de abstinencia leve') WHEN (@Resultado BETWEEN 13 AND 16) THEN CONCAT(@Resultado, ' - Síndrome de abstinencia moderado') WHEN @Resultado > 16 THEN CONCAT(@Resultado, ' - Síndrome de abstinencia severo') END
			WHEN 107 THEN CASE WHEN @Resultado = 0 THEN CONCAT(@Resultado, ' - Choque compensado, trasfusión usualmente no requerida') WHEN @Resultado = 1 THEN CONCAT(@Resultado, ' - Choque leve, trasfusión posible') WHEN @Resultado = 2 THEN CONCAT(@Resultado, ' - Choque moderado, trasfusión usualmente requerida') WHEN @Resultado = 3 THEN CONCAT(@Resultado, ' - Choque severo, trasfusión masiva probable') END
			WHEN 108 THEN CASE WHEN @Resultado = -1 THEN 'Sin riesgo' WHEN (@Resultado BETWEEN 0 AND 2) THEN CONCAT(@Resultado, ' - Sin sospecha de EPOC') WHEN (@Resultado BETWEEN 3 And 5) THEN CONCAT(@Resultado, ' - Sospecha de EPOC') END
			WHEN 109 THEN CASE WHEN (@Resultado BETWEEN 0 AND 2) THEN CONCAT(@Resultado, ' - Nivel bajo de ansiedad') WHEN (@Resultado BETWEEN 3 AND 6) THEN CONCAT(@Resultado, ' - Nivel alto de ansiedad') END
			WHEN 110 THEN CASE WHEN @Resultado = 1 THEN  Concat(@Resultado, ' punto ',' - riesgo bajo < 10 % - riesgo cardiovascular bajo') WHEN @Resultado = 2 THEN  Concat(@Resultado, ' puntos ',' - riesgo moderado 10 - < 20 % - riesgo cardiovascular moderado') WHEN @Resultado = 3 THEN  Concat(@Resultado, ' puntos ',' - riesgo alto 20 - < 30 % - riesgo cardiovascular alto') WHEN @Resultado = 4 THEN  Concat(@Resultado, ' puntos ',' - riesgo muy alto 30 - < 40 % - riesgo cardiovascular muy alto') WHEN @Resultado = 5 THEN  Concat(@Resultado, ' puntos ',' - riesgo extremadamente alto - >= 40 % - riesgo cardiovascular extremadamente alto') END
			WHEN 111 THEN CASE WHEN (@Resultado < 5) THEN CONCAT('IPA ',@Resultado,' - Grado tabaquismo leve') WHEN (@Resultado BETWEEN 5 And 15) THEN  CONCAT('IPA ',@Resultado,' - Grado tabaquismo moderado') WHEN (@Resultado BETWEEN 16 And 25) THEN  CONCAT('IPA ',@Resultado,' - Grado tabaquismo grave') WHEN (@Resultado > 25) THEN  CONCAT('IPA ',@Resultado,' - Grado tabaquismo muy grave') END		
			WHEN 112 THEN CASE WHEN @Resultado = 0 THEN CONCAT(@Resultado,' - No hay dificultad respiratoria') WHEN (@Resultado BETWEEN 1 AND 3) THEN CONCAT(@Resultado,' - Dificultad respiratoria leve') WHEN (@Resultado BETWEEN 4 AND 6) THEN CONCAT(@Resultado,' - Dificultad respiratoria moderada') WHEN (@Resultado BETWEEN 7 AND 10) THEN CONCAT(@Resultado,' - Dificultad respiratoria severa') END
			WHEN 113 THEN CASE WHEN @Resultado <= 2 THEN CONCAT(@Resultado,' - Bajo riesgo de caídas') WHEN @Resultado > 2 THEN  CONCAT(@Resultado,' - Alto riesgo de caídas') END
			WHEN 118 THEN CASE WHEN @Resultado = 1 THEN 'Sin riesgo de preeclampsia' WHEN @Resultado = 2 THEN 'Riesgo moderado de preeclampsia' WHEN @Resultado = 3 THEN 'Riesgo alto de preeclampsia' END
			WHEN 119 THEN CASE WHEN (@Resultado BETWEEN 0 AND 3) THEN CONCAT(@Resultado,' - Disfunción grave') WHEN (@Resultado BETWEEN 4 AND 6) THEN CONCAT(@Resultado,' - Disfunción moderada') WHEN (@Resultado BETWEEN 7 AND 10) THEN CONCAT(@Resultado,' - Funcionalidad normal') END
			WHEN 120 THEN CASE WHEN (@Resultado BETWEEN 0 AND 5) THEN CONCAT(@Resultado,' - Bajo riesgo nutricional') WHEN (@Resultado BETWEEN 6 AND 10) THEN CONCAT(@Resultado,' - Alto riesgo nutricional') END
			WHEN 121 THEN CASE WHEN (@Resultado BETWEEN 7 AND 16) THEN CONCAT(@Resultado,' - Riesgo alto') WHEN (@Resultado BETWEEN 17 AND 22) THEN CONCAT(@Resultado,' - Riesgo medio') WHEN (@Resultado >= 23) THEN CONCAT(@Resultado,' - Riesgo bajo') END
			WHEN 122 THEN CASE WHEN (@Resultado BETWEEN 0 AND 30) THEN CONCAT(@Resultado,' - Síntomas leves') WHEN (@Resultado BETWEEN 31 AND 70) THEN CONCAT(@Resultado,' - Síntomas moderados') WHEN (@Resultado >= 71) THEN CONCAT(@Resultado,' - Síntomas graves') END
			WHEN 123 THEN CASE WHEN (@Resultado BETWEEN 0 And 2) THEN Concat(@Resultado,' - No cumple criterio de UCI') WHEN (@Resultado BETWEEN 3 And 9) THEN Concat(@Resultado,' - Cumple criterio de UCI') WHEN (@Resultado BETWEEN 10 And 19) then Concat((@Resultado - 9),' - Cumple criterio de UCI') WHEN (@Resultado >= 20) then Concat((@Resultado - 18),' - Cumple criterio de UCI') END
			WHEN 124 THEN CASE WHEN (@Resultado BETWEEN 0 AND 5) THEN CONCAT(@Resultado,' - Sin riesgo significativo') WHEN (@Resultado >= 6) THEN CONCAT(@Resultado,' - Riesgo suicida positivo (requiere intervención)') END
			END

    RETURN @InterpretacionEscala

END
GO
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Función que traduce el puntaje numérico de una escala clínica aplicada en historia clínica al texto interpretativo correspondiente según el tipo de escala. Recibe el código de la escala, el resultado numérico, un valor decimal, el sexo del paciente y el identificador del registro de escala (IDHCESCALAS), y devuelve una cadena con el puntaje y su categoría diagnóstica en lenguaje clínico. Cubre más de 30 escalas de valoración como Glasgow (nivel de consciencia), Braden (riesgo de úlceras por presión), AUDIT (consumo de alcohol), APGAR familiar (función familiar), PHQ (depresión), Barthel (dependencia funcional), Zarit (sobrecarga del cuidador), FINDRISC (riesgo de diabetes), EPOC, NYHA, Child-Pugh, entre otras. Se apoya en las tablas HCESCALADSQR y HCESCALASRESULTITEMS para obtener los puntajes parciales y respuestas por ítem, y en ESCALAGLASGOW para los componentes de apertura ocular, respuesta verbal y motora. Es la función central para mostrar al profesional de salud la interpretación clínica del resultado de cualquier escala de valoración aplicada al paciente.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'FUNCTION', @level1name = N'InterpretacionEscala';
GO
EXECUTE sp_addextendedproperty @name = N'MS_DescriptionSource', @value = N'backport_from_v25.47c_2026-05-05', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'FUNCTION', @level1name = N'InterpretacionEscala';
GO
GO
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_Purpose', @value=N'Devuelve el texto interpretativo (puntaje + categoría clínica) correspondiente a una escala de valoración aplicada en historia clínica, según el código de escala, el resultado obtenido y el sexo del paciente.', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'FUNCTION', @level1name=N'InterpretacionEscala';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_Preconditions', @value=N'El código de escala debe corresponder a uno de los valores soportados (1-113, 118-124); de lo contrario el resultado será NULL; Para escalas 29, 30 y 31 debe existir un registro en dbo.ESCALAGLASGOW con el IDHCESCALAS indicado; Para escala 51 debe existir un registro en dbo.HCESCALADSQR con el IDHCESCALAS indicado; Para escala 60 deben existir filas en dbo.HCESCALASRESULTITEMS asociadas al IDHCESCALAS; Para escalas que evalúan @Resultado numéricamente, el valor recibido como varchar debe ser convertible a número (la escala 99 hace CAST explícito a INT); Para escala 62 el parámetro Sexo determina la tabla de clasificación (1 = masculino, otro valor = femenino); Para escalas 66, 76, 81 y 83 debe suministrarse un ResultadoDecimal válido', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'FUNCTION', @level1name=N'InterpretacionEscala';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_Invariants', @value=N'La interpretación textual siempre se determina por el código de escala recibido; no existe rama por defecto, por lo que un código no contemplado produce NULL; Para la mayoría de escalas el texto retornado contiene el puntaje numérico concatenado con su interpretación clínica; Las escalas 29, 30 y 31 (Glasgow) requieren existencia de un registro en ESCALAGLASGOW con el mismo IDHCESCALAS; si no existe la consulta retorna NULL; La escala 51 depende exclusivamente de dbo.HCESCALADSQR para los cuatro subresultados; La escala 60 depende de HCESCALASRESULTITEMS y mapea TAGPREGUNTA 001-010 a sustancias específicas; La escala 62 cambia la clasificación de riesgo según el parámetro Sexo (1 = una tabla, otro valor = tabla alternativa); Las escalas 66, 76, 81 y 83 utilizan ResultadoDecimal en lugar de Resultado, ignorando el valor entero; La función no modifica datos: es de solo lectura', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'FUNCTION', @level1name=N'InterpretacionEscala';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_DomainConcepts', @value=N'Escalas clínicas; AUDIT (consumo de alcohol); APGAR familiar; Riesgo de depresión; Violencia doméstica; Adherencia al tratamiento; Diabetes mellitus tipo II; Deterioro cognitivo (MMSE); Dependencia tabáquica (Fagerström); Estadios de enfermedad renal/hepática; Úlcera de pie diabético (Wagner); EPOC (CAT, exacerbaciones, GOLD A-D); Coeficiente intelectual; APACHE / clasificación UCI; Karnofsky / ECOG; Glasgow (adulto, pediátrico, lactante); Escala de Barthel; Riesgo de caídas; Riesgo de desnutrición (MNA); Depresión geriátrica (Yesavage); Sobrecarga del cuidador (Zarit); Higiene oral; RASS (sedación-agitación); DSQR / tamizaje de salud mental; ASSIST (sustancias psicoactivas); EuroSCORE II; NYHA; Killip; TIMI; DAS28 (artritis reumatoide) (+9 adicionales)', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'FUNCTION', @level1name=N'InterpretacionEscala';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_Decisions', @value=N'si CodigoEscala = 1 (AUDIT consumo de alcohol) → Clasifica de ''Bebedor social'' (0-1) a ''Dependencia alcohólica'' (4) según puntaje; si CodigoEscala = 2 (APGAR familiar) → Clasifica función familiar: buena (18-20), disfunción leve (14-17), moderada (10-13) o severa (resto); si CodigoEscala = 3 (Riesgo depresión) → Sin riesgo (0-9), en riesgo (10-12), sospecha de depresión (>12); si CodigoEscala IN (29,30,31) → Construye interpretación de Glasgow (adulto/niño/lactante) leyendo APERTURAOCULAR, RESPUESTAVERVAL y RESPUESTAMOTORA desde ESCALAGLASGOW filtrando por IDHCESCALAS; si CodigoEscala = 51 (DSQR) → Lee RESULTADO1..RESULTADO4 desde dbo.HCESCALADSQR para interpretar trastornos depresivo/ansioso, psicótico, convulsivo y consumo de alcohol; si CodigoEscala = 60 (ASSIST sustancias) → Concatena resultados por sustancia (tabaco, alcohol, cannabis, cocaína, anfetaminas, inhalantes, sedantes, alucinógenos, opiáceos, otras) desde HCESCALASRESULTITEMS; si CodigoEscala = 62 (Riesgo cardiovascular por sexo) → Si Sexo=1 aplica tabla masculina; en otro caso aplica tabla femenina con distintos umbrales; si CodigoEscala IN (66,76,81,83) → Usa ResultadoDecimal en lugar de Resultado entero para clasificar (EuroSCORE II, riesgo, DAS28, dificultad); si CodigoEscala IN (22,48,49) → Devuelve el Resultado tal cual sin transformación (escalas Abreviada Desarrollo, Norton, Vass); si CodigoEscala = 123 → Para puntajes 10-19 resta 9 y para >=20 resta 18 antes de mostrar, conservando el criterio ''Cumple criterio de UCI''; si CodigoEscala no coincide con ningún WHEN → Retorna NULL (no hay rama ELSE en el CASE principal)', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'FUNCTION', @level1name=N'InterpretacionEscala';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_Consumes', @value=N'dbo.ESCALAGLASGOW; dbo.HCESCALADSQR; dbo.HCESCALASRESULTITEMS', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'FUNCTION', @level1name=N'InterpretacionEscala';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_BR_Source', @value=N'ai_claude-opus-4-7_tier-c_2026-05-06', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'FUNCTION', @level1name=N'InterpretacionEscala';
GO
