-- =============================================
-- Author:		<Author,Juan David Patiño Cabrea,Name>
-- Create date: <Create Date,08-05-2018,>
-- Description:	<Description,Sp que me lista la Información de las Fichas del Sivigila>
-- =============================================
CREATE PROCEDURE [dbo].[SP_HC_ListarFichaSivigila100]
(
  @IdFicha as Int,
  @NumFicha as Int
)

AS
BEGIN
  SET NOCOUNT ON;

  	Select 
		convert(varchar(10),FECHACCIDENTE,103) As 'Fecha Accidente',Rtrim(DIRACCIDENTE) As 'Direccion Accidente',
		CASE ACTIVIDADACCI  WHEN '1' THEN 'X' END AS 'Recreacion',CASE ACTIVIDADACCI   WHEN '2' THEN 'X' END AS 'Actividad agricola',CASE ACTIVIDADACCI   WHEN '3' THEN 'X' END AS 'Oficios domesticos',CASE ACTIVIDADACCI   WHEN '4' THEN 'X' END AS 'Recoleccion desechos',CASE ACTIVIDADACCI   WHEN '5' THEN 'X' END AS 'Actividad acuatica',CASE ACTIVIDADACCI   WHEN '6' THEN 'X' END AS 'Caminar',CASE ACTIVIDADACCI   WHEN '7' THEN 'X' END AS 'Otr Actividad', Rtrim(OTRACTIVIDAD) As 'Otra Actividad',
		CASE TIPOATENCION   WHEN '1' THEN 'X' END AS 'Incision',CASE TIPOATENCION   WHEN '2' THEN 'X' END AS 'Puncion',CASE TIPOATENCION   WHEN '3' THEN 'X' END AS 'Sangria',CASE TIPOATENCION   WHEN '4' THEN 'X' END AS 'Torniquete',CASE TIPOATENCION   WHEN '5' THEN 'X' END AS 'Inmovilización enfermo', CASE TIPOATENCION   WHEN '6' THEN 'X' END AS 'Inmovilización miembro', CASE TIPOATENCION   WHEN '7' THEN 'X' END AS 'Succion mecanica', CASE TIPOATENCION WHEN '8' THEN 'X' END AS 'Otr Atencion', Rtrim(OTRATENCION) As 'Otra Atencion',
	  	CASE SOMETIDAPRAC   WHEN '1' THEN 'X' END AS 'Pocimas',CASE SOMETIDAPRAC   WHEN '2' THEN 'X' END AS 'Rezos',CASE SOMETIDAPRAC   WHEN '3' THEN 'X' END AS 'Emplastos hierbas',CASE SOMETIDAPRAC   WHEN '4' THEN 'X' END AS 'Succion bucal',CASE SOMETIDAPRAC   WHEN '5' THEN 'X' END AS 'Ninguno', CASE SOMETIDAPRAC   WHEN '6' THEN 'X' END AS 'Otr Practica', Rtrim(OTRAPRACTICA) As 'Otra Practica',
		CASE LOCAMORDEDURA  WHEN '1' THEN 'X' END AS 'Cabeza',CASE LOCAMORDEDURA   WHEN '2' THEN 'X' END AS 'Miembros superiores',CASE LOCAMORDEDURA   WHEN '3' THEN 'X' END AS 'Miembros inferiores',CASE LOCAMORDEDURA   WHEN '4' THEN 'X' END AS 'Torax anterior',CASE LOCAMORDEDURA   WHEN '5' THEN 'X' END AS 'Abdomen', CASE LOCAMORDEDURA   WHEN '6' THEN 'X' END AS 'Espalda', CASE LOCAMORDEDURA   WHEN '7' THEN 'X' END AS 'Cuello', CASE LOCAMORDEDURA   WHEN '8' THEN 'X' END AS 'Genitales', CASE LOCAMORDEDURA   WHEN '9' THEN 'X' END AS 'Gluteos', CASE LOCAMORDEDURA   WHEN '10' THEN 'X' END AS 'Dedos pie', CASE LOCAMORDEDURA  WHEN '11' THEN 'X' END AS 'Dedos mano', 
		CASE HUELLACOLMILLO WHEN '1' THEN 'X' END AS 'Huella Si',CASE HUELLACOLMILLO WHEN '0' THEN 'X' END AS 'Huella No', CASE VIOSERPIENTE  WHEN '1' THEN 'X' END AS 'Serpiente Si',CASE VIOSERPIENTE WHEN '0' THEN 'X' END AS 'Serpiente No', CASE SERPCAPTURADA WHEN '1' THEN 'X' END AS 'Serpiente Capturada Si',CASE SERPCAPTURADA WHEN '0' THEN 'X' END AS 'Serpiente Capturada No',
		CASE AGENGENERO     WHEN '1' THEN 'X' END AS 'Bothrops',CASE AGENGENERO   WHEN '2' THEN 'X' END AS 'Crotalus',CASE AGENGENERO   WHEN '3' THEN 'X' END AS 'Micrurus',CASE AGENGENERO   WHEN '4' THEN 'X' END AS 'Lachesis',CASE AGENGENERO   WHEN '5' THEN 'X' END AS 'Pelamis', CASE AGENGENERO   WHEN '6' THEN 'X' END AS 'Colubrido', CASE AGENGENERO   WHEN '7' THEN 'X' END AS 'Sin identificar', CASE AGENGENERO  WHEN '8' THEN 'X' END AS 'Otr Agente genero',Rtrim(OTROAGENGENE) As 'Otro Agente genero',
		CASE AGENNOMBRE     WHEN '1' THEN 'X' END AS 'Mapana',CASE AGENNOMBRE   WHEN '2' THEN 'X' END AS 'Equis',CASE AGENNOMBRE   WHEN '3' THEN 'X' END AS 'Cuatro narices',CASE AGENNOMBRE   WHEN '4' THEN 'X' END AS 'Cabeza candado',CASE AGENNOMBRE   WHEN '5' THEN 'X' END AS 'Rabo chucha', CASE AGENNOMBRE   WHEN '6' THEN 'X' END AS 'Verrugosa rieca', CASE AGENNOMBRE   WHEN '7' THEN 'X' END AS 'Vibora pestaña', CASE AGENNOMBRE   WHEN '8' THEN 'X' END AS 'Rabo aji', CASE AGENNOMBRE   WHEN '9' THEN 'X' END AS 'Veintricuatro', CASE AGENNOMBRE   WHEN '10' THEN 'X' END AS 'Jergon', CASE AGENNOMBRE  WHEN '11' THEN 'X' END AS 'Jararaca',CASE AGENNOMBRE  WHEN '12' THEN 'X' END AS 'Cascabel',CASE AGENNOMBRE  WHEN '13' THEN 'X' END AS 'Coral',CASE AGENNOMBRE  WHEN '14' THEN 'X' END AS 'Boca dorada',CASE AGENNOMBRE  WHEN '15' THEN 'X' END AS 'Patoco',CASE AGENNOMBRE  WHEN '16' THEN 'X' END AS 'Desconocido',CASE AGENNOMBRE  WHEN '17' THEN 'X' END AS 'Otr Agente Nombre', Rtrim(OTROAGENNOM) As 'Otro Agente Nombre',
		CASE EDEMA when '1' THEN 'X' END AS 'EDEMA',CASE DOLOR when '1' THEN 'X' END AS 'DOLOR',CASE ERITEMA  when '1' THEN 'X' END AS 'ERITEMA',CASE FLICTENAS  when '1' THEN 'X' END AS 'FLICTENAS',CASE PARESTESIAS when '1' THEN 'X' END AS 'PARESTESIAS',CASE EQUIMOSIS when '1' THEN 'X' END AS 'EQUIMOSIS',CASE HEMATOMAS  when '1' THEN 'X' END AS 'HEMATOMAS',CASE OTRAMANILOCAL when '1' THEN 'X' END AS 'OTRAMANILOCAL',Rtrim(CUALOTRAML) As 'Otra Manifestacion Locales',
		CASE NAUSEA  when '1' THEN 'X' END AS 'NAUSEA',CASE HIPOTENSION when '1' THEN 'X' END AS 'HIPOTENSION',CASE DEBILIDADMUSCU  when '1' THEN 'X' END AS 'DEBILIDADMUSCU',CASE HEMATEMESIS  when '1' THEN 'X' END AS 'HEMATEMESIS',CASE DIFIHABLAR  when '1' THEN 'X' END AS 'DIFIHABLAR',CASE VOMITO  when '1' THEN 'X' END AS 'VOMITO',CASE DOLORABDOMI  when '1' THEN 'X' END AS 'DOLORABDOMI',CASE OLIGURIA  when '1' THEN 'X' END AS 'OLIGURIA',CASE HEMATURINA when '1' THEN 'X' END AS 'HEMATURINA',CASE DISFAGIA when '1' THEN 'X' END AS 'DISFAGIA',CASE SIALORREA  when '1' THEN 'X' END AS 'SIALORREA',CASE FASCIESNEU  when '1' THEN 'X' END AS 'FASCIESNEU',CASE CIANOSIS  when '1' THEN 'X' END AS 'CIANOSIS',CASE HEMATOQUEXIA  when '1' THEN 'X' END AS 'HEMATOQUEXIA',CASE DIARREA  when '1' THEN 'X' END AS 'DIARREA',CASE ALTERAVISION  when '1' THEN 'X' END AS 'ALTERAVISION',CASE EPISTAXIS when '1' THEN 'X' END AS 'EPISTAXIS',CASE VERTIGO when '1' THEN 'X' END AS 'VERTIGO',CASE BRADICARDIA when '1' THEN 'X' END AS 'BRADICARDIA',CASE ALTERASENSO when '1' THEN 'X' END AS 'ALTERASENSO',CASE GINGIVORRAGIA when '1' THEN 'X' END AS 'GINGIVORRAGIA',CASE PTOSISPALPEBRAL when '1' THEN 'X' END AS 'PTOSISPALPEBRAL',CASE OTRAMANISISTE  when '1' THEN 'X' END AS 'OTRAMANISISTE',Rtrim(CUALOTRAMS) As 'Otra Manifestacion sistematica',
		CASE CELULITIS  when '1' THEN 'X' END AS 'CELULITIS',CASE ABSCESO  when '1' THEN 'X' END AS 'ABSCESO',CASE NECROSIS when '1' THEN 'X' END AS 'NECROSIS',CASE MIONECROSIS  when '1' THEN 'X' END AS 'MIONECROSIS',CASE FASCEITIS  when '1' THEN 'X' END AS 'FASCEITIS',CASE ALTERACIRCU  when '1' THEN 'X' END AS 'ALTERACIRCU',CASE SINDROMECOM  when '1' THEN 'X' END AS 'SINDROMECOM ',CASE OTRACOMLILOCA  when '1' THEN 'X' END AS 'OTRACOMLILOCA', Rtrim(CUALOTRACL) As 'Otra Complicacion Locales',
		CASE ANEMIAGUDA  when '1' THEN 'X' END AS 'ANEMIAGUDA',CASE EDEMACEREBRAL when '1' THEN 'X' END AS 'EDEMACEREBRAL',CASE SHOCKHIPO  when '1' THEN 'X' END AS 'SHOCKHIPO',CASE FALLAVENTILA  when '1' THEN 'X' END AS 'FALLAVENTILA',CASE SHOCKSEPTICO  when '1' THEN 'X' END AS 'SHOCKSEPTICO',CASE COMA  when '1' THEN 'X' END AS 'COMA',CASE IRA  when '1' THEN 'X' END AS 'IRA',CASE CID  when '1' THEN 'X' END AS 'CID',CASE HEMORRAGIAIN  when '1' THEN 'X' END AS 'HEMORRAGIAIN',CASE OTRACOMPSISTE  when '1' THEN 'X' END AS 'OTRACOMPSISTE',Rtrim(CUALOTRACS) As 'Otra Complicacion Sistematica',
		CASE GRACEDADACCI  when '1' THEN 'X' END AS 'Leve',CASE GRACEDADACCI  when '2' THEN 'X' END AS 'Moderado',CASE GRACEDADACCI  when '3' THEN 'X' END AS 'Grave',CASE GRACEDADACCI  when '4' THEN 'X' END AS 'No Envenenamiento',
		CASE Rtrim(EMPLEOSUERO)  when '1' THEN 'X' END AS 'Empelo Suero si',CASE Rtrim(EMPLEOSUERO)  when '0' THEN 'X' END AS 'Empelo Suero No', Rtrim(TIEMPOTRANS) As 'Tiempo Transcurrido',
		CASE Rtrim(TIPOSUERO) when '1' THEN 'X' END AS 'Antiofidico',CASE Rtrim(TIPOSUERO) when '2' THEN 'X' END AS 'Anti Coral',
		CASE Rtrim(REACCIONES) when '1' THEN 'X' END AS 'Ninguna',CASE Rtrim(REACCIONES) when '2' THEN 'X' END AS 'Localizada',CASE Rtrim(REACCIONES) when '3' THEN 'X' END AS 'Generalizada',Rtrim(DOSISUERO) As 'Dosis Suero',
		Rtrim(TIEMPOADM) As 'Tiempo Administraccion',
		CASE Rtrim(REMITIDO) when '1' THEN 'X' END AS 'Remitido Si',CASE Rtrim(REMITIDO) when '0' THEN 'X' END AS 'Remitido No',
		CASE Rtrim(TRATAMIENTOQX) when '1' THEN 'X' END AS 'Tratamientod Qx Si',CASE Rtrim(TRATAMIENTOQX) when '0' THEN 'X' END AS 'Tratamientod Qx No',
		CASE TIPOTRATAQX WHEN 1 THEN 'Drenaje de absceso' WHEN 2 THEN 'Limpieza quirúrgica' WHEN 3 THEN 'Desbridamiento'  WHEN 4 THEN 'Fasciotomía' WHEN 5 THEN 'Injerto de piel' WHEN 6 THEN 'Amputación'  END  AS 'Tipo Tratamiento',
		CASE Rtrim(FABRICANTE) when '1' THEN 'X' END AS 'Probiol',CASE Rtrim(FABRICANTE) when '2' THEN 'X' END AS 'Bioclon',CASE Rtrim(FABRICANTE) when '3' THEN 'X' END AS 'INS',CASE Rtrim(FABRICANTE) when '4' THEN 'X' END AS 'Sel Otro Fabrican',
	    Rtrim(OTROFABRICANTE) AS 'Otro Fabricante',
		Rtrim(LOTE) as 'Lote', 
		VERSION AS 'VERSION', 
		JSON AS 'JSON',
		TIEMPOTRANSDIAS As 'Tiempo Transcurrido Dias'

	From 
		HCFICHA100 
	
	Where 
		IDFICHANOTIFICACION  = @IdFicha  

	
END
GO
-- EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Procedimiento que recupera y formatea toda la información clínica y epidemiológica de la Ficha SIVIGILA 100 (notificación obligatoria de accidente ofídico o mordedura de serpiente) a partir de su identificador de ficha y número de ficha. Consulta la tabla HCFICHA100 y transforma los códigos numéricos en marcas legibles (''X'') para imprimir o exportar el formulario oficial del SIVIGILA, incluyendo: fecha y dirección del accidente, actividad que realizaba el paciente al momento del accidente, tipo de atención prehospitalaria recibida, prácticas populares o caseras aplicadas, localización anatómica de la mordedura, características del animal agresor (género taxonómico y nombre común), y el conjunto completo de signos y síntomas locales (edema, dolor, eritema, flictenas, equimosis, hematomas, etc.) y sistémicos (náuseas, hipotensión, hematemesis, debilidad muscular, entre otros). Se usa para generar el reporte impreso de la ficha epidemiológica requerida por las autoridades de salud pública (INS/SIVIGILA) ante cada caso de accidente ofídico atendido en la institución.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'SP_HC_ListarFichaSivigila100';
-- GO
-- EXECUTE sp_addextendedproperty @name = N'MS_DescriptionSource', @value = N'backport_from_v25.47c_2026-05-05', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'SP_HC_ListarFichaSivigila100';
-- GO
-- GO
-- GO
-- EXEC sys.sp_addextendedproperty @name=N'MS_BR_Purpose', @value=N'Recupera y formatea los datos clínicos y epidemiológicos de una ficha Sivigila (accidente ofídico) para visualización/impresión, traduciendo códigos numéricos a marcas ''X'' por categoría.', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'PROCEDURE', @level1name=N'SP_HC_ListarFichaSivigila100';
-- GO
-- EXEC sys.sp_addextendedproperty @name=N'MS_BR_Preconditions', @value=N'Debe existir un registro en HCFICHA100 cuyo IDFICHANOTIFICACION coincida con el identificador recibido.', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'PROCEDURE', @level1name=N'SP_HC_ListarFichaSivigila100';
-- GO
-- EXEC sys.sp_addextendedproperty @name=N'MS_BR_Invariants', @value=N'Solo se retornan fichas que coinciden exactamente con el IDFICHANOTIFICACION solicitado.; Los campos categóricos se presentan como columnas independientes con ''X'' o NULL, nunca como el código original.; La fecha del accidente se entrega siempre en formato dd/mm/yyyy (estilo 103).', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'PROCEDURE', @level1name=N'SP_HC_ListarFichaSivigila100';
-- GO
-- EXEC sys.sp_addextendedproperty @name=N'MS_BR_DomainConcepts', @value=N'Ficha de notificación Sivigila; Accidente ofídico; Agente agresor (género y especie de serpiente); Manifestaciones clínicas locales y sistémicas; Complicaciones locales y sistémicas; Gravedad del envenenamiento; Suero antiofídico/anticoral; Reacciones al suero; Tratamiento quirúrgico; Fabricante del suero; Prácticas empíricas/tradicionales; Atención prehospitalaria', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'PROCEDURE', @level1name=N'SP_HC_ListarFichaSivigila100';
-- GO
-- EXEC sys.sp_addextendedproperty @name=N'MS_BR_SideEffects', @value=N'[RETURN_RESULT] HCFICHA100: Devuelve un resultset con los campos de la ficha filtrado por IDFICHANOTIFICACION, transformando códigos en marcas ''X'' según el valor para cada categoría (actividad, atención, prácticas, localización mordedura, género/nombre del agente, manifestaciones locales y sistémicas, complicaciones, gravedad, suero, reacciones, remisión, tratamiento Qx, fabricante).', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'PROCEDURE', @level1name=N'SP_HC_ListarFichaSivigila100';
-- GO
-- EXEC sys.sp_addextendedproperty @name=N'MS_BR_Decisions', @value=N'si ACTIVIDADACCI ∈ {1..7} → Marca con ''X'' la actividad correspondiente (Recreación, Agrícola, Doméstico, Recolección desechos, Acuática, Caminar, Otra).; si TIPOATENCION ∈ {1..8} → Marca tipo de atención prehospitalaria (Incisión, Punción, Sangría, Torniquete, Inmovilización enfermo/miembro, Succión mecánica, Otra).; si SOMETIDAPRAC ∈ {1..6} → Marca práctica empírica recibida (Pócimas, Rezos, Emplastos, Succión bucal, Ninguno, Otra).; si LOCAMORDEDURA ∈ {1..11} → Marca región anatómica de la mordedura.; si HUELLACOLMILLO/VIOSERPIENTE/SERPCAPTURADA = 1 o 0 → Marca Sí/No para huella de colmillo, visualización y captura de la serpiente.; si AGENGENERO ∈ {1..8} → Marca el género del agente (Bothrops, Crotalus, Micrurus, Lachesis, Pelamis, Colúbrido, Sin identificar, Otro).; si AGENNOMBRE ∈ {1..17} → Marca el nombre común de la serpiente.; si GRACEDADACCI ∈ {1..4} → Clasifica gravedad: Leve, Moderado, Grave, No envenenamiento.; si EMPLEOSUERO = 1/0 → Marca si se empleó suero antiofídico.; si TIPOSUERO ∈ {1,2} → Marca tipo de suero (Antiofídico o Anticoral).; si REACCIONES ∈ {1,2,3} → Marca reacción al suero (Ninguna, Localizada, Generalizada).; si TIPOTRATAQX ∈ {1..6} → Devuelve descripción del tratamiento quirúrgico (Drenaje absceso, Limpieza quirúrgica, Desbridamiento, Fasciotomía, Injerto piel, Amputación).; si FABRICANTE ∈ {1..4} → Marca fabricante del suero (Probiol, Bioclon, INS, Otro).', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'PROCEDURE', @level1name=N'SP_HC_ListarFichaSivigila100';
-- GO
-- EXEC sys.sp_addextendedproperty @name=N'MS_BR_Consumes', @value=N'dbo.HCFICHA100', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'PROCEDURE', @level1name=N'SP_HC_ListarFichaSivigila100';
-- GO
-- EXEC sys.sp_addextendedproperty @name=N'MS_BR_Source', @value=N'ai_claude-opus-4-7_tier-c_2026-05-06', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'PROCEDURE', @level1name=N'SP_HC_ListarFichaSivigila100';
-- GO
