
-- =============================================
-- Create date: <Create Date,04-01-2024>
-- Description:	<Description,Stored procedure que lista la información de la ficha distrital 875>
-- =============================================

CREATE PROCEDURE [dbo].[SP_HC_ListarFichaDistrital875]
(
  @IdFicha as Int,
  @NumFicha as varchar(10)
)

AS
BEGIN
  SET NOCOUNT ON;
		
		Select
				CASE Child WHEN 1 THEN 'X' END AS 'Hijo', CASE CivilStatus WHEN 1 THEN 1 ELSE 0 END AS 'Soltero', CASE CivilStatus WHEN 2 THEN 1 ELSE 0 END AS 'Casado', CASE CivilStatus WHEN 3 THEN 1 ELSE 0 END AS 'Divorciado', CASE CivilStatus WHEN 4 THEN 1 ELSE 0 END AS 'Separado',
				CASE CivilStatus WHEN 5 THEN 1 ELSE 0 END AS 'Viudo',CASE CivilStatus WHEN 6 THEN 1 ELSE 0 END AS 'Unión libre',CASE CivilStatus WHEN 7 THEN 1 ELSE 0 END AS 'Sin dato civil',CASE EducationLevel WHEN 1 THEN 1 ELSE 0 END AS 'No escuela', CASE EducationLevel WHEN 2 THEN 1 ELSE 0 END AS 'Preescolar',
				CASE EducationLevel WHEN 3 THEN 1 ELSE 0 END AS 'Primaria incompleta',CASE EducationLevel WHEN 4 THEN 1 ELSE 0 END AS 'Primaria completa', CASE EducationLevel WHEN 5 THEN 1 ELSE 0 END AS 'Secundaria incompleta', CASE EducationLevel WHEN 6 THEN 1 ELSE 0 END AS 'Secundaria completa',
				CASE EducationLevel WHEN 7 THEN 1 ELSE 0 END AS 'Tecnico incompleta', CASE EducationLevel WHEN 8 THEN 1 ELSE 0 END AS 'Tecnico completa', CASE EducationLevel WHEN 9 THEN 1 ELSE 0 END AS 'Universidad incompleta', CASE EducationLevel WHEN 10 THEN 1 ELSE 0 END AS 'Universidad completa',
				CASE EducationLevel WHEN 11 THEN 1 ELSE 0 END AS 'Postgrado incompleta', CASE EducationLevel WHEN 12 THEN 1 ELSE 0 END AS 'Postgrado completa', CASE EducationLevel WHEN 13 THEN 1 ELSE 0 END AS 'Sin dato educacion', CASE InitialRiskLevel WHEN 1 THEN 1 ELSE 0 END AS 'Prioritario',
				CASE InitialRiskLevel WHEN 0 THEN 1 ELSE 0 END AS 'Control', CASE FinalClassification WHEN 1 THEN 1 ELSE 0 END AS 'No aplica clasificacion', CASE FinalClassification WHEN 2 THEN 1 ELSE 0 END AS 'Descartado', CASE FinalClassification WHEN 3 THEN 1 ELSE 0 END AS 'Conf laboratorio',
				CASE FinalClassification WHEN 4 THEN 1 ELSE 0 END AS 'Otra actualizacion',CASE FinalClassification WHEN 5 THEN 1 ELSE 0 END AS 'Conf clinica',CASE FinalClassification WHEN 6 THEN 1 ELSE 0 END AS 'Descartado digitacion', CASE FinalClassification WHEN 7 THEN 1 ELSE 0 END AS 'Conf nexo',
				CASE FinalRiskLevel WHEN 1 THEN 1 ELSE 0 END AS 'Prioritario final', CASE FinalRiskLevel WHEN 0 THEN 1 ELSE 0 END AS 'Control final', SED, CASE TRY_CAST( JSON_VALUE(FamilyFormation,'$.SOLO') AS BIT) WHEN 1 THEN 'X' END AS 'SoloFormation', CASE TRY_CAST( JSON_VALUE(FamilyFormation,'$.PADRE') AS BIT) WHEN 1 THEN 'X' END AS 'PADREFormation',
				CASE TRY_CAST( JSON_VALUE(FamilyFormation,'$.MADRE') AS BIT) WHEN 1 THEN 'X' END AS 'MADREFormation', CASE TRY_CAST( JSON_VALUE(FamilyFormation,'$.PADRASTRO') AS BIT) WHEN 1 THEN 'X' END AS 'PADRASTROFormation',  CASE TRY_CAST( JSON_VALUE(FamilyFormation,'$.MADRASTRA') AS BIT) WHEN 1 THEN 'X' END AS 'MADRASTRAFormation',
				CASE TRY_CAST( JSON_VALUE(FamilyFormation,'$.HERMANOS') AS BIT) WHEN 1 THEN 'X' END AS 'HERMANOSFormation',CASE TRY_CAST( JSON_VALUE(FamilyFormation,'$.PAREJA') AS BIT) WHEN 1 THEN 'X' END AS 'PAREJAFormation', CASE TRY_CAST( JSON_VALUE(FamilyFormation,'$.HIJOS') AS BIT) WHEN 1 THEN 'X' END AS 'HIJOSFormation',
				CASE TRY_CAST( JSON_VALUE(FamilyFormation,'$.ABUELOS') AS BIT) WHEN 1 THEN 'X' END AS 'ABUELOSFormation', CASE TRY_CAST( JSON_VALUE(FamilyFormation,'$.OTROS') AS BIT) WHEN 1 THEN 'X' END AS 'OTROSFormation', CASE PersonWithDisability WHEN 1 THEN 'X' END AS 'Persona con discapacidad', CASE TRY_CAST( JSON_VALUE(VictimActivity,'$.LIDERES') AS BIT) WHEN 1 THEN 'X' END AS 'LIDERESActivity',
				CASE TRY_CAST( JSON_VALUE(VictimActivity,'$.TRABAJADOR') AS BIT) WHEN 1 THEN 'X' END AS 'TRABAJADORActivity', CASE TRY_CAST( JSON_VALUE(VictimActivity,'$.CUIDADOHOGAR') AS BIT) WHEN 1 THEN 'X' END AS 'CUIDADOHOGARActivity', CASE TRY_CAST( JSON_VALUE(VictimActivity,'$.ESTUDIANTE') AS BIT) WHEN 1 THEN 'X' END AS 'ESTUDIANTEActivity',
				CASE TRY_CAST( JSON_VALUE(VictimActivity,'$.PERSONAPROSTITUCION') AS BIT) WHEN 1 THEN 'X' END AS 'PERSONAPROSTITUCIONActivity',CASE TRY_CAST( JSON_VALUE(VictimActivity,'$.PERSONACUIDAOTRA') AS BIT) WHEN 1 THEN 'X' END AS 'PERSONACUIDAOTRAActivity', CASE TRY_CAST( JSON_VALUE(VictimActivity,'$.OTRO') AS BIT) WHEN 1 THEN 'X' END AS 'OTROActivity',
				CASE TRY_CAST( JSON_VALUE(VictimActivity,'$.CAMPESINO') AS BIT) WHEN 1 THEN 'X' END AS 'CAMPESINOActivity',CASE TRY_CAST( JSON_VALUE(VictimActivity,'$.NINGUNA') AS BIT) WHEN 1 THEN 'X' END AS 'NINGUNAActivity', CASE SexualOrientation WHEN 1 THEN 1 ELSE 0 END AS 'Homosexual',CASE SexualOrientation WHEN 2 THEN 1 ELSE 0 END AS 'Bisexual', CASE SexualOrientation WHEN 3 THEN 1 ELSE 0 END AS 'Heterosexual',
				CASE SexualOrientation WHEN 4 THEN 1 ELSE 0 END AS 'Asexual',CASE GenderIdentity WHEN 1 THEN 1 ELSE 0 END AS 'Masculino',CASE GenderIdentity WHEN 2 THEN 1 ELSE 0 END AS 'Femenino', CASE GenderIdentity WHEN 3 THEN 1 ELSE 0 END AS 'Transgenero', CASE SPAConsumer WHEN 1 THEN 1 ELSE 0 END AS 'SiSPA', CASE SPAConsumer WHEN 0 THEN 1 ELSE 0 END AS 'NoSPA',
				CASE HeadOfHousehold WHEN 1 THEN 1 ELSE 0 END AS 'SiJefaturaHogar', CASE HeadOfHousehold WHEN 0 THEN 1 ELSE 0 END AS 'NoJefaturaHogar', CASE AlcoholVictim WHEN 1 THEN 1 ELSE 0 END AS 'SiAlcohol', CASE AlcoholVictim WHEN 0 THEN 1 ELSE 0 END AS 'NoAlcohol', CASE LiveWiththeAgressor WHEN 1 THEN 1 ELSE 0 END AS 'SiConviveAgresor', CASE LiveWiththeAgressor WHEN 0 THEN 1 ELSE 0 END AS 'NoConviveAgresor',
				CASE ArmedConflict WHEN 1 THEN 1 ELSE 0 END AS 'SiConflictoArmado', CASE ArmedConflict WHEN 0 THEN 1 ELSE 0 END AS 'NoConflictoArmado', CASE VictimOfArmedConflict WHEN 1 THEN 1 ELSE 0 END AS 'SiVictimaConflicto', CASE VictimOfArmedConflict WHEN 0 THEN 1 ELSE 0 END AS 'NoVictimaConflicto',CASE MentalDisorder WHEN 1 THEN 1 ELSE 0 END AS 'SiTrastornoMental', CASE MentalDisorder WHEN 0 THEN 1 ELSE 0 END AS 'NoTrastornoMental',
				CASE UnfavorableSocioeconomic WHEN 1 THEN 1 ELSE 0 END AS 'SiCondicionesDesfavorables', CASE UnfavorableSocioeconomic WHEN 0 THEN 1 ELSE 0 END AS 'NoCondicionesDesfavorables', CASE Unemployment WHEN 1 THEN 1 ELSE 0 END AS 'SiDesempleo', CASE Unemployment WHEN 0 THEN 1 ELSE 0 END AS 'NoDesempleo',CASE StableCouple WHEN 1 THEN 1 ELSE 0 END AS 'SiParejaEstable', CASE StableCouple WHEN 0 THEN 1 ELSE 0 END AS 'NoParejaEstable',
				CASE Children WHEN 1 THEN 1 ELSE 0 END AS 'SiHijos',CASE Children WHEN 0 THEN 1 ELSE 0 END AS 'NoHijos',CASE NoSupportNetworks WHEN 1 THEN 1 ELSE 0 END AS 'SiRedesApoyo', CASE NoSupportNetworks WHEN 0 THEN 1 ELSE 0 END AS 'NoRedesApoyo', CASE IgnoranceOfRights WHEN 1 THEN 1 ELSE 0 END AS 'SiDesconocimientoDerechos', CASE IgnoranceOfRights WHEN 0 THEN 1 ELSE 0 END AS 'NoDesconocimientoDerechos',
				CASE HistoryOfViolence WHEN 1 THEN 1 ELSE 0 END AS 'SiAntecedentesViolencia', CASE HistoryOfViolence WHEN 0 THEN 1 ELSE 0 END AS 'NoAntecedentesViolencia', convert(varchar(10),DateEvent ,103) as 'FechaHecho', 

				iif(TRY_CAST( JSON_VALUE(TypeOfViolence1,'$.EMOCIONAL') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence2,'$.EMOCIONAL') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence3,'$.EMOCIONAL') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence4,'$.EMOCIONAL') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence5,'$.EMOCIONAL') AS BIT) = 1,
				CASE PlaceOcurrence1Agressor WHEN 1 THEN 'Vivienda' WHEN 2 THEN 'Vía pública' WHEN 3 THEN 'Comercio y áreas de servicios (tiendas, centro comercial, etc.)' WHEN 4 THEN 'Lugar de trabajo' WHEN 5 THEN 'Establecimiento educativo' WHEN 6 THEN 'Otro' WHEN 7 THEN 'Lugares de esparcimiento con expendio de alcohol' WHEN 8 THEN 'Área deportiva y recreativa' WHEN 9 THEN 'Otros espacios abiertos (bosques, potreros, etc.)' WHEN 10 THEN 'Institución de salud' END
				,'') AS 'LugarOcurrenciaEmocional',

				iif(TRY_CAST( JSON_VALUE(TypeOfViolence1,'$.FISICA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence2,'$.FISICA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence3,'$.FISICA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence4,'$.FISICA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence5,'$.FISICA') AS BIT) = 1,
				CASE PlaceOcurrence1Agressor WHEN 1 THEN 'Vivienda' WHEN 2 THEN 'Vía pública' WHEN 3 THEN 'Comercio y áreas de servicios (tiendas, centro comercial, etc.)' WHEN 4 THEN 'Lugar de trabajo' WHEN 5 THEN 'Establecimiento educativo' WHEN 6 THEN 'Otro' WHEN 7 THEN 'Lugares de esparcimiento con expendio de alcohol' WHEN 8 THEN 'Área deportiva y recreativa' WHEN 9 THEN 'Otros espacios abiertos (bosques, potreros, etc.)' WHEN 10 THEN 'Institución de salud' END
				,'') AS 'LugarOcurrenciaFisica',

				iif(TRY_CAST( JSON_VALUE(TypeOfViolence1,'$.SEXUAL') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence2,'$.SEXUAL') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence3,'$.SEXUAL') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence4,'$.SEXUAL') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence5,'$.SEXUAL') AS BIT) = 1,
				CASE PlaceOcurrence1Agressor WHEN 1 THEN 'Vivienda' WHEN 2 THEN 'Vía pública' WHEN 3 THEN 'Comercio y áreas de servicios (tiendas, centro comercial, etc.)' WHEN 4 THEN 'Lugar de trabajo' WHEN 5 THEN 'Establecimiento educativo' WHEN 6 THEN 'Otro' WHEN 7 THEN 'Lugares de esparcimiento con expendio de alcohol' WHEN 8 THEN 'Área deportiva y recreativa' WHEN 9 THEN 'Otros espacios abiertos (bosques, potreros, etc.)' WHEN 10 THEN 'Institución de salud' END
				,'') AS 'LugarOcurrenciaSexual',

				iif(TRY_CAST( JSON_VALUE(TypeOfViolence1,'$.ECONOMICA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence2,'$.ECONOMICA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence3,'$.ECONOMICA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence4,'$.ECONOMICA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence5,'$.ECONOMICA') AS BIT) = 1,
				CASE PlaceOcurrence1Agressor WHEN 1 THEN 'Vivienda' WHEN 2 THEN 'Vía pública' WHEN 3 THEN 'Comercio y áreas de servicios (tiendas, centro comercial, etc.)' WHEN 4 THEN 'Lugar de trabajo' WHEN 5 THEN 'Establecimiento educativo' WHEN 6 THEN 'Otro' WHEN 7 THEN 'Lugares de esparcimiento con expendio de alcohol' WHEN 8 THEN 'Área deportiva y recreativa' WHEN 9 THEN 'Otros espacios abiertos (bosques, potreros, etc.)' WHEN 10 THEN 'Institución de salud' END
				,'') AS 'LugarOcurrenciaEconomica',

				iif(TRY_CAST( JSON_VALUE(TypeOfViolence1,'$.NEGLIGENCIA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence2,'$.NEGLIGENCIA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence3,'$.NEGLIGENCIA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence4,'$.NEGLIGENCIA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence5,'$.NEGLIGENCIA') AS BIT) = 1,
				CASE PlaceOcurrence1Agressor WHEN 1 THEN 'Vivienda' WHEN 2 THEN 'Vía pública' WHEN 3 THEN 'Comercio y áreas de servicios (tiendas, centro comercial, etc.)' WHEN 4 THEN 'Lugar de trabajo' WHEN 5 THEN 'Establecimiento educativo' WHEN 6 THEN 'Otro' WHEN 7 THEN 'Lugares de esparcimiento con expendio de alcohol' WHEN 8 THEN 'Área deportiva y recreativa' WHEN 9 THEN 'Otros espacios abiertos (bosques, potreros, etc.)' WHEN 10 THEN 'Institución de salud' END
				,'') AS 'LugarOcurrenciaNegligencia',

				iif(TRY_CAST( JSON_VALUE(TypeOfViolence1,'$.ABANDONO') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence2,'$.ABANDONO') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence3,'$.ABANDONO') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence4,'$.ABANDONO') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence5,'$.ABANDONO') AS BIT) = 1,
				CASE PlaceOcurrence1Agressor WHEN 1 THEN 'Vivienda' WHEN 2 THEN 'Vía pública' WHEN 3 THEN 'Comercio y áreas de servicios (tiendas, centro comercial, etc.)' WHEN 4 THEN 'Lugar de trabajo' WHEN 5 THEN 'Establecimiento educativo' WHEN 6 THEN 'Otro' WHEN 7 THEN 'Lugares de esparcimiento con expendio de alcohol' WHEN 8 THEN 'Área deportiva y recreativa' WHEN 9 THEN 'Otros espacios abiertos (bosques, potreros, etc.)' WHEN 10 THEN 'Institución de salud' END
				,'') AS 'LugarOcurrenciaAbandono',

				iif(TRY_CAST( JSON_VALUE(TypeOfViolence1,'$.EMOCIONAL') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence2,'$.EMOCIONAL') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence3,'$.EMOCIONAL') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence4,'$.EMOCIONAL') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence5,'$.EMOCIONAL') AS BIT) = 1,
				CASE HappenedBefore1Agressor WHEN 1 THEN 1 ELSE 0 END
				,'') AS 'SiOcurrioAntesEmocional',

				iif(TRY_CAST( JSON_VALUE(TypeOfViolence1,'$.EMOCIONAL') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence2,'$.EMOCIONAL') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence3,'$.EMOCIONAL') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence4,'$.EMOCIONAL') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence5,'$.EMOCIONAL') AS BIT) = 1,
				CASE HappenedBefore1Agressor WHEN 0 THEN 1 ELSE 0 END
				,'') AS 'NoOcurrioAntesEmocional',

				iif(TRY_CAST( JSON_VALUE(TypeOfViolence1,'$.FISICA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence2,'$.FISICA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence3,'$.FISICA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence4,'$.FISICA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence5,'$.FISICA') AS BIT) = 1,
				CASE HappenedBefore1Agressor WHEN 1 THEN 1 ELSE 0 END
				,'') AS 'SiOcurrioAntesFisica',

				iif(TRY_CAST( JSON_VALUE(TypeOfViolence1,'$.FISICA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence2,'$.FISICA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence3,'$.FISICA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence4,'$.FISICA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence5,'$.FISICA') AS BIT) = 1,
				CASE HappenedBefore1Agressor WHEN 0 THEN 1 ELSE 0 END
				,'') AS 'NoOcurrioAntesFisica',

				iif(TRY_CAST( JSON_VALUE(TypeOfViolence1,'$.SEXUAL') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence2,'$.SEXUAL') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence3,'$.SEXUAL') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence4,'$.SEXUAL') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence5,'$.SEXUAL') AS BIT) = 1,
				CASE HappenedBefore1Agressor WHEN 1 THEN 1 ELSE 0 END
				,'') AS 'SiOcurrioAntesSexual',

				iif(TRY_CAST( JSON_VALUE(TypeOfViolence1,'$.SEXUAL') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence2,'$.SEXUAL') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence3,'$.SEXUAL') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence4,'$.SEXUAL') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence5,'$.SEXUAL') AS BIT) = 1,
				CASE HappenedBefore1Agressor WHEN 0 THEN 1 ELSE 0 END
				,'') AS 'NoOcurrioAntesSexual',

				iif(TRY_CAST( JSON_VALUE(TypeOfViolence1,'$.ECONOMICA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence2,'$.ECONOMICA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence3,'$.ECONOMICA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence4,'$.ECONOMICA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence5,'$.ECONOMICA') AS BIT) = 1,
				CASE HappenedBefore1Agressor WHEN 1 THEN 1 ELSE 0 END
				,'') AS 'SiOcurrioAntesEconomica',

				iif(TRY_CAST( JSON_VALUE(TypeOfViolence1,'$.ECONOMICA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence2,'$.ECONOMICA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence3,'$.ECONOMICA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence4,'$.ECONOMICA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence5,'$.ECONOMICA') AS BIT) = 1,
				CASE HappenedBefore1Agressor WHEN 0 THEN 1 ELSE 0 END
				,'') AS 'NoOcurrioAntesEconomica',

				iif(TRY_CAST( JSON_VALUE(TypeOfViolence1,'$.NEGLIGENCIA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence2,'$.NEGLIGENCIA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence3,'$.NEGLIGENCIA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence4,'$.NEGLIGENCIA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence5,'$.NEGLIGENCIA') AS BIT) = 1,
				CASE HappenedBefore1Agressor WHEN 1 THEN 1 ELSE 0 END
				,'') AS 'SiOcurrioAntesNegligencia',

				iif(TRY_CAST( JSON_VALUE(TypeOfViolence1,'$.NEGLIGENCIA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence2,'$.NEGLIGENCIA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence3,'$.NEGLIGENCIA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence4,'$.NEGLIGENCIA') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence5,'$.NEGLIGENCIA') AS BIT) = 1,
				CASE HappenedBefore1Agressor WHEN 0 THEN 1 ELSE 0 END
				,'') AS 'NoOcurrioAntesNegligencia',

				iif(TRY_CAST( JSON_VALUE(TypeOfViolence1,'$.ABANDONO') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence2,'$.ABANDONO') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence3,'$.ABANDONO') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence4,'$.ABANDONO') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence5,'$.ABANDONO') AS BIT) = 1,
				CASE HappenedBefore1Agressor WHEN 1 THEN 1 ELSE 0 END
				,'') AS 'SiOcurrioAntesAbandono',

				iif(TRY_CAST( JSON_VALUE(TypeOfViolence1,'$.ABANDONO') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence2,'$.ABANDONO') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence3,'$.ABANDONO') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence4,'$.ABANDONO') AS BIT) = 1 OR TRY_CAST( JSON_VALUE(TypeOfViolence5,'$.ABANDONO') AS BIT) = 1,
				CASE HappenedBefore1Agressor WHEN 0 THEN 1 ELSE 0 END
				,'') AS 'NoOcurrioAntesAbandono',

				CASE TRY_CAST( JSON_VALUE(TypeOfViolence1,'$.EMOCIONAL') AS BIT) WHEN 1 THEN 'X' END AS 'EMOCIONALViolence1', CASE TRY_CAST( JSON_VALUE(TypeOfViolence1,'$.FISICA') AS BIT) WHEN 1 THEN 'X' END AS 'FISICAViolence1', CASE TRY_CAST( JSON_VALUE(TypeOfViolence1,'$.SEXUAL') AS BIT) WHEN 1 THEN 'X' END AS 'SEXUALViolence1', CASE TRY_CAST( JSON_VALUE(TypeOfViolence1,'$.ECONOMICA') AS BIT) WHEN 1 THEN 'X' END AS 'ECONOMICAViolence1',
				CASE TRY_CAST( JSON_VALUE(TypeOfViolence1,'$.NEGLIGENCIA') AS BIT) WHEN 1 THEN 'X' END AS 'NEGLIGENCIAViolence1',CASE TRY_CAST( JSON_VALUE(TypeOfViolence1,'$.ABANDONO') AS BIT) WHEN 1 THEN 'X' END AS 'ABANDONOViolence1',

				CASE TRY_CAST( JSON_VALUE(TypeOfViolence2,'$.EMOCIONAL') AS BIT) WHEN 1 THEN 'X' END AS 'EMOCIONALViolence2', CASE TRY_CAST( JSON_VALUE(TypeOfViolence2,'$.FISICA') AS BIT) WHEN 1 THEN 'X' END AS 'FISICAViolence2', CASE TRY_CAST( JSON_VALUE(TypeOfViolence2,'$.SEXUAL') AS BIT) WHEN 1 THEN 'X' END AS 'SEXUALViolence2', CASE TRY_CAST( JSON_VALUE(TypeOfViolence2,'$.ECONOMICA') AS BIT) WHEN 1 THEN 'X' END AS 'ECONOMICAViolence2',
				CASE TRY_CAST( JSON_VALUE(TypeOfViolence2,'$.NEGLIGENCIA') AS BIT) WHEN 1 THEN 'X' END AS 'NEGLIGENCIAViolence2',CASE TRY_CAST( JSON_VALUE(TypeOfViolence2,'$.ABANDONO') AS BIT) WHEN 1 THEN 'X' END AS 'ABANDONOViolence2',

				CASE TRY_CAST( JSON_VALUE(TypeOfViolence3,'$.EMOCIONAL') AS BIT) WHEN 1 THEN 'X' END AS 'EMOCIONALViolence3', CASE TRY_CAST( JSON_VALUE(TypeOfViolence3,'$.FISICA') AS BIT) WHEN 1 THEN 'X' END AS 'FISICAViolence3', CASE TRY_CAST( JSON_VALUE(TypeOfViolence3,'$.SEXUAL') AS BIT) WHEN 1 THEN 'X' END AS 'SEXUALViolence3', CASE TRY_CAST( JSON_VALUE(TypeOfViolence3,'$.ECONOMICA') AS BIT) WHEN 1 THEN 'X' END AS 'ECONOMICAViolence3',
				CASE TRY_CAST( JSON_VALUE(TypeOfViolence3,'$.NEGLIGENCIA') AS BIT) WHEN 1 THEN 'X' END AS 'NEGLIGENCIAViolence3',CASE TRY_CAST( JSON_VALUE(TypeOfViolence3,'$.ABANDONO') AS BIT) WHEN 1 THEN 'X' END AS 'ABANDONOViolence3',

				CASE TRY_CAST( JSON_VALUE(TypeOfViolence4,'$.EMOCIONAL') AS BIT) WHEN 1 THEN 'X' END AS 'EMOCIONALViolence4', CASE TRY_CAST( JSON_VALUE(TypeOfViolence4,'$.FISICA') AS BIT) WHEN 1 THEN 'X' END AS 'FISICAViolence4', CASE TRY_CAST( JSON_VALUE(TypeOfViolence4,'$.SEXUAL') AS BIT) WHEN 1 THEN 'X' END AS 'SEXUALViolence4', CASE TRY_CAST( JSON_VALUE(TypeOfViolence4,'$.ECONOMICA') AS BIT) WHEN 1 THEN 'X' END AS 'ECONOMICAViolence4',
				CASE TRY_CAST( JSON_VALUE(TypeOfViolence4,'$.NEGLIGENCIA') AS BIT) WHEN 1 THEN 'X' END AS 'NEGLIGENCIAViolence4',CASE TRY_CAST( JSON_VALUE(TypeOfViolence4,'$.ABANDONO') AS BIT) WHEN 1 THEN 'X' END AS 'ABANDONOViolence4',

				CASE TRY_CAST( JSON_VALUE(TypeOfViolence5,'$.EMOCIONAL') AS BIT) WHEN 1 THEN 'X' END AS 'EMOCIONALViolence5', CASE TRY_CAST( JSON_VALUE(TypeOfViolence5,'$.FISICA') AS BIT) WHEN 1 THEN 'X' END AS 'FISICAViolence5', CASE TRY_CAST( JSON_VALUE(TypeOfViolence5,'$.SEXUAL') AS BIT) WHEN 1 THEN 'X' END AS 'SEXUALViolence5', CASE TRY_CAST( JSON_VALUE(TypeOfViolence5,'$.ECONOMICA') AS BIT) WHEN 1 THEN 'X' END AS 'ECONOMICAViolence5',
				CASE TRY_CAST( JSON_VALUE(TypeOfViolence5,'$.NEGLIGENCIA') AS BIT) WHEN 1 THEN 'X' END AS 'NEGLIGENCIAViolence5',CASE TRY_CAST( JSON_VALUE(TypeOfViolence5,'$.ABANDONO') AS BIT) WHEN 1 THEN 'X' END AS 'ABANDONOViolence5',

				CASE Sex1Agressor WHEN 1 THEN 1 ELSE 0 END AS 'MasculinoSexo1', CASE Sex1Agressor WHEN 2 THEN 1 ELSE 0 END AS 'FemeninoSexo1',
				CASE Sex2Agressor WHEN 1 THEN 1 ELSE 0 END AS 'MasculinoSexo2', CASE Sex2Agressor WHEN 2 THEN 1 ELSE 0 END AS 'FemeninoSexo2',
				CASE Sex3Agressor WHEN 1 THEN 1 ELSE 0 END AS 'MasculinoSexo3', CASE Sex3Agressor WHEN 2 THEN 1 ELSE 0 END AS 'FemeninoSexo3',
				CASE Sex4Agressor WHEN 1 THEN 1 ELSE 0 END AS 'MasculinoSexo4', CASE Sex4Agressor WHEN 2 THEN 1 ELSE 0 END AS 'FemeninoSexo4',
				CASE Sex5Agressor WHEN 1 THEN 1 ELSE 0 END AS 'MasculinoSexo5', CASE Sex5Agressor WHEN 2 THEN 1 ELSE 0 END AS 'FemeninoSexo5',

				Age1Agressor AS 'EdadAgresor1',Age2Agressor AS 'EdadAgresor2',Age3Agressor AS 'EdadAgresor3',Age4Agressor AS 'EdadAgresor4',Age5Agressor AS 'EdadAgresor5',

				CASE Relation1Agressor WHEN 1 THEN 'Padre' WHEN 2 THEN 'Madre' WHEN 3 THEN 'Padrastro' WHEN 4 THEN 'Madrastra' WHEN 5 THEN 'Hermano (a)' WHEN 6 THEN 'Pareja' WHEN 7 THEN 'Hijo (a)' WHEN 8 THEN 'Abuelo (a)' WHEN 9 THEN 'Otro familiar' WHEN 10 THEN 'Conocido' 
				WHEN 11 THEN 'Desconocido' WHEN 12 THEN 'Docentes' WHEN 13 THEN 'Administrativos' WHEN 14 THEN 'Estudiantes' WHEN 15 THEN 'Mujer gestante' WHEN 16 THEN 'Expareja' WHEN 17 THEN 'Vecino'  WHEN 18 THEN 'Jefe' WHEN 19 THEN 'Sacerdote' WHEN 20 THEN 'Servidor público' END AS 'RelacionAgresor1',

				CASE Relation2Agressor WHEN 1 THEN 'Padre' WHEN 2 THEN 'Madre' WHEN 3 THEN 'Padrastro' WHEN 4 THEN 'Madrastra' WHEN 5 THEN 'Hermano (a)' WHEN 6 THEN 'Pareja' WHEN 7 THEN 'Hijo (a)' WHEN 8 THEN 'Abuelo (a)' WHEN 9 THEN 'Otro familiar' WHEN 10 THEN 'Conocido' 
				WHEN 11 THEN 'Desconocido' WHEN 12 THEN 'Docentes' WHEN 13 THEN 'Administrativos' WHEN 14 THEN 'Estudiantes' WHEN 15 THEN 'Mujer gestante' WHEN 16 THEN 'Expareja' WHEN 17 THEN 'Vecino'  WHEN 18 THEN 'Jefe' WHEN 19 THEN 'Sacerdote' WHEN 20 THEN 'Servidor público' END AS 'RelacionAgresor2',

				CASE Relation3Agressor WHEN 1 THEN 'Padre' WHEN 2 THEN 'Madre' WHEN 3 THEN 'Padrastro' WHEN 4 THEN 'Madrastra' WHEN 5 THEN 'Hermano (a)' WHEN 6 THEN 'Pareja' WHEN 7 THEN 'Hijo (a)' WHEN 8 THEN 'Abuelo (a)' WHEN 9 THEN 'Otro familiar' WHEN 10 THEN 'Conocido' 
				WHEN 11 THEN 'Desconocido' WHEN 12 THEN 'Docentes' WHEN 13 THEN 'Administrativos' WHEN 14 THEN 'Estudiantes' WHEN 15 THEN 'Mujer gestante' WHEN 16 THEN 'Expareja' WHEN 17 THEN 'Vecino'  WHEN 18 THEN 'Jefe' WHEN 19 THEN 'Sacerdote' WHEN 20 THEN 'Servidor público' END AS 'RelacionAgresor3',

				CASE Relation4Agressor WHEN 1 THEN 'Padre' WHEN 2 THEN 'Madre' WHEN 3 THEN 'Padrastro' WHEN 4 THEN 'Madrastra' WHEN 5 THEN 'Hermano (a)' WHEN 6 THEN 'Pareja' WHEN 7 THEN 'Hijo (a)' WHEN 8 THEN 'Abuelo (a)' WHEN 9 THEN 'Otro familiar' WHEN 10 THEN 'Conocido' 
				WHEN 11 THEN 'Desconocido' WHEN 12 THEN 'Docentes' WHEN 13 THEN 'Administrativos' WHEN 14 THEN 'Estudiantes' WHEN 15 THEN 'Mujer gestante' WHEN 16 THEN 'Expareja' WHEN 17 THEN 'Vecino'  WHEN 18 THEN 'Jefe' WHEN 19 THEN 'Sacerdote' WHEN 20 THEN 'Servidor público' END AS 'RelacionAgresor4',

				CASE Relation5Agressor WHEN 1 THEN 'Padre' WHEN 2 THEN 'Madre' WHEN 3 THEN 'Padrastro' WHEN 4 THEN 'Madrastra' WHEN 5 THEN 'Hermano (a)' WHEN 6 THEN 'Pareja' WHEN 7 THEN 'Hijo (a)' WHEN 8 THEN 'Abuelo (a)' WHEN 9 THEN 'Otro familiar' WHEN 10 THEN 'Conocido' 
				WHEN 11 THEN 'Desconocido' WHEN 12 THEN 'Docentes' WHEN 13 THEN 'Administrativos' WHEN 14 THEN 'Estudiantes' WHEN 15 THEN 'Mujer gestante' WHEN 16 THEN 'Expareja' WHEN 17 THEN 'Vecino'  WHEN 18 THEN 'Jefe' WHEN 19 THEN 'Sacerdote' WHEN 20 THEN 'Servidor público' END AS 'RelacionAgresor5',

				CASE Drugs1Agressor WHEN 1 THEN 1 ELSE 0 END AS 'SiDrogasAgresor1', CASE Drugs1Agressor WHEN 0 THEN 1 ELSE 0 END AS 'NoDrogasAgresor1',
				CASE Drugs2Agressor WHEN 1 THEN 1 ELSE 0 END AS 'SiDrogasAgresor2', CASE Drugs2Agressor WHEN 0 THEN 1 ELSE 0 END AS 'NoDrogasAgresor2',
				CASE Drugs3Agressor WHEN 1 THEN 1 ELSE 0 END AS 'SiDrogasAgresor3', CASE Drugs3Agressor WHEN 0 THEN 1 ELSE 0 END AS 'NoDrogasAgresor3',
				CASE Drugs4Agressor WHEN 1 THEN 1 ELSE 0 END AS 'SiDrogasAgresor4', CASE Drugs4Agressor WHEN 0 THEN 1 ELSE 0 END AS 'NoDrogasAgresor4',
				CASE Drugs5Agressor WHEN 1 THEN 1 ELSE 0 END AS 'SiDrogasAgresor5', CASE Drugs5Agressor WHEN 0 THEN 1 ELSE 0 END AS 'NoDrogasAgresor5',
								
				CASE TRY_CAST( JSON_VALUE(SexualViolence,'$.ACOSOSEXUAL') AS BIT) WHEN 1 THEN 'X' END AS 'Acoso sexual', CASE TRY_CAST( JSON_VALUE(SexualViolence,'$.ACCESOCARNAL') AS BIT) WHEN 1 THEN 'X' END AS 'Acceso carnal', CASE TRY_CAST( JSON_VALUE(SexualViolence,'$.MUTILACION') AS BIT) WHEN 1 THEN 'X' END AS 'Mutilacion genital', CASE TRY_CAST( JSON_VALUE(SexualViolence,'$.ENTORNOS') AS BIT) WHEN 1 THEN 'X' END AS 'Entornos digitales', 
				CASE TRY_CAST( JSON_VALUE(SexualViolence,'$.EXPLOTACION') AS BIT) WHEN 1 THEN 'X' END AS 'Explotación sexual', CASE TRY_CAST( JSON_VALUE(SexualViolence,'$.TRATADEPERSONAS') AS BIT) WHEN 1 THEN 'X' END AS 'Trata de personas',  CASE TRY_CAST( JSON_VALUE(SexualViolence,'$.ACTOSSEXUALES') AS BIT) WHEN 1 THEN 'X' END AS 'Actos sexuales', CASE TRY_CAST( JSON_VALUE(SexualViolence,'$.OTRAS') AS BIT) WHEN 1 THEN 'X' END AS 'Otras violencias', 
				
				CASE TRY_CAST( JSON_VALUE(HealthCareHealthProvider,'$.PROFILAXIS') AS BIT) WHEN 1 THEN 'X' END AS 'PROFILAXISHealthProvider', CASE TRY_CAST( JSON_VALUE(HealthCareHealthProvider,'$.OTRASPROFILAXIS') AS BIT) WHEN 1 THEN 'X' END AS 'OTRASPROFILAXISHealthProvider', CASE TRY_CAST( JSON_VALUE(HealthCareHealthProvider,'$.REMISION') AS BIT) WHEN 1 THEN 'X' END AS 'REMISIONHealthProvider',
				CASE TRY_CAST( JSON_VALUE(HealthCareHealthProvider,'$.ATENCIONURGENCIAS') AS BIT) WHEN 1 THEN 'X' END AS 'ATENCIONURGENCIASHealthProvider', CASE TRY_CAST( JSON_VALUE(HealthCareHealthProvider,'$.PROFILAXISHB') AS BIT) WHEN 1 THEN 'X' END AS 'PROFILAXISHBHealthProvider', CASE TRY_CAST( JSON_VALUE(HealthCareHealthProvider,'$.ORIENTACIONIVE') AS BIT) WHEN 1 THEN 'X' END AS 'ORIENTACIONIVEHealthProvider',
				CASE TRY_CAST( JSON_VALUE(HealthCareHealthProvider,'$.TOMAPRUEBAS') AS BIT) WHEN 1 THEN 'X' END AS 'TOMAPRUEBASHealthProvider', CASE TRY_CAST( JSON_VALUE(HealthCareHealthProvider,'$.ANTICONCEPCION') AS BIT) WHEN 1 THEN 'X' END AS 'ANTICONCEPCIONHealthProvider', CASE TRY_CAST( JSON_VALUE(HealthCareHealthProvider,'$.SALUDMENTAL') AS BIT) WHEN 1 THEN 'X' END AS 'SALUDMENTALHealthProvider',
				CASE TRY_CAST( JSON_VALUE(HealthCareHealthProvider,'$.RECOLECCION') AS BIT) WHEN 1 THEN 'X' END AS 'RECOLECCIONHealthProvider', CASE TRY_CAST( JSON_VALUE(HealthCareHealthProvider,'$.INFORME') AS BIT) WHEN 1 THEN 'X' END AS 'INFORMEHealthProvider', CASE TRY_CAST( JSON_VALUE(Mechanisms,'$.AHORCAMIENTO') AS BIT) WHEN 1 THEN 'X' END AS 'AHORCAMIENTOMechanisms', 
				CASE TRY_CAST( JSON_VALUE(Mechanisms,'$.CORTANTE') AS BIT) WHEN 1 THEN 'X' END AS 'CORTANTEMechanisms',CASE TRY_CAST( JSON_VALUE(Mechanisms,'$.QUEMADURASACIDO') AS BIT) WHEN 1 THEN 'X' END AS 'QUEMADURASACIDOMechanisms', CASE TRY_CAST( JSON_VALUE(Mechanisms,'$.SUSTANCIAS') AS BIT) WHEN 1 THEN 'X' END AS 'SUSTANCIASMechanisms', CASE TRY_CAST( JSON_VALUE(Mechanisms,'$.CAIDAS') AS BIT) WHEN 1 THEN 'X' END AS 'CAIDASMechanisms',
				CASE TRY_CAST( JSON_VALUE(Mechanisms,'$.PROYECTIL') AS BIT) WHEN 1 THEN 'X' END AS 'PROYECTILMechanisms', CASE TRY_CAST( JSON_VALUE(Mechanisms,'$.QUEMADURASLIQUIDOS') AS BIT) WHEN 1 THEN 'X' END AS 'QUEMADURASLIQUIDOSMechanisms', CASE TRY_CAST( JSON_VALUE(Mechanisms,'$.CONTUNDENTE') AS BIT) WHEN 1 THEN 'X' END AS 'CONTUNDENTEMechanisms', CASE TRY_CAST( JSON_VALUE(Mechanisms,'$.QUEMADURASFUEGO') AS BIT) WHEN 1 THEN 'X' END AS 'QUEMADURASFUEGOMechanisms',
				CASE TRY_CAST( JSON_VALUE(Mechanisms,'$.OTROS') AS BIT) WHEN 1 THEN 'X' END AS 'OTROSMechanisms', OtherMechanisms as 'CualOtroMecanismo',CASE TRY_CAST( JSON_VALUE(AnatomicalSiteWithBurn,'$.CARA') AS BIT) WHEN 1 THEN 'X' END AS 'CARAAnatomicalSite', CASE TRY_CAST( JSON_VALUE(AnatomicalSiteWithBurn,'$.CUELLO') AS BIT) WHEN 1 THEN 'X' END AS 'CUELLOAnatomicalSite', CASE TRY_CAST( JSON_VALUE(AnatomicalSiteWithBurn,'$.MANO') AS BIT) WHEN 1 THEN 'X' END AS 'MANOAnatomicalSite',
				CASE TRY_CAST( JSON_VALUE(AnatomicalSiteWithBurn,'$.PIES') AS BIT) WHEN 1 THEN 'X' END AS 'PIESAnatomicalSite',CASE TRY_CAST( JSON_VALUE(AnatomicalSiteWithBurn,'$.PLIEGUES') AS BIT) WHEN 1 THEN 'X' END AS 'PLIEGUESAnatomicalSite', CASE TRY_CAST( JSON_VALUE(AnatomicalSiteWithBurn,'$.GENITALES') AS BIT) WHEN 1 THEN 'X' END AS 'GENITALESAnatomicalSite',CASE TRY_CAST( JSON_VALUE(AnatomicalSiteWithBurn,'$.TRONCO') AS BIT) WHEN 1 THEN 'X' END AS 'TRONCOAnatomicalSite',
				CASE TRY_CAST( JSON_VALUE(AnatomicalSiteWithBurn,'$.MIEMBROSUPERIOR') AS BIT) WHEN 1 THEN 'X' END AS 'MIEMBROSUPERIORAnatomicalSite',CASE TRY_CAST( JSON_VALUE(AnatomicalSiteWithBurn,'$.MIEMBROINFERIOR') AS BIT) WHEN 1 THEN 'X' END AS 'MIEMBROINFERIORAnatomicalSite', CASE BurnDegree WHEN 1 THEN 1 ELSE 0 END AS 'PrimerGrado',CASE BurnDegree WHEN 2 THEN 1 ELSE 0 END AS 'SegundoGrado',CASE BurnDegree WHEN 3 THEN 1 ELSE 0 END AS 'TercerGrado',
				CASE Extension WHEN 1 THEN 1 ELSE 0 END AS 'Menor5', CASE Extension WHEN 2 THEN 1 ELSE 0 END AS 'Del6', CASE Extension WHEN 3 THEN 1 ELSE 0 END AS 'Mayor15', CASE TRY_CAST( JSON_VALUE(AtTimeOfCare,'$.HEMATOMAS') AS BIT) WHEN 1 THEN 'X' END AS 'HEMATOMASAtTime',CASE TRY_CAST( JSON_VALUE(AtTimeOfCare,'$.DOLORES') AS BIT) WHEN 1 THEN 'X' END AS 'DOLORESAtTime', CASE TRY_CAST( JSON_VALUE(AtTimeOfCare,'$.FRACTURAS') AS BIT) WHEN 1 THEN 'X' END AS 'FRACTURASAtTime',
				CASE TRY_CAST( JSON_VALUE(AtTimeOfCare,'$.TRISTEZA') AS BIT) WHEN 1 THEN 'X' END AS 'TRISTEZAAtTime', CASE TRY_CAST( JSON_VALUE(AtTimeOfCare,'$.ANGUSTIA') AS BIT) WHEN 1 THEN 'X' END AS 'ANGUSTIAAtTime', CASE TRY_CAST( JSON_VALUE(AtTimeOfCare,'$.PROBLEMASDORMIR') AS BIT) WHEN 1 THEN 'X' END AS 'PROBLEMASDORMIRAtTime', CASE TRY_CAST( JSON_VALUE(AtTimeOfCare,'$.OTROSPROBLEMAS') AS BIT) WHEN 1 THEN 'X' END AS 'OTROSPROBLEMASAtTime',
				CASE TRY_CAST( JSON_VALUE(ManagementInstitution,'$.ATENCION') AS BIT) WHEN 1 THEN 'X' END AS 'ATENCIONManagement',CASE TRY_CAST( JSON_VALUE(ManagementInstitution,'$.ASESORIAPSICOLOGICA') AS BIT) WHEN 1 THEN 'X' END AS 'ASESORIAPSICOLOGICAManagement',CASE TRY_CAST( JSON_VALUE(ManagementInstitution,'$.ASESORIALEGAL') AS BIT) WHEN 1 THEN 'X' END AS 'ASESORIALEGALManagement',CASE TRY_CAST( JSON_VALUE(ManagementInstitution,'$.PROTECCION') AS BIT) WHEN 1 THEN 'X' END AS 'PROTECCIONManagement',
				CASE TRY_CAST( JSON_VALUE(ManagementInstitution,'$.ORIENTACION') AS BIT) WHEN 1 THEN 'X' END AS 'ORIENTACIONManagement',CASE TRY_CAST( JSON_VALUE(ManagementInstitution,'$.REMISION') AS BIT) WHEN 1 THEN 'X' END AS 'REMISIONManagement',CASE TRY_CAST( JSON_VALUE(ManagementInstitution,'$.OTRA') AS BIT) WHEN 1 THEN 'X' END AS 'OTRAManagement', CASE WhereCaseDetected WHEN 1 THEN 1 ELSE 0 END AS 'WhereConsultaExterna', CASE WhereCaseDetected WHEN 2 THEN 1 ELSE 0 END AS 'WhereUrgencias',
				CASE WhereCaseDetected WHEN 3 THEN 1 ELSE 0 END AS 'WhereLinea',CASE WhereCaseDetected WHEN 4 THEN 1 ELSE 0 END AS 'WhereCentroEducativo', CASE WhereCaseDetected WHEN 5 THEN 1 ELSE 0 END AS 'WhereReporteComunitario',CASE WhereCaseDetected WHEN 6 THEN 1 ELSE 0 END AS 'WhereOtro', WhichCaseDetected as 'CualDonde', CASE RiskAssessment WHEN 1 THEN 1 ELSE 0 END AS 'ValoracionAlto', CASE RiskAssessment WHEN 2 THEN 1 ELSE 0 END AS 'ValoracionMedio', 
				CASE RiskAssessment WHEN 3 THEN 1 ELSE 0 END AS 'ValoracionBajo',CASE RiskAssessment WHEN 4 THEN 1 ELSE 0 END AS 'ValoracionNinguno', EntityMonitoring as 'EntidadSeguimiento', convert(varchar(10),MonitoringStartDate ,103) as 'FechaInicioSeguimieno', CASE HomeVisitScheduled WHEN 1 THEN 1 ELSE 0 END AS 'SiProgramoVisita', CASE HomeVisitScheduled WHEN 0 THEN 1 ELSE 0 END AS 'NoProgramoVisita', convert(varchar(10),HomeVisitScheduledDate ,103) as 'FechaProgramacionVisita',
				CASE HomeVisitDone WHEN 1 THEN 1 ELSE 0 END AS 'SiRealizoVisita', CASE HomeVisitDone WHEN 0 THEN 1 ELSE 0 END AS 'NoRealizoVisita', convert(varchar(10),HomeVisitDoneDate ,103) as 'FechaRealizoVisita', CASE IdentifiedParentingStyle WHEN 1 THEN 1 ELSE 0 END AS 'EstiloCrianzaAutoritario', CASE IdentifiedParentingStyle WHEN 2 THEN 1 ELSE 0 END AS 'EstiloCrianzaDemocratico', CASE IdentifiedParentingStyle WHEN 3 THEN 1 ELSE 0 END AS 'EstiloCrianzaNegligente',
				CASE IdentifiedParentingStyle WHEN 4 THEN 1 ELSE 0 END AS 'EstiloCrianzaPermisivo',CASE InitialReferralDone WHEN 1 THEN 1 ELSE 0 END AS 'SiRealizoRemision', CASE InitialReferralDone WHEN 0 THEN 1 ELSE 0 END AS 'NoRealizoRemision',CASE TRY_CAST( JSON_VALUE(WhereInitialReferral,'$.CENTROICBF') AS BIT) WHEN 1 THEN 'X' END AS 'CENTROICBFReferral', CASE TRY_CAST( JSON_VALUE(WhereInitialReferral,'$.CAIVAS') AS BIT) WHEN 1 THEN 'X' END AS 'CAIVASReferral',
				CASE TRY_CAST( JSON_VALUE(WhereInitialReferral,'$.MEDICINALEGAL') AS BIT) WHEN 1 THEN 'X' END AS 'MEDICINALEGALReferral',CASE TRY_CAST( JSON_VALUE(WhereInitialReferral,'$.OTRAINSTITUCION') AS BIT) WHEN 1 THEN 'X' END AS 'OTRAINSTITUCIONReferral',CASE TRY_CAST( JSON_VALUE(WhereInitialReferral,'$.CASAREFUGIO') AS BIT) WHEN 1 THEN 'X' END AS 'CASAREFUGIOReferral',CASE TRY_CAST( JSON_VALUE(WhereInitialReferral,'$.CAVI') AS BIT) WHEN 1 THEN 'X' END AS 'CAVIReferral',
				CASE TRY_CAST( JSON_VALUE(WhereInitialReferral,'$.ESPACIOVIVIENDA') AS BIT) WHEN 1 THEN 'X' END AS 'ESPACIOVIVIENDAReferral',CASE TRY_CAST( JSON_VALUE(WhereInitialReferral,'$.COMISARIAFAMILIA') AS BIT) WHEN 1 THEN 'X' END AS 'COMISARIAFAMILIAReferral',CASE TRY_CAST( JSON_VALUE(WhereInitialReferral,'$.CURNN') AS BIT) WHEN 1 THEN 'X' END AS 'CURNNReferral',CASE TRY_CAST( JSON_VALUE(WhereInitialReferral,'$.SALUDMENTAL') AS BIT) WHEN 1 THEN 'X' END AS 'SALUDMENTALReferral',
				CASE TRY_CAST( JSON_VALUE(WhereInitialReferral,'$.CASAIGUALDAD') AS BIT) WHEN 1 THEN 'X' END AS 'CASAIGUALDADReferral',CASE TRY_CAST( JSON_VALUE(WhereInitialReferral,'$.CASAJUSTICIA') AS BIT) WHEN 1 THEN 'X' END AS 'CASAJUSTICIAReferral',CASE TRY_CAST( JSON_VALUE(WhereInitialReferral,'$.SECRETARIAINTEGRACION') AS BIT) WHEN 1 THEN 'X' END AS 'SECRETARIAINTEGRACIONReferral', InitialReferralOthers AS 'OtraRemisionInicial', FiledToICBF AS 'RadicadoICBF', FiledToPolice AS 'RadicadoComisaria',
				FiledToProsecutorOffice AS 'RadicadoFiscalia', FiledToOther AS 'RadicadoOtro',CASE TRY_CAST( JSON_VALUE(MonitoringActivity,'$.NOAPLICA') AS BIT) WHEN 1 THEN 'X' END AS 'NOAPLICAMonitoring',CASE TRY_CAST( JSON_VALUE(MonitoringActivity,'$.SEGUIMIENTOTELEFONO') AS BIT) WHEN 1 THEN 'X' END AS 'SEGUIMIENTOTELEFONOMonitoring',CASE TRY_CAST( JSON_VALUE(MonitoringActivity,'$.VIDEOLLAMADA') AS BIT) WHEN 1 THEN 'X' END AS 'VIDEOLLAMADAMonitoring',
				CASE TRY_CAST( JSON_VALUE(MonitoringActivity,'$.VISITADOMICILIARIA') AS BIT) WHEN 1 THEN 'X' END AS 'VISITADOMICILIARIAMonitoring',CASE TRY_CAST( JSON_VALUE(MonitoringActivity,'$.CHAT') AS BIT) WHEN 1 THEN 'X' END AS 'CHATMonitoring',CASE TRY_CAST( JSON_VALUE(MonitoringActivity,'$.MONITOREOENTIDAD') AS BIT) WHEN 1 THEN 'X' END AS 'MONITOREOENTIDADMonitoring', NumberOfMonitoring as 'NumeroSeguimientos',
				CASE TRY_CAST( JSON_VALUE(CaseClosedIn,'$.CUMPLIMIENTOINTEGRAL') AS BIT) WHEN 1 THEN 'X' END AS 'CUMPLIMIENTOINTEGRALClosedIn',CASE TRY_CAST( JSON_VALUE(CaseClosedIn,'$.INICIOJUDICIALIZACION') AS BIT) WHEN 1 THEN 'X' END AS 'INICIOJUDICIALIZACIONClosedIn',CASE TRY_CAST( JSON_VALUE(CaseClosedIn,'$.ATENCIONINTEGRAL') AS BIT) WHEN 1 THEN 'X' END AS 'ATENCIONINTEGRALClosedIn',CASE TRY_CAST( JSON_VALUE(CaseClosedIn,'$.INTEGRALJUDICIALIZACION') AS BIT) WHEN 1 THEN 'X' END AS 'INTEGRALJUDICIALIZACIONClosedIn',
				CASE TRY_CAST( JSON_VALUE(CaseClosedIn,'$.PROCESORESTABLECIMIENTO') AS BIT) WHEN 1 THEN 'X' END AS 'PROCESORESTABLECIMIENTOClosedIn', convert(varchar(10),CaseClosingDate ,103) AS 'FechaCierreCaso', ResponsibleIECProfessional AS 'ProfesionalIEC', CASE FALLIDO WHEN 1 THEN 1 ELSE 0 END AS 'SiFallido', CASE FALLIDO WHEN 0 THEN 1 ELSE 0 END AS 'NoFallido', CASE SISVECOSCheck WHEN 1 THEN 'X' END AS 'SISVECOSCheck',SISVECOSText AS 'SISVECOSTexto',
				CASE SIVELCECheck WHEN 1 THEN 'X' END AS 'SIVELCECheck',SIVELCEText AS 'SIVELCETexto', CASE VESPACheck WHEN 1 THEN 'X' END AS 'VESPACheck',VESPAText AS 'VESPATexto',InitialCaseNumber AS 'NumeroCasoInicial', Observations AS 'Observaciones',
				VERSION AS 'VERSION'
	
			From 
				HCFICHA875D 

			Where 
				IDFICHANOTIFICACION  = @IdFicha 

END
GO
-- EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Procedimiento que recupera y presenta el detalle completo de una Ficha Distrital 875 (ficha de violencia basada en género y factores de riesgo psicosocial) a partir de su identificador y número de ficha. Transforma los valores codificados de la tabla HCFICHA875D en etiquetas legibles de negocio para estado civil, nivel educativo, nivel de riesgo inicial y final, clasificación final, composición familiar, orientación sexual, identidad de género, consumo de SPA, jefatura del hogar, convivencia con el agresor, conflicto armado, trastorno mental, situación socioeconómica, desempleo y tipos de violencia, entre otros factores de vulnerabilidad. Se usa para imprimir o visualizar el formulario oficial de la ficha distrital 875 de salud pública, que reporta casos de violencia intrafamiliar y de género ante las autoridades distritales.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'SP_HC_ListarFichaDistrital875';
-- GO
-- EXECUTE sp_addextendedproperty @name = N'MS_DescriptionSource', @value = N'backport_from_v25.47c_2026-05-05', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'SP_HC_ListarFichaDistrital875';
-- GO
-- GO
-- GO
-- EXEC sys.sp_addextendedproperty @name=N'MS_BR_Purpose', @value=N'Devuelve la información detallada de una ficha de notificación distrital 875 (violencias) transformando códigos numéricos y estructuras JSON en banderas/etiquetas legibles para reporte.', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'PROCEDURE', @level1name=N'SP_HC_ListarFichaDistrital875';
-- GO
-- EXEC sys.sp_addextendedproperty @name=N'MS_BR_Preconditions', @value=N'Debe existir un registro en HCFICHA875D cuyo IDFICHANOTIFICACION coincida con el parámetro de ficha recibido.', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'PROCEDURE', @level1name=N'SP_HC_ListarFichaDistrital875';
-- GO
-- EXEC sys.sp_addextendedproperty @name=N'MS_BR_Invariants', @value=N'Todas las banderas binarias se devuelven como 1/0 o ''X''/NULL según el patrón de la columna correspondiente.; Las fechas (DateEvent, MonitoringStartDate, HomeVisitScheduledDate, HomeVisitDoneDate, CaseClosingDate) se formatean siempre en estilo 103 (dd/mm/yyyy).; Las columnas tipo JSON (FamilyFormation, VictimActivity, TypeOfViolence1..5, SexualViolence, HealthCareHealthProvider, Mechanisms, AnatomicalSiteWithBurn, AtTimeOfCare, ManagementInstitution, WhereInitialReferral, MonitoringActivity, CaseClosedIn) se interpretan vía JSON_VALUE con TRY_CAST a BIT, devolviendo ''X'' solo cuando el valor es 1.; Los campos de lugar de ocurrencia y ''ocurrió antes'' se devuelven solo si el tipo de violencia correspondiente está marcado en alguno de los 5 episodios; en caso contrario se devuelve cadena vacía.; El procedimiento siempre opera sobre una sola ficha identificada por IDFICHANOTIFICACION.', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'PROCEDURE', @level1name=N'SP_HC_ListarFichaDistrital875';
-- GO
-- EXEC sys.sp_addextendedproperty @name=N'MS_BR_SideEffects', @value=N'[RETURN_RESULT] dbo.HCFICHA875D: Cuando IDFICHANOTIFICACION = @IdFicha, retorna un único conjunto de columnas con los datos decodificados de la ficha (estado civil, escolaridad, riesgo, clasificación, tipos de violencia, agresores, atención en salud, seguimiento, cierre, etc.).', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'PROCEDURE', @level1name=N'SP_HC_ListarFichaDistrital875';
-- GO
-- EXEC sys.sp_addextendedproperty @name=N'MS_BR_Decisions', @value=N'si CivilStatus IN (1..7) → Marca 1 en la columna correspondiente (Soltero, Casado, Divorciado, Separado, Viudo, Unión libre, Sin dato civil) y 0 en las demás.; si EducationLevel IN (1..13) → Activa la bandera del nivel educativo correspondiente (desde ''No escuela'' hasta ''Sin dato educacion'').; si InitialRiskLevel = 1 / 0 → Clasifica como ''Prioritario'' o ''Control'' inicial respectivamente.; si FinalClassification IN (1..7) → Define la clasificación final del caso: No aplica, Descartado, Confirmado por laboratorio, Otra actualización, Confirmado clínica, Descartado por digitación o Confirmado por nexo.; si FinalRiskLevel = 1 / 0 → Marca ''Prioritario final'' o ''Control final''.; si Para cada TypeOfViolence1..5, JSON_VALUE($.EMOCIONAL/FISICA/SEXUAL/ECONOMICA/NEGLIGENCIA/ABANDONO) = 1 → Devuelve el lugar de ocurrencia (PlaceOcurrence1Agressor mapeado a etiqueta) y la marca de ''ocurrió antes'' (HappenedBefore1Agressor) asociada a ese tipo de violencia. else Devuelve cadena vacía para esos campos.; si PlaceOcurrence1Agressor IN (1..10) → Traduce el código a etiqueta textual (Vivienda, Vía pública, Comercio, Lugar de trabajo, Establecimiento educativo, Otro, Esparcimiento con alcohol, Área deportiva, Espacios abiertos, Institución de salud).; si RelationNAgressor IN (1..20) → Traduce código de relación del agresor a etiqueta (Padre, Madre, Padrastro, ... Servidor público) para los hasta 5 agresores.; si BurnDegree IN (1..3) → Marca grado de quemadura (Primer/Segundo/Tercer grado).; si Extension IN (1..3) → Clasifica la extensión de la quemadura en Menor 5%, 6-15% o Mayor 15%.; si WhereCaseDetected IN (1..6) → Indica el lugar de detección del caso (Consulta externa, Urgencias, Línea, Centro educativo, Reporte comunitario u Otro).; si RiskAssessment IN (1..4) → Clasifica la valoración de riesgo (Alto, Medio, Bajo, Ninguno).; si IdentifiedParentingStyle IN (1..4) → Marca estilo de crianza identificado (Autoritario, Democrático, Negligente, Permisivo).', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'PROCEDURE', @level1name=N'SP_HC_ListarFichaDistrital875';
-- GO
-- EXEC sys.sp_addextendedproperty @name=N'MS_BR_Consumes', @value=N'dbo.HCFICHA875D', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'PROCEDURE', @level1name=N'SP_HC_ListarFichaDistrital875';
-- GO
-- EXEC sys.sp_addextendedproperty @name=N'MS_BR_Source', @value=N'ai_claude-opus-4-7_tier-c_2026-05-06', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'PROCEDURE', @level1name=N'SP_HC_ListarFichaDistrital875';
-- GO
