

CREATE PROCEDURE [dbo].[SPHC_ATENCIONURGENCIAS_CTE]
(
@CENTROATENCION CHAR(10),
@USUARIO CHAR(20),
@UFUNCIONAL CHAR(20)
)
AS
BEGIN
	SET NOCOUNT ON;

--NECESITAMOS SABER SI LA UNIDAD QUE ESTA HACIENDO LA CONSULTA ES DE ATENCIÓN PRIORITARIA O URGENCIAS
DECLARE @ATENCIONPRIORITARIA BIT = (SELECT CASE UFUTIPUNI WHEN 31 THEN 1 ELSE 0 END FROM INUNIFUNC WITH (NOLOCK) WHERE UFUCODIGO = @UFUNCIONAL)
DECLARE @ESTADO_3 AS INT = 3
DECLARE @ESTADO_4 AS INT = 4
DECLARE @FECHAINICIOCARGUE DATE = '01/01/2021' 

IF @ATENCIONPRIORITARIA=1 
BEGIN 

;WITH ADINGRESO_NO_ANULADO
AS
(
SELECT UFUCODIGO, CODTIPPAC AS TIPO, RTRIM(IPCODPACI) AS IDENTIFICACION, VIVESOLO, NUMINGRES, IESTADOIN, CODCENATE, IPCODPACI, IFECHAING, CODTIPPAC FROM DBO.ADINGRESO 
WHERE CAST(IFECHAING AS DATE)>@FECHAINICIOCARGUE AND IESTADOIN <> 'A' AND UFUEGRMED IS NULL AND NUMINGRES IS NOT NULL  
AND CODCENATE=@CENTROATENCION AND UFUCODIGO = @UFUNCIONAL
)

,ADINGRESO_ABIERTO
AS
(
SELECT UFUCODIGO, CODTIPPAC AS TIPO, RTRIM(IPCODPACI) AS IDENTIFICACION, VIVESOLO, NUMINGRES, IESTADOIN, CODCENATE, IPCODPACI, IFECHAING, CODTIPPAC FROM DBO.ADINGRESO 
WHERE CAST(IFECHAING AS DATE)>@FECHAINICIOCARGUE AND IESTADOIN = ' ' AND UFUEGRMED IS NULL AND (REQTRIAGE = 0 OR REQTRIAGE IS NULL) 
AND CODCENATE=@CENTROATENCION AND UFUCODIGO = @UFUNCIONAL
)	

,POBESPECIAL
AS
(
SELECT COUNT(*) POBESPECIAL, IPCODPACI FROM DBO.ADPOBESPEPAC Z WITH(NOLOCK) 
INNER JOIN ADPOBESPE X WITH(NOLOCK) ON X.ID = Z.IDADPOBESPE 
WHERE TIPOPOESPERIES = 1
GROUP BY IPCODPACI
)

,ACOMPANANTES
AS
(
SELECT COUNT(*) ACOMPANANTES, NUMINGRES, IPCODPACI FROM ADACOMPAN WITH(NOLOCK) 
GROUP BY NUMINGRES, IPCODPACI
)

,INGRESO_AMBORDIMA
AS
(
SELECT DISTINCT A.NUMINGRES FROM  ADINGRESO AS A WITH(NOLOCK) INNER JOIN AMBORDIMA AS B WITH(NOLOCK) ON B.IPCODPACI = A.IPCODPACI
WHERE  CONVERT(VARCHAR(10),CONVERT(DATE,A.IFECHAING,106),103) = CONVERT(VARCHAR(10),CONVERT(DATE,B.FECORDMED,106),103)
) 

, HC_HISPACA
AS
(
SELECT COUNT(ID) CONTEO, NUMINGRES FROM HCHISPACA WITH(NOLOCK) 
GROUP BY NUMINGRES
)

, DOCUMENTO_BLOQUEADO
AS
(
SELECT NUMDOCUME FROM DBO.INDOCUMEN WITH(NOLOCK) WHERE CODDOCUME=@ESTADO_3 AND CODUSUARI<>@USUARIO
)

, ATENCION_URGENCIAS
AS (
SELECT 	A.TRIAFECHA AS FECHALLEGADA, K.UFUCODIGO,A.TRIORIGEN,CASE A.TRIORIGEN WHEN 1  THEN '1 - PACIENTES MEDICINA GENERAL' WHEN 2 THEN '2 - PACIENTES MEDICINA ESPECIALIZADA' END AS ORIGEN,
		K.CODTIPPAC AS TIPO, TRIANUMER AS CONSECUTIVO,RTRIM(TRIANOMCA) AS [DX SINDROMATICO],RTRIM(K.IPCODPACI) AS IDENTIFICACION, RTRIM(F.IPNOMCOMP) AS [NOMBRE PACIENTE], TRIAFECHA AS [FECHA TRIAGE],0 AS MINUTOS,0 AS BARRA,CAST(0 AS BIT) AS CONFIRMADO,CAST(0 AS BIT) AS AUSENTE,A.NUMINGRES AS INGRESO,IPFECNACI AS 'FECHA NACIMIENTO' ,CAST('' AS CHAR(50)) AS EDAD,RTRIM(G.DESESPECI) AS ESPECIALIDAD
		, CASE WHEN F.IPTIPODOC IN(6,7) THEN 1 ELSE 0 END AS ASMS
		, F.ZONAPARTADA,
		L.RIESGOAGRE,
		PE.POBESPECIAL, --(SELECT COUNT(*) FROM DBO.ADPOBESPEPAC Z WITH(NOLOCK) INNER JOIN ADPOBESPE X WITH(NOLOCK) ON X.ID = Z.IDADPOBESPE WHERE IPCODPACI = F.IPCODPACI AND TIPOPOESPERIES = 1) AS POBESPECIAL,
		K.VIVESOLO,
		AC.ACOMPANANTES,   --(SELECT COUNT(*) FROM ADACOMPAN WITH(NOLOCK) WHERE NUMINGRES = K.NUMINGRES) AS ACOMPANANTES,
		CONVERT(BIT,0) AS RIESGO, RTRIM(F.CODENTIDA) + '-'+ RTRIM(M.NOMENTIDA) AS ENTIDADPACIENTE
		FROM DBO.ADTRIAGEU A WITH(NOLOCK) 
		LEFT JOIN ADINGRESO_NO_ANULADO K WITH(NOLOCK) ON A.NUMINGRES = K.NUMINGRES LEFT JOIN INGRESO_AMBORDIMA AM WITH(NOLOCK) ON K.NUMINGRES=AM.NUMINGRES AND AM.NUMINGRES IS NULL --AND K.NUMINGRES NOT IN (SELECT DISTINCT A.NUMINGRES FROM  ADINGRESO AS A WITH(NOLOCK) INNER JOIN AMBORDIMA AS B WITH(NOLOCK) ON B.IPCODPACI = A.IPCODPACI WHERE  CONVERT(VARCHAR(10),CONVERT(DATE,A.IFECHAING,106),103) = CONVERT(VARCHAR(10),CONVERT(DATE,B.FECORDMED,106),103)) 
		--INNER JOIN DBO.INPROFSAL D WITH(NOLOCK) ON D.CODPROSAL=A.CODPROSAL 
		INNER JOIN DBO.ADCATTRIU E WITH(NOLOCK) ON E.TRIACATEG=A.TRIACATEG 
		INNER JOIN DBO.INPACIENT F WITH(NOLOCK) ON K.IPCODPACI=F.IPCODPACI 
	    LEFT JOIN DBO.INESPECIA G WITH(NOLOCK) ON A.CODESPECI=G.CODESPECI 
		LEFT JOIN DBO.ADACTIVID L WITH(NOLOCK) ON F.CODACTIVI = L.CODACTIVI 
		LEFT JOIN DBO.INENTIDAD M WITH(NOLOCK) ON M.CODENTIDA = F.CODENTIDA 
		LEFT JOIN HC_HISPACA HC WITH(NOLOCK) ON K.NUMINGRES =HC.NUMINGRES AND CONTEO=0 --AND (SELECT COUNT(ID) FROM HCHISPACA WITH(NOLOCK) WHERE NUMINGRES = K.NUMINGRES) = 0 
		LEFT JOIN DOCUMENTO_BLOQUEADO DOC WITH(NOLOCK) ON K.IPCODPACI=DOC.NUMDOCUME AND DOC.NUMDOCUME IS NULL
		LEFT JOIN POBESPECIAL PE WITH(NOLOCK) ON K.IPCODPACI=PE.IPCODPACI
		LEFT JOIN ACOMPANANTES AC WITH(NOLOCK) ON K.IPCODPACI=AC.IPCODPACI
		--WHERE 
		--K.UFUEGRMED IS NULL 
		/* K.IFECHAING > '21/10/2016' VALIDACIÓN PARA MEDILASER DEBIDO QUE SE LE ESTABA MOSTRANDO MUCHOS PACIENTES*/
		--AND K.IFECHAING > @FECHAINICIOCARGUE 
		--AND K.IESTADOIN <> @IESTADOIN_ANULADO 
		--AND K.NUMINGRES NOT IN (SELECT DISTINCT A.NUMINGRES FROM  ADINGRESO AS A WITH(NOLOCK) INNER JOIN AMBORDIMA AS B WITH(NOLOCK) ON B.IPCODPACI = A.IPCODPACI WHERE  CONVERT(VARCHAR(10),CONVERT(DATE,A.IFECHAING,106),103) = CONVERT(VARCHAR(10),CONVERT(DATE,B.FECORDMED,106),103)) 
		--AND (SELECT COUNT(ID) FROM HCHISPACA WITH(NOLOCK) WHERE NUMINGRES = K.NUMINGRES) = 0 
		--AND K.CODCENATE = @CENTROATENCION 
		--AND K.UFUCODIGO = @UFUNCIONAL
		--AND K.NUMINGRES IS NOT NULL 
		--AND K.NUMINGRES NOT IN (SELECT NUMDOCUME FROM DBO.INDOCUMEN WITH(NOLOCK) WHERE CODDOCUME=@ESTADO_3 AND CODUSUARI<>@USUARIO) 

					UNION
	
					SELECT 
					K.IFECHAING AS FECHALLEGADA, K.UFUCODIGO,0 AS TRIORIGEN,	'3 - PACIENTES SIN CLASIFICACIÓN DE TRIAGE' AS ORIGEN,
					K.CODTIPPAC AS TIPO, 0 AS CONSECUTIVO,
					'' AS [DX SINDROMATICO],RTRIM(K.IPCODPACI) AS IDENTIFICACION,RTRIM(F.IPNOMCOMP) AS [NOMBRE PACIENTE], 
					K.IFECHAING AS [FECHA TRIAGE],0 AS MINUTOS,0 AS BARRA,CAST(0 AS BIT) AS CONFIRMADO,CAST(0 AS BIT) AS AUSENTE,K.NUMINGRES AS INGRESO,
					IPFECNACI AS 'FECHA NACIMIENTO' ,CAST('' AS CHAR(50)) AS EDAD,'' AS ESPECIALIDAD
					, CASE WHEN F.IPTIPODOC IN(6,7) THEN 1 ELSE 0 END AS ASMS
					, F.ZONAPARTADA,
					L.RIESGOAGRE,
					PE.POBESPECIAL, --(SELECT COUNT(*) FROM DBO.ADPOBESPEPAC Z WITH(NOLOCK) INNER JOIN ADPOBESPE X WITH(NOLOCK) ON X.ID = Z.IDADPOBESPE WHERE IPCODPACI = F.IPCODPACI AND TIPOPOESPERIES = 1) AS POBESPECIAL,
					K.VIVESOLO,
					AC.ACOMPANANTES,   --(SELECT COUNT(*) FROM ADACOMPAN WITH(NOLOCK) WHERE NUMINGRES = K.NUMINGRES) AS ACOMPANANTES,
					CONVERT(BIT,0) AS RIESGO, RTRIM(F.CODENTIDA) + '-'+ RTRIM(M.NOMENTIDA) AS ENTIDADPACIENTE
					FROM ADINGRESO_ABIERTO K WITH(NOLOCK) LEFT JOIN INGRESO_AMBORDIMA AM WITH(NOLOCK) ON K.NUMINGRES=AM.NUMINGRES AND AM.NUMINGRES IS NULL --AND K.NUMINGRES NOT IN (SELECT DISTINCT A.NUMINGRES FROM  ADINGRESO AS A WITH(NOLOCK) INNER JOIN AMBORDIMA AS B WITH(NOLOCK) ON B.IPCODPACI = A.IPCODPACI WHERE  CONVERT(VARCHAR(10),CONVERT(DATE,A.IFECHAING,106),103) = CONVERT(VARCHAR(10),CONVERT(DATE,B.FECORDMED,106),103)) 
					INNER JOIN DBO.INPACIENT F WITH(NOLOCK) ON K.IPCODPACI=F.IPCODPACI 
					LEFT JOIN DBO.ADACTIVID L WITH(NOLOCK) ON F.CODACTIVI = L.CODACTIVI 
					LEFT JOIN DBO.INENTIDAD M WITH(NOLOCK) ON M.CODENTIDA = F.CODENTIDA
					LEFT JOIN DOCUMENTO_BLOQUEADO DOC WITH(NOLOCK) ON K.IPCODPACI=DOC.NUMDOCUME AND DOC.NUMDOCUME IS NULL
					LEFT JOIN POBESPECIAL PE WITH(NOLOCK) ON K.IPCODPACI=PE.IPCODPACI
					LEFT JOIN ACOMPANANTES AC WITH(NOLOCK) ON K.IPCODPACI=AC.IPCODPACI
					LEFT JOIN HC_HISPACA HC WITH(NOLOCK) ON K.NUMINGRES =HC.NUMINGRES AND CONTEO=0 
					/* K.IFECHAING > '21/10/2016' VALIDACIÓN PARA MEDILASER DEBIDO QUE SE LE ESTABA MOSTRANDO MUCHOS PACIENTES*/
					--WHERE  K.UFUEGRMED IS NULL 
					--AND K.IFECHAING > @FECHAINICIOCARGUE 
					--AND K.IESTADOIN = @IESTADOIN_ABIERTO 
					--AND K.NUMINGRES NOT IN (SELECT DISTINCT A.NUMINGRES FROM  ADINGRESO AS A WITH(NOLOCK) INNER JOIN AMBORDIMA AS B WITH(NOLOCK) ON B.IPCODPACI = A.IPCODPACI WHERE  CONVERT(VARCHAR(10),CONVERT(DATE,A.IFECHAING,106),103) = CONVERT(VARCHAR(10),CONVERT(DATE,B.FECORDMED,106),103))
					--AND (K.REQTRIAGE = 0 OR K.REQTRIAGE IS NULL) 
					--AND (SELECT COUNT(ID) FROM HCHISPACA WITH(NOLOCK) WHERE NUMINGRES = K.NUMINGRES) = 0 
					--AND K.CODCENATE = @CENTROATENCION
					--AND K.UFUCODIGO = @UFUNCIONAL 
					--AND K.NUMINGRES NOT IN (SELECT NUMDOCUME FROM DBO.INDOCUMEN WITH(NOLOCK) WHERE CODDOCUME=@ESTADO_3 AND CODUSUARI<>@USUARIO) 
) 
SELECT * FROM ATENCION_URGENCIAS ORDER BY [FECHA TRIAGE]
END

ELSE BEGIN

; WITH POBESPECIAL
AS
(
SELECT COUNT(*) POBESPECIAL, IPCODPACI FROM DBO.ADPOBESPEPAC Z WITH(NOLOCK) 
INNER JOIN ADPOBESPE X WITH(NOLOCK) ON X.ID = Z.IDADPOBESPE 
WHERE TIPOPOESPERIES = 1
GROUP BY IPCODPACI
)

,ACOMPANANTES
AS
(
SELECT COUNT(*) ACOMPANANTES, NUMINGRES, IPCODPACI FROM ADACOMPAN WITH(NOLOCK) 
GROUP BY NUMINGRES, IPCODPACI
)

, DOCUMENTO_BLOQUEADO
AS
(
SELECT NUMDOCUME FROM DBO.INDOCUMEN WITH(NOLOCK) WHERE CODDOCUME=@ESTADO_3 AND CODUSUARI<>@USUARIO
)

, HC_HISPACA
AS
(
SELECT COUNT(ID) CONTEO, NUMINGRES FROM HCHISPACA WITH(NOLOCK) 
GROUP BY NUMINGRES
)

,CLASIFICADO_CON_INGRESO
AS
(
		SELECT 
			B.UFUCODIGO,A.TRIORIGEN,CASE A.TRIORIGEN WHEN 1  THEN '1 - PACIENTES MEDICINA GENERAL' WHEN 2 THEN '2 - PACIENTES MEDICINA ESPECIALIZADA' END AS ORIGEN,K.CODTIPPAC AS TIPO, TRIANUMER AS CONSECUTIVO,RTRIM(TRIANOMCA) AS [DX SINDROMATICO],RTRIM(B.IPCODPACI) AS IDENTIFICACION,RTRIM(F.IPNOMCOMP) AS [NOMBRE PACIENTE], TRIAFECHA AS [FECHA TRIAGE],0 AS MINUTOS,0 AS BARRA,CASE CAST(TRIAGECLA AS CHAR) WHEN '1' THEN '1 - REANIMACIÓN' WHEN '2' THEN '2 - EMERGENCIA' WHEN '3' THEN '3 - URGENCIA MÉDICA' WHEN '4' THEN '4 - URGENCIA DIFERIDA' WHEN '5' THEN '5 - NO URGENTE' END AS TRIAGE,CAST(0 AS BIT) AS CONFIRMADO,CAST(0 AS BIT) AS AUSENTE,A.NUMINGRES AS INGRESO,IPFECNACI AS 'FECHA NACIMIENTO' ,CAST('' AS CHAR(50)) AS EDAD,RTRIM(G.DESESPECI) AS ESPECIALIDAD
			, CASE WHEN F.IPTIPODOC IN(6,7) THEN 1 ELSE 0 END AS ASMS
			, F.ZONAPARTADA,
			L.RIESGOAGRE,
			PE.POBESPECIAL,--(SELECT COUNT(*) FROM DBO.ADPOBESPEPAC Z WITH(NOLOCK) INNER JOIN ADPOBESPE X WITH(NOLOCK) ON X.ID = Z.IDADPOBESPE WHERE IPCODPACI = F.IPCODPACI AND TIPOPOESPERIES = 1) AS POBESPECIAL,
			K.VIVESOLO,
			AC.ACOMPANANTES,--(SELECT COUNT(*) FROM ADACOMPAN WITH(NOLOCK) WHERE NUMINGRES = K.NUMINGRES) AS ACOMPANANTES,
			CONVERT(BIT,0) AS RIESGO, RTRIM(F.CODENTIDA) + '-'+ RTRIM(M.NOMENTIDA) AS ENTIDADPACIENTE
		FROM 
			DBO.ADTRIAGEU A WITH(NOLOCK) 
			INNER JOIN DBO.ADINGRESO K WITH(NOLOCK) ON A.NUMINGRES = K.NUMINGRES AND A.NUMINGRES IS NOT NULL AND A.CODCENATE = @CENTROATENCION 
            INNER JOIN DBO.ADCONTURG B WITH(NOLOCK) ON A.CODCONCEC=B.CODCONCEC AND B.CONESTADO = @ESTADO_4  
			--INNER JOIN DBO.INPROFSAL D WITH(NOLOCK) ON D.CODPROSAL=A.CODPROSAL 
			INNER JOIN DBO.ADCATTRIU E WITH(NOLOCK) ON E.TRIACATEG=A.TRIACATEG 
			INNER JOIN DBO.INPACIENT F WITH(NOLOCK) ON B.IPCODPACI=F.IPCODPACI 
			LEFT JOIN DBO.INESPECIA G WITH(NOLOCK) ON A.CODESPECI=G.CODESPECI 
			LEFT JOIN DBO.ADACTIVID L WITH(NOLOCK) ON F.CODACTIVI = L.CODACTIVI 
			LEFT JOIN DBO.INENTIDAD M WITH(NOLOCK) ON M.CODENTIDA = F.CODENTIDA 
			LEFT JOIN DOCUMENTO_BLOQUEADO DOC WITH(NOLOCK) ON K.IPCODPACI=DOC.NUMDOCUME AND DOC.NUMDOCUME IS NULL --AND A.NUMINGRES NOT IN (SELECT NUMDOCUME FROM DBO.INDOCUMEN WITH(NOLOCK) WHERE CODDOCUME=@ESTADO_3 AND CODUSUARI<>@USUARIO)  
			LEFT JOIN POBESPECIAL PE WITH(NOLOCK) ON K.IPCODPACI=PE.IPCODPACI
			LEFT JOIN ACOMPANANTES AC WITH(NOLOCK) ON K.IPCODPACI=AC.IPCODPACI
			LEFT JOIN HC_HISPACA HC WITH(NOLOCK) ON K.NUMINGRES =HC.NUMINGRES AND CONTEO=0
		 WHERE B.CONESTADO = @ESTADO_4 
			AND K.UFUCODIGO = @UFUNCIONAL
			--AND A.NUMINGRES NOT IN (SELECT NUMDOCUME FROM DBO.INDOCUMEN WITH(NOLOCK) WHERE CODDOCUME=@ESTADO_3 AND CODUSUARI<>@USUARIO)  
			--ORDER BY TRIAGECLA
 )

SELECT * FROM CLASIFICADO_CON_INGRESO ORDER BY [FECHA TRIAGE]
END

END
GO
-- EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'Procedimiento que carga la lista de trabajo de urgencias o atención prioritaria para un centro de atención y unidad funcional específicos. Consolida en una sola vista operativa todos los pacientes en espera o en atención activa: los que ya tienen clasificación de triage, los que están en proceso de ingreso sin triage aún, y los que ingresaron directamente sin clasificación. Para cada paciente combina datos del ingreso (ADINGRESO), información demográfica del paciente (INPACIENT), categoría de triage (ADCATTRIU), especialidad solicitada, entidad aseguradora, acompañantes registrados (ADACOMPAN), pertenencia a población especial como gestantes o víctimas (ADPOBESPEPAC/ADPOBESPE), riesgo de agresividad, y estado del documento (bloqueado o disponible para edición). Determina si la unidad funcional es de atención prioritaria o de urgencias convencionales consultando el catálogo INUNIFUNC, y filtra ingresos no anulados, sin egreso médico y dentro del rango de fechas válido, excluyendo pacientes cuya historia clínica ya fue iniciada o cuyo documento está siendo editado por otro usuario. Se usa en el módulo de urgencias para que el personal asistencial vea en tiempo real la sala de espera y el estado de cada paciente.', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'SPHC_ATENCIONURGENCIAS_CTE';
-- GO
-- EXECUTE sp_addextendedproperty @name = N'MS_DescriptionSource', @value = N'backport_from_v25.47c_2026-05-05', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'PROCEDURE', @level1name = N'SPHC_ATENCIONURGENCIAS_CTE';
-- GO
-- GO
-- GO
-- EXEC sys.sp_addextendedproperty @name=N'MS_BR_Purpose', @value=N'Lista los pacientes pendientes de atención en una unidad de urgencias o atención prioritaria, combinando triage clasificado, ingresos abiertos sin triage y consultas de urgencia activas, con datos de riesgo y acompañamiento.', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'PROCEDURE', @level1name=N'SPHC_ATENCIONURGENCIAS_CTE';
-- GO
-- EXEC sys.sp_addextendedproperty @name=N'MS_BR_Preconditions', @value=N'La unidad funcional debe existir en INUNIFUNC para determinar si es de atención prioritaria (UFUTIPUNI=31).; El usuario que consulta se utiliza para excluir documentos bloqueados por otros usuarios en INDOCUMEN.; Debe existir relación válida entre ADINGRESO/ADTRIAGEU/ADCONTURG, INPACIENT y catálogos (ADCATTRIU, INENTIDAD, etc.).', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'PROCEDURE', @level1name=N'SPHC_ATENCIONURGENCIAS_CTE';
-- GO
-- EXEC sys.sp_addextendedproperty @name=N'MS_BR_Invariants', @value=N'Solo se consideran ingresos con IFECHAING posterior al 01/01/2021.; Se excluyen ingresos anulados (IESTADOIN = ''A'') y los que ya tienen egreso médico (UFUEGRMED IS NOT NULL) en la rama prioritaria.; En la rama de ingresos abiertos sólo se incluyen los que no requieren triage (REQTRIAGE = 0 o NULL) y están en estado '' ''.; Se descartan pacientes cuyo documento esté bloqueado en INDOCUMEN (CODDOCUME=3) por un usuario distinto al que consulta.; Se descartan ingresos con historia clínica ya registrada en HCHISPACA (CONTEO = 0).; Se descartan ingresos del mismo día que tengan orden médica ambulatoria asociada al paciente (AMBORDIMA).; Los resultados se filtran siempre por el centro de atención y la unidad funcional recibidos.; En la rama no prioritaria sólo se devuelven consultas de urgencia con CONESTADO = 4.; El listado siempre se ordena por FECHA TRIAGE.; El procedimiento es de solo lectura (no realiza INSERT/UPDATE/DELETE).', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'PROCEDURE', @level1name=N'SPHC_ATENCIONURGENCIAS_CTE';
-- GO
-- EXEC sys.sp_addextendedproperty @name=N'MS_BR_DomainConcepts', @value=N'atención prioritaria; urgencias; triage; ingreso hospitalario; paciente; población especial; acompañantes; riesgo de agresividad; zona apartada; especialidad médica; entidad/aseguradora; documento bloqueado; historia clínica; orden médica ambulatoria', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'PROCEDURE', @level1name=N'SPHC_ATENCIONURGENCIAS_CTE';
-- GO
-- EXEC sys.sp_addextendedproperty @name=N'MS_BR_SideEffects', @value=N'[RETURN_RESULT] resultset: Si la unidad es de atención prioritaria (UFUTIPUNI=31) devuelve UNION de pacientes con triage (ADTRIAGEU + ADINGRESO no anulado) y pacientes con ingreso abierto sin requerimiento de triage, ordenado por FECHA TRIAGE.; [RETURN_RESULT] resultset: Si la unidad NO es de atención prioritaria, devuelve sólo pacientes con triage cuyo registro en ADCONTURG tiene CONESTADO=4 y la unidad funcional del ingreso coincide con la consultada.', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'PROCEDURE', @level1name=N'SPHC_ATENCIONURGENCIAS_CTE';
-- GO
-- EXEC sys.sp_addextendedproperty @name=N'MS_BR_Decisions', @value=N'si La unidad funcional consultada tiene UFUTIPUNI = 31 (atención prioritaria) → Devuelve listado combinado (UNION) de pacientes con triage registrado más pacientes con ingreso abierto sin clasificación de triage, filtrados por centro y unidad else Devuelve únicamente pacientes clasificados en triage con ingreso vigente cuya consulta de urgencias (ADCONTURG) tiene CONESTADO = 4; si INPACIENT.IPTIPODOC IN (6,7) → Marca el paciente con ASMS = 1 (indicador de tipo de documento especial, p.ej. extranjero/menor) else ASMS = 0; si ADTRIAGEU.TRIORIGEN = 1 / = 2 → Etiqueta el origen como ''PACIENTES MEDICINA GENERAL'' o ''PACIENTES MEDICINA ESPECIALIZADA'' respectivamente; si Rama prioritaria, segundo bloque del UNION (ingresos abiertos) → Etiqueta el origen como ''3 - PACIENTES SIN CLASIFICACIÓN DE TRIAGE''; si Rama no prioritaria: TRIAGECLA en 1..5 → Traduce el código de triage a su descripción (''REANIMACIÓN'',''EMERGENCIA'',''URGENCIA MÉDICA'',''URGENCIA DIFERIDA'',''NO URGENTE'')', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'PROCEDURE', @level1name=N'SPHC_ATENCIONURGENCIAS_CTE';
-- GO
-- EXEC sys.sp_addextendedproperty @name=N'MS_BR_Consumes', @value=N'dbo.INUNIFUNC; dbo.ADINGRESO; dbo.ADPOBESPEPAC; dbo.ADPOBESPE; dbo.ADACOMPAN; dbo.AMBORDIMA; dbo.HCHISPACA; dbo.INDOCUMEN; dbo.ADTRIAGEU; dbo.ADCATTRIU; dbo.INPACIENT; dbo.INESPECIA; dbo.ADACTIVID; dbo.INENTIDAD; dbo.ADCONTURG', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'PROCEDURE', @level1name=N'SPHC_ATENCIONURGENCIAS_CTE';
-- GO
-- EXEC sys.sp_addextendedproperty @name=N'MS_BR_Source', @value=N'ai_claude-opus-4-7_tier-c_2026-05-06', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'PROCEDURE', @level1name=N'SPHC_ATENCIONURGENCIAS_CTE';
-- GO
