CREATE PROCEDURE [dbo].[SPREP_HC_Generales_DatosReporte]
(
@CodigoPaciente Varchar(25),
@NumeroFolio nChar(10),
@NumeroIngreso Char(10)
)
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

    -- Insert statements for procedure here
          
SELECT
	A.UFUCODIGO AS 'CODIGO UNIDAD FUNCIONAL', A.NUMINGRES AS INGRESO, A.NUMEFOLIO AS 'NUMERO FOLIO', RTRIM(B.nomcenate) + ' - ' + RTRIM(C.UFUDESCRI) AS UBICACION, 
	FECINIATE AS 'FECHA DE ATENCION INICIAL', MOTCONSUL AS 'MOTIVO CONSULTA', ENFACTUAL AS 'ENFERMEDAD ACTUAL', REVSISTEMA AS 'REVISION POR SISTEMAS', ANALISISP AS ANALISIS, dbo.DestinoPaciente(INDICAPAC) AS 'DESTINO DEL PACIENTE', INDICAMED AS 'INDICACIONES MEDICAS', 
	D.CODIGONIT AS 'IDENTIFICACION MEDICO', dbo.CompleteProfessionalDocumentType(D.IDADTIPOIDENTIFICA) AS 'TIPO IDENTIFICACION', D.NOMMEDICO AS 'NOMBRE MEDICO',D.TARJETAPR AS 'TARJETA PROFESIONAL',D.MEDIFIRMA AS 'FIRMA PROFESIONAL', ANTOTRPAC AS 'OTROS ANTECEDENTES',TENARTSIS as SISTOLICA,TENARTDIA as DIASTOLICA,'' as InterpretacionTensionArterial,'' as InterpretacionIMC,RTRIM(CAST(TENARTSIS AS CHAR)) + '/' + RTRIM(CAST(TENARTDIA AS CHAR)) AS 'TENSION ARTERIAL', TEMPERPAC AS TEMPERATURA, FRECARPAC AS 'FRECUENCIA CARDIACA', FRERESPAC AS 'FRECUENCIA RESPIRATORIA', ISNULL(REGSO2PAC,'') AS 'SATURACION DE OXIGENO', TALLAPACI AS 'TALLA PACIENTE', PESOPACIE AS 'PESO PACIENTE', ISNULL(FISOBSPAC,'') AS OBSERVACIONES, CASE ANOCABPAC WHEN 1 THEN 0 WHEN 0 THEN 1 END 'CHECK CABEZA NORMAL',ANOCABPAC AS 'CHECK CABEZA ANOMALIA', DESCABPAC AS 'DESCRIPCION ANOMALIA CABEZA', 
	CASE ANOOJOPAC WHEN 1 THEN 0 WHEN 0 THEN 1 END 'CHECK OJOS NORMAL',ANOOJOPAC AS 'CHECK OJOS ANOMALIA', DESOJOPAC AS 'DESCRIPCION ANOMALIA OJOS', CASE ANOORLPAC WHEN 1 THEN 0 WHEN 0 THEN 1 END 'CHECK ORL NORMAL', ANOORLPAC AS 'CHECK ORL ANOMALIA', DESORLPAC AS 'DESCRIPCION ANOMALIA ORL', CASE ANOCUEPAC WHEN 1 THEN 0 WHEN 0 THEN 1 END 'CHECK CUELLO NORMAL', ANOCUEPAC AS 'CHECK CUELLO ANOMALIA', DESCUEPAC AS 'DESCRIPCION ANOMALIA CUELLO', CASE ANOCAPPAC WHEN 1 THEN 0 WHEN 0 THEN 1 END 'CHECK CARDIOPULMONAR NORMAL', ANOCAPPAC AS 'CHECK CARDIOPULMONAR ANOMALIA', DESCAPPAC AS 'DESCRIPCION ANOMALIA CARDIOPULMONAR', CASE ANOABDPAC WHEN 1 THEN 0 WHEN 0 THEN 1 END 'CHECK ABDOMEN NORMAL', ANOABDPAC AS 'CHECK ABDOMEN ANOMALIA', DESABDPAC AS 'DESCRIPCION ANOMALIA ABDOMEN', 
	CASE ANOGEUOAC WHEN 1 THEN 0 WHEN 0 THEN 1 END 'CHECK GENITOURINARIO NORMAL', ANOGEUOAC AS 'CHECK GENITOURINARIO ANOMALIA', DESGEUOAC AS 'DESCRIPCION ANOMALIA GENITOURINARIO', CASE ANOEXTPAC WHEN 1 THEN 0 WHEN 0 THEN 1 END 'CHECK EXTREMIDADES NORMAL', ANOEXTPAC AS 'CHECK EXTREMIDADES ANOMALIA', DESEXTPAC AS 'DESCRIPCION ANOMALIA EXTREMIDADES', CASE ANONEUPAC WHEN 1 THEN 0 WHEN 0 THEN 1 END 'CHECK NEUROLOGICA NORMAL', ANONEUPAC AS 'CHECK NEUROLOGICA ANOMALIA', DESNEUPAC AS 'DESCRIPCION ANOMALIA NEUROLOGICA', CASE ANOPIELPA WHEN 1 THEN 0 WHEN 0 THEN 1 END 'CHECK PIEL NORMAL',ANOPIELPA AS 'CHECK PIEL ANOMALIA', DESPEILPA AS 'DESCRIPCION ANOMALIA PIEL',
	NEOPERCEF AS 'PERIMETRO CEFALICO', NEOPERTOR AS 'PERIMETRO TORAXICO', NEOPERABD AS 'PERIMETRO ABDOMINAL',CASE SOPVENPAC WHEN 1 THEN 0 WHEN 0 THEN 1 END AS 'CHECK SOPORTE VENTILATORIO NO',SOPVENPAC AS 'CHECK SOPORTE VENTILATORIO SI', SOPVENDES AS 'DESCRIPCION SOPORTE VENTILATORIO',CASE SOPINOPAC WHEN 1 THEN 0 WHEN 0 THEN 1 END AS 'CHECK SOPORTE INOTROPICO NO',SOPINOPAC AS 'CHECK SOPORTE INOTROPICO SI', SOPINODES AS 'DESCRIPCION SOPORTE INOTROPICO', CASE ACCESOPAC WHEN 1 THEN 0 WHEN 0 THEN 1 END AS 'CHECK ACCESO NO', ACCESOPAC AS 'CHECK ACCESO SI', ACCESODES AS 'DESCRIPCION ACCESO', UCIADUPVC AS 'UCI ADULTOS PVC', UCIADUCUN AS 'UCI ADULTOS CUNA', UCIADUPIA AS 'UCI ADULTOS PIA', UCIADUGLU AS 'UCI ADULTOS GLUCOMETRIA', UCIADULRG AS 'UCI ADULTOS RG', UCIADUPIC AS 'UCI ADULTOS PIC', 
	RTRIM(E.DESESPECI) AS 'DESCRIPCION DE LA ESPECIALIDAD',RTRIM(C.UFUDESCRI) AS 'DESCRIPCION UNIDAD FUNCIONAL',PESOPACIE, TALLAPACI, CASE  WHEN TALLAPACI IS NULL THEN 0 WHEN TALLAPACI IS NOT NULL THEN  CASE  WHEN TALLAPACI = 0 THEN 0  WHEN TALLAPACI <> 0 THEN convert(decimal(18,2), (convert(decimal(18,2),PESOPACIE) / 1000) / ((convert(decimal(18,2),TALLAPACI) / 100) * (convert(decimal(18,2),TALLAPACI) / 100))) END  END AS 'INDICE DE MASA CORPORAL',(CAST(TENARTSIS AS DECIMAL) + (CAST(TENARTDIA AS DECIMAL)*2))/3 AS 'TENSION ARTERIAL MEDIA', H.FECFIRFOL AS 'FECHA FIRMA FOLIO' , PESOSEC, case ESTADIO when 1 then '1 - TFG igual o mayor a 90 ml/min' when 2 then '2 - TFG entre 60 y menor de 90 ml/min' when 3 then '3 - TFG entre 30 y menor de 60 ml/min' when 4 then '4 - TFG entre 15 y menor de 30 ml/min' when 5 then '5 - TFG menos de 15 ml/min' when 6 then '99 - Desconocido' END ESTADIO, ACCVASCULAR, ULTRAFILTRA, ULTRAFILTRAV, TIEMPOSESIO, KTV,G.PB as 'PB',g.DOLOR as 'DOLOR', 
	case G.TFG when '988' then '988 - No Aplica. Tiene ERC Estadio 5 y ya no se mide la Creatinina.' when '999' then '999 - No hay reporte de Creatinina ' ELSE TRY_CAST(REPLACE(TFG,',','.')AS varchar) END TFG, 
	G.INTERPESOPARATALLA, G.INTERPESOPARAEDAD, G.INTERPERIMETROCEFA, G.INTERTALLAPARAEDAD, G.INTERINDICEMASACO, concat(CONTROL.NUMCONTRL,' ',case CONTROL.UNICONTRL when 1 then 'Dias' when 2 then 'Meses' END) 'PROXIMO CONTROL', 
	CASE WHEN(PESOPACIE <> 0 AND TALLAPACI <> 0) THEN ( CASE  WHEN DATEDIFF(YEAR, IPFECNACI, FECINIATE) >= 18 THEN Sqrt( ( (CAST(PESOPACIE AS DECIMAL) / 1000) * CAST(TALLAPACI AS DECIMAL)) / 3600) 
	WHEN DATEDIFF(YEAR, IPFECNACI, FECINIATE) < 18 THEN ( CASE	WHEN PESOPACIE < 10000 THEN ( ( ( ( CAST(PESOPACIE AS DECIMAL) / 1000) * 4) + 9) / 100 ) 
	WHEN PESOPACIE >= 10000 THEN ( ( ( ( CAST(PESOPACIE AS DECIMAL) / 1000) * 4) + 7) /  ( ( CAST(PESOPACIE AS DECIMAL) / 1000) + 90) )  END )	END )  END AS 'SUPERFICIE CORPORAL TOTAL' 
FROM dbo.HCURGING1 A With(Nolock)  
	INNER JOIN dbo.ADcenaten B With(Nolock) ON A.CODCENATE = B.codcenate  
	INNER JOIN dbo.INUNIFUNC C With(Nolock) ON A.UFUCODIGO = C.UFUCODIGO  
	INNER JOIN dbo.INPROFSAL D With(Nolock) ON A.CODPROSAL = D.CODPROSAL  
	LEFT OUTER JOIN dbo.INESPECIA E With(Nolock) ON A.CODESPTRA = E.CODESPECI  
	INNER JOIN dbo.INESPECIA ESP With(Nolock) ON D.CODESPEC1 = ESP.CODESPECI  
	LEFT OUTER JOIN dbo.HCANTPACI F With(Nolock) ON A.NUMEFOLIO = F.NUMEFOLIO AND A.IPCODPACI = F.IPCODPACI 
	AND A.NUMINGRES = F.NUMINGRES  
	LEFT OUTER JOIN dbo.HCEXFISIC G With(Nolock) ON A.NUMEFOLIO = G.NUMEFOLIO AND A.IPCODPACI = G.IPCODPACI 
	AND A.NUMINGRES = G.NUMINGRES  
	LEFT OUTER JOIN dbo.HCFIRMFOL H With(Nolock) ON A.IPCODPACI = H.IPCODPACI AND A.NUMEFOLIO = H.NUMEFOLIO  
	LEFT OUTER JOIN dbo.HCDESCOEX CONTROL With(Nolock) ON A.IPCODPACI = CONTROL.IPCODPACI 
	AND A.NUMEFOLIO = CONTROL.NUMEFOLIO 
	LEFT JOIN dbo.ADTIPOIDENTIFICA T WITH(NOLOCK) ON D.IDADTIPOIDENTIFICA = T.ID  
	INNER JOIN  dbo.INPACIENT AS PAC With(Nolock) ON A.IPCODPACI = PAC.IPCODPACI  
WHERE A.IPCODPACI=@CodigoPaciente AND A.NUMINGRES=@NumeroIngreso AND A.NUMEFOLIO=@NumeroFolio

END
GO


