'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel
Imports System.Globalization
Imports System.Runtime.Serialization
Imports System.Runtime.CompilerServices
Imports Domain.Base.Entities

<DataContract(IsReference:=True)>
Partial Public Class Consecutive
    Implements IObjectWithChangeTracker
    Implements INotifyPropertyChanged

	#Region "Aux Property"
 Private _ConsecutiveAux As Consecutive

 <DataMember()>
    Public Property ConsecutiveAux As Consecutive
        Get
            Return Me._ConsecutiveAux
        End Get
        Set(value As Consecutive)
            Me._ConsecutiveAux = value
        End Set
    End Property


#End Region

#Region "Simple Properties"

    <DataMember()>
    Public Property Id() As Integer
        Get
            Return _id
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_id, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'Id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _id = value
                OnPropertyChanged("Id")
            End If
        End Set
    End Property

    Private _id As Integer

    <DataMember()>
    Public Property Code() As Integer
        Get
            Return _code
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_code, value) Then
                ChangeTracker.RecordOriginalValue("Code", _code)
                _code = value
                OnPropertyChanged("Code")
            End If
        End Set
    End Property

    Private _code As Integer

    <DataMember()>
    Public Property Description() As String
        Get
            Return _description
        End Get
        Set(ByVal value As String)
            If Not Equals(_description, value) Then
                ChangeTracker.RecordOriginalValue("Description", _description)
                _description = value
                OnPropertyChanged("Description")
            End If
        End Set
    End Property

    Private _description As String

    <DataMember()>
    Public Property NumberConsecutive() As Decimal
        Get
            Return _numberConsecutive
        End Get
        Set(ByVal value As Decimal)
            If Not Equals(_numberConsecutive, value) Then
                ChangeTracker.RecordOriginalValue("NumberConsecutive", _numberConsecutive)
                _numberConsecutive = value
                OnPropertyChanged("NumberConsecutive")
            End If
        End Set
    End Property

    Private _numberConsecutive As Decimal

#End Region

#Region "ChangeTracking"

    Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
        If ChangeTracker.State <> ObjectState.Added AndAlso ChangeTracker.State <> ObjectState.Deleted Then
            ChangeTracker.State = ObjectState.Modified
        End If
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Protected Overridable Sub OnNavigationPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Private _changeTracker As ObjectChangeTracker

    <DataMember()>
    Public Property ChangeTracker() As ObjectChangeTracker Implements IObjectWithChangeTracker.ChangeTracker
        Get
            If _changeTracker Is Nothing Then
                _changeTracker = New ObjectChangeTracker()
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            Return _changeTracker
        End Get
        Set(ByVal value As ObjectChangeTracker)
            If _changeTracker IsNot Nothing Then
                RemoveHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            _changeTracker = value
            If _changeTracker IsNot Nothing Then
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
        End Set
    End Property

    Private Sub HandleObjectStateChanging(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.ClearNavigationProperties()
        End If
    End Sub

    Private _isDeserializing As Boolean
    Protected Property IsDeserializing() As Boolean
        Get
            Return _isDeserializing
        End Get
        Private Set(ByVal value As Boolean)
            _isDeserializing = value
        End Set
    End Property

    <OnDeserializing()>
    Public Sub OnDeserializingMethod(ByVal context As StreamingContext)
        IsDeserializing = True
    End Sub

    <OnDeserialized()>
    Public Sub OnDeserializedMethod(ByVal context As StreamingContext)
        IsDeserializing = False
        ChangeTracker.ChangeTrackingEnabled = True
    End Sub

    Protected Overridable Sub ClearNavigationProperties()
    End Sub

#End Region

End Class
