//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace Infrastructure.Data.Xpo.InventoryRepository
{

    [Persistent(@"Inventory.Diagnostic")]
    public partial class DiagnosticXpo : XPLiteObject
    {
        int fId;
        [Key(true)]
        public int Id
        {
            get { return fId; }
            set { SetPropertyValue<int>("Id", ref fId, value); }
        }
        string fCode;
        [Size(20)]
        public string Code
        {
            get { return fCode; }
            set { SetPropertyValue<string>("Code", ref fCode, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }

        [PersistentAlias("concat(concat(Code,' - '),Name)")]
        public string CodeName
        {
            get { return Convert.ToString(this.EvaluateAlias("CodeName")); }
        }

        decimal fMinimumAge;
        public decimal MinimumAge
        {
            get { return fMinimumAge; }
            set { SetPropertyValue<decimal>("MinimumAge", ref fMinimumAge, value); }
        }
        byte fMinimumAgeMeasurementUnit;
        public byte MinimumAgeMeasurementUnit
        {
            get { return fMinimumAgeMeasurementUnit; }
            set { SetPropertyValue<byte>("MinimumAgeMeasurementUnit", ref fMinimumAgeMeasurementUnit, value); }
        }
        decimal fMaximumAge;
        public decimal MaximumAge
        {
            get { return fMaximumAge; }
            set { SetPropertyValue<decimal>("MaximumAge", ref fMaximumAge, value); }
        }
        byte fMaximumAgeMeasurementUnit;
        public byte MaximumAgeMeasurementUnit
        {
            get { return fMaximumAgeMeasurementUnit; }
            set { SetPropertyValue<byte>("MaximumAgeMeasurementUnit", ref fMaximumAgeMeasurementUnit, value); }
        }
        bool fAppliesToMale;
        public bool AppliesToMale
        {
            get { return fAppliesToMale; }
            set { SetPropertyValue<bool>("AppliesToMale", ref fAppliesToMale, value); }
        }
        bool fAppliesToFemale;
        public bool AppliesToFemale
        {
            get { return fAppliesToFemale; }
            set { SetPropertyValue<bool>("AppliesToFemale", ref fAppliesToFemale, value); }
        }
        bool fRequiresNotification;
        public bool RequiresNotification
        {
            get { return fRequiresNotification; }
            set { SetPropertyValue<bool>("RequiresNotification", ref fRequiresNotification, value); }
        }
        string fCodeCIE10;
        [Size(4)]
        public string CodeCIE10
        {
            get { return fCodeCIE10; }
            set { SetPropertyValue<string>("CodeCIE10", ref fCodeCIE10, value); }
        }
        bool fNotAllowMainDiagnosis;
        public bool NotAllowMainDiagnosis
        {
            get { return fNotAllowMainDiagnosis; }
            set { SetPropertyValue<bool>("NotAllowMainDiagnosis", ref fNotAllowMainDiagnosis, value); }
        }
        bool fStatus;
        public bool Status
        {
            get { return fStatus; }
            set { SetPropertyValue<bool>("Status", ref fStatus, value); }
        }
        string fCreationUser;
        [Size(20)]
        public string CreationUser
        {
            get { return fCreationUser; }
            set { SetPropertyValue<string>("CreationUser", ref fCreationUser, value); }
        }
        DateTime fCreationDate;
        public DateTime CreationDate
        {
            get { return fCreationDate; }
            set { SetPropertyValue<DateTime>("CreationDate", ref fCreationDate, value); }
        }
        string fModificationUser;
        [Size(20)]
        public string ModificationUser
        {
            get { return fModificationUser; }
            set { SetPropertyValue<string>("ModificationUser", ref fModificationUser, value); }
        }
        DateTime fModificationDate;
        public DateTime ModificationDate
        {
            get { return fModificationDate; }
            set { SetPropertyValue<DateTime>("ModificationDate", ref fModificationDate, value); }
        }
        [Association(@"Inventory_POSPathologiesReferencesInventory_Diagnostic", typeof(POSPathologiesXpo))]
        public XPCollection<POSPathologiesXpo> POSPathologiesXpo { get { return GetCollection<POSPathologiesXpo>("POSPathologiesXpo"); } }
        public DiagnosticXpo(Session session) : base(session) { }
    }

}
