CREATE TABLE [dbo].[oportunidadmedica] (
    [ID_COMPANY]                          VARCHAR (9)     NULL,
    [TIPO AGENDAMIENTO]                   VARCHAR (23)    NULL,
    [CODIGO IPS]                          VARCHAR (13)    NULL,
    [CENTRO ATENCION]                     VARCHAR (100)   NULL,
    [UNIDAD FUNCIONAL]                    VARCHAR (60)    NULL,
    [CODIGO REPS ESPECIALIDAD]            CHAR (5)        NULL,
    [CODIGO ESPECIALIDAD]                 CHAR (3)        NULL,
    [ESPECIALIDAD]                        VARCHAR (60)    NULL,
    [MEDICO]                              VARCHAR (60)    NULL,
    [ACTIVIDAD AGENDAMIENTO]              NVARCHAR (150)  NULL,
    [CONSULTORIO]                         NVARCHAR (100)  NULL,
    [DURACION ACTIVIDAD]                  VARCHAR (14)    NULL,
    [TIPO IDENTIFICACION]                 VARCHAR (2)     NULL,
    [DESCRIPCION IDENTIFICACION]          VARCHAR (31)    NULL,
    [NRO IDENTIFICACION]                  VARCHAR (25)    NOT NULL,
    [ID PACIENTE]                         INT             NOT NULL,
    [FECHA NACIMIENTO]                    DATE            NULL,
    [EDAD]                                INT             NULL,
    [CODIGO SEXO]                         VARCHAR (1)     NULL,
    [SEXO]                                VARCHAR (6)     NULL,
    [PRIMER APELLIDO]                     VARCHAR (20)    NULL,
    [SEGUNDO APELLIDO]                    VARCHAR (20)    NULL,
    [PRIMER NOMBRE]                       VARCHAR (20)    NULL,
    [SEGUNDO NOMBRE]                      VARCHAR (20)    NULL,
    [CORREO]                              VARCHAR (50)    NULL,
    [CODIGO DEPARTAMENTO]                 CHAR (2)        NOT NULL,
    [NOMBRE DEPARTAMENTO RESIDENCIA]      CHAR (40)       NOT NULL,
    [CODIGO MUNICIPIO RESIDENCIA]         CHAR (3)        NOT NULL,
    [NOMBRE MUNICIPIO RESIDENCIA]         CHAR (40)       NOT NULL,
    [DIRECCION]                           VARCHAR (MAX)   NULL,
    [CELULAR]                             VARCHAR (MAX)   NOT NULL,
    [TELEFONO FIJO]                       VARCHAR (MAX)   NOT NULL,
    [FORMA DE SOLICITUD]                  VARCHAR (10)    NULL,
    [TIPO DE CITA]                        VARCHAR (14)    NOT NULL,
    [MODALIDAD]                           VARCHAR (12)    NOT NULL,
    [CODIGO ENTIDAD]                      VARCHAR (9)     NULL,
    [ENTIDAD]                             VARCHAR (300)   NULL,
    [REGIMEN]                             VARCHAR (27)    NULL,
    [GRUPO ATENCION]                      VARCHAR (100)   NULL,
    [ID AGENDA]                           INT             NOT NULL,
    [FECHA DESEADA DE CITA]               VARCHAR (30)    NULL,
    [MEJOR CITA DISPONIBLE]               VARCHAR (30)    NULL,
    [FECHA ASIGNACION DE CITA]            VARCHAR (30)    NULL,
    [FECHA HORA ASIGNACION DE CITA]       VARCHAR (30)    NULL,
    [FECHA FINAL ASIGNACION DE CITA]      VARCHAR (30)    NULL,
    [FECHA HORA FINAL ASIGNACION DE CITA] VARCHAR (30)    NULL,
    [FECHA SOLICITUD DE CITA]             VARCHAR (30)    NULL,
    [FECHA CANCELACION DE CITA]           VARCHAR (30)    NULL,
    [FECHA REGISTRO EN BASE DE DATOS]     VARCHAR (30)    NULL,
    [FECHA ASIGNACION vs FECHA SOLICITUD] INT             NULL,
    [FECHA ASIGNACION vs FECHA DESEADA]   INT             NULL,
    [DISPONIBILIDAD DE AGENDA]            INT             NULL,
    [CITA EXTRA]                          VARCHAR (2)     NOT NULL,
    [CODIGO CUPS]                         VARCHAR (20)    NULL,
    [DESCRIPCION CUPS]                    VARCHAR (300)   NULL,
    [USUARIO QUE REGISTRO LA CITA]        VARCHAR (60)    NULL,
    [ESTADO INICIAL]                      VARCHAR (8)     NOT NULL,
    [ESTADO ACTUAL]                       VARCHAR (11)    NULL,
    [CODIGO CANCELACION]                  VARCHAR (3)     NOT NULL,
    [DESCRIPCION CANCELACION]             NVARCHAR (150)  NOT NULL,
    [NUMERO AUTORIZACION]                 VARCHAR (30)    NULL,
    [INGRESO DE ATENCION]                 CHAR (10)       NOT NULL,
    [CODIGO DEL DIAGNOSTICO]              CHAR (4)        NULL,
    [DIAGNOSTICO]                         CHAR (350)      NULL,
    [CANTIDAD]                            INT             NOT NULL,
    [FECHA BUSQUEDA]                      DATE            NULL,
    [AÑO BUSQUEDA]                        INT             NULL,
    [MES BUSQUEDA]                        INT             NULL,
    [MES NOMBRE BUSQUEDA]                 NVARCHAR (4000) NOT NULL,
    [ULT_ACTUAL]                          DATETIME        NULL
);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Tabla desnormalizada que consolida información de oportunidad en la asignación de citas médicas, registrando datos del paciente (identificación, demografía, contacto y residencia), del prestador (IPS, centro de atención, especialidad, médico, consultorio) y de la agenda (fechas deseada, asignada, cancelada y disponibilidad). Incluye métricas de oportunidad calculadas como la diferencia en días entre fecha de solicitud y asignación, y entre fecha deseada y asignada. Almacena el estado inicial y actual de la cita, entidad aseguradora, régimen y código CUPS, orientada a reporting y seguimiento regulatorio de oportunidad médica.', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'oportunidadmedica';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DescriptionSource', @value=N'ai_claude-sonnet-4-6_2026-05-05', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'oportunidadmedica';
GO
