CREATE TABLE [dbo].[RadioterapiaAplicaciones] (
    [ID_COMPANY]                       VARCHAR (9)     NULL,
    [TIPO IDENTIFICACION]              VARCHAR (2)     NULL,
    [NRO DE IDENTIFICACION]            VARCHAR (25)    NOT NULL,
    [NOMBRE]                           VARCHAR (250)   NULL,
    [FECHA NACIMIENTO]                 DATE            NULL,
    [MUNICIPIO]                        CHAR (40)       NULL,
    [DEPARTAMENTO]                     CHAR (40)       NULL,
    [CODIGO EPS]                       VARCHAR (20)    NOT NULL,
    [NOMBRE EPS]                       VARCHAR (300)   NOT NULL,
    [REGIMEN]                          VARCHAR (27)    NOT NULL,
    [CODIGO GRUPO ATENCION]            VARCHAR (20)    NOT NULL,
    [GRUPO ATENCION]                   VARCHAR (100)   NOT NULL,
    [TIPO LIQUIDACION]                 VARCHAR (29)    NULL,
    [CIUDAD]                           CHAR (40)       NOT NULL,
    [CENTRO ATENCION]                  CHAR (100)      NOT NULL,
    [DIAGNOSTICO]                      VARCHAR (357)   NULL,
    [TIPO DIAGNOSTICO]                 VARCHAR (21)    NULL,
    [FECHA PATOLOGIA]                  DATE            NULL,
    [FECHA ORDENAMIENTO]               DATE            NULL,
    [PROFESIONAL ORDENO]               CHAR (60)       NOT NULL,
    [ESPECIALIDAD]                     CHAR (60)       NULL,
    [ESTADO]                           VARCHAR (95)    NULL,
    [CUPS]                             CHAR (20)       NOT NULL,
    [DESCRIPCION CUPS]                 CHAR (300)      NOT NULL,
    [CANTIDAD]                         INT             NOT NULL,
    [NRO AUTORIZACION]                 CHAR (15)       NULL,
    [FECHA SIMULACION]                 DATE            NULL,
    [FECHA PLANEACION]                 DATE            NULL,
    [PROFESIONAL REALIZA PLANEACION]   CHAR (60)       NULL,
    [FECHA ESQUEMA]                    DATE            NULL,
    [DOSIS TOTAL]                      INT             NOT NULL,
    [DOSIS SESION]                     INT             NOT NULL,
    [NRO SESIONES]                     INT             NOT NULL,
    [NRO SESION]                       BIGINT          NULL,
    [FECHA APLICACION]                 DATE            NULL,
    [OBSERVACION]                      VARCHAR (MAX)   NULL,
    [PROFESIONAL APLICO]               CHAR (60)       NOT NULL,
    [CENTRO ATENCION APLICO]           CHAR (100)      NOT NULL,
    [PROFESIONAL APLICO PRIMERA DOSIS] CHAR (60)       NULL,
    [CENTRO ATENCION PRIMER DOSIS]     CHAR (100)      NOT NULL,
    [DOSIS TURNO UNO]                  DECIMAL (18, 2) NULL,
    [DOSIS TURNO DOS]                  DECIMAL (18, 2) NULL,
    [DOSIS TURNO TRES]                 DECIMAL (18, 2) NULL,
    [DOSIS TURNO CUATRO]               DECIMAL (18, 2) NULL,
    [DOSIS TURNO CINCO]                DECIMAL (18, 2) NULL,
    [DOSIS TURNO SEIS]                 DECIMAL (18, 2) NULL,
    [TOTAL DOSIS SESION]               DECIMAL (18, 2) NULL,
    [INGRESO]                          CHAR (10)       NOT NULL,
    [FECHA BUSQUEDA]                   DATE            NULL,
    [ULT_ACTUAL]                       DATETIME        NULL
);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Tabla que registra las aplicaciones de radioterapia realizadas a pacientes, almacenando datos demográficos, de aseguramiento (EPS, régimen) y del proceso clínico completo: desde el diagnóstico, ordenamiento y planeación hasta la ejecución de cada sesión. Captura el esquema de dosificación (dosis total, por sesión y por turno en hasta seis turnos), el número de sesión aplicada, los profesionales intervinientes y los centros de atención, junto con códigos CUPS y número de autorización.', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'RadioterapiaAplicaciones';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DescriptionSource', @value=N'ai_claude-sonnet-4-6_2026-05-05', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'RadioterapiaAplicaciones';
GO
