'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel
Imports System.Globalization
Imports System.IO
Imports System.Reflection
Imports System.Runtime.Serialization.Formatters.Binary
Imports System.Runtime.Serialization
Imports System.Runtime.CompilerServices
Imports Domain.Base.Entities
Imports System.Data.Entity.ModelConfiguration

<DataContract(IsReference:=True), Serializable(), KnownType(GetType(Address))>
<KnownType(GetType(City))>
<KnownType(GetType(Department))>
<KnownType(GetType(Person))>
<KnownType(GetType(BasicBilling))>
Partial Public Class Address
	Inherits Entity(Of Address)
    Implements IObjectWithChangeTracker
    Implements INotifyPropertyChanged

#Region "Simple Properties"

	Private _id As Integer
	<DataMember()>
	Public Property Id() As Integer
        Get
            Return _id
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_id, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'Id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _id = value
                OnPropertyChanged("Id")
            End If
        End Set
    End Property

	Private _idPerson As Integer
	<DataMember()>
	Public Property IdPerson() As Integer
        Get
            Return _idPerson
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_idPerson, value) Then
                ChangeTracker.RecordOriginalValue("IdPerson", _idPerson)
                If Not IsDeserializing Then
                    If Person IsNot Nothing AndAlso Not Equals(Person.Id, value) Then
                        Person = Nothing
                    End If
                End If
                _idPerson = value
                OnPropertyChanged("IdPerson")
            End If
        End Set
    End Property

	Private _addresss As String
	<DataMember()>
	Public Property Addresss() As String
        Get
            Return _addresss
        End Get
        Set(ByVal value As String)
            If Not Equals(_addresss, value) Then
                _addresss = value
                OnPropertyChanged("Addresss")
            End If
        End Set
    End Property

	Private _state As Boolean
	<DataMember()>
	Public Property State() As Boolean
        Get
            Return _state
        End Get
        Set(ByVal value As Boolean)
            If Not Equals(_state, value) Then
                _state = value
                OnPropertyChanged("State")
            End If
        End Set
    End Property

	Private _synchronized As String
	<DataMember()>
	Public Property Synchronized() As String
        Get
            Return _synchronized
        End Get
        Set(ByVal value As String)
            If Not Equals(_synchronized, value) Then
                _synchronized = value
                OnPropertyChanged("Synchronized")
            End If
        End Set
    End Property

	Private _departmentId As Nullable(Of Integer)
	<DataMember()>
	Public Property DepartmentId() As Nullable(Of Integer)
        Get
            Return _departmentId
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_departmentId, value) Then
                ChangeTracker.RecordOriginalValue("DepartmentId", _departmentId)
                If Not IsDeserializing Then
                    If Department IsNot Nothing AndAlso Not Equals(Department.Id, value) Then
                        Department = Nothing
                    End If
                End If
                _departmentId = value
                OnPropertyChanged("DepartmentId")
            End If
        End Set
    End Property

	Private _cityId As Nullable(Of Integer)
	<DataMember()>
	Public Property CityId() As Nullable(Of Integer)
        Get
            Return _cityId
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_cityId, value) Then
                ChangeTracker.RecordOriginalValue("CityId", _cityId)
                If Not IsDeserializing Then
                    If City IsNot Nothing AndAlso Not Equals(City.Id, value) Then
                        City = Nothing
                    End If
                End If
                _cityId = value
                OnPropertyChanged("CityId")
            End If
        End Set
    End Property

#End Region

#Region "Navigation Properties"

    <DataMember()>
    Public Property City() As City
        Get
            Return _city
        End Get
        Set(ByVal value As City)
            If _city IsNot value Then
                Dim previousValue As City = _city
                _city = value
                FixupCity(previousValue)
                OnNavigationPropertyChanged("City")
            End If
        End Set
    End Property

    Private _city As City


    <DataMember()>
    Public Property Department() As Department
        Get
            Return _department
        End Get
        Set(ByVal value As Department)
            If _department IsNot value Then
                Dim previousValue As Department = _department
                _department = value
                FixupDepartment(previousValue)
                OnNavigationPropertyChanged("Department")
            End If
        End Set
    End Property

    Private _department As Department


    <DataMember()>
    Public Property Person() As Person
        Get
            Return _person
        End Get
        Set(ByVal value As Person)
            If _person IsNot value Then
                Dim previousValue As Person = _person
                _person = value
                FixupPerson(previousValue)
                OnNavigationPropertyChanged("Person")
            End If
        End Set
    End Property

    Private _person As Person


    <DataMember()>
	Public Property BasicBilling() As TrackableCollection(Of BasicBilling)
		Get
            If _basicBilling Is Nothing Then
                _basicBilling = New TrackableCollection(Of BasicBilling)
                AddHandler _basicBilling.CollectionChanged, AddressOf FixupBasicBilling
            End If
            Return _basicBilling
        End Get
        Set(ByVal value As TrackableCollection(Of BasicBilling))
            If _basicBilling IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _basicBilling IsNot Nothing Then
                    RemoveHandler _basicBilling.CollectionChanged, AddressOf FixupBasicBilling
                End If
                _basicBilling = value
                If _basicBilling IsNot Nothing Then
                    AddHandler _basicBilling.CollectionChanged, AddressOf FixupBasicBilling
                End If
                OnNavigationPropertyChanged("BasicBilling")
            End If
        End Set
    End Property

    Private _basicBilling As TrackableCollection(Of BasicBilling)

#End Region

#Region "ChangeTracking"

    Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
        If ChangeTracker.State <> ObjectState.Added AndAlso ChangeTracker.State <> ObjectState.Deleted Then
            ChangeTracker.State = ObjectState.Modified
        End If
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Protected Overridable Sub OnNavigationPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Private _changeTracker As ObjectChangeTracker

    <DataMember()>
    Public Property ChangeTracker() As ObjectChangeTracker Implements IObjectWithChangeTracker.ChangeTracker
        Get
            If _changeTracker Is Nothing Then
                _changeTracker = New ObjectChangeTracker()
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            Return _changeTracker
        End Get
        Set(ByVal value As ObjectChangeTracker)
            If _changeTracker IsNot Nothing Then
                RemoveHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            _changeTracker = value
            If _changeTracker IsNot Nothing Then
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
        End Set
    End Property

    Private Sub HandleObjectStateChanging(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.ClearNavigationProperties()
        End If
    End Sub

    Private _isDeserializing As Boolean
    Protected Property IsDeserializing() As Boolean
        Get
            Return _isDeserializing
        End Get
        Private Set(ByVal value As Boolean)
            _isDeserializing = value
        End Set
    End Property

    <OnDeserializing()>
    Public Sub OnDeserializingMethod(ByVal context As StreamingContext)
        IsDeserializing = True
    End Sub

    <OnDeserialized()>
    Public Sub OnDeserializedMethod(ByVal context As StreamingContext)
        IsDeserializing = False
        ChangeTracker.ChangeTrackingEnabled = True
    End Sub

    Protected Overridable Sub ClearNavigationProperties()
        City = Nothing
        Department = Nothing
        Person = Nothing
        BasicBilling.Clear()
    End Sub

#End Region

#Region "Association Fixup"

    Private Sub FixupCity(ByVal previousValue As City, Optional ByVal skipKeys As Boolean = False)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.Address.Contains(Me) Then
            previousValue.Address.Remove(Me)
        End If

        If City IsNot Nothing Then
            City.Address.Add(Me)

            CityId = City.Id
        ElseIf Not skipKeys Then
            CityId = Nothing
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("City") AndAlso
                ChangeTracker.OriginalValues("City") Is City Then
                ChangeTracker.OriginalValues.Remove("City")
            Else
                ChangeTracker.RecordOriginalValue("City", previousValue)
            End If
            If City IsNot Nothing AndAlso Not City.ChangeTracker.ChangeTrackingEnabled Then
                City.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupDepartment(ByVal previousValue As Department, Optional ByVal skipKeys As Boolean = False)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.Address.Contains(Me) Then
            previousValue.Address.Remove(Me)
        End If

        If Department IsNot Nothing Then
            Department.Address.Add(Me)

            DepartmentId = Department.Id
        ElseIf Not skipKeys Then
            DepartmentId = Nothing
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("Department") AndAlso
                ChangeTracker.OriginalValues("Department") Is Department Then
                ChangeTracker.OriginalValues.Remove("Department")
            Else
                ChangeTracker.RecordOriginalValue("Department", previousValue)
            End If
            If Department IsNot Nothing AndAlso Not Department.ChangeTracker.ChangeTrackingEnabled Then
                Department.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupPerson(ByVal previousValue As Person)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.Address.Contains(Me) Then
            previousValue.Address.Remove(Me)
        End If

        If Person IsNot Nothing Then
            Person.Address.Add(Me)

            IdPerson = Person.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("Person") AndAlso
                ChangeTracker.OriginalValues("Person") Is Person Then
                ChangeTracker.OriginalValues.Remove("Person")
            Else
                ChangeTracker.RecordOriginalValue("Person", previousValue)
            End If
            If Person IsNot Nothing AndAlso Not Person.ChangeTracker.ChangeTrackingEnabled Then
                Person.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupBasicBilling(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As BasicBilling In e.NewItems
                item.Address = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("BasicBilling", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As BasicBilling In e.OldItems
                If item.Address Is Me Then
                    item.Address = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("BasicBilling", item)
                End If
            Next
        End If
    End Sub

#End Region

End Class

