'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel
Imports System.Globalization
Imports System.IO
Imports System.Reflection
Imports System.Runtime.Serialization.Formatters.Binary
Imports System.Runtime.Serialization
Imports System.Runtime.CompilerServices
Imports Domain.Base.Entities
Imports System.Data.Entity.ModelConfiguration

<DataContract(IsReference:=True), Serializable(), KnownType(GetType(AuthorizationSchedule))>
<KnownType(GetType(AuthorizationScheduleTemplate))>
<KnownType(GetType(AuthorizationScheduleDetail))>
Partial Public Class AuthorizationSchedule
	Inherits Entity(Of AuthorizationSchedule)
    Implements IObjectWithChangeTracker
    Implements INotifyPropertyChanged

#Region "Simple Properties"

	Private _id As Integer
	<DataMember()>
	Public Property Id() As Integer
        Get
            Return _id
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_id, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'Id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _id = value
                OnPropertyChanged("Id")
            End If
        End Set
    End Property

	Private _authorizationScheduleTemplateId As Integer
	<DataMember()>
	Public Property AuthorizationScheduleTemplateId() As Integer
        Get
            Return _authorizationScheduleTemplateId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_authorizationScheduleTemplateId, value) Then
                ChangeTracker.RecordOriginalValue("AuthorizationScheduleTemplateId", _authorizationScheduleTemplateId)
                If Not IsDeserializing Then
                    If AuthorizationScheduleTemplate IsNot Nothing AndAlso Not Equals(AuthorizationScheduleTemplate.Id, value) Then
                        AuthorizationScheduleTemplate = Nothing
                    End If
                End If
                _authorizationScheduleTemplateId = value
                OnPropertyChanged("AuthorizationScheduleTemplateId")
            End If
        End Set
    End Property

	Private _month As Integer
	<DataMember()>
	Public Property Month() As Integer
        Get
            Return _month
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_month, value) Then
                _month = value
                OnPropertyChanged("Month")
            End If
        End Set
    End Property

	Private _year As Integer
	<DataMember()>
	Public Property Year() As Integer
        Get
            Return _year
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_year, value) Then
                _year = value
                OnPropertyChanged("Year")
            End If
        End Set
    End Property

	Private _userId As Integer
	<DataMember()>
	Public Property UserId() As Integer
        Get
            Return _userId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_userId, value) Then
                _userId = value
                OnPropertyChanged("UserId")
            End If
        End Set
    End Property

	Private _userCode As String
	<DataMember()>
	Public Property UserCode() As String
        Get
            Return _userCode
        End Get
        Set(ByVal value As String)
            If Not Equals(_userCode, value) Then
                _userCode = value
                OnPropertyChanged("UserCode")
            End If
        End Set
    End Property

	Private _status As Boolean
	<DataMember()>
	Public Property Status() As Boolean
        Get
            Return _status
        End Get
        Set(ByVal value As Boolean)
            If Not Equals(_status, value) Then
                _status = value
                OnPropertyChanged("Status")
            End If
        End Set
    End Property

#End Region

#Region "Navigation Properties"

    <DataMember()>
    Public Property AuthorizationScheduleTemplate() As AuthorizationScheduleTemplate
        Get
            Return _authorizationScheduleTemplate
        End Get
        Set(ByVal value As AuthorizationScheduleTemplate)
            If _authorizationScheduleTemplate IsNot value Then
                Dim previousValue As AuthorizationScheduleTemplate = _authorizationScheduleTemplate
                _authorizationScheduleTemplate = value
                FixupAuthorizationScheduleTemplate(previousValue)
                OnNavigationPropertyChanged("AuthorizationScheduleTemplate")
            End If
        End Set
    End Property

    Private _authorizationScheduleTemplate As AuthorizationScheduleTemplate


    <DataMember()>
	Public Property AuthorizationScheduleDetail() As TrackableCollection(Of AuthorizationScheduleDetail)
		Get
            If _authorizationScheduleDetail Is Nothing Then
                _authorizationScheduleDetail = New TrackableCollection(Of AuthorizationScheduleDetail)
                AddHandler _authorizationScheduleDetail.CollectionChanged, AddressOf FixupAuthorizationScheduleDetail
            End If
            Return _authorizationScheduleDetail
        End Get
        Set(ByVal value As TrackableCollection(Of AuthorizationScheduleDetail))
            If _authorizationScheduleDetail IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _authorizationScheduleDetail IsNot Nothing Then
                    RemoveHandler _authorizationScheduleDetail.CollectionChanged, AddressOf FixupAuthorizationScheduleDetail
                End If
                _authorizationScheduleDetail = value
                If _authorizationScheduleDetail IsNot Nothing Then
                    AddHandler _authorizationScheduleDetail.CollectionChanged, AddressOf FixupAuthorizationScheduleDetail
                End If
                OnNavigationPropertyChanged("AuthorizationScheduleDetail")
            End If
        End Set
    End Property

    Private _authorizationScheduleDetail As TrackableCollection(Of AuthorizationScheduleDetail)

#End Region

#Region "ChangeTracking"

    Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
        If ChangeTracker.State <> ObjectState.Added AndAlso ChangeTracker.State <> ObjectState.Deleted Then
            ChangeTracker.State = ObjectState.Modified
        End If
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Protected Overridable Sub OnNavigationPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Private _changeTracker As ObjectChangeTracker

    <DataMember()>
    Public Property ChangeTracker() As ObjectChangeTracker Implements IObjectWithChangeTracker.ChangeTracker
        Get
            If _changeTracker Is Nothing Then
                _changeTracker = New ObjectChangeTracker()
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            Return _changeTracker
        End Get
        Set(ByVal value As ObjectChangeTracker)
            If _changeTracker IsNot Nothing Then
                RemoveHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            _changeTracker = value
            If _changeTracker IsNot Nothing Then
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
        End Set
    End Property

    Private Sub HandleObjectStateChanging(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.ClearNavigationProperties()
        End If
    End Sub

    Private _isDeserializing As Boolean
    Protected Property IsDeserializing() As Boolean
        Get
            Return _isDeserializing
        End Get
        Private Set(ByVal value As Boolean)
            _isDeserializing = value
        End Set
    End Property

    <OnDeserializing()>
    Public Sub OnDeserializingMethod(ByVal context As StreamingContext)
        IsDeserializing = True
    End Sub

    <OnDeserialized()>
    Public Sub OnDeserializedMethod(ByVal context As StreamingContext)
        IsDeserializing = False
        ChangeTracker.ChangeTrackingEnabled = True
    End Sub

    Protected Overridable Sub ClearNavigationProperties()
        AuthorizationScheduleTemplate = Nothing
        AuthorizationScheduleDetail.Clear()
    End Sub

#End Region

#Region "Association Fixup"

    Private Sub FixupAuthorizationScheduleTemplate(ByVal previousValue As AuthorizationScheduleTemplate)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.AuthorizationSchedule.Contains(Me) Then
            previousValue.AuthorizationSchedule.Remove(Me)
        End If

        If AuthorizationScheduleTemplate IsNot Nothing Then
            AuthorizationScheduleTemplate.AuthorizationSchedule.Add(Me)

            AuthorizationScheduleTemplateId = AuthorizationScheduleTemplate.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("AuthorizationScheduleTemplate") AndAlso
                ChangeTracker.OriginalValues("AuthorizationScheduleTemplate") Is AuthorizationScheduleTemplate Then
                ChangeTracker.OriginalValues.Remove("AuthorizationScheduleTemplate")
            Else
                ChangeTracker.RecordOriginalValue("AuthorizationScheduleTemplate", previousValue)
            End If
            If AuthorizationScheduleTemplate IsNot Nothing AndAlso Not AuthorizationScheduleTemplate.ChangeTracker.ChangeTrackingEnabled Then
                AuthorizationScheduleTemplate.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupAuthorizationScheduleDetail(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As AuthorizationScheduleDetail In e.NewItems
                item.AuthorizationSchedule = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("AuthorizationScheduleDetail", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As AuthorizationScheduleDetail In e.OldItems
                If item.AuthorizationSchedule Is Me Then
                    item.AuthorizationSchedule = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("AuthorizationScheduleDetail", item)
                End If
            Next
        End If
    End Sub

#End Region

End Class

