'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel
Imports System.Globalization
Imports System.IO
Imports System.Reflection
Imports System.Runtime.Serialization.Formatters.Binary
Imports System.Runtime.Serialization
Imports System.Runtime.CompilerServices
Imports Domain.Base.Entities
Imports System.Data.Entity.ModelConfiguration

<DataContract(IsReference:=True), Serializable(), KnownType(GetType(CashReceiptAccountReceivableShare))>
<KnownType(GetType(CashReceiptAccountReceivable))>
<KnownType(GetType(AccountReceivableShare))>
Partial Public Class CashReceiptAccountReceivableShare
	Inherits Entity(Of CashReceiptAccountReceivableShare)
    Implements IObjectWithChangeTracker
    Implements INotifyPropertyChanged

#Region "Simple Properties"

	Private _id As Integer
	<DataMember()>
	Public Property Id() As Integer
        Get
            Return _id
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_id, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'Id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _id = value
                OnPropertyChanged("Id")
            End If
        End Set
    End Property

	Private _cashReceiptAccountReceivableId As Integer
	<DataMember()>
	Public Property CashReceiptAccountReceivableId() As Integer
        Get
            Return _cashReceiptAccountReceivableId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_cashReceiptAccountReceivableId, value) Then
                ChangeTracker.RecordOriginalValue("CashReceiptAccountReceivableId", _cashReceiptAccountReceivableId)
                If Not IsDeserializing Then
                    If CashReceiptAccountReceivable IsNot Nothing AndAlso Not Equals(CashReceiptAccountReceivable.Id, value) Then
                        CashReceiptAccountReceivable = Nothing
                    End If
                End If
                _cashReceiptAccountReceivableId = value
                OnPropertyChanged("CashReceiptAccountReceivableId")
            End If
        End Set
    End Property

	Private _accountReceivableShareId As Integer
	<DataMember()>
	Public Property AccountReceivableShareId() As Integer
        Get
            Return _accountReceivableShareId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_accountReceivableShareId, value) Then
                ChangeTracker.RecordOriginalValue("AccountReceivableShareId", _accountReceivableShareId)
                If Not IsDeserializing Then
                    If AccountReceivableShare IsNot Nothing AndAlso Not Equals(AccountReceivableShare.Id, value) Then
                        AccountReceivableShare = Nothing
                    End If
                End If
                _accountReceivableShareId = value
                OnPropertyChanged("AccountReceivableShareId")
            End If
        End Set
    End Property

	Private _value As Decimal
	<DataMember()>
	Public Property Value() As Decimal
        Get
            Return _value
        End Get
        Set(ByVal value As Decimal)
            If Not Equals(_value, value) Then
                _value = value
                OnPropertyChanged("Value")
            End If
        End Set
    End Property

#End Region

#Region "Navigation Properties"

    <DataMember()>
    Public Property CashReceiptAccountReceivable() As CashReceiptAccountReceivable
        Get
            Return _cashReceiptAccountReceivable
        End Get
        Set(ByVal value As CashReceiptAccountReceivable)
            If _cashReceiptAccountReceivable IsNot value Then
                Dim previousValue As CashReceiptAccountReceivable = _cashReceiptAccountReceivable
                _cashReceiptAccountReceivable = value
                FixupCashReceiptAccountReceivable(previousValue)
                OnNavigationPropertyChanged("CashReceiptAccountReceivable")
            End If
        End Set
    End Property

    Private _cashReceiptAccountReceivable As CashReceiptAccountReceivable


    <DataMember()>
    Public Property AccountReceivableShare() As AccountReceivableShare
        Get
            Return _accountReceivableShare
        End Get
        Set(ByVal value As AccountReceivableShare)
            If _accountReceivableShare IsNot value Then
                Dim previousValue As AccountReceivableShare = _accountReceivableShare
                _accountReceivableShare = value
                FixupAccountReceivableShare(previousValue)
                OnNavigationPropertyChanged("AccountReceivableShare")
            End If
        End Set
    End Property

    Private _accountReceivableShare As AccountReceivableShare


#End Region

#Region "ChangeTracking"

    Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
        If ChangeTracker.State <> ObjectState.Added AndAlso ChangeTracker.State <> ObjectState.Deleted Then
            ChangeTracker.State = ObjectState.Modified
        End If
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Protected Overridable Sub OnNavigationPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Private _changeTracker As ObjectChangeTracker

    <DataMember()>
    Public Property ChangeTracker() As ObjectChangeTracker Implements IObjectWithChangeTracker.ChangeTracker
        Get
            If _changeTracker Is Nothing Then
                _changeTracker = New ObjectChangeTracker()
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            Return _changeTracker
        End Get
        Set(ByVal value As ObjectChangeTracker)
            If _changeTracker IsNot Nothing Then
                RemoveHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            _changeTracker = value
            If _changeTracker IsNot Nothing Then
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
        End Set
    End Property

    Private Sub HandleObjectStateChanging(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.ClearNavigationProperties()
        End If
    End Sub

    Private _isDeserializing As Boolean
    Protected Property IsDeserializing() As Boolean
        Get
            Return _isDeserializing
        End Get
        Private Set(ByVal value As Boolean)
            _isDeserializing = value
        End Set
    End Property

    <OnDeserializing()>
    Public Sub OnDeserializingMethod(ByVal context As StreamingContext)
        IsDeserializing = True
    End Sub

    <OnDeserialized()>
    Public Sub OnDeserializedMethod(ByVal context As StreamingContext)
        IsDeserializing = False
        ChangeTracker.ChangeTrackingEnabled = True
    End Sub

    Protected Overridable Sub ClearNavigationProperties()
        CashReceiptAccountReceivable = Nothing
        AccountReceivableShare = Nothing
    End Sub

#End Region

#Region "Association Fixup"

    Private Sub FixupCashReceiptAccountReceivable(ByVal previousValue As CashReceiptAccountReceivable)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.CashReceiptAccountReceivableShare.Contains(Me) Then
            previousValue.CashReceiptAccountReceivableShare.Remove(Me)
        End If

        If CashReceiptAccountReceivable IsNot Nothing Then
            CashReceiptAccountReceivable.CashReceiptAccountReceivableShare.Add(Me)

            CashReceiptAccountReceivableId = CashReceiptAccountReceivable.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("CashReceiptAccountReceivable") AndAlso
                ChangeTracker.OriginalValues("CashReceiptAccountReceivable") Is CashReceiptAccountReceivable Then
                ChangeTracker.OriginalValues.Remove("CashReceiptAccountReceivable")
            Else
                ChangeTracker.RecordOriginalValue("CashReceiptAccountReceivable", previousValue)
            End If
            If CashReceiptAccountReceivable IsNot Nothing AndAlso Not CashReceiptAccountReceivable.ChangeTracker.ChangeTrackingEnabled Then
                CashReceiptAccountReceivable.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupAccountReceivableShare(ByVal previousValue As AccountReceivableShare)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.CashReceiptAccountReceivableShare.Contains(Me) Then
            previousValue.CashReceiptAccountReceivableShare.Remove(Me)
        End If

        If AccountReceivableShare IsNot Nothing Then
            AccountReceivableShare.CashReceiptAccountReceivableShare.Add(Me)

            AccountReceivableShareId = AccountReceivableShare.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("AccountReceivableShare") AndAlso
                ChangeTracker.OriginalValues("AccountReceivableShare") Is AccountReceivableShare Then
                ChangeTracker.OriginalValues.Remove("AccountReceivableShare")
            Else
                ChangeTracker.RecordOriginalValue("AccountReceivableShare", previousValue)
            End If
            If AccountReceivableShare IsNot Nothing AndAlso Not AccountReceivableShare.ChangeTracker.ChangeTrackingEnabled Then
                AccountReceivableShare.StartTracking()
            End If
        End If
    End Sub

#End Region

End Class

