'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel
Imports System.Globalization
Imports System.IO
Imports System.Reflection
Imports System.Runtime.Serialization.Formatters.Binary
Imports System.Runtime.Serialization
Imports System.Runtime.CompilerServices
Imports Domain.Base.Entities
Imports System.Data.Entity.ModelConfiguration

<DataContract(IsReference:=True), Serializable(), KnownType(GetType(City))>
<KnownType(GetType(Department))>
<KnownType(GetType(RetentionConcepts))>
<KnownType(GetType(EntityBankAccounts))>
<KnownType(GetType(HealthProvider))>
<KnownType(GetType(FixedAssetInsurance))>
<KnownType(GetType(FixedAssetLocation))>
<KnownType(GetType(OperatingUnit))>
<KnownType(GetType(PersonStudy))>
<KnownType(GetType(BranchOffice))>
<KnownType(GetType(Supplier))>
<KnownType(GetType(Address))>
<KnownType(GetType(RetentionConceptByCity))>
<KnownType(GetType(Person))>
Partial Public Class City
	Inherits Entity(Of City)
    Implements IObjectWithChangeTracker
    Implements INotifyPropertyChanged

#Region "Simple Properties"

	Private _id As Integer
	<DataMember()>
	Public Property Id() As Integer
        Get
            Return _id
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_id, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'Id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _id = value
                OnPropertyChanged("Id")
            End If
        End Set
    End Property

	Private _departamentId As Integer
	<DataMember()>
	Public Property DepartamentId() As Integer
        Get
            Return _departamentId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_departamentId, value) Then
                ChangeTracker.RecordOriginalValue("DepartamentId", _departamentId)
                If Not IsDeserializing Then
                    If Department IsNot Nothing AndAlso Not Equals(Department.Id, value) Then
                        Department = Nothing
                    End If
                End If
                _departamentId = value
                OnPropertyChanged("DepartamentId")
            End If
        End Set
    End Property

	Private _code As String
	<DataMember()>
	Public Property Code() As String
        Get
            Return _code
        End Get
        Set(ByVal value As String)
            If Not Equals(_code, value) Then
                _code = value
                OnPropertyChanged("Code")
            End If
        End Set
    End Property

	Private _name As String
	<DataMember()>
	Public Property Name() As String
        Get
            Return _name
        End Get
        Set(ByVal value As String)
            If Not Equals(_name, value) Then
                _name = value
                OnPropertyChanged("Name")
            End If
        End Set
    End Property

	Private _iCARetentionConceptId As Nullable(Of Integer)
	<DataMember()>
	Public Property ICARetentionConceptId() As Nullable(Of Integer)
        Get
            Return _iCARetentionConceptId
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_iCARetentionConceptId, value) Then
                ChangeTracker.RecordOriginalValue("ICARetentionConceptId", _iCARetentionConceptId)
                If Not IsDeserializing Then
                    If RetentionConcepts IsNot Nothing AndAlso Not Equals(RetentionConcepts.Id, value) Then
                        RetentionConcepts = Nothing
                    End If
                End If
                _iCARetentionConceptId = value
                OnPropertyChanged("ICARetentionConceptId")
            End If
        End Set
    End Property

	Private _state As Boolean
	<DataMember()>
	Public Property State() As Boolean
        Get
            Return _state
        End Get
        Set(ByVal value As Boolean)
            If Not Equals(_state, value) Then
                _state = value
                OnPropertyChanged("State")
            End If
        End Set
    End Property

	Private _creationUser As String
	<DataMember()>
	Public Property CreationUser() As String
        Get
            Return _creationUser
        End Get
        Set(ByVal value As String)
            If Not Equals(_creationUser, value) Then
                _creationUser = value
                OnPropertyChanged("CreationUser")
            End If
        End Set
    End Property

	Private _creationDate As Date
	<DataMember()>
	Public Property CreationDate() As Date
        Get
            Return _creationDate
        End Get
        Set(ByVal value As Date)
            If Not Equals(_creationDate, value) Then
                _creationDate = value
                OnPropertyChanged("CreationDate")
            End If
        End Set
    End Property

	Private _modificationUser As String
	<DataMember()>
	Public Property ModificationUser() As String
        Get
            Return _modificationUser
        End Get
        Set(ByVal value As String)
            If Not Equals(_modificationUser, value) Then
                _modificationUser = value
                OnPropertyChanged("ModificationUser")
            End If
        End Set
    End Property

	Private _modificationDate As Nullable(Of Date)
	<DataMember()>
	Public Property ModificationDate() As Nullable(Of Date)
        Get
            Return _modificationDate
        End Get
        Set(ByVal value As Nullable(Of Date))
            If Not Equals(_modificationDate, value) Then
                _modificationDate = value
                OnPropertyChanged("ModificationDate")
            End If
        End Set
    End Property

	Private _timeStamp As Byte()
	<DataMember()>
	Public Property TimeStamp() As Byte()
        Get
            Return _timeStamp
        End Get
        Set(ByVal value As Byte())
            If _timeStamp IsNot value Then
                ChangeTracker.RecordOriginalValue("TimeStamp", _timeStamp)
                _timeStamp = value
                OnPropertyChanged("TimeStamp")
            End If
        End Set
    End Property

#End Region

#Region "Navigation Properties"

    <DataMember()>
    Public Property Department() As Department
        Get
            Return _department
        End Get
        Set(ByVal value As Department)
            If _department IsNot value Then
                Dim previousValue As Department = _department
                _department = value
                FixupDepartment(previousValue)
                OnNavigationPropertyChanged("Department")
            End If
        End Set
    End Property

    Private _department As Department


    <DataMember()>
    Public Property RetentionConcepts() As RetentionConcepts
        Get
            Return _retentionConcepts
        End Get
        Set(ByVal value As RetentionConcepts)
            If _retentionConcepts IsNot value Then
                Dim previousValue As RetentionConcepts = _retentionConcepts
                _retentionConcepts = value
                FixupRetentionConcepts(previousValue)
                OnNavigationPropertyChanged("RetentionConcepts")
            End If
        End Set
    End Property

    Private _retentionConcepts As RetentionConcepts


    <DataMember()>
	Public Property EntityBankAccounts() As TrackableCollection(Of EntityBankAccounts)
		Get
            If _entityBankAccounts Is Nothing Then
                _entityBankAccounts = New TrackableCollection(Of EntityBankAccounts)
                AddHandler _entityBankAccounts.CollectionChanged, AddressOf FixupEntityBankAccounts
            End If
            Return _entityBankAccounts
        End Get
        Set(ByVal value As TrackableCollection(Of EntityBankAccounts))
            If _entityBankAccounts IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _entityBankAccounts IsNot Nothing Then
                    RemoveHandler _entityBankAccounts.CollectionChanged, AddressOf FixupEntityBankAccounts
                End If
                _entityBankAccounts = value
                If _entityBankAccounts IsNot Nothing Then
                    AddHandler _entityBankAccounts.CollectionChanged, AddressOf FixupEntityBankAccounts
                End If
                OnNavigationPropertyChanged("EntityBankAccounts")
            End If
        End Set
    End Property

    Private _entityBankAccounts As TrackableCollection(Of EntityBankAccounts)

    <DataMember()>
	Public Property HealthProvider() As TrackableCollection(Of HealthProvider)
		Get
            If _healthProvider Is Nothing Then
                _healthProvider = New TrackableCollection(Of HealthProvider)
                AddHandler _healthProvider.CollectionChanged, AddressOf FixupHealthProvider
            End If
            Return _healthProvider
        End Get
        Set(ByVal value As TrackableCollection(Of HealthProvider))
            If _healthProvider IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _healthProvider IsNot Nothing Then
                    RemoveHandler _healthProvider.CollectionChanged, AddressOf FixupHealthProvider
                End If
                _healthProvider = value
                If _healthProvider IsNot Nothing Then
                    AddHandler _healthProvider.CollectionChanged, AddressOf FixupHealthProvider
                End If
                OnNavigationPropertyChanged("HealthProvider")
            End If
        End Set
    End Property

    Private _healthProvider As TrackableCollection(Of HealthProvider)

    <DataMember()>
	Public Property FixedAssetInsurance() As TrackableCollection(Of FixedAssetInsurance)
		Get
            If _fixedAssetInsurance Is Nothing Then
                _fixedAssetInsurance = New TrackableCollection(Of FixedAssetInsurance)
                AddHandler _fixedAssetInsurance.CollectionChanged, AddressOf FixupFixedAssetInsurance
            End If
            Return _fixedAssetInsurance
        End Get
        Set(ByVal value As TrackableCollection(Of FixedAssetInsurance))
            If _fixedAssetInsurance IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _fixedAssetInsurance IsNot Nothing Then
                    RemoveHandler _fixedAssetInsurance.CollectionChanged, AddressOf FixupFixedAssetInsurance
                End If
                _fixedAssetInsurance = value
                If _fixedAssetInsurance IsNot Nothing Then
                    AddHandler _fixedAssetInsurance.CollectionChanged, AddressOf FixupFixedAssetInsurance
                End If
                OnNavigationPropertyChanged("FixedAssetInsurance")
            End If
        End Set
    End Property

    Private _fixedAssetInsurance As TrackableCollection(Of FixedAssetInsurance)

    <DataMember()>
	Public Property FixedAssetLocation() As TrackableCollection(Of FixedAssetLocation)
		Get
            If _fixedAssetLocation Is Nothing Then
                _fixedAssetLocation = New TrackableCollection(Of FixedAssetLocation)
                AddHandler _fixedAssetLocation.CollectionChanged, AddressOf FixupFixedAssetLocation
            End If
            Return _fixedAssetLocation
        End Get
        Set(ByVal value As TrackableCollection(Of FixedAssetLocation))
            If _fixedAssetLocation IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _fixedAssetLocation IsNot Nothing Then
                    RemoveHandler _fixedAssetLocation.CollectionChanged, AddressOf FixupFixedAssetLocation
                End If
                _fixedAssetLocation = value
                If _fixedAssetLocation IsNot Nothing Then
                    AddHandler _fixedAssetLocation.CollectionChanged, AddressOf FixupFixedAssetLocation
                End If
                OnNavigationPropertyChanged("FixedAssetLocation")
            End If
        End Set
    End Property

    Private _fixedAssetLocation As TrackableCollection(Of FixedAssetLocation)

    <DataMember()>
	Public Property OperatingUnit() As TrackableCollection(Of OperatingUnit)
		Get
            If _operatingUnit Is Nothing Then
                _operatingUnit = New TrackableCollection(Of OperatingUnit)
                AddHandler _operatingUnit.CollectionChanged, AddressOf FixupOperatingUnit
            End If
            Return _operatingUnit
        End Get
        Set(ByVal value As TrackableCollection(Of OperatingUnit))
            If _operatingUnit IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _operatingUnit IsNot Nothing Then
                    RemoveHandler _operatingUnit.CollectionChanged, AddressOf FixupOperatingUnit
                End If
                _operatingUnit = value
                If _operatingUnit IsNot Nothing Then
                    AddHandler _operatingUnit.CollectionChanged, AddressOf FixupOperatingUnit
                End If
                OnNavigationPropertyChanged("OperatingUnit")
            End If
        End Set
    End Property

    Private _operatingUnit As TrackableCollection(Of OperatingUnit)

    <DataMember()>
	Public Property PersonStudy() As TrackableCollection(Of PersonStudy)
		Get
            If _personStudy Is Nothing Then
                _personStudy = New TrackableCollection(Of PersonStudy)
                AddHandler _personStudy.CollectionChanged, AddressOf FixupPersonStudy
            End If
            Return _personStudy
        End Get
        Set(ByVal value As TrackableCollection(Of PersonStudy))
            If _personStudy IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _personStudy IsNot Nothing Then
                    RemoveHandler _personStudy.CollectionChanged, AddressOf FixupPersonStudy
                End If
                _personStudy = value
                If _personStudy IsNot Nothing Then
                    AddHandler _personStudy.CollectionChanged, AddressOf FixupPersonStudy
                End If
                OnNavigationPropertyChanged("PersonStudy")
            End If
        End Set
    End Property

    Private _personStudy As TrackableCollection(Of PersonStudy)

    <DataMember()>
	Public Property BranchOffice() As TrackableCollection(Of BranchOffice)
		Get
            If _branchOffice Is Nothing Then
                _branchOffice = New TrackableCollection(Of BranchOffice)
                AddHandler _branchOffice.CollectionChanged, AddressOf FixupBranchOffice
            End If
            Return _branchOffice
        End Get
        Set(ByVal value As TrackableCollection(Of BranchOffice))
            If _branchOffice IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _branchOffice IsNot Nothing Then
                    RemoveHandler _branchOffice.CollectionChanged, AddressOf FixupBranchOffice
                End If
                _branchOffice = value
                If _branchOffice IsNot Nothing Then
                    AddHandler _branchOffice.CollectionChanged, AddressOf FixupBranchOffice
                End If
                OnNavigationPropertyChanged("BranchOffice")
            End If
        End Set
    End Property

    Private _branchOffice As TrackableCollection(Of BranchOffice)

    <DataMember()>
	Public Property Supplier() As TrackableCollection(Of Supplier)
		Get
            If _supplier Is Nothing Then
                _supplier = New TrackableCollection(Of Supplier)
                AddHandler _supplier.CollectionChanged, AddressOf FixupSupplier
            End If
            Return _supplier
        End Get
        Set(ByVal value As TrackableCollection(Of Supplier))
            If _supplier IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _supplier IsNot Nothing Then
                    RemoveHandler _supplier.CollectionChanged, AddressOf FixupSupplier
                End If
                _supplier = value
                If _supplier IsNot Nothing Then
                    AddHandler _supplier.CollectionChanged, AddressOf FixupSupplier
                End If
                OnNavigationPropertyChanged("Supplier")
            End If
        End Set
    End Property

    Private _supplier As TrackableCollection(Of Supplier)

    <DataMember()>
	Public Property Address() As TrackableCollection(Of Address)
		Get
            If _address Is Nothing Then
                _address = New TrackableCollection(Of Address)
                AddHandler _address.CollectionChanged, AddressOf FixupAddress
            End If
            Return _address
        End Get
        Set(ByVal value As TrackableCollection(Of Address))
            If _address IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _address IsNot Nothing Then
                    RemoveHandler _address.CollectionChanged, AddressOf FixupAddress
                End If
                _address = value
                If _address IsNot Nothing Then
                    AddHandler _address.CollectionChanged, AddressOf FixupAddress
                End If
                OnNavigationPropertyChanged("Address")
            End If
        End Set
    End Property

    Private _address As TrackableCollection(Of Address)

    <DataMember()>
	Public Property RetentionConceptByCity() As TrackableCollection(Of RetentionConceptByCity)
		Get
            If _retentionConceptByCity Is Nothing Then
                _retentionConceptByCity = New TrackableCollection(Of RetentionConceptByCity)
                AddHandler _retentionConceptByCity.CollectionChanged, AddressOf FixupRetentionConceptByCity
            End If
            Return _retentionConceptByCity
        End Get
        Set(ByVal value As TrackableCollection(Of RetentionConceptByCity))
            If _retentionConceptByCity IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _retentionConceptByCity IsNot Nothing Then
                    RemoveHandler _retentionConceptByCity.CollectionChanged, AddressOf FixupRetentionConceptByCity
                End If
                _retentionConceptByCity = value
                If _retentionConceptByCity IsNot Nothing Then
                    AddHandler _retentionConceptByCity.CollectionChanged, AddressOf FixupRetentionConceptByCity
                End If
                OnNavigationPropertyChanged("RetentionConceptByCity")
            End If
        End Set
    End Property

    Private _retentionConceptByCity As TrackableCollection(Of RetentionConceptByCity)

    <DataMember()>
	Public Property Person() As TrackableCollection(Of Person)
		Get
            If _person Is Nothing Then
                _person = New TrackableCollection(Of Person)
                AddHandler _person.CollectionChanged, AddressOf FixupPerson
            End If
            Return _person
        End Get
        Set(ByVal value As TrackableCollection(Of Person))
            If _person IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _person IsNot Nothing Then
                    RemoveHandler _person.CollectionChanged, AddressOf FixupPerson
                End If
                _person = value
                If _person IsNot Nothing Then
                    AddHandler _person.CollectionChanged, AddressOf FixupPerson
                End If
                OnNavigationPropertyChanged("Person")
            End If
        End Set
    End Property

    Private _person As TrackableCollection(Of Person)

    <DataMember()>
	Public Property Person1() As TrackableCollection(Of Person)
		Get
            If _person1 Is Nothing Then
                _person1 = New TrackableCollection(Of Person)
                AddHandler _person1.CollectionChanged, AddressOf FixupPerson1
            End If
            Return _person1
        End Get
        Set(ByVal value As TrackableCollection(Of Person))
            If _person1 IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _person1 IsNot Nothing Then
                    RemoveHandler _person1.CollectionChanged, AddressOf FixupPerson1
                End If
                _person1 = value
                If _person1 IsNot Nothing Then
                    AddHandler _person1.CollectionChanged, AddressOf FixupPerson1
                End If
                OnNavigationPropertyChanged("Person1")
            End If
        End Set
    End Property

    Private _person1 As TrackableCollection(Of Person)

#End Region

#Region "ChangeTracking"

    Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
        If ChangeTracker.State <> ObjectState.Added AndAlso ChangeTracker.State <> ObjectState.Deleted Then
            ChangeTracker.State = ObjectState.Modified
        End If
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Protected Overridable Sub OnNavigationPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Private _changeTracker As ObjectChangeTracker

    <DataMember()>
    Public Property ChangeTracker() As ObjectChangeTracker Implements IObjectWithChangeTracker.ChangeTracker
        Get
            If _changeTracker Is Nothing Then
                _changeTracker = New ObjectChangeTracker()
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            Return _changeTracker
        End Get
        Set(ByVal value As ObjectChangeTracker)
            If _changeTracker IsNot Nothing Then
                RemoveHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            _changeTracker = value
            If _changeTracker IsNot Nothing Then
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
        End Set
    End Property

    Private Sub HandleObjectStateChanging(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.ClearNavigationProperties()
        End If
    End Sub

    Private _isDeserializing As Boolean
    Protected Property IsDeserializing() As Boolean
        Get
            Return _isDeserializing
        End Get
        Private Set(ByVal value As Boolean)
            _isDeserializing = value
        End Set
    End Property

    <OnDeserializing()>
    Public Sub OnDeserializingMethod(ByVal context As StreamingContext)
        IsDeserializing = True
    End Sub

    <OnDeserialized()>
    Public Sub OnDeserializedMethod(ByVal context As StreamingContext)
        IsDeserializing = False
        ChangeTracker.ChangeTrackingEnabled = True
    End Sub

    Protected Overridable Sub ClearNavigationProperties()
        Department = Nothing
        RetentionConcepts = Nothing
        EntityBankAccounts.Clear()
        HealthProvider.Clear()
        FixedAssetInsurance.Clear()
        FixedAssetLocation.Clear()
        OperatingUnit.Clear()
        PersonStudy.Clear()
        BranchOffice.Clear()
        Supplier.Clear()
        Address.Clear()
        RetentionConceptByCity.Clear()
        Person.Clear()
        Person1.Clear()
    End Sub

#End Region

#Region "Association Fixup"

    Private Sub FixupDepartment(ByVal previousValue As Department)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.City.Contains(Me) Then
            previousValue.City.Remove(Me)
        End If

        If Department IsNot Nothing Then
            Department.City.Add(Me)

            DepartamentId = Department.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("Department") AndAlso
                ChangeTracker.OriginalValues("Department") Is Department Then
                ChangeTracker.OriginalValues.Remove("Department")
            Else
                ChangeTracker.RecordOriginalValue("Department", previousValue)
            End If
            If Department IsNot Nothing AndAlso Not Department.ChangeTracker.ChangeTrackingEnabled Then
                Department.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupRetentionConcepts(ByVal previousValue As RetentionConcepts, Optional ByVal skipKeys As Boolean = False)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.City.Contains(Me) Then
            previousValue.City.Remove(Me)
        End If

        If RetentionConcepts IsNot Nothing Then
            RetentionConcepts.City.Add(Me)

            ICARetentionConceptId = RetentionConcepts.Id
        ElseIf Not skipKeys Then
            ICARetentionConceptId = Nothing
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("RetentionConcepts") AndAlso
                ChangeTracker.OriginalValues("RetentionConcepts") Is RetentionConcepts Then
                ChangeTracker.OriginalValues.Remove("RetentionConcepts")
            Else
                ChangeTracker.RecordOriginalValue("RetentionConcepts", previousValue)
            End If
            If RetentionConcepts IsNot Nothing AndAlso Not RetentionConcepts.ChangeTracker.ChangeTrackingEnabled Then
                RetentionConcepts.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupEntityBankAccounts(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As EntityBankAccounts In e.NewItems
                item.City = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("EntityBankAccounts", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As EntityBankAccounts In e.OldItems
                If item.City Is Me Then
                    item.City = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("EntityBankAccounts", item)
                End If
            Next
        End If
    End Sub

    Private Sub FixupHealthProvider(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As HealthProvider In e.NewItems
                item.City = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("HealthProvider", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As HealthProvider In e.OldItems
                If item.City Is Me Then
                    item.City = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("HealthProvider", item)
                End If
            Next
        End If
    End Sub

    Private Sub FixupFixedAssetInsurance(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As FixedAssetInsurance In e.NewItems
                item.City = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("FixedAssetInsurance", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As FixedAssetInsurance In e.OldItems
                If item.City Is Me Then
                    item.City = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("FixedAssetInsurance", item)
                End If
            Next
        End If
    End Sub

    Private Sub FixupFixedAssetLocation(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As FixedAssetLocation In e.NewItems
                item.City = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("FixedAssetLocation", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As FixedAssetLocation In e.OldItems
                If item.City Is Me Then
                    item.City = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("FixedAssetLocation", item)
                End If
            Next
        End If
    End Sub

    Private Sub FixupOperatingUnit(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As OperatingUnit In e.NewItems
                item.City = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("OperatingUnit", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As OperatingUnit In e.OldItems
                If item.City Is Me Then
                    item.City = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("OperatingUnit", item)
                End If
            Next
        End If
    End Sub

    Private Sub FixupPersonStudy(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As PersonStudy In e.NewItems
                item.City = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("PersonStudy", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As PersonStudy In e.OldItems
                If item.City Is Me Then
                    item.City = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("PersonStudy", item)
                End If
            Next
        End If
    End Sub

    Private Sub FixupBranchOffice(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As BranchOffice In e.NewItems
                item.City = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("BranchOffice", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As BranchOffice In e.OldItems
                If item.City Is Me Then
                    item.City = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("BranchOffice", item)
                End If
            Next
        End If
    End Sub

    Private Sub FixupSupplier(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As Supplier In e.NewItems
                item.City = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("Supplier", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As Supplier In e.OldItems
                If item.City Is Me Then
                    item.City = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("Supplier", item)
                End If
            Next
        End If
    End Sub

    Private Sub FixupAddress(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As Address In e.NewItems
                item.City = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("Address", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As Address In e.OldItems
                If item.City Is Me Then
                    item.City = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("Address", item)
                End If
            Next
        End If
    End Sub

    Private Sub FixupRetentionConceptByCity(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As RetentionConceptByCity In e.NewItems
                item.City = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("RetentionConceptByCity", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As RetentionConceptByCity In e.OldItems
                If item.City Is Me Then
                    item.City = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("RetentionConceptByCity", item)
                End If
            Next
        End If
    End Sub

    Private Sub FixupPerson(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As Person In e.NewItems
                item.City = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("Person", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As Person In e.OldItems
                If item.City Is Me Then
                    item.City = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("Person", item)
                End If
            Next
        End If
    End Sub

    Private Sub FixupPerson1(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As Person In e.NewItems
                item.City1 = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("Person1", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As Person In e.OldItems
                If item.City1 Is Me Then
                    item.City1 = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("Person1", item)
                End If
            Next
        End If
    End Sub

#End Region

End Class

