'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel
Imports System.Globalization
Imports System.IO
Imports System.Reflection
Imports System.Runtime.Serialization.Formatters.Binary
Imports System.Runtime.Serialization
Imports System.Runtime.CompilerServices
Imports Domain.Base.Entities
Imports System.Data.Entity.ModelConfiguration

<DataContract(IsReference:=True), Serializable(), KnownType(GetType(ElectronicSupportDocument))>
<KnownType(GetType(ThirdParty))>
<KnownType(GetType(BillingAuthorization))>
<KnownType(GetType(OperatingUnit))>
<KnownType(GetType(ElectronicSupportDocumentDetail))>
<KnownType(GetType(ElectronicSupportDocumentAdjustmentNote))>
Partial Public Class ElectronicSupportDocument
	Inherits Entity(Of ElectronicSupportDocument)
    Implements IObjectWithChangeTracker
    Implements INotifyPropertyChanged

#Region "Simple Properties"

	Private _id As Integer
	<DataMember()>
	Public Property Id() As Integer
        Get
            Return _id
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_id, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'Id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _id = value
                OnPropertyChanged("Id")
            End If
        End Set
    End Property

	Private _code As String
	<DataMember()>
	Public Property Code() As String
        Get
            Return _code
        End Get
        Set(ByVal value As String)
            If Not Equals(_code, value) Then
                _code = value
                OnPropertyChanged("Code")
            End If
        End Set
    End Property

	Private _documentDate As Date
	<DataMember()>
	Public Property DocumentDate() As Date
        Get
            Return _documentDate
        End Get
        Set(ByVal value As Date)
            If Not Equals(_documentDate, value) Then
                _documentDate = value
                OnPropertyChanged("DocumentDate")
            End If
        End Set
    End Property

	Private _radicationDate As Date
	<DataMember()>
	Public Property RadicationDate() As Date
        Get
            Return _radicationDate
        End Get
        Set(ByVal value As Date)
            If Not Equals(_radicationDate, value) Then
                _radicationDate = value
                OnPropertyChanged("RadicationDate")
            End If
        End Set
    End Property

	Private _dueDate As Date
	<DataMember()>
	Public Property DueDate() As Date
        Get
            Return _dueDate
        End Get
        Set(ByVal value As Date)
            If Not Equals(_dueDate, value) Then
                _dueDate = value
                OnPropertyChanged("DueDate")
            End If
        End Set
    End Property

	Private _supplierThirdPartyId As Integer
	<DataMember()>
	Public Property SupplierThirdPartyId() As Integer
        Get
            Return _supplierThirdPartyId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_supplierThirdPartyId, value) Then
                ChangeTracker.RecordOriginalValue("SupplierThirdPartyId", _supplierThirdPartyId)
                If Not IsDeserializing Then
                    If ThirdParty IsNot Nothing AndAlso Not Equals(ThirdParty.Id, value) Then
                        ThirdParty = Nothing
                    End If
                End If
                _supplierThirdPartyId = value
                OnPropertyChanged("SupplierThirdPartyId")
            End If
        End Set
    End Property

	Private _customerThirdPartyId As Integer
	<DataMember()>
	Public Property CustomerThirdPartyId() As Integer
        Get
            Return _customerThirdPartyId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_customerThirdPartyId, value) Then
                ChangeTracker.RecordOriginalValue("CustomerThirdPartyId", _customerThirdPartyId)
                If Not IsDeserializing Then
                    If ThirdParty1 IsNot Nothing AndAlso Not Equals(ThirdParty1.Id, value) Then
                        ThirdParty1 = Nothing
                    End If
                End If
                _customerThirdPartyId = value
                OnPropertyChanged("CustomerThirdPartyId")
            End If
        End Set
    End Property

	Private _billingAuthorizationId As Integer
	<DataMember()>
	Public Property BillingAuthorizationId() As Integer
        Get
            Return _billingAuthorizationId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_billingAuthorizationId, value) Then
                ChangeTracker.RecordOriginalValue("BillingAuthorizationId", _billingAuthorizationId)
                If Not IsDeserializing Then
                    If BillingAuthorization IsNot Nothing AndAlso Not Equals(BillingAuthorization.Id, value) Then
                        BillingAuthorization = Nothing
                    End If
                End If
                _billingAuthorizationId = value
                OnPropertyChanged("BillingAuthorizationId")
            End If
        End Set
    End Property

	Private _description As String
	<DataMember()>
	Public Property Description() As String
        Get
            Return _description
        End Get
        Set(ByVal value As String)
            If Not Equals(_description, value) Then
                _description = value
                OnPropertyChanged("Description")
            End If
        End Set
    End Property

	Private _subTotalValue As Decimal
	<DataMember()>
	Public Property SubTotalValue() As Decimal
        Get
            Return _subTotalValue
        End Get
        Set(ByVal value As Decimal)
            If Not Equals(_subTotalValue, value) Then
                _subTotalValue = value
                OnPropertyChanged("SubTotalValue")
            End If
        End Set
    End Property

	Private _taxValue As Decimal
	<DataMember()>
	Public Property TaxValue() As Decimal
        Get
            Return _taxValue
        End Get
        Set(ByVal value As Decimal)
            If Not Equals(_taxValue, value) Then
                _taxValue = value
                OnPropertyChanged("TaxValue")
            End If
        End Set
    End Property

	Private _totalValue As Decimal
	<DataMember()>
	Public Property TotalValue() As Decimal
        Get
            Return _totalValue
        End Get
        Set(ByVal value As Decimal)
            If Not Equals(_totalValue, value) Then
                _totalValue = value
                OnPropertyChanged("TotalValue")
            End If
        End Set
    End Property

	Private _status As Boolean
	<DataMember()>
	Public Property Status() As Boolean
        Get
            Return _status
        End Get
        Set(ByVal value As Boolean)
            If Not Equals(_status, value) Then
                _status = value
                OnPropertyChanged("Status")
            End If
        End Set
    End Property

	Private _cUDS As String
	<DataMember()>
	Public Property CUDS() As String
        Get
            Return _cUDS
        End Get
        Set(ByVal value As String)
            If Not Equals(_cUDS, value) Then
                _cUDS = value
                OnPropertyChanged("CUDS")
            End If
        End Set
    End Property

	Private _entityCode As String
	<DataMember()>
	Public Property EntityCode() As String
        Get
            Return _entityCode
        End Get
        Set(ByVal value As String)
            If Not Equals(_entityCode, value) Then
                _entityCode = value
                OnPropertyChanged("EntityCode")
            End If
        End Set
    End Property

	Private _entityName As String
	<DataMember()>
	Public Property EntityName() As String
        Get
            Return _entityName
        End Get
        Set(ByVal value As String)
            If Not Equals(_entityName, value) Then
                _entityName = value
                OnPropertyChanged("EntityName")
            End If
        End Set
    End Property

	Private _entityId As Nullable(Of Integer)
	<DataMember()>
	Public Property EntityId() As Nullable(Of Integer)
        Get
            Return _entityId
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_entityId, value) Then
                _entityId = value
                OnPropertyChanged("EntityId")
            End If
        End Set
    End Property

	Private _creationUser As String
	<DataMember()>
	Public Property CreationUser() As String
        Get
            Return _creationUser
        End Get
        Set(ByVal value As String)
            If Not Equals(_creationUser, value) Then
                _creationUser = value
                OnPropertyChanged("CreationUser")
            End If
        End Set
    End Property

	Private _creationDate As Date
	<DataMember()>
	Public Property CreationDate() As Date
        Get
            Return _creationDate
        End Get
        Set(ByVal value As Date)
            If Not Equals(_creationDate, value) Then
                _creationDate = value
                OnPropertyChanged("CreationDate")
            End If
        End Set
    End Property

	Private _modificationUser As String
	<DataMember()>
	Public Property ModificationUser() As String
        Get
            Return _modificationUser
        End Get
        Set(ByVal value As String)
            If Not Equals(_modificationUser, value) Then
                _modificationUser = value
                OnPropertyChanged("ModificationUser")
            End If
        End Set
    End Property

	Private _modificationDate As Nullable(Of Date)
	<DataMember()>
	Public Property ModificationDate() As Nullable(Of Date)
        Get
            Return _modificationDate
        End Get
        Set(ByVal value As Nullable(Of Date))
            If Not Equals(_modificationDate, value) Then
                _modificationDate = value
                OnPropertyChanged("ModificationDate")
            End If
        End Set
    End Property

	Private _timeStamp As Byte()
	<DataMember()>
	Public Property TimeStamp() As Byte()
        Get
            Return _timeStamp
        End Get
        Set(ByVal value As Byte())
            If _timeStamp IsNot value Then
                _timeStamp = value
                OnPropertyChanged("TimeStamp")
            End If
        End Set
    End Property

	Private _documentNumber As String
	<DataMember()>
	Public Property DocumentNumber() As String
        Get
            Return _documentNumber
        End Get
        Set(ByVal value As String)
            If Not Equals(_documentNumber, value) Then
                _documentNumber = value
                OnPropertyChanged("DocumentNumber")
            End If
        End Set
    End Property

	Private _operativeUnitId As Integer
	<DataMember()>
	Public Property OperativeUnitId() As Integer
        Get
            Return _operativeUnitId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_operativeUnitId, value) Then
                ChangeTracker.RecordOriginalValue("OperativeUnitId", _operativeUnitId)
                If Not IsDeserializing Then
                    If OperatingUnit IsNot Nothing AndAlso Not Equals(OperatingUnit.Id, value) Then
                        OperatingUnit = Nothing
                    End If
                End If
                _operativeUnitId = value
                OnPropertyChanged("OperativeUnitId")
            End If
        End Set
    End Property

	Private _retry As Integer
	<DataMember()>
	Public Property Retry() As Integer
        Get
            Return _retry
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_retry, value) Then
                _retry = value
                OnPropertyChanged("Retry")
            End If
        End Set
    End Property

	Private _statusElectronic As Byte
	<DataMember()>
	Public Property StatusElectronic() As Byte
        Get
            Return _statusElectronic
        End Get
        Set(ByVal value As Byte)
            If Not Equals(_statusElectronic, value) Then
                _statusElectronic = value
                OnPropertyChanged("StatusElectronic")
            End If
        End Set
    End Property

	Private _shippingDate As Nullable(Of Date)
	<DataMember()>
	Public Property ShippingDate() As Nullable(Of Date)
        Get
            Return _shippingDate
        End Get
        Set(ByVal value As Nullable(Of Date))
            If Not Equals(_shippingDate, value) Then
                _shippingDate = value
                OnPropertyChanged("ShippingDate")
            End If
        End Set
    End Property

	Private _zipKey As String
	<DataMember()>
	Public Property ZipKey() As String
        Get
            Return _zipKey
        End Get
        Set(ByVal value As String)
            If Not Equals(_zipKey, value) Then
                _zipKey = value
                OnPropertyChanged("ZipKey")
            End If
        End Set
    End Property

	Private _year As Integer
	<DataMember()>
	Public Property Year() As Integer
        Get
            Return _year
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_year, value) Then
                _year = value
                OnPropertyChanged("Year")
            End If
        End Set
    End Property

	Private _qR As String
	<DataMember()>
	Public Property QR() As String
        Get
            Return _qR
        End Get
        Set(ByVal value As String)
            If Not Equals(_qR, value) Then
                _qR = value
                OnPropertyChanged("QR")
            End If
        End Set
    End Property

	Private _consecutive As Integer
	<DataMember()>
	Public Property Consecutive() As Integer
        Get
            Return _consecutive
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_consecutive, value) Then
                _consecutive = value
                OnPropertyChanged("Consecutive")
            End If
        End Set
    End Property

	Private _filePath As String
	<DataMember()>
	Public Property FilePath() As String
        Get
            Return _filePath
        End Get
        Set(ByVal value As String)
            If Not Equals(_filePath, value) Then
                _filePath = value
                OnPropertyChanged("FilePath")
            End If
        End Set
    End Property

#End Region

#Region "Navigation Properties"

    <DataMember()>
    Public Property ThirdParty() As ThirdParty
        Get
            Return _thirdParty
        End Get
        Set(ByVal value As ThirdParty)
            If _thirdParty IsNot value Then
                Dim previousValue As ThirdParty = _thirdParty
                _thirdParty = value
                FixupThirdParty(previousValue)
                OnNavigationPropertyChanged("ThirdParty")
            End If
        End Set
    End Property

    Private _thirdParty As ThirdParty


    <DataMember()>
    Public Property ThirdParty1() As ThirdParty
        Get
            Return _thirdParty1
        End Get
        Set(ByVal value As ThirdParty)
            If _thirdParty1 IsNot value Then
                Dim previousValue As ThirdParty = _thirdParty1
                _thirdParty1 = value
                FixupThirdParty1(previousValue)
                OnNavigationPropertyChanged("ThirdParty1")
            End If
        End Set
    End Property

    Private _thirdParty1 As ThirdParty


    <DataMember()>
    Public Property BillingAuthorization() As BillingAuthorization
        Get
            Return _billingAuthorization
        End Get
        Set(ByVal value As BillingAuthorization)
            If _billingAuthorization IsNot value Then
                Dim previousValue As BillingAuthorization = _billingAuthorization
                _billingAuthorization = value
                FixupBillingAuthorization(previousValue)
                OnNavigationPropertyChanged("BillingAuthorization")
            End If
        End Set
    End Property

    Private _billingAuthorization As BillingAuthorization


    <DataMember()>
    Public Property OperatingUnit() As OperatingUnit
        Get
            Return _operatingUnit
        End Get
        Set(ByVal value As OperatingUnit)
            If _operatingUnit IsNot value Then
                Dim previousValue As OperatingUnit = _operatingUnit
                _operatingUnit = value
                FixupOperatingUnit(previousValue)
                OnNavigationPropertyChanged("OperatingUnit")
            End If
        End Set
    End Property

    Private _operatingUnit As OperatingUnit


    <DataMember()>
	Public Property ElectronicSupportDocumentDetail() As TrackableCollection(Of ElectronicSupportDocumentDetail)
		Get
            If _electronicSupportDocumentDetail Is Nothing Then
                _electronicSupportDocumentDetail = New TrackableCollection(Of ElectronicSupportDocumentDetail)
                AddHandler _electronicSupportDocumentDetail.CollectionChanged, AddressOf FixupElectronicSupportDocumentDetail
            End If
            Return _electronicSupportDocumentDetail
        End Get
        Set(ByVal value As TrackableCollection(Of ElectronicSupportDocumentDetail))
            If _electronicSupportDocumentDetail IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _electronicSupportDocumentDetail IsNot Nothing Then
                    RemoveHandler _electronicSupportDocumentDetail.CollectionChanged, AddressOf FixupElectronicSupportDocumentDetail
                End If
                _electronicSupportDocumentDetail = value
                If _electronicSupportDocumentDetail IsNot Nothing Then
                    AddHandler _electronicSupportDocumentDetail.CollectionChanged, AddressOf FixupElectronicSupportDocumentDetail
                End If
                OnNavigationPropertyChanged("ElectronicSupportDocumentDetail")
            End If
        End Set
    End Property

    Private _electronicSupportDocumentDetail As TrackableCollection(Of ElectronicSupportDocumentDetail)

    <DataMember()>
	Public Property ElectronicSupportDocumentAdjustmentNote() As TrackableCollection(Of ElectronicSupportDocumentAdjustmentNote)
		Get
            If _electronicSupportDocumentAdjustmentNote Is Nothing Then
                _electronicSupportDocumentAdjustmentNote = New TrackableCollection(Of ElectronicSupportDocumentAdjustmentNote)
                AddHandler _electronicSupportDocumentAdjustmentNote.CollectionChanged, AddressOf FixupElectronicSupportDocumentAdjustmentNote
            End If
            Return _electronicSupportDocumentAdjustmentNote
        End Get
        Set(ByVal value As TrackableCollection(Of ElectronicSupportDocumentAdjustmentNote))
            If _electronicSupportDocumentAdjustmentNote IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _electronicSupportDocumentAdjustmentNote IsNot Nothing Then
                    RemoveHandler _electronicSupportDocumentAdjustmentNote.CollectionChanged, AddressOf FixupElectronicSupportDocumentAdjustmentNote
                End If
                _electronicSupportDocumentAdjustmentNote = value
                If _electronicSupportDocumentAdjustmentNote IsNot Nothing Then
                    AddHandler _electronicSupportDocumentAdjustmentNote.CollectionChanged, AddressOf FixupElectronicSupportDocumentAdjustmentNote
                End If
                OnNavigationPropertyChanged("ElectronicSupportDocumentAdjustmentNote")
            End If
        End Set
    End Property

    Private _electronicSupportDocumentAdjustmentNote As TrackableCollection(Of ElectronicSupportDocumentAdjustmentNote)

#End Region

#Region "ChangeTracking"

    Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
        If ChangeTracker.State <> ObjectState.Added AndAlso ChangeTracker.State <> ObjectState.Deleted Then
            ChangeTracker.State = ObjectState.Modified
        End If
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Protected Overridable Sub OnNavigationPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Private _changeTracker As ObjectChangeTracker

    <DataMember()>
    Public Property ChangeTracker() As ObjectChangeTracker Implements IObjectWithChangeTracker.ChangeTracker
        Get
            If _changeTracker Is Nothing Then
                _changeTracker = New ObjectChangeTracker()
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            Return _changeTracker
        End Get
        Set(ByVal value As ObjectChangeTracker)
            If _changeTracker IsNot Nothing Then
                RemoveHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            _changeTracker = value
            If _changeTracker IsNot Nothing Then
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
        End Set
    End Property

    Private Sub HandleObjectStateChanging(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.ClearNavigationProperties()
        End If
    End Sub

    Private _isDeserializing As Boolean
    Protected Property IsDeserializing() As Boolean
        Get
            Return _isDeserializing
        End Get
        Private Set(ByVal value As Boolean)
            _isDeserializing = value
        End Set
    End Property

    <OnDeserializing()>
    Public Sub OnDeserializingMethod(ByVal context As StreamingContext)
        IsDeserializing = True
    End Sub

    <OnDeserialized()>
    Public Sub OnDeserializedMethod(ByVal context As StreamingContext)
        IsDeserializing = False
        ChangeTracker.ChangeTrackingEnabled = True
    End Sub

    Protected Overridable Sub ClearNavigationProperties()
        ThirdParty = Nothing
        ThirdParty1 = Nothing
        BillingAuthorization = Nothing
        OperatingUnit = Nothing
        ElectronicSupportDocumentDetail.Clear()
        ElectronicSupportDocumentAdjustmentNote.Clear()
    End Sub

#End Region

#Region "Association Fixup"

    Private Sub FixupThirdParty(ByVal previousValue As ThirdParty)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.ElectronicSupportDocument.Contains(Me) Then
            previousValue.ElectronicSupportDocument.Remove(Me)
        End If

        If ThirdParty IsNot Nothing Then
            ThirdParty.ElectronicSupportDocument.Add(Me)

            SupplierThirdPartyId = ThirdParty.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("ThirdParty") AndAlso
                ChangeTracker.OriginalValues("ThirdParty") Is ThirdParty Then
                ChangeTracker.OriginalValues.Remove("ThirdParty")
            Else
                ChangeTracker.RecordOriginalValue("ThirdParty", previousValue)
            End If
            If ThirdParty IsNot Nothing AndAlso Not ThirdParty.ChangeTracker.ChangeTrackingEnabled Then
                ThirdParty.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupThirdParty1(ByVal previousValue As ThirdParty)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.ElectronicSupportDocument1.Contains(Me) Then
            previousValue.ElectronicSupportDocument1.Remove(Me)
        End If

        If ThirdParty1 IsNot Nothing Then
            ThirdParty1.ElectronicSupportDocument1.Add(Me)

            CustomerThirdPartyId = ThirdParty1.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("ThirdParty1") AndAlso
                ChangeTracker.OriginalValues("ThirdParty1") Is ThirdParty1 Then
                ChangeTracker.OriginalValues.Remove("ThirdParty1")
            Else
                ChangeTracker.RecordOriginalValue("ThirdParty1", previousValue)
            End If
            If ThirdParty1 IsNot Nothing AndAlso Not ThirdParty1.ChangeTracker.ChangeTrackingEnabled Then
                ThirdParty1.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupBillingAuthorization(ByVal previousValue As BillingAuthorization)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.ElectronicSupportDocument.Contains(Me) Then
            previousValue.ElectronicSupportDocument.Remove(Me)
        End If

        If BillingAuthorization IsNot Nothing Then
            BillingAuthorization.ElectronicSupportDocument.Add(Me)

            BillingAuthorizationId = BillingAuthorization.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("BillingAuthorization") AndAlso
                ChangeTracker.OriginalValues("BillingAuthorization") Is BillingAuthorization Then
                ChangeTracker.OriginalValues.Remove("BillingAuthorization")
            Else
                ChangeTracker.RecordOriginalValue("BillingAuthorization", previousValue)
            End If
            If BillingAuthorization IsNot Nothing AndAlso Not BillingAuthorization.ChangeTracker.ChangeTrackingEnabled Then
                BillingAuthorization.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupOperatingUnit(ByVal previousValue As OperatingUnit)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.ElectronicSupportDocument.Contains(Me) Then
            previousValue.ElectronicSupportDocument.Remove(Me)
        End If

        If OperatingUnit IsNot Nothing Then
            OperatingUnit.ElectronicSupportDocument.Add(Me)

            OperativeUnitId = OperatingUnit.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("OperatingUnit") AndAlso
                ChangeTracker.OriginalValues("OperatingUnit") Is OperatingUnit Then
                ChangeTracker.OriginalValues.Remove("OperatingUnit")
            Else
                ChangeTracker.RecordOriginalValue("OperatingUnit", previousValue)
            End If
            If OperatingUnit IsNot Nothing AndAlso Not OperatingUnit.ChangeTracker.ChangeTrackingEnabled Then
                OperatingUnit.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupElectronicSupportDocumentDetail(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As ElectronicSupportDocumentDetail In e.NewItems
                item.ElectronicSupportDocument = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("ElectronicSupportDocumentDetail", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As ElectronicSupportDocumentDetail In e.OldItems
                If item.ElectronicSupportDocument Is Me Then
                    item.ElectronicSupportDocument = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("ElectronicSupportDocumentDetail", item)
                End If
            Next
        End If
    End Sub

    Private Sub FixupElectronicSupportDocumentAdjustmentNote(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As ElectronicSupportDocumentAdjustmentNote In e.NewItems
                item.ElectronicSupportDocument = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("ElectronicSupportDocumentAdjustmentNote", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As ElectronicSupportDocumentAdjustmentNote In e.OldItems
                If item.ElectronicSupportDocument Is Me Then
                    item.ElectronicSupportDocument = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("ElectronicSupportDocumentAdjustmentNote", item)
                End If
            Next
        End If
    End Sub

#End Region

End Class

