'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel
Imports System.Globalization
Imports System.IO
Imports System.Reflection
Imports System.Runtime.Serialization.Formatters.Binary
Imports System.Runtime.Serialization
Imports System.Runtime.CompilerServices
Imports Domain.Base.Entities
Imports System.Data.Entity.ModelConfiguration

<DataContract(IsReference:=True), Serializable(), KnownType(GetType(GroupersCups))>
<KnownType(GetType(Groupers))>
<KnownType(GetType(CUPSEntity))>
<KnownType(GetType(ContractDescriptions))>
<KnownType(GetType(CUPSEntityContractDescriptions))>
Partial Public Class GroupersCups
	Inherits Entity(Of GroupersCups)
    Implements IObjectWithChangeTracker
    Implements INotifyPropertyChanged

#Region "Simple Properties"

	Private _id As Integer
	<DataMember()>
	Public Property Id() As Integer
        Get
            Return _id
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_id, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'Id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _id = value
                OnPropertyChanged("Id")
            End If
        End Set
    End Property

	Private _grouperId As Integer
	<DataMember()>
	Public Property GrouperId() As Integer
        Get
            Return _grouperId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_grouperId, value) Then
                ChangeTracker.RecordOriginalValue("GrouperId", _grouperId)
                If Not IsDeserializing Then
                    If Groupers IsNot Nothing AndAlso Not Equals(Groupers.Id, value) Then
                        Groupers = Nothing
                    End If
                End If
                _grouperId = value
                OnPropertyChanged("GrouperId")
            End If
        End Set
    End Property

	Private _cUPSEntityId As Integer
	<DataMember()>
	Public Property CUPSEntityId() As Integer
        Get
            Return _cUPSEntityId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_cUPSEntityId, value) Then
                ChangeTracker.RecordOriginalValue("CUPSEntityId", _cUPSEntityId)
                If Not IsDeserializing Then
                    If CUPSEntity IsNot Nothing AndAlso Not Equals(CUPSEntity.Id, value) Then
                        CUPSEntity = Nothing
                    End If
                End If
                _cUPSEntityId = value
                OnPropertyChanged("CUPSEntityId")
            End If
        End Set
    End Property

	Private _cUPSEntityContractDescriptionId As Nullable(Of Integer)
	<DataMember()>
	Public Property CUPSEntityContractDescriptionId() As Nullable(Of Integer)
        Get
            Return _cUPSEntityContractDescriptionId
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_cUPSEntityContractDescriptionId, value) Then
                ChangeTracker.RecordOriginalValue("CUPSEntityContractDescriptionId", _cUPSEntityContractDescriptionId)
                If Not IsDeserializing Then
                    If CUPSEntityContractDescriptions IsNot Nothing AndAlso Not Equals(CUPSEntityContractDescriptions.Id, value) Then
                        CUPSEntityContractDescriptions = Nothing
                    End If
                End If
                _cUPSEntityContractDescriptionId = value
                OnPropertyChanged("CUPSEntityContractDescriptionId")
            End If
        End Set
    End Property

	Private _contractDescriptionId As Nullable(Of Integer)
	<DataMember()>
	Public Property ContractDescriptionId() As Nullable(Of Integer)
        Get
            Return _contractDescriptionId
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_contractDescriptionId, value) Then
                ChangeTracker.RecordOriginalValue("ContractDescriptionId", _contractDescriptionId)
                If Not IsDeserializing Then
                    If ContractDescriptions IsNot Nothing AndAlso Not Equals(ContractDescriptions.Id, value) Then
                        ContractDescriptions = Nothing
                    End If
                End If
                _contractDescriptionId = value
                OnPropertyChanged("ContractDescriptionId")
            End If
        End Set
    End Property

#End Region

#Region "Navigation Properties"

    <DataMember()>
    Public Property Groupers() As Groupers
        Get
            Return _groupers
        End Get
        Set(ByVal value As Groupers)
            If _groupers IsNot value Then
                Dim previousValue As Groupers = _groupers
                _groupers = value
                FixupGroupers(previousValue)
                OnNavigationPropertyChanged("Groupers")
            End If
        End Set
    End Property

    Private _groupers As Groupers


    <DataMember()>
    Public Property CUPSEntity() As CUPSEntity
        Get
            Return _cUPSEntity
        End Get
        Set(ByVal value As CUPSEntity)
            If _cUPSEntity IsNot value Then
                Dim previousValue As CUPSEntity = _cUPSEntity
                _cUPSEntity = value
                FixupCUPSEntity(previousValue)
                OnNavigationPropertyChanged("CUPSEntity")
            End If
        End Set
    End Property

    Private _cUPSEntity As CUPSEntity


    <DataMember()>
    Public Property ContractDescriptions() As ContractDescriptions
        Get
            Return _contractDescriptions
        End Get
        Set(ByVal value As ContractDescriptions)
            If _contractDescriptions IsNot value Then
                Dim previousValue As ContractDescriptions = _contractDescriptions
                _contractDescriptions = value
                FixupContractDescriptions(previousValue)
                OnNavigationPropertyChanged("ContractDescriptions")
            End If
        End Set
    End Property

    Private _contractDescriptions As ContractDescriptions


    <DataMember()>
    Public Property CUPSEntityContractDescriptions() As CUPSEntityContractDescriptions
        Get
            Return _cUPSEntityContractDescriptions
        End Get
        Set(ByVal value As CUPSEntityContractDescriptions)
            If _cUPSEntityContractDescriptions IsNot value Then
                Dim previousValue As CUPSEntityContractDescriptions = _cUPSEntityContractDescriptions
                _cUPSEntityContractDescriptions = value
                FixupCUPSEntityContractDescriptions(previousValue)
                OnNavigationPropertyChanged("CUPSEntityContractDescriptions")
            End If
        End Set
    End Property

    Private _cUPSEntityContractDescriptions As CUPSEntityContractDescriptions


#End Region

#Region "ChangeTracking"

    Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
        If ChangeTracker.State <> ObjectState.Added AndAlso ChangeTracker.State <> ObjectState.Deleted Then
            ChangeTracker.State = ObjectState.Modified
        End If
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Protected Overridable Sub OnNavigationPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Private _changeTracker As ObjectChangeTracker

    <DataMember()>
    Public Property ChangeTracker() As ObjectChangeTracker Implements IObjectWithChangeTracker.ChangeTracker
        Get
            If _changeTracker Is Nothing Then
                _changeTracker = New ObjectChangeTracker()
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            Return _changeTracker
        End Get
        Set(ByVal value As ObjectChangeTracker)
            If _changeTracker IsNot Nothing Then
                RemoveHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            _changeTracker = value
            If _changeTracker IsNot Nothing Then
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
        End Set
    End Property

    Private Sub HandleObjectStateChanging(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.ClearNavigationProperties()
        End If
    End Sub

    Private _isDeserializing As Boolean
    Protected Property IsDeserializing() As Boolean
        Get
            Return _isDeserializing
        End Get
        Private Set(ByVal value As Boolean)
            _isDeserializing = value
        End Set
    End Property

    <OnDeserializing()>
    Public Sub OnDeserializingMethod(ByVal context As StreamingContext)
        IsDeserializing = True
    End Sub

    <OnDeserialized()>
    Public Sub OnDeserializedMethod(ByVal context As StreamingContext)
        IsDeserializing = False
        ChangeTracker.ChangeTrackingEnabled = True
    End Sub

    Protected Overridable Sub ClearNavigationProperties()
        Groupers = Nothing
        CUPSEntity = Nothing
        ContractDescriptions = Nothing
        CUPSEntityContractDescriptions = Nothing
    End Sub

#End Region

#Region "Association Fixup"

    Private Sub FixupGroupers(ByVal previousValue As Groupers)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.GroupersCups.Contains(Me) Then
            previousValue.GroupersCups.Remove(Me)
        End If

        If Groupers IsNot Nothing Then
            Groupers.GroupersCups.Add(Me)

            GrouperId = Groupers.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("Groupers") AndAlso
                ChangeTracker.OriginalValues("Groupers") Is Groupers Then
                ChangeTracker.OriginalValues.Remove("Groupers")
            Else
                ChangeTracker.RecordOriginalValue("Groupers", previousValue)
            End If
            If Groupers IsNot Nothing AndAlso Not Groupers.ChangeTracker.ChangeTrackingEnabled Then
                Groupers.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupCUPSEntity(ByVal previousValue As CUPSEntity)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.GroupersCups.Contains(Me) Then
            previousValue.GroupersCups.Remove(Me)
        End If

        If CUPSEntity IsNot Nothing Then
            CUPSEntity.GroupersCups.Add(Me)

            CUPSEntityId = CUPSEntity.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("CUPSEntity") AndAlso
                ChangeTracker.OriginalValues("CUPSEntity") Is CUPSEntity Then
                ChangeTracker.OriginalValues.Remove("CUPSEntity")
            Else
                ChangeTracker.RecordOriginalValue("CUPSEntity", previousValue)
            End If
            If CUPSEntity IsNot Nothing AndAlso Not CUPSEntity.ChangeTracker.ChangeTrackingEnabled Then
                CUPSEntity.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupContractDescriptions(ByVal previousValue As ContractDescriptions, Optional ByVal skipKeys As Boolean = False)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.GroupersCups.Contains(Me) Then
            previousValue.GroupersCups.Remove(Me)
        End If

        If ContractDescriptions IsNot Nothing Then
            ContractDescriptions.GroupersCups.Add(Me)

            ContractDescriptionId = ContractDescriptions.Id
        ElseIf Not skipKeys Then
            ContractDescriptionId = Nothing
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("ContractDescriptions") AndAlso
                ChangeTracker.OriginalValues("ContractDescriptions") Is ContractDescriptions Then
                ChangeTracker.OriginalValues.Remove("ContractDescriptions")
            Else
                ChangeTracker.RecordOriginalValue("ContractDescriptions", previousValue)
            End If
            If ContractDescriptions IsNot Nothing AndAlso Not ContractDescriptions.ChangeTracker.ChangeTrackingEnabled Then
                ContractDescriptions.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupCUPSEntityContractDescriptions(ByVal previousValue As CUPSEntityContractDescriptions, Optional ByVal skipKeys As Boolean = False)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.GroupersCups.Contains(Me) Then
            previousValue.GroupersCups.Remove(Me)
        End If

        If CUPSEntityContractDescriptions IsNot Nothing Then
            CUPSEntityContractDescriptions.GroupersCups.Add(Me)

            CUPSEntityContractDescriptionId = CUPSEntityContractDescriptions.Id
        ElseIf Not skipKeys Then
            CUPSEntityContractDescriptionId = Nothing
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("CUPSEntityContractDescriptions") AndAlso
                ChangeTracker.OriginalValues("CUPSEntityContractDescriptions") Is CUPSEntityContractDescriptions Then
                ChangeTracker.OriginalValues.Remove("CUPSEntityContractDescriptions")
            Else
                ChangeTracker.RecordOriginalValue("CUPSEntityContractDescriptions", previousValue)
            End If
            If CUPSEntityContractDescriptions IsNot Nothing AndAlso Not CUPSEntityContractDescriptions.ChangeTracker.ChangeTrackingEnabled Then
                CUPSEntityContractDescriptions.StartTracking()
            End If
        End If
    End Sub

#End Region

End Class

