'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel
Imports System.Globalization
Imports System.IO
Imports System.Reflection
Imports System.Runtime.Serialization.Formatters.Binary
Imports System.Runtime.Serialization
Imports System.Runtime.CompilerServices
Imports Domain.Base.Entities
Imports System.Data.Entity.ModelConfiguration

<DataContract(IsReference:=True), Serializable(), KnownType(GetType(InteropCostSecuenceDetail))>
<KnownType(GetType(OperatingUnit))>
<KnownType(GetType(Sequense))>
<KnownType(GetType(InteropCostSecuence))>
Partial Public Class InteropCostSecuenceDetail
	Inherits Entity(Of InteropCostSecuenceDetail)
    Implements IObjectWithChangeTracker
    Implements INotifyPropertyChanged

#Region "Simple Properties"

	Private _id As Integer
	<DataMember()>
	Public Property Id() As Integer
        Get
            Return _id
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_id, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'Id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _id = value
                OnPropertyChanged("Id")
            End If
        End Set
    End Property

	Private _sequenseInteropCostId As Integer
	<DataMember()>
	Public Property SequenseInteropCostId() As Integer
        Get
            Return _sequenseInteropCostId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_sequenseInteropCostId, value) Then
                ChangeTracker.RecordOriginalValue("SequenseInteropCostId", _sequenseInteropCostId)
                If Not IsDeserializing Then
                    If InteropCostSecuence IsNot Nothing AndAlso Not Equals(InteropCostSecuence.Id, value) Then
                        InteropCostSecuence = Nothing
                    End If
                End If
                _sequenseInteropCostId = value
                OnPropertyChanged("SequenseInteropCostId")
            End If
        End Set
    End Property

	Private _idSequense As Integer
	<DataMember()>
	Public Property IdSequense() As Integer
        Get
            Return _idSequense
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_idSequense, value) Then
                ChangeTracker.RecordOriginalValue("IdSequense", _idSequense)
                If Not IsDeserializing Then
                    If Sequense IsNot Nothing AndAlso Not Equals(Sequense.Id, value) Then
                        Sequense = Nothing
                    End If
                End If
                _idSequense = value
                OnPropertyChanged("IdSequense")
            End If
        End Set
    End Property

	Private _idOperatingUnit As Nullable(Of Integer)
	<DataMember()>
	Public Property IdOperatingUnit() As Nullable(Of Integer)
        Get
            Return _idOperatingUnit
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_idOperatingUnit, value) Then
                ChangeTracker.RecordOriginalValue("IdOperatingUnit", _idOperatingUnit)
                If Not IsDeserializing Then
                    If OperatingUnit IsNot Nothing AndAlso Not Equals(OperatingUnit.Id, value) Then
                        OperatingUnit = Nothing
                    End If
                End If
                _idOperatingUnit = value
                OnPropertyChanged("IdOperatingUnit")
            End If
        End Set
    End Property

	Private _next As Long
	<DataMember()>
	Public Property [Next]() As Long
        Get
            Return _next
        End Get
        Set(ByVal value As Long)
            If Not Equals(_next, value) Then
                _next = value
                OnPropertyChanged("Next")
            End If
        End Set
    End Property

#End Region

#Region "Navigation Properties"

    <DataMember()>
    Public Property OperatingUnit() As OperatingUnit
        Get
            Return _operatingUnit
        End Get
        Set(ByVal value As OperatingUnit)
            If _operatingUnit IsNot value Then
                Dim previousValue As OperatingUnit = _operatingUnit
                _operatingUnit = value
                FixupOperatingUnit(previousValue)
                OnNavigationPropertyChanged("OperatingUnit")
            End If
        End Set
    End Property

    Private _operatingUnit As OperatingUnit


    <DataMember()>
    Public Property Sequense() As Sequense
        Get
            Return _sequense
        End Get
        Set(ByVal value As Sequense)
            If _sequense IsNot value Then
                Dim previousValue As Sequense = _sequense
                _sequense = value
                FixupSequense(previousValue)
                OnNavigationPropertyChanged("Sequense")
            End If
        End Set
    End Property

    Private _sequense As Sequense


    <DataMember()>
    Public Property InteropCostSecuence() As InteropCostSecuence
        Get
            Return _interopCostSecuence
        End Get
        Set(ByVal value As InteropCostSecuence)
            If _interopCostSecuence IsNot value Then
                Dim previousValue As InteropCostSecuence = _interopCostSecuence
                _interopCostSecuence = value
                FixupInteropCostSecuence(previousValue)
                OnNavigationPropertyChanged("InteropCostSecuence")
            End If
        End Set
    End Property

    Private _interopCostSecuence As InteropCostSecuence


#End Region

#Region "ChangeTracking"

    Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
        If ChangeTracker.State <> ObjectState.Added AndAlso ChangeTracker.State <> ObjectState.Deleted Then
            ChangeTracker.State = ObjectState.Modified
        End If
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Protected Overridable Sub OnNavigationPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Private _changeTracker As ObjectChangeTracker

    <DataMember()>
    Public Property ChangeTracker() As ObjectChangeTracker Implements IObjectWithChangeTracker.ChangeTracker
        Get
            If _changeTracker Is Nothing Then
                _changeTracker = New ObjectChangeTracker()
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            Return _changeTracker
        End Get
        Set(ByVal value As ObjectChangeTracker)
            If _changeTracker IsNot Nothing Then
                RemoveHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            _changeTracker = value
            If _changeTracker IsNot Nothing Then
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
        End Set
    End Property

    Private Sub HandleObjectStateChanging(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.ClearNavigationProperties()
        End If
    End Sub

    Private _isDeserializing As Boolean
    Protected Property IsDeserializing() As Boolean
        Get
            Return _isDeserializing
        End Get
        Private Set(ByVal value As Boolean)
            _isDeserializing = value
        End Set
    End Property

    <OnDeserializing()>
    Public Sub OnDeserializingMethod(ByVal context As StreamingContext)
        IsDeserializing = True
    End Sub

    <OnDeserialized()>
    Public Sub OnDeserializedMethod(ByVal context As StreamingContext)
        IsDeserializing = False
        ChangeTracker.ChangeTrackingEnabled = True
    End Sub

    Protected Overridable Sub ClearNavigationProperties()
        OperatingUnit = Nothing
        Sequense = Nothing
        InteropCostSecuence = Nothing
    End Sub

#End Region

#Region "Association Fixup"

    Private Sub FixupOperatingUnit(ByVal previousValue As OperatingUnit, Optional ByVal skipKeys As Boolean = False)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.InteropCostSecuenceDetail.Contains(Me) Then
            previousValue.InteropCostSecuenceDetail.Remove(Me)
        End If

        If OperatingUnit IsNot Nothing Then
            OperatingUnit.InteropCostSecuenceDetail.Add(Me)

            IdOperatingUnit = OperatingUnit.Id
        ElseIf Not skipKeys Then
            IdOperatingUnit = Nothing
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("OperatingUnit") AndAlso
                ChangeTracker.OriginalValues("OperatingUnit") Is OperatingUnit Then
                ChangeTracker.OriginalValues.Remove("OperatingUnit")
            Else
                ChangeTracker.RecordOriginalValue("OperatingUnit", previousValue)
            End If
            If OperatingUnit IsNot Nothing AndAlso Not OperatingUnit.ChangeTracker.ChangeTrackingEnabled Then
                OperatingUnit.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupSequense(ByVal previousValue As Sequense)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.InteropCostSecuenceDetail.Contains(Me) Then
            previousValue.InteropCostSecuenceDetail.Remove(Me)
        End If

        If Sequense IsNot Nothing Then
            Sequense.InteropCostSecuenceDetail.Add(Me)

            IdSequense = Sequense.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("Sequense") AndAlso
                ChangeTracker.OriginalValues("Sequense") Is Sequense Then
                ChangeTracker.OriginalValues.Remove("Sequense")
            Else
                ChangeTracker.RecordOriginalValue("Sequense", previousValue)
            End If
            If Sequense IsNot Nothing AndAlso Not Sequense.ChangeTracker.ChangeTrackingEnabled Then
                Sequense.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupInteropCostSecuence(ByVal previousValue As InteropCostSecuence)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.InteropCostSecuenceDetail.Contains(Me) Then
            previousValue.InteropCostSecuenceDetail.Remove(Me)
        End If

        If InteropCostSecuence IsNot Nothing Then
            InteropCostSecuence.InteropCostSecuenceDetail.Add(Me)

            SequenseInteropCostId = InteropCostSecuence.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("InteropCostSecuence") AndAlso
                ChangeTracker.OriginalValues("InteropCostSecuence") Is InteropCostSecuence Then
                ChangeTracker.OriginalValues.Remove("InteropCostSecuence")
            Else
                ChangeTracker.RecordOriginalValue("InteropCostSecuence", previousValue)
            End If
            If InteropCostSecuence IsNot Nothing AndAlso Not InteropCostSecuence.ChangeTracker.ChangeTrackingEnabled Then
                InteropCostSecuence.StartTracking()
            End If
        End If
    End Sub

#End Region

End Class

