'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel
Imports System.Globalization
Imports System.IO
Imports System.Reflection
Imports System.Runtime.Serialization.Formatters.Binary
Imports System.Runtime.Serialization
Imports System.Runtime.CompilerServices
Imports Domain.Base.Entities
Imports System.Data.Entity.ModelConfiguration

<DataContract(IsReference:=True), Serializable(), KnownType(GetType(LowTaxLiquidationDetail))>
<KnownType(GetType(LowTaxLiquidation))>
Partial Public Class LowTaxLiquidationDetail
	Inherits Entity(Of LowTaxLiquidationDetail)
    Implements IObjectWithChangeTracker
    Implements INotifyPropertyChanged

#Region "Simple Properties"

	Private _id As Integer
	<DataMember()>
	Public Property Id() As Integer
        Get
            Return _id
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_id, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'Id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _id = value
                OnPropertyChanged("Id")
            End If
        End Set
    End Property

	Private _lowTaxLiquidationId As Integer
	<DataMember()>
	Public Property LowTaxLiquidationId() As Integer
        Get
            Return _lowTaxLiquidationId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_lowTaxLiquidationId, value) Then
                ChangeTracker.RecordOriginalValue("LowTaxLiquidationId", _lowTaxLiquidationId)
                If Not IsDeserializing Then
                    If LowTaxLiquidation IsNot Nothing AndAlso Not Equals(LowTaxLiquidation.Id, value) Then
                        LowTaxLiquidation = Nothing
                    End If
                End If
                _lowTaxLiquidationId = value
                OnPropertyChanged("LowTaxLiquidationId")
            End If
        End Set
    End Property

	Private _concept As Byte
	<DataMember()>
	Public Property Concept() As Byte
        Get
            Return _concept
        End Get
        Set(ByVal value As Byte)
            If Not Equals(_concept, value) Then
                _concept = value
                OnPropertyChanged("Concept")
            End If
        End Set
    End Property

	Private _numberOfDays As Integer
	<DataMember()>
	Public Property NumberOfDays() As Integer
        Get
            Return _numberOfDays
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_numberOfDays, value) Then
                _numberOfDays = value
                OnPropertyChanged("NumberOfDays")
            End If
        End Set
    End Property

	Private _quantity As Integer
	<DataMember()>
	Public Property Quantity() As Integer
        Get
            Return _quantity
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_quantity, value) Then
                _quantity = value
                OnPropertyChanged("Quantity")
            End If
        End Set
    End Property

	Private _totalValueTax As Nullable(Of Decimal)
	<DataMember()>
	Public Property TotalValueTax() As Nullable(Of Decimal)
        Get
            Return _totalValueTax
        End Get
        Set(ByVal value As Nullable(Of Decimal))
            If Not Equals(_totalValueTax, value) Then
                _totalValueTax = value
                OnPropertyChanged("TotalValueTax")
            End If
        End Set
    End Property

#End Region

#Region "Navigation Properties"

    <DataMember()>
    Public Property LowTaxLiquidation() As LowTaxLiquidation
        Get
            Return _lowTaxLiquidation
        End Get
        Set(ByVal value As LowTaxLiquidation)
            If _lowTaxLiquidation IsNot value Then
                Dim previousValue As LowTaxLiquidation = _lowTaxLiquidation
                _lowTaxLiquidation = value
                FixupLowTaxLiquidation(previousValue)
                OnNavigationPropertyChanged("LowTaxLiquidation")
            End If
        End Set
    End Property

    Private _lowTaxLiquidation As LowTaxLiquidation


#End Region

#Region "ChangeTracking"

    Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
        If ChangeTracker.State <> ObjectState.Added AndAlso ChangeTracker.State <> ObjectState.Deleted Then
            ChangeTracker.State = ObjectState.Modified
        End If
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Protected Overridable Sub OnNavigationPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Private _changeTracker As ObjectChangeTracker

    <DataMember()>
    Public Property ChangeTracker() As ObjectChangeTracker Implements IObjectWithChangeTracker.ChangeTracker
        Get
            If _changeTracker Is Nothing Then
                _changeTracker = New ObjectChangeTracker()
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            Return _changeTracker
        End Get
        Set(ByVal value As ObjectChangeTracker)
            If _changeTracker IsNot Nothing Then
                RemoveHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            _changeTracker = value
            If _changeTracker IsNot Nothing Then
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
        End Set
    End Property

    Private Sub HandleObjectStateChanging(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.ClearNavigationProperties()
        End If
    End Sub

    Private _isDeserializing As Boolean
    Protected Property IsDeserializing() As Boolean
        Get
            Return _isDeserializing
        End Get
        Private Set(ByVal value As Boolean)
            _isDeserializing = value
        End Set
    End Property

    <OnDeserializing()>
    Public Sub OnDeserializingMethod(ByVal context As StreamingContext)
        IsDeserializing = True
    End Sub

    <OnDeserialized()>
    Public Sub OnDeserializedMethod(ByVal context As StreamingContext)
        IsDeserializing = False
        ChangeTracker.ChangeTrackingEnabled = True
    End Sub

    Protected Overridable Sub ClearNavigationProperties()
        LowTaxLiquidation = Nothing
    End Sub

#End Region

#Region "Association Fixup"

    Private Sub FixupLowTaxLiquidation(ByVal previousValue As LowTaxLiquidation)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.LowTaxLiquidationDetail.Contains(Me) Then
            previousValue.LowTaxLiquidationDetail.Remove(Me)
        End If

        If LowTaxLiquidation IsNot Nothing Then
            LowTaxLiquidation.LowTaxLiquidationDetail.Add(Me)

            LowTaxLiquidationId = LowTaxLiquidation.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("LowTaxLiquidation") AndAlso
                ChangeTracker.OriginalValues("LowTaxLiquidation") Is LowTaxLiquidation Then
                ChangeTracker.OriginalValues.Remove("LowTaxLiquidation")
            Else
                ChangeTracker.RecordOriginalValue("LowTaxLiquidation", previousValue)
            End If
            If LowTaxLiquidation IsNot Nothing AndAlso Not LowTaxLiquidation.ChangeTracker.ChangeTrackingEnabled Then
                LowTaxLiquidation.StartTracking()
            End If
        End If
    End Sub

#End Region

End Class

