'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel
Imports System.Globalization
Imports System.IO
Imports System.Reflection
Imports System.Runtime.Serialization.Formatters.Binary
Imports System.Runtime.Serialization
Imports System.Runtime.CompilerServices
Imports Domain.Base.Entities
Imports System.Data.Entity.ModelConfiguration

<DataContract(IsReference:=True), Serializable(), KnownType(GetType(Package))>
<KnownType(GetType(InventoryMeasurementUnit))>
<KnownType(GetType(InventoryProduct))>
<KnownType(GetType(InventoryRiskLevel))>
<KnownType(GetType(ProductRateDetail))>
<KnownType(GetType(ProductSubGroup))>
<KnownType(GetType(ConfirmationUnitDose))>
<KnownType(GetType(Package))>
<KnownType(GetType(UnitDoseType))>
<KnownType(GetType(PackageDetail))>
<KnownType(GetType(PackagePersonalized))>
<KnownType(GetType(RequestMixingStationDetail))>
<KnownType(GetType(RequestPackageDetailStatus))>
<KnownType(GetType(RequestUnitDoseExternalCareCenterMaquila))>
<KnownType(GetType(RequestUnitDoseInventoryDetail))>
<KnownType(GetType(ProductGroup))>
<KnownType(GetType(ATCEntity))>
<KnownType(GetType(ExternalPatientPreparation))>
<KnownType(GetType(ATC))>
Partial Public Class Package
	Inherits Entity(Of Package)
    Implements IObjectWithChangeTracker
    Implements INotifyPropertyChanged

#Region "Simple Properties"

	Private _id As Integer
	<DataMember()>
	Public Property Id() As Integer
        Get
            Return _id
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_id, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'Id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _id = value
                OnPropertyChanged("Id")
            End If
        End Set
    End Property

	Private _code As String
	<DataMember()>
	Public Property Code() As String
        Get
            Return _code
        End Get
        Set(ByVal value As String)
            If Not Equals(_code, value) Then
                _code = value
                OnPropertyChanged("Code")
            End If
        End Set
    End Property

	Private _name As String
	<DataMember()>
	Public Property Name() As String
        Get
            Return _name
        End Get
        Set(ByVal value As String)
            If Not Equals(_name, value) Then
                _name = value
                OnPropertyChanged("Name")
            End If
        End Set
    End Property

	Private _description As String
	<DataMember()>
	Public Property Description() As String
        Get
            Return _description
        End Get
        Set(ByVal value As String)
            If Not Equals(_description, value) Then
                _description = value
                OnPropertyChanged("Description")
            End If
        End Set
    End Property

	Private _riskLevelId As Nullable(Of Integer)
	<DataMember()>
	Public Property RiskLevelId() As Nullable(Of Integer)
        Get
            Return _riskLevelId
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_riskLevelId, value) Then
                ChangeTracker.RecordOriginalValue("RiskLevelId", _riskLevelId)
                If Not IsDeserializing Then
                    If InventoryRiskLevel IsNot Nothing AndAlso Not Equals(InventoryRiskLevel.Id, value) Then
                        InventoryRiskLevel = Nothing
                    End If
                End If
                _riskLevelId = value
                OnPropertyChanged("RiskLevelId")
            End If
        End Set
    End Property

	Private _codeAlternative As String
	<DataMember()>
	Public Property CodeAlternative() As String
        Get
            Return _codeAlternative
        End Get
        Set(ByVal value As String)
            If Not Equals(_codeAlternative, value) Then
                _codeAlternative = value
                OnPropertyChanged("CodeAlternative")
            End If
        End Set
    End Property

	Private _codeAlternativeTwo As String
	<DataMember()>
	Public Property CodeAlternativeTwo() As String
        Get
            Return _codeAlternativeTwo
        End Get
        Set(ByVal value As String)
            If Not Equals(_codeAlternativeTwo, value) Then
                _codeAlternativeTwo = value
                OnPropertyChanged("CodeAlternativeTwo")
            End If
        End Set
    End Property

	Private _productGroupId As Nullable(Of Integer)
	<DataMember()>
	Public Property ProductGroupId() As Nullable(Of Integer)
        Get
            Return _productGroupId
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_productGroupId, value) Then
                ChangeTracker.RecordOriginalValue("ProductGroupId", _productGroupId)
                If Not IsDeserializing Then
                    If ProductGroup IsNot Nothing AndAlso Not Equals(ProductGroup.Id, value) Then
                        ProductGroup = Nothing
                    End If
                End If
                _productGroupId = value
                OnPropertyChanged("ProductGroupId")
            End If
        End Set
    End Property

	Private _productSubGroupId As Nullable(Of Integer)
	<DataMember()>
	Public Property ProductSubGroupId() As Nullable(Of Integer)
        Get
            Return _productSubGroupId
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_productSubGroupId, value) Then
                ChangeTracker.RecordOriginalValue("ProductSubGroupId", _productSubGroupId)
                If Not IsDeserializing Then
                    If ProductSubGroup IsNot Nothing AndAlso Not Equals(ProductSubGroup.Id, value) Then
                        ProductSubGroup = Nothing
                    End If
                End If
                _productSubGroupId = value
                OnPropertyChanged("ProductSubGroupId")
            End If
        End Set
    End Property

	Private _manufacturerId As Nullable(Of Integer)
	<DataMember()>
	Public Property ManufacturerId() As Nullable(Of Integer)
        Get
            Return _manufacturerId
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_manufacturerId, value) Then
                _manufacturerId = value
                OnPropertyChanged("ManufacturerId")
            End If
        End Set
    End Property

	Private _codeSICE As String
	<DataMember()>
	Public Property CodeSICE() As String
        Get
            Return _codeSICE
        End Get
        Set(ByVal value As String)
            If Not Equals(_codeSICE, value) Then
                _codeSICE = value
                OnPropertyChanged("CodeSICE")
            End If
        End Set
    End Property

	Private _pOSProduct As Nullable(Of Boolean)
	<DataMember()>
	Public Property POSProduct() As Nullable(Of Boolean)
        Get
            Return _pOSProduct
        End Get
        Set(ByVal value As Nullable(Of Boolean))
            If Not Equals(_pOSProduct, value) Then
                _pOSProduct = value
                OnPropertyChanged("POSProduct")
            End If
        End Set
    End Property

	Private _billingGroupId As Nullable(Of Integer)
	<DataMember()>
	Public Property BillingGroupId() As Nullable(Of Integer)
        Get
            Return _billingGroupId
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_billingGroupId, value) Then
                _billingGroupId = value
                OnPropertyChanged("BillingGroupId")
            End If
        End Set
    End Property

	Private _productControl As Nullable(Of Boolean)
	<DataMember()>
	Public Property ProductControl() As Nullable(Of Boolean)
        Get
            Return _productControl
        End Get
        Set(ByVal value As Nullable(Of Boolean))
            If Not Equals(_productControl, value) Then
                _productControl = value
                OnPropertyChanged("ProductControl")
            End If
        End Set
    End Property

	Private _productWithPriceControl As Nullable(Of Boolean)
	<DataMember()>
	Public Property ProductWithPriceControl() As Nullable(Of Boolean)
        Get
            Return _productWithPriceControl
        End Get
        Set(ByVal value As Nullable(Of Boolean))
            If Not Equals(_productWithPriceControl, value) Then
                _productWithPriceControl = value
                OnPropertyChanged("ProductWithPriceControl")
            End If
        End Set
    End Property

	Private _authorizationByOrderNumber As Nullable(Of Integer)
	<DataMember()>
	Public Property AuthorizationByOrderNumber() As Nullable(Of Integer)
        Get
            Return _authorizationByOrderNumber
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_authorizationByOrderNumber, value) Then
                _authorizationByOrderNumber = value
                OnPropertyChanged("AuthorizationByOrderNumber")
            End If
        End Set
    End Property

	Private _maximumControlPeriod As Nullable(Of Boolean)
	<DataMember()>
	Public Property MaximumControlPeriod() As Nullable(Of Boolean)
        Get
            Return _maximumControlPeriod
        End Get
        Set(ByVal value As Nullable(Of Boolean))
            If Not Equals(_maximumControlPeriod, value) Then
                _maximumControlPeriod = value
                OnPropertyChanged("MaximumControlPeriod")
            End If
        End Set
    End Property

	Private _osmolarityTotal As Nullable(Of Decimal)
	<DataMember()>
	Public Property OsmolarityTotal() As Nullable(Of Decimal)
        Get
            Return _osmolarityTotal
        End Get
        Set(ByVal value As Nullable(Of Decimal))
            If Not Equals(_osmolarityTotal, value) Then
                _osmolarityTotal = value
                OnPropertyChanged("OsmolarityTotal")
            End If
        End Set
    End Property

	Private _volumeTotalOrder As Nullable(Of Decimal)
	<DataMember()>
	Public Property VolumeTotalOrder() As Nullable(Of Decimal)
        Get
            Return _volumeTotalOrder
        End Get
        Set(ByVal value As Nullable(Of Decimal))
            If Not Equals(_volumeTotalOrder, value) Then
                _volumeTotalOrder = value
                OnPropertyChanged("VolumeTotalOrder")
            End If
        End Set
    End Property

	Private _volumeTotalOrderMeasurementUnitId As Nullable(Of Integer)
	<DataMember()>
	Public Property VolumeTotalOrderMeasurementUnitId() As Nullable(Of Integer)
        Get
            Return _volumeTotalOrderMeasurementUnitId
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_volumeTotalOrderMeasurementUnitId, value) Then
                ChangeTracker.RecordOriginalValue("VolumeTotalOrderMeasurementUnitId", _volumeTotalOrderMeasurementUnitId)
                If Not IsDeserializing Then
                    If InventoryMeasurementUnit2 IsNot Nothing AndAlso Not Equals(InventoryMeasurementUnit2.Id, value) Then
                        InventoryMeasurementUnit2 = Nothing
                    End If
                End If
                _volumeTotalOrderMeasurementUnitId = value
                OnPropertyChanged("VolumeTotalOrderMeasurementUnitId")
            End If
        End Set
    End Property

	Private _volumeTotalOrderPurga As Nullable(Of Decimal)
	<DataMember()>
	Public Property VolumeTotalOrderPurga() As Nullable(Of Decimal)
        Get
            Return _volumeTotalOrderPurga
        End Get
        Set(ByVal value As Nullable(Of Decimal))
            If Not Equals(_volumeTotalOrderPurga, value) Then
                _volumeTotalOrderPurga = value
                OnPropertyChanged("VolumeTotalOrderPurga")
            End If
        End Set
    End Property

	Private _weightTotalSolution As Nullable(Of Decimal)
	<DataMember()>
	Public Property WeightTotalSolution() As Nullable(Of Decimal)
        Get
            Return _weightTotalSolution
        End Get
        Set(ByVal value As Nullable(Of Decimal))
            If Not Equals(_weightTotalSolution, value) Then
                _weightTotalSolution = value
                OnPropertyChanged("WeightTotalSolution")
            End If
        End Set
    End Property

	Private _creationUser As String
	<DataMember()>
	Public Property CreationUser() As String
        Get
            Return _creationUser
        End Get
        Set(ByVal value As String)
            If Not Equals(_creationUser, value) Then
                _creationUser = value
                OnPropertyChanged("CreationUser")
            End If
        End Set
    End Property

	Private _creationDate As Date
	<DataMember()>
	Public Property CreationDate() As Date
        Get
            Return _creationDate
        End Get
        Set(ByVal value As Date)
            If Not Equals(_creationDate, value) Then
                _creationDate = value
                OnPropertyChanged("CreationDate")
            End If
        End Set
    End Property

	Private _modificationUser As String
	<DataMember()>
	Public Property ModificationUser() As String
        Get
            Return _modificationUser
        End Get
        Set(ByVal value As String)
            If Not Equals(_modificationUser, value) Then
                _modificationUser = value
                OnPropertyChanged("ModificationUser")
            End If
        End Set
    End Property

	Private _modificationDate As Nullable(Of Date)
	<DataMember()>
	Public Property ModificationDate() As Nullable(Of Date)
        Get
            Return _modificationDate
        End Get
        Set(ByVal value As Nullable(Of Date))
            If Not Equals(_modificationDate, value) Then
                _modificationDate = value
                OnPropertyChanged("ModificationDate")
            End If
        End Set
    End Property

	Private _timeStamp As Byte()
	<DataMember()>
	Public Property TimeStamp() As Byte()
        Get
            Return _timeStamp
        End Get
        Set(ByVal value As Byte())
            If _timeStamp IsNot value Then
                _timeStamp = value
                OnPropertyChanged("TimeStamp")
            End If
        End Set
    End Property

	Private _state As Boolean
	<DataMember()>
	Public Property State() As Boolean
        Get
            Return _state
        End Get
        Set(ByVal value As Boolean)
            If Not Equals(_state, value) Then
                _state = value
                OnPropertyChanged("State")
            End If
        End Set
    End Property

	Private _measurementUnitId As Nullable(Of Integer)
	<DataMember()>
	Public Property MeasurementUnitId() As Nullable(Of Integer)
        Get
            Return _measurementUnitId
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_measurementUnitId, value) Then
                ChangeTracker.RecordOriginalValue("MeasurementUnitId", _measurementUnitId)
                If Not IsDeserializing Then
                    If InventoryMeasurementUnit1 IsNot Nothing AndAlso Not Equals(InventoryMeasurementUnit1.Id, value) Then
                        InventoryMeasurementUnit1 = Nothing
                    End If
                End If
                _measurementUnitId = value
                OnPropertyChanged("MeasurementUnitId")
            End If
        End Set
    End Property

	Private _refrigeratedTerm As Integer
	<DataMember()>
	Public Property RefrigeratedTerm() As Integer
        Get
            Return _refrigeratedTerm
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_refrigeratedTerm, value) Then
                _refrigeratedTerm = value
                OnPropertyChanged("RefrigeratedTerm")
            End If
        End Set
    End Property

	Private _environmentalTemperatureTerm As Integer
	<DataMember()>
	Public Property EnvironmentalTemperatureTerm() As Integer
        Get
            Return _environmentalTemperatureTerm
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_environmentalTemperatureTerm, value) Then
                _environmentalTemperatureTerm = value
                OnPropertyChanged("EnvironmentalTemperatureTerm")
            End If
        End Set
    End Property

	Private _purge As Decimal
	<DataMember()>
	Public Property Purge() As Decimal
        Get
            Return _purge
        End Get
        Set(ByVal value As Decimal)
            If Not Equals(_purge, value) Then
                _purge = value
                OnPropertyChanged("Purge")
            End If
        End Set
    End Property

	Private _infusionSpeed As Nullable(Of Integer)
	<DataMember()>
	Public Property InfusionSpeed() As Nullable(Of Integer)
        Get
            Return _infusionSpeed
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_infusionSpeed, value) Then
                _infusionSpeed = value
                OnPropertyChanged("InfusionSpeed")
            End If
        End Set
    End Property

	Private _preparationInstructions As String
	<DataMember()>
	Public Property PreparationInstructions() As String
        Get
            Return _preparationInstructions
        End Get
        Set(ByVal value As String)
            If Not Equals(_preparationInstructions, value) Then
                _preparationInstructions = value
                OnPropertyChanged("PreparationInstructions")
            End If
        End Set
    End Property

	Private _specialConsiderations As String
	<DataMember()>
	Public Property SpecialConsiderations() As String
        Get
            Return _specialConsiderations
        End Get
        Set(ByVal value As String)
            If Not Equals(_specialConsiderations, value) Then
                _specialConsiderations = value
                OnPropertyChanged("SpecialConsiderations")
            End If
        End Set
    End Property

	Private _unitDoseTypeId As Integer
	<DataMember()>
	Public Property UnitDoseTypeId() As Integer
        Get
            Return _unitDoseTypeId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_unitDoseTypeId, value) Then
                ChangeTracker.RecordOriginalValue("UnitDoseTypeId", _unitDoseTypeId)
                If Not IsDeserializing Then
                    If UnitDoseType IsNot Nothing AndAlso Not Equals(UnitDoseType.Id, value) Then
                        UnitDoseType = Nothing
                    End If
                End If
                _unitDoseTypeId = value
                OnPropertyChanged("UnitDoseTypeId")
            End If
        End Set
    End Property

	Private _concentration As Nullable(Of Decimal)
	<DataMember()>
	Public Property Concentration() As Nullable(Of Decimal)
        Get
            Return _concentration
        End Get
        Set(ByVal value As Nullable(Of Decimal))
            If Not Equals(_concentration, value) Then
                _concentration = value
                OnPropertyChanged("Concentration")
            End If
        End Set
    End Property

	Private _concentrationMeasurementUnitId As Nullable(Of Integer)
	<DataMember()>
	Public Property ConcentrationMeasurementUnitId() As Nullable(Of Integer)
        Get
            Return _concentrationMeasurementUnitId
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_concentrationMeasurementUnitId, value) Then
                ChangeTracker.RecordOriginalValue("ConcentrationMeasurementUnitId", _concentrationMeasurementUnitId)
                If Not IsDeserializing Then
                    If InventoryMeasurementUnit IsNot Nothing AndAlso Not Equals(InventoryMeasurementUnit.Id, value) Then
                        InventoryMeasurementUnit = Nothing
                    End If
                End If
                _concentrationMeasurementUnitId = value
                OnPropertyChanged("ConcentrationMeasurementUnitId")
            End If
        End Set
    End Property

	Private _aTCId As Nullable(Of Integer)
	<DataMember()>
	Public Property ATCId() As Nullable(Of Integer)
        Get
            Return _aTCId
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_aTCId, value) Then
                ChangeTracker.RecordOriginalValue("ATCId", _aTCId)
                If Not IsDeserializing Then
                    If ATCEntity IsNot Nothing AndAlso Not Equals(ATCEntity.Id, value) Then
                        ATCEntity = Nothing
                    End If
                End If
                _aTCId = value
                OnPropertyChanged("ATCId")
            End If
        End Set
    End Property

	Private _justification As String
	<DataMember()>
	Public Property Justification() As String
        Get
            Return _justification
        End Get
        Set(ByVal value As String)
            If Not Equals(_justification, value) Then
                _justification = value
                OnPropertyChanged("Justification")
            End If
        End Set
    End Property

	Private _standardMix As Nullable(Of Boolean)
	<DataMember()>
	Public Property StandardMix() As Nullable(Of Boolean)
        Get
            Return _standardMix
        End Get
        Set(ByVal value As Nullable(Of Boolean))
            If Not Equals(_standardMix, value) Then
                _standardMix = value
                OnPropertyChanged("StandardMix")
            End If
        End Set
    End Property

	Private _photoProtection As Boolean
	<DataMember()>
	Public Property PhotoProtection() As Boolean
        Get
            Return _photoProtection
        End Get
        Set(ByVal value As Boolean)
            If Not Equals(_photoProtection, value) Then
                _photoProtection = value
                OnPropertyChanged("PhotoProtection")
            End If
        End Set
    End Property

	Private _preparationType As Nullable(Of Byte)
	<DataMember()>
	Public Property PreparationType() As Nullable(Of Byte)
        Get
            Return _preparationType
        End Get
        Set(ByVal value As Nullable(Of Byte))
            If Not Equals(_preparationType, value) Then
                _preparationType = value
                OnPropertyChanged("PreparationType")
            End If
        End Set
    End Property

	Private _personalizedMasterPreparation As Boolean
	<DataMember()>
	Public Property PersonalizedMasterPreparation() As Boolean
        Get
            Return _personalizedMasterPreparation
        End Get
        Set(ByVal value As Boolean)
            If Not Equals(_personalizedMasterPreparation, value) Then
                _personalizedMasterPreparation = value
                OnPropertyChanged("PersonalizedMasterPreparation")
            End If
        End Set
    End Property

	Private _associatedPackageId As Nullable(Of Integer)
	<DataMember()>
	Public Property AssociatedPackageId() As Nullable(Of Integer)
        Get
            Return _associatedPackageId
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_associatedPackageId, value) Then
                ChangeTracker.RecordOriginalValue("AssociatedPackageId", _associatedPackageId)
                If Not IsDeserializing Then
                    If Package2 IsNot Nothing AndAlso Not Equals(Package2.Id, value) Then
                        Package2 = Nothing
                    End If
                End If
                _associatedPackageId = value
                OnPropertyChanged("AssociatedPackageId")
            End If
        End Set
    End Property

	Private _labelType As Nullable(Of Byte)
	<DataMember()>
	Public Property LabelType() As Nullable(Of Byte)
        Get
            Return _labelType
        End Get
        Set(ByVal value As Nullable(Of Byte))
            If Not Equals(_labelType, value) Then
                _labelType = value
                OnPropertyChanged("LabelType")
            End If
        End Set
    End Property

	Private _productId As Nullable(Of Integer)
	<DataMember()>
	Public Property ProductId() As Nullable(Of Integer)
        Get
            Return _productId
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_productId, value) Then
                ChangeTracker.RecordOriginalValue("ProductId", _productId)
                If Not IsDeserializing Then
                    If InventoryProduct IsNot Nothing AndAlso Not Equals(InventoryProduct.Id, value) Then
                        InventoryProduct = Nothing
                    End If
                End If
                _productId = value
                OnPropertyChanged("ProductId")
            End If
        End Set
    End Property

	Private _vehicleOptimization As Boolean
	<DataMember()>
	Public Property VehicleOptimization() As Boolean
        Get
            Return _vehicleOptimization
        End Get
        Set(ByVal value As Boolean)
            If Not Equals(_vehicleOptimization, value) Then
                _vehicleOptimization = value
                OnPropertyChanged("VehicleOptimization")
            End If
        End Set
    End Property

	Private _storage As Nullable(Of Integer)
	<DataMember()>
	Public Property Storage() As Nullable(Of Integer)
        Get
            Return _storage
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_storage, value) Then
                _storage = value
                OnPropertyChanged("Storage")
            End If
        End Set
    End Property

	Private _readjustments As Byte
	<DataMember()>
	Public Property Readjustments() As Byte
        Get
            Return _readjustments
        End Get
        Set(ByVal value As Byte)
            If Not Equals(_readjustments, value) Then
                _readjustments = value
                OnPropertyChanged("Readjustments")
            End If
        End Set
    End Property

	Private _concentrationAntibiotic As String
	<DataMember()>
	Public Property ConcentrationAntibiotic() As String
        Get
            Return _concentrationAntibiotic
        End Get
        Set(ByVal value As String)
            If Not Equals(_concentrationAntibiotic, value) Then
                _concentrationAntibiotic = value
                OnPropertyChanged("ConcentrationAntibiotic")
            End If
        End Set
    End Property

	Private _volumeTotalPrepared As Nullable(Of Decimal)
	<DataMember()>
	Public Property VolumeTotalPrepared() As Nullable(Of Decimal)
        Get
            Return _volumeTotalPrepared
        End Get
        Set(ByVal value As Nullable(Of Decimal))
            If Not Equals(_volumeTotalPrepared, value) Then
                _volumeTotalPrepared = value
                OnPropertyChanged("VolumeTotalPrepared")
            End If
        End Set
    End Property

	Private _measurementPreparedId As Nullable(Of Integer)
	<DataMember()>
	Public Property MeasurementPreparedId() As Nullable(Of Integer)
        Get
            Return _measurementPreparedId
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_measurementPreparedId, value) Then
                ChangeTracker.RecordOriginalValue("MeasurementPreparedId", _measurementPreparedId)
                If Not IsDeserializing Then
                    If InventoryMeasurementUnit3 IsNot Nothing AndAlso Not Equals(InventoryMeasurementUnit3.Id, value) Then
                        InventoryMeasurementUnit3 = Nothing
                    End If
                End If
                _measurementPreparedId = value
                OnPropertyChanged("MeasurementPreparedId")
            End If
        End Set
    End Property

	Private _nptId As Nullable(Of Integer)
	<DataMember()>
	Public Property NptId() As Nullable(Of Integer)
        Get
            Return _nptId
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_nptId, value) Then
                _nptId = value
                OnPropertyChanged("NptId")
            End If
        End Set
    End Property

	Private _mainDrugId As Nullable(Of Integer)
	<DataMember()>
	Public Property MainDrugId() As Nullable(Of Integer)
        Get
            Return _mainDrugId
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_mainDrugId, value) Then
                ChangeTracker.RecordOriginalValue("MainDrugId", _mainDrugId)
                If Not IsDeserializing Then
                    If ATC IsNot Nothing AndAlso Not Equals(ATC.Id, value) Then
                        ATC = Nothing
                    End If
                End If
                _mainDrugId = value
                OnPropertyChanged("MainDrugId")
            End If
        End Set
    End Property

	Private _stabilityHour As Nullable(Of System.TimeSpan)
	<DataMember()>
	Public Property StabilityHour() As Nullable(Of System.TimeSpan)
        Get
            Return _stabilityHour
        End Get
        Set(ByVal value As Nullable(Of System.TimeSpan))
            If Not Equals(_stabilityHour, value) Then
                _stabilityHour = value
                OnPropertyChanged("StabilityHour")
            End If
        End Set
    End Property

	Private _typeStability As Nullable(Of Byte)
	<DataMember()>
	Public Property TypeStability() As Nullable(Of Byte)
        Get
            Return _typeStability
        End Get
        Set(ByVal value As Nullable(Of Byte))
            If Not Equals(_typeStability, value) Then
                _typeStability = value
                OnPropertyChanged("TypeStability")
            End If
        End Set
    End Property

	Private _stabilityDays As Nullable(Of Integer)
	<DataMember()>
	Public Property StabilityDays() As Nullable(Of Integer)
        Get
            Return _stabilityDays
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_stabilityDays, value) Then
                _stabilityDays = value
                OnPropertyChanged("StabilityDays")
            End If
        End Set
    End Property

#End Region

#Region "Navigation Properties"

    <DataMember()>
    Public Property InventoryMeasurementUnit() As InventoryMeasurementUnit
        Get
            Return _inventoryMeasurementUnit
        End Get
        Set(ByVal value As InventoryMeasurementUnit)
            If _inventoryMeasurementUnit IsNot value Then
                Dim previousValue As InventoryMeasurementUnit = _inventoryMeasurementUnit
                _inventoryMeasurementUnit = value
                FixupInventoryMeasurementUnit(previousValue)
                OnNavigationPropertyChanged("InventoryMeasurementUnit")
            End If
        End Set
    End Property

    Private _inventoryMeasurementUnit As InventoryMeasurementUnit


    <DataMember()>
    Public Property InventoryMeasurementUnit1() As InventoryMeasurementUnit
        Get
            Return _inventoryMeasurementUnit1
        End Get
        Set(ByVal value As InventoryMeasurementUnit)
            If _inventoryMeasurementUnit1 IsNot value Then
                Dim previousValue As InventoryMeasurementUnit = _inventoryMeasurementUnit1
                _inventoryMeasurementUnit1 = value
                FixupInventoryMeasurementUnit1(previousValue)
                OnNavigationPropertyChanged("InventoryMeasurementUnit1")
            End If
        End Set
    End Property

    Private _inventoryMeasurementUnit1 As InventoryMeasurementUnit


    <DataMember()>
    Public Property InventoryMeasurementUnit2() As InventoryMeasurementUnit
        Get
            Return _inventoryMeasurementUnit2
        End Get
        Set(ByVal value As InventoryMeasurementUnit)
            If _inventoryMeasurementUnit2 IsNot value Then
                Dim previousValue As InventoryMeasurementUnit = _inventoryMeasurementUnit2
                _inventoryMeasurementUnit2 = value
                FixupInventoryMeasurementUnit2(previousValue)
                OnNavigationPropertyChanged("InventoryMeasurementUnit2")
            End If
        End Set
    End Property

    Private _inventoryMeasurementUnit2 As InventoryMeasurementUnit


    <DataMember()>
    Public Property InventoryProduct() As InventoryProduct
        Get
            Return _inventoryProduct
        End Get
        Set(ByVal value As InventoryProduct)
            If _inventoryProduct IsNot value Then
                Dim previousValue As InventoryProduct = _inventoryProduct
                _inventoryProduct = value
                FixupInventoryProduct(previousValue)
                OnNavigationPropertyChanged("InventoryProduct")
            End If
        End Set
    End Property

    Private _inventoryProduct As InventoryProduct


    <DataMember()>
    Public Property InventoryRiskLevel() As InventoryRiskLevel
        Get
            Return _inventoryRiskLevel
        End Get
        Set(ByVal value As InventoryRiskLevel)
            If _inventoryRiskLevel IsNot value Then
                Dim previousValue As InventoryRiskLevel = _inventoryRiskLevel
                _inventoryRiskLevel = value
                FixupInventoryRiskLevel(previousValue)
                OnNavigationPropertyChanged("InventoryRiskLevel")
            End If
        End Set
    End Property

    Private _inventoryRiskLevel As InventoryRiskLevel


    <DataMember()>
	Public Property ProductRateDetail() As TrackableCollection(Of ProductRateDetail)
		Get
            If _productRateDetail Is Nothing Then
                _productRateDetail = New TrackableCollection(Of ProductRateDetail)
                AddHandler _productRateDetail.CollectionChanged, AddressOf FixupProductRateDetail
            End If
            Return _productRateDetail
        End Get
        Set(ByVal value As TrackableCollection(Of ProductRateDetail))
            If _productRateDetail IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _productRateDetail IsNot Nothing Then
                    RemoveHandler _productRateDetail.CollectionChanged, AddressOf FixupProductRateDetail
                End If
                _productRateDetail = value
                If _productRateDetail IsNot Nothing Then
                    AddHandler _productRateDetail.CollectionChanged, AddressOf FixupProductRateDetail
                End If
                OnNavigationPropertyChanged("ProductRateDetail")
            End If
        End Set
    End Property

    Private _productRateDetail As TrackableCollection(Of ProductRateDetail)

    <DataMember()>
    Public Property ProductSubGroup() As ProductSubGroup
        Get
            Return _productSubGroup
        End Get
        Set(ByVal value As ProductSubGroup)
            If _productSubGroup IsNot value Then
                Dim previousValue As ProductSubGroup = _productSubGroup
                _productSubGroup = value
                FixupProductSubGroup(previousValue)
                OnNavigationPropertyChanged("ProductSubGroup")
            End If
        End Set
    End Property

    Private _productSubGroup As ProductSubGroup


    <DataMember()>
	Public Property ConfirmationUnitDose() As TrackableCollection(Of ConfirmationUnitDose)
		Get
            If _confirmationUnitDose Is Nothing Then
                _confirmationUnitDose = New TrackableCollection(Of ConfirmationUnitDose)
                AddHandler _confirmationUnitDose.CollectionChanged, AddressOf FixupConfirmationUnitDose
            End If
            Return _confirmationUnitDose
        End Get
        Set(ByVal value As TrackableCollection(Of ConfirmationUnitDose))
            If _confirmationUnitDose IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _confirmationUnitDose IsNot Nothing Then
                    RemoveHandler _confirmationUnitDose.CollectionChanged, AddressOf FixupConfirmationUnitDose
                End If
                _confirmationUnitDose = value
                If _confirmationUnitDose IsNot Nothing Then
                    AddHandler _confirmationUnitDose.CollectionChanged, AddressOf FixupConfirmationUnitDose
                End If
                OnNavigationPropertyChanged("ConfirmationUnitDose")
            End If
        End Set
    End Property

    Private _confirmationUnitDose As TrackableCollection(Of ConfirmationUnitDose)

    <DataMember()>
	Public Property Package1() As TrackableCollection(Of Package)
		Get
            If _package1 Is Nothing Then
                _package1 = New TrackableCollection(Of Package)
                AddHandler _package1.CollectionChanged, AddressOf FixupPackage1
            End If
            Return _package1
        End Get
        Set(ByVal value As TrackableCollection(Of Package))
            If _package1 IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _package1 IsNot Nothing Then
                    RemoveHandler _package1.CollectionChanged, AddressOf FixupPackage1
                End If
                _package1 = value
                If _package1 IsNot Nothing Then
                    AddHandler _package1.CollectionChanged, AddressOf FixupPackage1
                End If
                OnNavigationPropertyChanged("Package1")
            End If
        End Set
    End Property

    Private _package1 As TrackableCollection(Of Package)

    <DataMember()>
    Public Property Package2() As Package
        Get
            Return _package2
        End Get
        Set(ByVal value As Package)
            If _package2 IsNot value Then
                Dim previousValue As Package = _package2
                _package2 = value
                FixupPackage2(previousValue)
                OnNavigationPropertyChanged("Package2")
            End If
        End Set
    End Property

    Private _package2 As Package


    <DataMember()>
    Public Property UnitDoseType() As UnitDoseType
        Get
            Return _unitDoseType
        End Get
        Set(ByVal value As UnitDoseType)
            If _unitDoseType IsNot value Then
                Dim previousValue As UnitDoseType = _unitDoseType
                _unitDoseType = value
                FixupUnitDoseType(previousValue)
                OnNavigationPropertyChanged("UnitDoseType")
            End If
        End Set
    End Property

    Private _unitDoseType As UnitDoseType


    <DataMember()>
	Public Property PackageDetail() As TrackableCollection(Of PackageDetail)
		Get
            If _packageDetail Is Nothing Then
                _packageDetail = New TrackableCollection(Of PackageDetail)
                AddHandler _packageDetail.CollectionChanged, AddressOf FixupPackageDetail
            End If
            Return _packageDetail
        End Get
        Set(ByVal value As TrackableCollection(Of PackageDetail))
            If _packageDetail IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _packageDetail IsNot Nothing Then
                    RemoveHandler _packageDetail.CollectionChanged, AddressOf FixupPackageDetail
                End If
                _packageDetail = value
                If _packageDetail IsNot Nothing Then
                    AddHandler _packageDetail.CollectionChanged, AddressOf FixupPackageDetail
                End If
                OnNavigationPropertyChanged("PackageDetail")
            End If
        End Set
    End Property

    Private _packageDetail As TrackableCollection(Of PackageDetail)

    <DataMember()>
	Public Property PackagePersonalized() As TrackableCollection(Of PackagePersonalized)
		Get
            If _packagePersonalized Is Nothing Then
                _packagePersonalized = New TrackableCollection(Of PackagePersonalized)
                AddHandler _packagePersonalized.CollectionChanged, AddressOf FixupPackagePersonalized
            End If
            Return _packagePersonalized
        End Get
        Set(ByVal value As TrackableCollection(Of PackagePersonalized))
            If _packagePersonalized IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _packagePersonalized IsNot Nothing Then
                    RemoveHandler _packagePersonalized.CollectionChanged, AddressOf FixupPackagePersonalized
                End If
                _packagePersonalized = value
                If _packagePersonalized IsNot Nothing Then
                    AddHandler _packagePersonalized.CollectionChanged, AddressOf FixupPackagePersonalized
                End If
                OnNavigationPropertyChanged("PackagePersonalized")
            End If
        End Set
    End Property

    Private _packagePersonalized As TrackableCollection(Of PackagePersonalized)

    <DataMember()>
	Public Property RequestMixingStationDetail() As TrackableCollection(Of RequestMixingStationDetail)
		Get
            If _requestMixingStationDetail Is Nothing Then
                _requestMixingStationDetail = New TrackableCollection(Of RequestMixingStationDetail)
                AddHandler _requestMixingStationDetail.CollectionChanged, AddressOf FixupRequestMixingStationDetail
            End If
            Return _requestMixingStationDetail
        End Get
        Set(ByVal value As TrackableCollection(Of RequestMixingStationDetail))
            If _requestMixingStationDetail IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _requestMixingStationDetail IsNot Nothing Then
                    RemoveHandler _requestMixingStationDetail.CollectionChanged, AddressOf FixupRequestMixingStationDetail
                End If
                _requestMixingStationDetail = value
                If _requestMixingStationDetail IsNot Nothing Then
                    AddHandler _requestMixingStationDetail.CollectionChanged, AddressOf FixupRequestMixingStationDetail
                End If
                OnNavigationPropertyChanged("RequestMixingStationDetail")
            End If
        End Set
    End Property

    Private _requestMixingStationDetail As TrackableCollection(Of RequestMixingStationDetail)

    <DataMember()>
	Public Property RequestPackageDetailStatus() As TrackableCollection(Of RequestPackageDetailStatus)
		Get
            If _requestPackageDetailStatus Is Nothing Then
                _requestPackageDetailStatus = New TrackableCollection(Of RequestPackageDetailStatus)
                AddHandler _requestPackageDetailStatus.CollectionChanged, AddressOf FixupRequestPackageDetailStatus
            End If
            Return _requestPackageDetailStatus
        End Get
        Set(ByVal value As TrackableCollection(Of RequestPackageDetailStatus))
            If _requestPackageDetailStatus IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _requestPackageDetailStatus IsNot Nothing Then
                    RemoveHandler _requestPackageDetailStatus.CollectionChanged, AddressOf FixupRequestPackageDetailStatus
                End If
                _requestPackageDetailStatus = value
                If _requestPackageDetailStatus IsNot Nothing Then
                    AddHandler _requestPackageDetailStatus.CollectionChanged, AddressOf FixupRequestPackageDetailStatus
                End If
                OnNavigationPropertyChanged("RequestPackageDetailStatus")
            End If
        End Set
    End Property

    Private _requestPackageDetailStatus As TrackableCollection(Of RequestPackageDetailStatus)

    <DataMember()>
	Public Property RequestUnitDoseExternalCareCenterMaquila() As TrackableCollection(Of RequestUnitDoseExternalCareCenterMaquila)
		Get
            If _requestUnitDoseExternalCareCenterMaquila Is Nothing Then
                _requestUnitDoseExternalCareCenterMaquila = New TrackableCollection(Of RequestUnitDoseExternalCareCenterMaquila)
                AddHandler _requestUnitDoseExternalCareCenterMaquila.CollectionChanged, AddressOf FixupRequestUnitDoseExternalCareCenterMaquila
            End If
            Return _requestUnitDoseExternalCareCenterMaquila
        End Get
        Set(ByVal value As TrackableCollection(Of RequestUnitDoseExternalCareCenterMaquila))
            If _requestUnitDoseExternalCareCenterMaquila IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _requestUnitDoseExternalCareCenterMaquila IsNot Nothing Then
                    RemoveHandler _requestUnitDoseExternalCareCenterMaquila.CollectionChanged, AddressOf FixupRequestUnitDoseExternalCareCenterMaquila
                End If
                _requestUnitDoseExternalCareCenterMaquila = value
                If _requestUnitDoseExternalCareCenterMaquila IsNot Nothing Then
                    AddHandler _requestUnitDoseExternalCareCenterMaquila.CollectionChanged, AddressOf FixupRequestUnitDoseExternalCareCenterMaquila
                End If
                OnNavigationPropertyChanged("RequestUnitDoseExternalCareCenterMaquila")
            End If
        End Set
    End Property

    Private _requestUnitDoseExternalCareCenterMaquila As TrackableCollection(Of RequestUnitDoseExternalCareCenterMaquila)

    <DataMember()>
	Public Property RequestUnitDoseInventoryDetail() As TrackableCollection(Of RequestUnitDoseInventoryDetail)
		Get
            If _requestUnitDoseInventoryDetail Is Nothing Then
                _requestUnitDoseInventoryDetail = New TrackableCollection(Of RequestUnitDoseInventoryDetail)
                AddHandler _requestUnitDoseInventoryDetail.CollectionChanged, AddressOf FixupRequestUnitDoseInventoryDetail
            End If
            Return _requestUnitDoseInventoryDetail
        End Get
        Set(ByVal value As TrackableCollection(Of RequestUnitDoseInventoryDetail))
            If _requestUnitDoseInventoryDetail IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _requestUnitDoseInventoryDetail IsNot Nothing Then
                    RemoveHandler _requestUnitDoseInventoryDetail.CollectionChanged, AddressOf FixupRequestUnitDoseInventoryDetail
                End If
                _requestUnitDoseInventoryDetail = value
                If _requestUnitDoseInventoryDetail IsNot Nothing Then
                    AddHandler _requestUnitDoseInventoryDetail.CollectionChanged, AddressOf FixupRequestUnitDoseInventoryDetail
                End If
                OnNavigationPropertyChanged("RequestUnitDoseInventoryDetail")
            End If
        End Set
    End Property

    Private _requestUnitDoseInventoryDetail As TrackableCollection(Of RequestUnitDoseInventoryDetail)

    <DataMember()>
    Public Property InventoryMeasurementUnit3() As InventoryMeasurementUnit
        Get
            Return _inventoryMeasurementUnit3
        End Get
        Set(ByVal value As InventoryMeasurementUnit)
            If _inventoryMeasurementUnit3 IsNot value Then
                Dim previousValue As InventoryMeasurementUnit = _inventoryMeasurementUnit3
                _inventoryMeasurementUnit3 = value
                FixupInventoryMeasurementUnit3(previousValue)
                OnNavigationPropertyChanged("InventoryMeasurementUnit3")
            End If
        End Set
    End Property

    Private _inventoryMeasurementUnit3 As InventoryMeasurementUnit


    <DataMember()>
    Public Property ProductGroup() As ProductGroup
        Get
            Return _productGroup
        End Get
        Set(ByVal value As ProductGroup)
            If _productGroup IsNot value Then
                Dim previousValue As ProductGroup = _productGroup
                _productGroup = value
                FixupProductGroup(previousValue)
                OnNavigationPropertyChanged("ProductGroup")
            End If
        End Set
    End Property

    Private _productGroup As ProductGroup


    <DataMember()>
    Public Property ATCEntity() As ATCEntity
        Get
            Return _aTCEntity
        End Get
        Set(ByVal value As ATCEntity)
            If _aTCEntity IsNot value Then
                Dim previousValue As ATCEntity = _aTCEntity
                _aTCEntity = value
                FixupATCEntity(previousValue)
                OnNavigationPropertyChanged("ATCEntity")
            End If
        End Set
    End Property

    Private _aTCEntity As ATCEntity


    <DataMember()>
	Public Property ExternalPatientPreparation() As TrackableCollection(Of ExternalPatientPreparation)
		Get
            If _externalPatientPreparation Is Nothing Then
                _externalPatientPreparation = New TrackableCollection(Of ExternalPatientPreparation)
                AddHandler _externalPatientPreparation.CollectionChanged, AddressOf FixupExternalPatientPreparation
            End If
            Return _externalPatientPreparation
        End Get
        Set(ByVal value As TrackableCollection(Of ExternalPatientPreparation))
            If _externalPatientPreparation IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _externalPatientPreparation IsNot Nothing Then
                    RemoveHandler _externalPatientPreparation.CollectionChanged, AddressOf FixupExternalPatientPreparation
                End If
                _externalPatientPreparation = value
                If _externalPatientPreparation IsNot Nothing Then
                    AddHandler _externalPatientPreparation.CollectionChanged, AddressOf FixupExternalPatientPreparation
                End If
                OnNavigationPropertyChanged("ExternalPatientPreparation")
            End If
        End Set
    End Property

    Private _externalPatientPreparation As TrackableCollection(Of ExternalPatientPreparation)

    <DataMember()>
    Public Property ATC() As ATC
        Get
            Return _aTC
        End Get
        Set(ByVal value As ATC)
            If _aTC IsNot value Then
                Dim previousValue As ATC = _aTC
                _aTC = value
                FixupATC(previousValue)
                OnNavigationPropertyChanged("ATC")
            End If
        End Set
    End Property

    Private _aTC As ATC


#End Region

#Region "ChangeTracking"

    Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
        If ChangeTracker.State <> ObjectState.Added AndAlso ChangeTracker.State <> ObjectState.Deleted Then
            ChangeTracker.State = ObjectState.Modified
        End If
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Protected Overridable Sub OnNavigationPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Private _changeTracker As ObjectChangeTracker

    <DataMember()>
    Public Property ChangeTracker() As ObjectChangeTracker Implements IObjectWithChangeTracker.ChangeTracker
        Get
            If _changeTracker Is Nothing Then
                _changeTracker = New ObjectChangeTracker()
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            Return _changeTracker
        End Get
        Set(ByVal value As ObjectChangeTracker)
            If _changeTracker IsNot Nothing Then
                RemoveHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            _changeTracker = value
            If _changeTracker IsNot Nothing Then
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
        End Set
    End Property

    Private Sub HandleObjectStateChanging(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.ClearNavigationProperties()
        End If
    End Sub

    Private _isDeserializing As Boolean
    Protected Property IsDeserializing() As Boolean
        Get
            Return _isDeserializing
        End Get
        Private Set(ByVal value As Boolean)
            _isDeserializing = value
        End Set
    End Property

    <OnDeserializing()>
    Public Sub OnDeserializingMethod(ByVal context As StreamingContext)
        IsDeserializing = True
    End Sub

    <OnDeserialized()>
    Public Sub OnDeserializedMethod(ByVal context As StreamingContext)
        IsDeserializing = False
        ChangeTracker.ChangeTrackingEnabled = True
    End Sub

    Protected Overridable Sub ClearNavigationProperties()
        InventoryMeasurementUnit = Nothing
        InventoryMeasurementUnit1 = Nothing
        InventoryMeasurementUnit2 = Nothing
        InventoryProduct = Nothing
        InventoryRiskLevel = Nothing
        ProductRateDetail.Clear()
        ProductSubGroup = Nothing
        ConfirmationUnitDose.Clear()
        Package1.Clear()
        Package2 = Nothing
        UnitDoseType = Nothing
        PackageDetail.Clear()
        PackagePersonalized.Clear()
        RequestMixingStationDetail.Clear()
        RequestPackageDetailStatus.Clear()
        RequestUnitDoseExternalCareCenterMaquila.Clear()
        RequestUnitDoseInventoryDetail.Clear()
        InventoryMeasurementUnit3 = Nothing
        ProductGroup = Nothing
        ATCEntity = Nothing
        ExternalPatientPreparation.Clear()
        ATC = Nothing
    End Sub

#End Region

#Region "Association Fixup"

    Private Sub FixupInventoryMeasurementUnit(ByVal previousValue As InventoryMeasurementUnit, Optional ByVal skipKeys As Boolean = False)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.Package.Contains(Me) Then
            previousValue.Package.Remove(Me)
        End If

        If InventoryMeasurementUnit IsNot Nothing Then
            InventoryMeasurementUnit.Package.Add(Me)

            ConcentrationMeasurementUnitId = InventoryMeasurementUnit.Id
        ElseIf Not skipKeys Then
            ConcentrationMeasurementUnitId = Nothing
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("InventoryMeasurementUnit") AndAlso
                ChangeTracker.OriginalValues("InventoryMeasurementUnit") Is InventoryMeasurementUnit Then
                ChangeTracker.OriginalValues.Remove("InventoryMeasurementUnit")
            Else
                ChangeTracker.RecordOriginalValue("InventoryMeasurementUnit", previousValue)
            End If
            If InventoryMeasurementUnit IsNot Nothing AndAlso Not InventoryMeasurementUnit.ChangeTracker.ChangeTrackingEnabled Then
                InventoryMeasurementUnit.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupInventoryMeasurementUnit1(ByVal previousValue As InventoryMeasurementUnit, Optional ByVal skipKeys As Boolean = False)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.Package1.Contains(Me) Then
            previousValue.Package1.Remove(Me)
        End If

        If InventoryMeasurementUnit1 IsNot Nothing Then
            InventoryMeasurementUnit1.Package1.Add(Me)

            MeasurementUnitId = InventoryMeasurementUnit1.Id
        ElseIf Not skipKeys Then
            MeasurementUnitId = Nothing
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("InventoryMeasurementUnit1") AndAlso
                ChangeTracker.OriginalValues("InventoryMeasurementUnit1") Is InventoryMeasurementUnit1 Then
                ChangeTracker.OriginalValues.Remove("InventoryMeasurementUnit1")
            Else
                ChangeTracker.RecordOriginalValue("InventoryMeasurementUnit1", previousValue)
            End If
            If InventoryMeasurementUnit1 IsNot Nothing AndAlso Not InventoryMeasurementUnit1.ChangeTracker.ChangeTrackingEnabled Then
                InventoryMeasurementUnit1.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupInventoryMeasurementUnit2(ByVal previousValue As InventoryMeasurementUnit, Optional ByVal skipKeys As Boolean = False)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.Package2.Contains(Me) Then
            previousValue.Package2.Remove(Me)
        End If

        If InventoryMeasurementUnit2 IsNot Nothing Then
            InventoryMeasurementUnit2.Package2.Add(Me)

            VolumeTotalOrderMeasurementUnitId = InventoryMeasurementUnit2.Id
        ElseIf Not skipKeys Then
            VolumeTotalOrderMeasurementUnitId = Nothing
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("InventoryMeasurementUnit2") AndAlso
                ChangeTracker.OriginalValues("InventoryMeasurementUnit2") Is InventoryMeasurementUnit2 Then
                ChangeTracker.OriginalValues.Remove("InventoryMeasurementUnit2")
            Else
                ChangeTracker.RecordOriginalValue("InventoryMeasurementUnit2", previousValue)
            End If
            If InventoryMeasurementUnit2 IsNot Nothing AndAlso Not InventoryMeasurementUnit2.ChangeTracker.ChangeTrackingEnabled Then
                InventoryMeasurementUnit2.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupInventoryProduct(ByVal previousValue As InventoryProduct, Optional ByVal skipKeys As Boolean = False)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.Package.Contains(Me) Then
            previousValue.Package.Remove(Me)
        End If

        If InventoryProduct IsNot Nothing Then
            InventoryProduct.Package.Add(Me)

            ProductId = InventoryProduct.Id
        ElseIf Not skipKeys Then
            ProductId = Nothing
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("InventoryProduct") AndAlso
                ChangeTracker.OriginalValues("InventoryProduct") Is InventoryProduct Then
                ChangeTracker.OriginalValues.Remove("InventoryProduct")
            Else
                ChangeTracker.RecordOriginalValue("InventoryProduct", previousValue)
            End If
            If InventoryProduct IsNot Nothing AndAlso Not InventoryProduct.ChangeTracker.ChangeTrackingEnabled Then
                InventoryProduct.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupInventoryRiskLevel(ByVal previousValue As InventoryRiskLevel, Optional ByVal skipKeys As Boolean = False)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.Package.Contains(Me) Then
            previousValue.Package.Remove(Me)
        End If

        If InventoryRiskLevel IsNot Nothing Then
            InventoryRiskLevel.Package.Add(Me)

            RiskLevelId = InventoryRiskLevel.Id
        ElseIf Not skipKeys Then
            RiskLevelId = Nothing
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("InventoryRiskLevel") AndAlso
                ChangeTracker.OriginalValues("InventoryRiskLevel") Is InventoryRiskLevel Then
                ChangeTracker.OriginalValues.Remove("InventoryRiskLevel")
            Else
                ChangeTracker.RecordOriginalValue("InventoryRiskLevel", previousValue)
            End If
            If InventoryRiskLevel IsNot Nothing AndAlso Not InventoryRiskLevel.ChangeTracker.ChangeTrackingEnabled Then
                InventoryRiskLevel.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupProductSubGroup(ByVal previousValue As ProductSubGroup, Optional ByVal skipKeys As Boolean = False)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.Package.Contains(Me) Then
            previousValue.Package.Remove(Me)
        End If

        If ProductSubGroup IsNot Nothing Then
            ProductSubGroup.Package.Add(Me)

            ProductSubGroupId = ProductSubGroup.Id
        ElseIf Not skipKeys Then
            ProductSubGroupId = Nothing
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("ProductSubGroup") AndAlso
                ChangeTracker.OriginalValues("ProductSubGroup") Is ProductSubGroup Then
                ChangeTracker.OriginalValues.Remove("ProductSubGroup")
            Else
                ChangeTracker.RecordOriginalValue("ProductSubGroup", previousValue)
            End If
            If ProductSubGroup IsNot Nothing AndAlso Not ProductSubGroup.ChangeTracker.ChangeTrackingEnabled Then
                ProductSubGroup.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupPackage2(ByVal previousValue As Package, Optional ByVal skipKeys As Boolean = False)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.Package1.Contains(Me) Then
            previousValue.Package1.Remove(Me)
        End If

        If Package2 IsNot Nothing Then
            Package2.Package1.Add(Me)

            AssociatedPackageId = Package2.Id
        ElseIf Not skipKeys Then
            AssociatedPackageId = Nothing
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("Package2") AndAlso
                ChangeTracker.OriginalValues("Package2") Is Package2 Then
                ChangeTracker.OriginalValues.Remove("Package2")
            Else
                ChangeTracker.RecordOriginalValue("Package2", previousValue)
            End If
            If Package2 IsNot Nothing AndAlso Not Package2.ChangeTracker.ChangeTrackingEnabled Then
                Package2.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupUnitDoseType(ByVal previousValue As UnitDoseType)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.Package.Contains(Me) Then
            previousValue.Package.Remove(Me)
        End If

        If UnitDoseType IsNot Nothing Then
            UnitDoseType.Package.Add(Me)

            UnitDoseTypeId = UnitDoseType.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("UnitDoseType") AndAlso
                ChangeTracker.OriginalValues("UnitDoseType") Is UnitDoseType Then
                ChangeTracker.OriginalValues.Remove("UnitDoseType")
            Else
                ChangeTracker.RecordOriginalValue("UnitDoseType", previousValue)
            End If
            If UnitDoseType IsNot Nothing AndAlso Not UnitDoseType.ChangeTracker.ChangeTrackingEnabled Then
                UnitDoseType.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupInventoryMeasurementUnit3(ByVal previousValue As InventoryMeasurementUnit, Optional ByVal skipKeys As Boolean = False)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.Package3.Contains(Me) Then
            previousValue.Package3.Remove(Me)
        End If

        If InventoryMeasurementUnit3 IsNot Nothing Then
            InventoryMeasurementUnit3.Package3.Add(Me)

            MeasurementPreparedId = InventoryMeasurementUnit3.Id
        ElseIf Not skipKeys Then
            MeasurementPreparedId = Nothing
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("InventoryMeasurementUnit3") AndAlso
                ChangeTracker.OriginalValues("InventoryMeasurementUnit3") Is InventoryMeasurementUnit3 Then
                ChangeTracker.OriginalValues.Remove("InventoryMeasurementUnit3")
            Else
                ChangeTracker.RecordOriginalValue("InventoryMeasurementUnit3", previousValue)
            End If
            If InventoryMeasurementUnit3 IsNot Nothing AndAlso Not InventoryMeasurementUnit3.ChangeTracker.ChangeTrackingEnabled Then
                InventoryMeasurementUnit3.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupProductGroup(ByVal previousValue As ProductGroup, Optional ByVal skipKeys As Boolean = False)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.Package.Contains(Me) Then
            previousValue.Package.Remove(Me)
        End If

        If ProductGroup IsNot Nothing Then
            ProductGroup.Package.Add(Me)

            ProductGroupId = ProductGroup.Id
        ElseIf Not skipKeys Then
            ProductGroupId = Nothing
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("ProductGroup") AndAlso
                ChangeTracker.OriginalValues("ProductGroup") Is ProductGroup Then
                ChangeTracker.OriginalValues.Remove("ProductGroup")
            Else
                ChangeTracker.RecordOriginalValue("ProductGroup", previousValue)
            End If
            If ProductGroup IsNot Nothing AndAlso Not ProductGroup.ChangeTracker.ChangeTrackingEnabled Then
                ProductGroup.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupATCEntity(ByVal previousValue As ATCEntity, Optional ByVal skipKeys As Boolean = False)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.Package.Contains(Me) Then
            previousValue.Package.Remove(Me)
        End If

        If ATCEntity IsNot Nothing Then
            ATCEntity.Package.Add(Me)

            ATCId = ATCEntity.Id
        ElseIf Not skipKeys Then
            ATCId = Nothing
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("ATCEntity") AndAlso
                ChangeTracker.OriginalValues("ATCEntity") Is ATCEntity Then
                ChangeTracker.OriginalValues.Remove("ATCEntity")
            Else
                ChangeTracker.RecordOriginalValue("ATCEntity", previousValue)
            End If
            If ATCEntity IsNot Nothing AndAlso Not ATCEntity.ChangeTracker.ChangeTrackingEnabled Then
                ATCEntity.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupATC(ByVal previousValue As ATC, Optional ByVal skipKeys As Boolean = False)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.Package.Contains(Me) Then
            previousValue.Package.Remove(Me)
        End If

        If ATC IsNot Nothing Then
            ATC.Package.Add(Me)

            MainDrugId = ATC.Id
        ElseIf Not skipKeys Then
            MainDrugId = Nothing
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("ATC") AndAlso
                ChangeTracker.OriginalValues("ATC") Is ATC Then
                ChangeTracker.OriginalValues.Remove("ATC")
            Else
                ChangeTracker.RecordOriginalValue("ATC", previousValue)
            End If
            If ATC IsNot Nothing AndAlso Not ATC.ChangeTracker.ChangeTrackingEnabled Then
                ATC.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupProductRateDetail(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As ProductRateDetail In e.NewItems
                item.Package = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("ProductRateDetail", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As ProductRateDetail In e.OldItems
                If item.Package Is Me Then
                    item.Package = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("ProductRateDetail", item)
                End If
            Next
        End If
    End Sub

    Private Sub FixupConfirmationUnitDose(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As ConfirmationUnitDose In e.NewItems
                item.Package = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("ConfirmationUnitDose", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As ConfirmationUnitDose In e.OldItems
                If item.Package Is Me Then
                    item.Package = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("ConfirmationUnitDose", item)
                End If
            Next
        End If
    End Sub

    Private Sub FixupPackage1(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As Package In e.NewItems
                item.Package2 = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("Package1", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As Package In e.OldItems
                If item.Package2 Is Me Then
                    item.Package2 = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("Package1", item)
                End If
            Next
        End If
    End Sub

    Private Sub FixupPackageDetail(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As PackageDetail In e.NewItems
                item.Package = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("PackageDetail", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As PackageDetail In e.OldItems
                If item.Package Is Me Then
                    item.Package = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("PackageDetail", item)
                End If
            Next
        End If
    End Sub

    Private Sub FixupPackagePersonalized(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As PackagePersonalized In e.NewItems
                item.Package = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("PackagePersonalized", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As PackagePersonalized In e.OldItems
                If item.Package Is Me Then
                    item.Package = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("PackagePersonalized", item)
                End If
            Next
        End If
    End Sub

    Private Sub FixupRequestMixingStationDetail(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As RequestMixingStationDetail In e.NewItems
                item.Package = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("RequestMixingStationDetail", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As RequestMixingStationDetail In e.OldItems
                If item.Package Is Me Then
                    item.Package = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("RequestMixingStationDetail", item)
                End If
            Next
        End If
    End Sub

    Private Sub FixupRequestPackageDetailStatus(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As RequestPackageDetailStatus In e.NewItems
                item.Package = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("RequestPackageDetailStatus", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As RequestPackageDetailStatus In e.OldItems
                If item.Package Is Me Then
                    item.Package = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("RequestPackageDetailStatus", item)
                End If
            Next
        End If
    End Sub

    Private Sub FixupRequestUnitDoseExternalCareCenterMaquila(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As RequestUnitDoseExternalCareCenterMaquila In e.NewItems
                item.Package = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("RequestUnitDoseExternalCareCenterMaquila", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As RequestUnitDoseExternalCareCenterMaquila In e.OldItems
                If item.Package Is Me Then
                    item.Package = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("RequestUnitDoseExternalCareCenterMaquila", item)
                End If
            Next
        End If
    End Sub

    Private Sub FixupRequestUnitDoseInventoryDetail(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As RequestUnitDoseInventoryDetail In e.NewItems
                item.Package = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("RequestUnitDoseInventoryDetail", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As RequestUnitDoseInventoryDetail In e.OldItems
                If item.Package Is Me Then
                    item.Package = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("RequestUnitDoseInventoryDetail", item)
                End If
            Next
        End If
    End Sub

    Private Sub FixupExternalPatientPreparation(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As ExternalPatientPreparation In e.NewItems
                item.Package = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("ExternalPatientPreparation", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As ExternalPatientPreparation In e.OldItems
                If item.Package Is Me Then
                    item.Package = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("ExternalPatientPreparation", item)
                End If
            Next
        End If
    End Sub

#End Region

End Class

