'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel
Imports System.Globalization
Imports System.IO
Imports System.Reflection
Imports System.Runtime.Serialization.Formatters.Binary
Imports System.Runtime.Serialization
Imports System.Runtime.CompilerServices
Imports Domain.Base.Entities
Imports System.Data.Entity.ModelConfiguration

<DataContract(IsReference:=True), Serializable(), KnownType(GetType(RefundDetail))>
<KnownType(GetType(Refunds))>
<KnownType(GetType(VoucherTransaction))>
Partial Public Class RefundDetail
	Inherits Entity(Of RefundDetail)
    Implements IObjectWithChangeTracker
    Implements INotifyPropertyChanged

#Region "Simple Properties"

	Private _id As Integer
	<DataMember()>
	Public Property Id() As Integer
        Get
            Return _id
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_id, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'Id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _id = value
                OnPropertyChanged("Id")
            End If
        End Set
    End Property

	Private _refundId As Integer
	<DataMember()>
	Public Property RefundId() As Integer
        Get
            Return _refundId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_refundId, value) Then
                ChangeTracker.RecordOriginalValue("RefundId", _refundId)
                If Not IsDeserializing Then
                    If Refunds IsNot Nothing AndAlso Not Equals(Refunds.Id, value) Then
                        Refunds = Nothing
                    End If
                End If
                _refundId = value
                OnPropertyChanged("RefundId")
            End If
        End Set
    End Property

	Private _voucherTransactionId As Integer
	<DataMember()>
	Public Property VoucherTransactionId() As Integer
        Get
            Return _voucherTransactionId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_voucherTransactionId, value) Then
                ChangeTracker.RecordOriginalValue("VoucherTransactionId", _voucherTransactionId)
                If Not IsDeserializing Then
                    If VoucherTransaction IsNot Nothing AndAlso Not Equals(VoucherTransaction.Id, value) Then
                        VoucherTransaction = Nothing
                    End If
                End If
                _voucherTransactionId = value
                OnPropertyChanged("VoucherTransactionId")
            End If
        End Set
    End Property

#End Region

#Region "Navigation Properties"

    <DataMember()>
    Public Property Refunds() As Refunds
        Get
            Return _refunds
        End Get
        Set(ByVal value As Refunds)
            If _refunds IsNot value Then
                Dim previousValue As Refunds = _refunds
                _refunds = value
                FixupRefunds(previousValue)
                OnNavigationPropertyChanged("Refunds")
            End If
        End Set
    End Property

    Private _refunds As Refunds


    <DataMember()>
    Public Property VoucherTransaction() As VoucherTransaction
        Get
            Return _voucherTransaction
        End Get
        Set(ByVal value As VoucherTransaction)
            If _voucherTransaction IsNot value Then
                Dim previousValue As VoucherTransaction = _voucherTransaction
                _voucherTransaction = value
                FixupVoucherTransaction(previousValue)
                OnNavigationPropertyChanged("VoucherTransaction")
            End If
        End Set
    End Property

    Private _voucherTransaction As VoucherTransaction


#End Region

#Region "ChangeTracking"

    Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
        If ChangeTracker.State <> ObjectState.Added AndAlso ChangeTracker.State <> ObjectState.Deleted Then
            ChangeTracker.State = ObjectState.Modified
        End If
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Protected Overridable Sub OnNavigationPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Private _changeTracker As ObjectChangeTracker

    <DataMember()>
    Public Property ChangeTracker() As ObjectChangeTracker Implements IObjectWithChangeTracker.ChangeTracker
        Get
            If _changeTracker Is Nothing Then
                _changeTracker = New ObjectChangeTracker()
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            Return _changeTracker
        End Get
        Set(ByVal value As ObjectChangeTracker)
            If _changeTracker IsNot Nothing Then
                RemoveHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            _changeTracker = value
            If _changeTracker IsNot Nothing Then
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
        End Set
    End Property

    Private Sub HandleObjectStateChanging(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.ClearNavigationProperties()
        End If
    End Sub

    Private _isDeserializing As Boolean
    Protected Property IsDeserializing() As Boolean
        Get
            Return _isDeserializing
        End Get
        Private Set(ByVal value As Boolean)
            _isDeserializing = value
        End Set
    End Property

    <OnDeserializing()>
    Public Sub OnDeserializingMethod(ByVal context As StreamingContext)
        IsDeserializing = True
    End Sub

    <OnDeserialized()>
    Public Sub OnDeserializedMethod(ByVal context As StreamingContext)
        IsDeserializing = False
        ChangeTracker.ChangeTrackingEnabled = True
    End Sub

    Protected Overridable Sub ClearNavigationProperties()
        Refunds = Nothing
        VoucherTransaction = Nothing
    End Sub

#End Region

#Region "Association Fixup"

    Private Sub FixupRefunds(ByVal previousValue As Refunds)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.RefundDetail.Contains(Me) Then
            previousValue.RefundDetail.Remove(Me)
        End If

        If Refunds IsNot Nothing Then
            Refunds.RefundDetail.Add(Me)

            RefundId = Refunds.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("Refunds") AndAlso
                ChangeTracker.OriginalValues("Refunds") Is Refunds Then
                ChangeTracker.OriginalValues.Remove("Refunds")
            Else
                ChangeTracker.RecordOriginalValue("Refunds", previousValue)
            End If
            If Refunds IsNot Nothing AndAlso Not Refunds.ChangeTracker.ChangeTrackingEnabled Then
                Refunds.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupVoucherTransaction(ByVal previousValue As VoucherTransaction)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.RefundDetail.Contains(Me) Then
            previousValue.RefundDetail.Remove(Me)
        End If

        If VoucherTransaction IsNot Nothing Then
            VoucherTransaction.RefundDetail.Add(Me)

            VoucherTransactionId = VoucherTransaction.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("VoucherTransaction") AndAlso
                ChangeTracker.OriginalValues("VoucherTransaction") Is VoucherTransaction Then
                ChangeTracker.OriginalValues.Remove("VoucherTransaction")
            Else
                ChangeTracker.RecordOriginalValue("VoucherTransaction", previousValue)
            End If
            If VoucherTransaction IsNot Nothing AndAlso Not VoucherTransaction.ChangeTracker.ChangeTrackingEnabled Then
                VoucherTransaction.StartTracking()
            End If
        End If
    End Sub

#End Region

End Class

