'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel
Imports System.Globalization
Imports System.IO
Imports System.Reflection
Imports System.Runtime.Serialization.Formatters.Binary
Imports System.Runtime.Serialization
Imports System.Runtime.CompilerServices
Imports Domain.Base.Entities
Imports System.Data.Entity.ModelConfiguration

<DataContract(IsReference:=True), Serializable(), KnownType(GetType(RequestUnitDoseExternalCareCenterPatient))>
<KnownType(GetType(PatientExternalCareCenter))>
<KnownType(GetType(RequestUnitDoseExternalCareCenter))>
<KnownType(GetType(RequestUnitDoseExternalCareCenterPatientDetails))>
<KnownType(GetType(UnitDoseType))>
<KnownType(GetType(ExternalPatientPreparation))>
Partial Public Class RequestUnitDoseExternalCareCenterPatient
	Inherits Entity(Of RequestUnitDoseExternalCareCenterPatient)
    Implements IObjectWithChangeTracker
    Implements INotifyPropertyChanged

#Region "Simple Properties"

	Private _id As Integer
	<DataMember()>
	Public Property Id() As Integer
        Get
            Return _id
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_id, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'Id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _id = value
                OnPropertyChanged("Id")
            End If
        End Set
    End Property

	Private _requestUnitDoseExternalCareCenterId As Integer
	<DataMember()>
	Public Property RequestUnitDoseExternalCareCenterId() As Integer
        Get
            Return _requestUnitDoseExternalCareCenterId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_requestUnitDoseExternalCareCenterId, value) Then
                ChangeTracker.RecordOriginalValue("RequestUnitDoseExternalCareCenterId", _requestUnitDoseExternalCareCenterId)
                If Not IsDeserializing Then
                    If RequestUnitDoseExternalCareCenter IsNot Nothing AndAlso Not Equals(RequestUnitDoseExternalCareCenter.Id, value) Then
                        RequestUnitDoseExternalCareCenter = Nothing
                    End If
                End If
                _requestUnitDoseExternalCareCenterId = value
                OnPropertyChanged("RequestUnitDoseExternalCareCenterId")
            End If
        End Set
    End Property

	Private _patientExternalCareCenterId As Integer
	<DataMember()>
	Public Property PatientExternalCareCenterId() As Integer
        Get
            Return _patientExternalCareCenterId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_patientExternalCareCenterId, value) Then
                ChangeTracker.RecordOriginalValue("PatientExternalCareCenterId", _patientExternalCareCenterId)
                If Not IsDeserializing Then
                    If PatientExternalCareCenter IsNot Nothing AndAlso Not Equals(PatientExternalCareCenter.Id, value) Then
                        PatientExternalCareCenter = Nothing
                    End If
                End If
                _patientExternalCareCenterId = value
                OnPropertyChanged("PatientExternalCareCenterId")
            End If
        End Set
    End Property

	Private _externalFunctionalUnitCode As String
	<DataMember()>
	Public Property ExternalFunctionalUnitCode() As String
        Get
            Return _externalFunctionalUnitCode
        End Get
        Set(ByVal value As String)
            If Not Equals(_externalFunctionalUnitCode, value) Then
                _externalFunctionalUnitCode = value
                OnPropertyChanged("ExternalFunctionalUnitCode")
            End If
        End Set
    End Property

	Private _bed As String
	<DataMember()>
	Public Property Bed() As String
        Get
            Return _bed
        End Get
        Set(ByVal value As String)
            If Not Equals(_bed, value) Then
                _bed = value
                OnPropertyChanged("Bed")
            End If
        End Set
    End Property

	Private _unitDoseTypeId As Integer
	<DataMember()>
	Public Property UnitDoseTypeId() As Integer
        Get
            Return _unitDoseTypeId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_unitDoseTypeId, value) Then
                ChangeTracker.RecordOriginalValue("UnitDoseTypeId", _unitDoseTypeId)
                If Not IsDeserializing Then
                    If UnitDoseType IsNot Nothing AndAlso Not Equals(UnitDoseType.Id, value) Then
                        UnitDoseType = Nothing
                    End If
                End If
                _unitDoseTypeId = value
                OnPropertyChanged("UnitDoseTypeId")
            End If
        End Set
    End Property

	Private _nptId As Nullable(Of Integer)
	<DataMember()>
	Public Property NptId() As Nullable(Of Integer)
        Get
            Return _nptId
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_nptId, value) Then
                _nptId = value
                OnPropertyChanged("NptId")
            End If
        End Set
    End Property

#End Region

#Region "Navigation Properties"

    <DataMember()>
    Public Property PatientExternalCareCenter() As PatientExternalCareCenter
        Get
            Return _patientExternalCareCenter
        End Get
        Set(ByVal value As PatientExternalCareCenter)
            If _patientExternalCareCenter IsNot value Then
                Dim previousValue As PatientExternalCareCenter = _patientExternalCareCenter
                _patientExternalCareCenter = value
                FixupPatientExternalCareCenter(previousValue)
                OnNavigationPropertyChanged("PatientExternalCareCenter")
            End If
        End Set
    End Property

    Private _patientExternalCareCenter As PatientExternalCareCenter


    <DataMember()>
    Public Property RequestUnitDoseExternalCareCenter() As RequestUnitDoseExternalCareCenter
        Get
            Return _requestUnitDoseExternalCareCenter
        End Get
        Set(ByVal value As RequestUnitDoseExternalCareCenter)
            If _requestUnitDoseExternalCareCenter IsNot value Then
                Dim previousValue As RequestUnitDoseExternalCareCenter = _requestUnitDoseExternalCareCenter
                _requestUnitDoseExternalCareCenter = value
                FixupRequestUnitDoseExternalCareCenter(previousValue)
                OnNavigationPropertyChanged("RequestUnitDoseExternalCareCenter")
            End If
        End Set
    End Property

    Private _requestUnitDoseExternalCareCenter As RequestUnitDoseExternalCareCenter


    <DataMember()>
	Public Property RequestUnitDoseExternalCareCenterPatientDetails() As TrackableCollection(Of RequestUnitDoseExternalCareCenterPatientDetails)
		Get
            If _requestUnitDoseExternalCareCenterPatientDetails Is Nothing Then
                _requestUnitDoseExternalCareCenterPatientDetails = New TrackableCollection(Of RequestUnitDoseExternalCareCenterPatientDetails)
                AddHandler _requestUnitDoseExternalCareCenterPatientDetails.CollectionChanged, AddressOf FixupRequestUnitDoseExternalCareCenterPatientDetails
            End If
            Return _requestUnitDoseExternalCareCenterPatientDetails
        End Get
        Set(ByVal value As TrackableCollection(Of RequestUnitDoseExternalCareCenterPatientDetails))
            If _requestUnitDoseExternalCareCenterPatientDetails IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _requestUnitDoseExternalCareCenterPatientDetails IsNot Nothing Then
                    RemoveHandler _requestUnitDoseExternalCareCenterPatientDetails.CollectionChanged, AddressOf FixupRequestUnitDoseExternalCareCenterPatientDetails
                End If
                _requestUnitDoseExternalCareCenterPatientDetails = value
                If _requestUnitDoseExternalCareCenterPatientDetails IsNot Nothing Then
                    AddHandler _requestUnitDoseExternalCareCenterPatientDetails.CollectionChanged, AddressOf FixupRequestUnitDoseExternalCareCenterPatientDetails
                End If
                OnNavigationPropertyChanged("RequestUnitDoseExternalCareCenterPatientDetails")
            End If
        End Set
    End Property

    Private _requestUnitDoseExternalCareCenterPatientDetails As TrackableCollection(Of RequestUnitDoseExternalCareCenterPatientDetails)

    <DataMember()>
    Public Property UnitDoseType() As UnitDoseType
        Get
            Return _unitDoseType
        End Get
        Set(ByVal value As UnitDoseType)
            If _unitDoseType IsNot value Then
                Dim previousValue As UnitDoseType = _unitDoseType
                _unitDoseType = value
                FixupUnitDoseType(previousValue)
                OnNavigationPropertyChanged("UnitDoseType")
            End If
        End Set
    End Property

    Private _unitDoseType As UnitDoseType


    <DataMember()>
	Public Property ExternalPatientPreparation() As TrackableCollection(Of ExternalPatientPreparation)
		Get
            If _externalPatientPreparation Is Nothing Then
                _externalPatientPreparation = New TrackableCollection(Of ExternalPatientPreparation)
                AddHandler _externalPatientPreparation.CollectionChanged, AddressOf FixupExternalPatientPreparation
            End If
            Return _externalPatientPreparation
        End Get
        Set(ByVal value As TrackableCollection(Of ExternalPatientPreparation))
            If _externalPatientPreparation IsNot value Then
                If ChangeTracker.ChangeTrackingEnabled Then
                    Throw New InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled")
                End If
                If _externalPatientPreparation IsNot Nothing Then
                    RemoveHandler _externalPatientPreparation.CollectionChanged, AddressOf FixupExternalPatientPreparation
                End If
                _externalPatientPreparation = value
                If _externalPatientPreparation IsNot Nothing Then
                    AddHandler _externalPatientPreparation.CollectionChanged, AddressOf FixupExternalPatientPreparation
                End If
                OnNavigationPropertyChanged("ExternalPatientPreparation")
            End If
        End Set
    End Property

    Private _externalPatientPreparation As TrackableCollection(Of ExternalPatientPreparation)

#End Region

#Region "ChangeTracking"

    Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
        If ChangeTracker.State <> ObjectState.Added AndAlso ChangeTracker.State <> ObjectState.Deleted Then
            ChangeTracker.State = ObjectState.Modified
        End If
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Protected Overridable Sub OnNavigationPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Private _changeTracker As ObjectChangeTracker

    <DataMember()>
    Public Property ChangeTracker() As ObjectChangeTracker Implements IObjectWithChangeTracker.ChangeTracker
        Get
            If _changeTracker Is Nothing Then
                _changeTracker = New ObjectChangeTracker()
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            Return _changeTracker
        End Get
        Set(ByVal value As ObjectChangeTracker)
            If _changeTracker IsNot Nothing Then
                RemoveHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            _changeTracker = value
            If _changeTracker IsNot Nothing Then
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
        End Set
    End Property

    Private Sub HandleObjectStateChanging(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.ClearNavigationProperties()
        End If
    End Sub

    Private _isDeserializing As Boolean
    Protected Property IsDeserializing() As Boolean
        Get
            Return _isDeserializing
        End Get
        Private Set(ByVal value As Boolean)
            _isDeserializing = value
        End Set
    End Property

    <OnDeserializing()>
    Public Sub OnDeserializingMethod(ByVal context As StreamingContext)
        IsDeserializing = True
    End Sub

    <OnDeserialized()>
    Public Sub OnDeserializedMethod(ByVal context As StreamingContext)
        IsDeserializing = False
        ChangeTracker.ChangeTrackingEnabled = True
    End Sub

    Protected Overridable Sub ClearNavigationProperties()
        PatientExternalCareCenter = Nothing
        RequestUnitDoseExternalCareCenter = Nothing
        RequestUnitDoseExternalCareCenterPatientDetails.Clear()
        UnitDoseType = Nothing
        ExternalPatientPreparation.Clear()
    End Sub

#End Region

#Region "Association Fixup"

    Private Sub FixupPatientExternalCareCenter(ByVal previousValue As PatientExternalCareCenter)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.RequestUnitDoseExternalCareCenterPatient.Contains(Me) Then
            previousValue.RequestUnitDoseExternalCareCenterPatient.Remove(Me)
        End If

        If PatientExternalCareCenter IsNot Nothing Then
            PatientExternalCareCenter.RequestUnitDoseExternalCareCenterPatient.Add(Me)

            PatientExternalCareCenterId = PatientExternalCareCenter.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("PatientExternalCareCenter") AndAlso
                ChangeTracker.OriginalValues("PatientExternalCareCenter") Is PatientExternalCareCenter Then
                ChangeTracker.OriginalValues.Remove("PatientExternalCareCenter")
            Else
                ChangeTracker.RecordOriginalValue("PatientExternalCareCenter", previousValue)
            End If
            If PatientExternalCareCenter IsNot Nothing AndAlso Not PatientExternalCareCenter.ChangeTracker.ChangeTrackingEnabled Then
                PatientExternalCareCenter.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupRequestUnitDoseExternalCareCenter(ByVal previousValue As RequestUnitDoseExternalCareCenter)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.RequestUnitDoseExternalCareCenterPatient.Contains(Me) Then
            previousValue.RequestUnitDoseExternalCareCenterPatient.Remove(Me)
        End If

        If RequestUnitDoseExternalCareCenter IsNot Nothing Then
            RequestUnitDoseExternalCareCenter.RequestUnitDoseExternalCareCenterPatient.Add(Me)

            RequestUnitDoseExternalCareCenterId = RequestUnitDoseExternalCareCenter.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("RequestUnitDoseExternalCareCenter") AndAlso
                ChangeTracker.OriginalValues("RequestUnitDoseExternalCareCenter") Is RequestUnitDoseExternalCareCenter Then
                ChangeTracker.OriginalValues.Remove("RequestUnitDoseExternalCareCenter")
            Else
                ChangeTracker.RecordOriginalValue("RequestUnitDoseExternalCareCenter", previousValue)
            End If
            If RequestUnitDoseExternalCareCenter IsNot Nothing AndAlso Not RequestUnitDoseExternalCareCenter.ChangeTracker.ChangeTrackingEnabled Then
                RequestUnitDoseExternalCareCenter.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupUnitDoseType(ByVal previousValue As UnitDoseType)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.RequestUnitDoseExternalCareCenterPatient.Contains(Me) Then
            previousValue.RequestUnitDoseExternalCareCenterPatient.Remove(Me)
        End If

        If UnitDoseType IsNot Nothing Then
            UnitDoseType.RequestUnitDoseExternalCareCenterPatient.Add(Me)

            UnitDoseTypeId = UnitDoseType.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("UnitDoseType") AndAlso
                ChangeTracker.OriginalValues("UnitDoseType") Is UnitDoseType Then
                ChangeTracker.OriginalValues.Remove("UnitDoseType")
            Else
                ChangeTracker.RecordOriginalValue("UnitDoseType", previousValue)
            End If
            If UnitDoseType IsNot Nothing AndAlso Not UnitDoseType.ChangeTracker.ChangeTrackingEnabled Then
                UnitDoseType.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupRequestUnitDoseExternalCareCenterPatientDetails(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As RequestUnitDoseExternalCareCenterPatientDetails In e.NewItems
                item.RequestUnitDoseExternalCareCenterPatient = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("RequestUnitDoseExternalCareCenterPatientDetails", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As RequestUnitDoseExternalCareCenterPatientDetails In e.OldItems
                If item.RequestUnitDoseExternalCareCenterPatient Is Me Then
                    item.RequestUnitDoseExternalCareCenterPatient = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("RequestUnitDoseExternalCareCenterPatientDetails", item)
                End If
            Next
        End If
    End Sub

    Private Sub FixupExternalPatientPreparation(ByVal sender As Object, ByVal e As NotifyCollectionChangedEventArgs)
        If IsDeserializing Then
            Return
        End If

        If e.NewItems IsNot Nothing Then
            For Each item As ExternalPatientPreparation In e.NewItems
                item.RequestUnitDoseExternalCareCenterPatient = Me
                If ChangeTracker.ChangeTrackingEnabled Then
                    If Not item.ChangeTracker.ChangeTrackingEnabled Then
                        item.StartTracking()
                    End If
                    ChangeTracker.RecordAdditionToCollectionProperties("ExternalPatientPreparation", item)
                End If
            Next
        End If

        If e.OldItems IsNot Nothing Then
            For Each item As ExternalPatientPreparation In e.OldItems
                If item.RequestUnitDoseExternalCareCenterPatient Is Me Then
                    item.RequestUnitDoseExternalCareCenterPatient = Nothing
                End If
                If ChangeTracker.ChangeTrackingEnabled Then
                    ChangeTracker.RecordRemovalFromCollectionProperties("ExternalPatientPreparation", item)
                End If
            Next
        End If
    End Sub

#End Region

End Class

