'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel
Imports System.Globalization
Imports System.IO
Imports System.Reflection
Imports System.Runtime.Serialization.Formatters.Binary
Imports System.Runtime.Serialization
Imports System.Runtime.CompilerServices
Imports Domain.Base.Entities
Imports System.Data.Entity.ModelConfiguration

<DataContract(IsReference:=True), Serializable(), KnownType(GetType(SettingInventoryMedicationsControl))>
<KnownType(GetType(SettingInventory))>
Partial Public Class SettingInventoryMedicationsControl
	Inherits Entity(Of SettingInventoryMedicationsControl)
    Implements IObjectWithChangeTracker
    Implements INotifyPropertyChanged

#Region "Simple Properties"

	Private _id As Integer
	<DataMember()>
	Public Property Id() As Integer
        Get
            Return _id
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_id, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'Id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _id = value
                OnPropertyChanged("Id")
            End If
        End Set
    End Property

	Private _settingInventoryId As Integer
	<DataMember()>
	Public Property SettingInventoryId() As Integer
        Get
            Return _settingInventoryId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_settingInventoryId, value) Then
                ChangeTracker.RecordOriginalValue("SettingInventoryId", _settingInventoryId)
                If Not IsDeserializing Then
                    If SettingInventory IsNot Nothing AndAlso Not Equals(SettingInventory.Id, value) Then
                        SettingInventory = Nothing
                    End If
                End If
                _settingInventoryId = value
                OnPropertyChanged("SettingInventoryId")
            End If
        End Set
    End Property

	Private _doseFrom As Nullable(Of Integer)
	<DataMember()>
	Public Property DoseFrom() As Nullable(Of Integer)
        Get
            Return _doseFrom
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_doseFrom, value) Then
                _doseFrom = value
                OnPropertyChanged("DoseFrom")
            End If
        End Set
    End Property

	Private _doseTo As Nullable(Of Integer)
	<DataMember()>
	Public Property DoseTo() As Nullable(Of Integer)
        Get
            Return _doseTo
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_doseTo, value) Then
                _doseTo = value
                OnPropertyChanged("DoseTo")
            End If
        End Set
    End Property

	Private _color As Integer
	<DataMember()>
	Public Property Color() As Integer
        Get
            Return _color
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_color, value) Then
                _color = value
                OnPropertyChanged("Color")
            End If
        End Set
    End Property

#End Region

#Region "Navigation Properties"

    <DataMember()>
    Public Property SettingInventory() As SettingInventory
        Get
            Return _settingInventory
        End Get
        Set(ByVal value As SettingInventory)
            If _settingInventory IsNot value Then
                Dim previousValue As SettingInventory = _settingInventory
                _settingInventory = value
                FixupSettingInventory(previousValue)
                OnNavigationPropertyChanged("SettingInventory")
            End If
        End Set
    End Property

    Private _settingInventory As SettingInventory


#End Region

#Region "ChangeTracking"

    Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
        If ChangeTracker.State <> ObjectState.Added AndAlso ChangeTracker.State <> ObjectState.Deleted Then
            ChangeTracker.State = ObjectState.Modified
        End If
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Protected Overridable Sub OnNavigationPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Private _changeTracker As ObjectChangeTracker

    <DataMember()>
    Public Property ChangeTracker() As ObjectChangeTracker Implements IObjectWithChangeTracker.ChangeTracker
        Get
            If _changeTracker Is Nothing Then
                _changeTracker = New ObjectChangeTracker()
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            Return _changeTracker
        End Get
        Set(ByVal value As ObjectChangeTracker)
            If _changeTracker IsNot Nothing Then
                RemoveHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            _changeTracker = value
            If _changeTracker IsNot Nothing Then
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
        End Set
    End Property

    Private Sub HandleObjectStateChanging(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.ClearNavigationProperties()
        End If
    End Sub

    Private _isDeserializing As Boolean
    Protected Property IsDeserializing() As Boolean
        Get
            Return _isDeserializing
        End Get
        Private Set(ByVal value As Boolean)
            _isDeserializing = value
        End Set
    End Property

    <OnDeserializing()>
    Public Sub OnDeserializingMethod(ByVal context As StreamingContext)
        IsDeserializing = True
    End Sub

    <OnDeserialized()>
    Public Sub OnDeserializedMethod(ByVal context As StreamingContext)
        IsDeserializing = False
        ChangeTracker.ChangeTrackingEnabled = True
    End Sub

    Protected Overridable Sub ClearNavigationProperties()
        SettingInventory = Nothing
    End Sub

#End Region

#Region "Association Fixup"

    Private Sub FixupSettingInventory(ByVal previousValue As SettingInventory)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.SettingInventoryMedicationsControl.Contains(Me) Then
            previousValue.SettingInventoryMedicationsControl.Remove(Me)
        End If

        If SettingInventory IsNot Nothing Then
            SettingInventory.SettingInventoryMedicationsControl.Add(Me)

            SettingInventoryId = SettingInventory.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("SettingInventory") AndAlso
                ChangeTracker.OriginalValues("SettingInventory") Is SettingInventory Then
                ChangeTracker.OriginalValues.Remove("SettingInventory")
            Else
                ChangeTracker.RecordOriginalValue("SettingInventory", previousValue)
            End If
            If SettingInventory IsNot Nothing AndAlso Not SettingInventory.ChangeTracker.ChangeTrackingEnabled Then
                SettingInventory.StartTracking()
            End If
        End If
    End Sub

#End Region

End Class

