'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel
Imports System.Globalization
Imports System.IO
Imports System.Reflection
Imports System.Runtime.Serialization.Formatters.Binary
Imports System.Runtime.Serialization
Imports System.Runtime.CompilerServices
Imports Domain.Base.Entities
Imports System.Data.Entity.ModelConfiguration

<DataContract(IsReference:=True), Serializable(), KnownType(GetType(SettingInventoryFunctionalUnit))>
<KnownType(GetType(FunctionalUnit))>
<KnownType(GetType(MainAccounts))>
<KnownType(GetType(SettingInventory))>
Partial Public Class SettingInventoryFunctionalUnit
	Inherits Entity(Of SettingInventoryFunctionalUnit)
    Implements IObjectWithChangeTracker
    Implements INotifyPropertyChanged

#Region "Simple Properties"

	Private _id As Integer
	<DataMember()>
	Public Property Id() As Integer
        Get
            Return _id
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_id, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'Id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _id = value
                OnPropertyChanged("Id")
            End If
        End Set
    End Property

	Private _settingInventoryId As Integer
	<DataMember()>
	Public Property SettingInventoryId() As Integer
        Get
            Return _settingInventoryId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_settingInventoryId, value) Then
                ChangeTracker.RecordOriginalValue("SettingInventoryId", _settingInventoryId)
                If Not IsDeserializing Then
                    If SettingInventory IsNot Nothing AndAlso Not Equals(SettingInventory.Id, value) Then
                        SettingInventory = Nothing
                    End If
                End If
                _settingInventoryId = value
                OnPropertyChanged("SettingInventoryId")
            End If
        End Set
    End Property

	Private _functionalUnitId As Integer
	<DataMember()>
	Public Property FunctionalUnitId() As Integer
        Get
            Return _functionalUnitId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_functionalUnitId, value) Then
                ChangeTracker.RecordOriginalValue("FunctionalUnitId", _functionalUnitId)
                If Not IsDeserializing Then
                    If FunctionalUnit IsNot Nothing AndAlso Not Equals(FunctionalUnit.Id, value) Then
                        FunctionalUnit = Nothing
                    End If
                End If
                _functionalUnitId = value
                OnPropertyChanged("FunctionalUnitId")
            End If
        End Set
    End Property

	Private _costAccountId As Integer
	<DataMember()>
	Public Property CostAccountId() As Integer
        Get
            Return _costAccountId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_costAccountId, value) Then
                ChangeTracker.RecordOriginalValue("CostAccountId", _costAccountId)
                If Not IsDeserializing Then
                    If MainAccounts IsNot Nothing AndAlso Not Equals(MainAccounts.Id, value) Then
                        MainAccounts = Nothing
                    End If
                End If
                _costAccountId = value
                OnPropertyChanged("CostAccountId")
            End If
        End Set
    End Property

	Private _salesAccountId As Integer
	<DataMember()>
	Public Property SalesAccountId() As Integer
        Get
            Return _salesAccountId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_salesAccountId, value) Then
                ChangeTracker.RecordOriginalValue("SalesAccountId", _salesAccountId)
                If Not IsDeserializing Then
                    If MainAccounts1 IsNot Nothing AndAlso Not Equals(MainAccounts1.Id, value) Then
                        MainAccounts1 = Nothing
                    End If
                End If
                _salesAccountId = value
                OnPropertyChanged("SalesAccountId")
            End If
        End Set
    End Property

#End Region

#Region "Navigation Properties"

    <DataMember()>
    Public Property FunctionalUnit() As FunctionalUnit
        Get
            Return _functionalUnit
        End Get
        Set(ByVal value As FunctionalUnit)
            If _functionalUnit IsNot value Then
                Dim previousValue As FunctionalUnit = _functionalUnit
                _functionalUnit = value
                FixupFunctionalUnit(previousValue)
                OnNavigationPropertyChanged("FunctionalUnit")
            End If
        End Set
    End Property

    Private _functionalUnit As FunctionalUnit


    <DataMember()>
    Public Property MainAccounts() As MainAccounts
        Get
            Return _mainAccounts
        End Get
        Set(ByVal value As MainAccounts)
            If _mainAccounts IsNot value Then
                Dim previousValue As MainAccounts = _mainAccounts
                _mainAccounts = value
                FixupMainAccounts(previousValue)
                OnNavigationPropertyChanged("MainAccounts")
            End If
        End Set
    End Property

    Private _mainAccounts As MainAccounts


    <DataMember()>
    Public Property MainAccounts1() As MainAccounts
        Get
            Return _mainAccounts1
        End Get
        Set(ByVal value As MainAccounts)
            If _mainAccounts1 IsNot value Then
                Dim previousValue As MainAccounts = _mainAccounts1
                _mainAccounts1 = value
                FixupMainAccounts1(previousValue)
                OnNavigationPropertyChanged("MainAccounts1")
            End If
        End Set
    End Property

    Private _mainAccounts1 As MainAccounts


    <DataMember()>
    Public Property SettingInventory() As SettingInventory
        Get
            Return _settingInventory
        End Get
        Set(ByVal value As SettingInventory)
            If _settingInventory IsNot value Then
                Dim previousValue As SettingInventory = _settingInventory
                _settingInventory = value
                FixupSettingInventory(previousValue)
                OnNavigationPropertyChanged("SettingInventory")
            End If
        End Set
    End Property

    Private _settingInventory As SettingInventory


#End Region

#Region "ChangeTracking"

    Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
        If ChangeTracker.State <> ObjectState.Added AndAlso ChangeTracker.State <> ObjectState.Deleted Then
            ChangeTracker.State = ObjectState.Modified
        End If
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Protected Overridable Sub OnNavigationPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Private _changeTracker As ObjectChangeTracker

    <DataMember()>
    Public Property ChangeTracker() As ObjectChangeTracker Implements IObjectWithChangeTracker.ChangeTracker
        Get
            If _changeTracker Is Nothing Then
                _changeTracker = New ObjectChangeTracker()
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            Return _changeTracker
        End Get
        Set(ByVal value As ObjectChangeTracker)
            If _changeTracker IsNot Nothing Then
                RemoveHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            _changeTracker = value
            If _changeTracker IsNot Nothing Then
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
        End Set
    End Property

    Private Sub HandleObjectStateChanging(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.ClearNavigationProperties()
        End If
    End Sub

    Private _isDeserializing As Boolean
    Protected Property IsDeserializing() As Boolean
        Get
            Return _isDeserializing
        End Get
        Private Set(ByVal value As Boolean)
            _isDeserializing = value
        End Set
    End Property

    <OnDeserializing()>
    Public Sub OnDeserializingMethod(ByVal context As StreamingContext)
        IsDeserializing = True
    End Sub

    <OnDeserialized()>
    Public Sub OnDeserializedMethod(ByVal context As StreamingContext)
        IsDeserializing = False
        ChangeTracker.ChangeTrackingEnabled = True
    End Sub

    Protected Overridable Sub ClearNavigationProperties()
        FunctionalUnit = Nothing
        MainAccounts = Nothing
        MainAccounts1 = Nothing
        SettingInventory = Nothing
    End Sub

#End Region

#Region "Association Fixup"

    Private Sub FixupFunctionalUnit(ByVal previousValue As FunctionalUnit)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.SettingInventoryFunctionalUnit.Contains(Me) Then
            previousValue.SettingInventoryFunctionalUnit.Remove(Me)
        End If

        If FunctionalUnit IsNot Nothing Then
            FunctionalUnit.SettingInventoryFunctionalUnit.Add(Me)

            FunctionalUnitId = FunctionalUnit.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("FunctionalUnit") AndAlso
                ChangeTracker.OriginalValues("FunctionalUnit") Is FunctionalUnit Then
                ChangeTracker.OriginalValues.Remove("FunctionalUnit")
            Else
                ChangeTracker.RecordOriginalValue("FunctionalUnit", previousValue)
            End If
            If FunctionalUnit IsNot Nothing AndAlso Not FunctionalUnit.ChangeTracker.ChangeTrackingEnabled Then
                FunctionalUnit.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupMainAccounts(ByVal previousValue As MainAccounts)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.SettingInventoryFunctionalUnit.Contains(Me) Then
            previousValue.SettingInventoryFunctionalUnit.Remove(Me)
        End If

        If MainAccounts IsNot Nothing Then
            MainAccounts.SettingInventoryFunctionalUnit.Add(Me)

            CostAccountId = MainAccounts.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("MainAccounts") AndAlso
                ChangeTracker.OriginalValues("MainAccounts") Is MainAccounts Then
                ChangeTracker.OriginalValues.Remove("MainAccounts")
            Else
                ChangeTracker.RecordOriginalValue("MainAccounts", previousValue)
            End If
            If MainAccounts IsNot Nothing AndAlso Not MainAccounts.ChangeTracker.ChangeTrackingEnabled Then
                MainAccounts.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupMainAccounts1(ByVal previousValue As MainAccounts)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.SettingInventoryFunctionalUnit1.Contains(Me) Then
            previousValue.SettingInventoryFunctionalUnit1.Remove(Me)
        End If

        If MainAccounts1 IsNot Nothing Then
            MainAccounts1.SettingInventoryFunctionalUnit1.Add(Me)

            SalesAccountId = MainAccounts1.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("MainAccounts1") AndAlso
                ChangeTracker.OriginalValues("MainAccounts1") Is MainAccounts1 Then
                ChangeTracker.OriginalValues.Remove("MainAccounts1")
            Else
                ChangeTracker.RecordOriginalValue("MainAccounts1", previousValue)
            End If
            If MainAccounts1 IsNot Nothing AndAlso Not MainAccounts1.ChangeTracker.ChangeTrackingEnabled Then
                MainAccounts1.StartTracking()
            End If
        End If
    End Sub

    Private Sub FixupSettingInventory(ByVal previousValue As SettingInventory)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.SettingInventoryFunctionalUnit.Contains(Me) Then
            previousValue.SettingInventoryFunctionalUnit.Remove(Me)
        End If

        If SettingInventory IsNot Nothing Then
            SettingInventory.SettingInventoryFunctionalUnit.Add(Me)

            SettingInventoryId = SettingInventory.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("SettingInventory") AndAlso
                ChangeTracker.OriginalValues("SettingInventory") Is SettingInventory Then
                ChangeTracker.OriginalValues.Remove("SettingInventory")
            Else
                ChangeTracker.RecordOriginalValue("SettingInventory", previousValue)
            End If
            If SettingInventory IsNot Nothing AndAlso Not SettingInventory.ChangeTracker.ChangeTrackingEnabled Then
                SettingInventory.StartTracking()
            End If
        End If
    End Sub

#End Region

End Class

