'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel
Imports System.Globalization
Imports System.IO
Imports System.Reflection
Imports System.Runtime.Serialization.Formatters.Binary
Imports System.Runtime.Serialization
Imports System.Runtime.CompilerServices
Imports Domain.Base.Entities
Imports System.Data.Entity.ModelConfiguration

<DataContract(IsReference:=True), Serializable(), KnownType(GetType(TraceabilityPaperworkAlert))>
<KnownType(GetType(TraceabilityPaperwork))>
Partial Public Class TraceabilityPaperworkAlert
	Inherits Entity(Of TraceabilityPaperworkAlert)
    Implements IObjectWithChangeTracker
    Implements INotifyPropertyChanged

#Region "Simple Properties"

	Private _id As Integer
	<DataMember()>
	Public Property Id() As Integer
        Get
            Return _id
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_id, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'Id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _id = value
                OnPropertyChanged("Id")
            End If
        End Set
    End Property

	Private _traceabilityPaperworkId As Integer
	<DataMember()>
	Public Property TraceabilityPaperworkId() As Integer
        Get
            Return _traceabilityPaperworkId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_traceabilityPaperworkId, value) Then
                ChangeTracker.RecordOriginalValue("TraceabilityPaperworkId", _traceabilityPaperworkId)
                If Not IsDeserializing Then
                    If TraceabilityPaperwork IsNot Nothing AndAlso Not Equals(TraceabilityPaperwork.Id, value) Then
                        TraceabilityPaperwork = Nothing
                    End If
                End If
                _traceabilityPaperworkId = value
                OnPropertyChanged("TraceabilityPaperworkId")
            End If
        End Set
    End Property

	Private _comments As String
	<DataMember()>
	Public Property Comments() As String
        Get
            Return _comments
        End Get
        Set(ByVal value As String)
            If Not Equals(_comments, value) Then
                _comments = value
                OnPropertyChanged("Comments")
            End If
        End Set
    End Property

	Private _status As Boolean
	<DataMember()>
	Public Property Status() As Boolean
        Get
            Return _status
        End Get
        Set(ByVal value As Boolean)
            If Not Equals(_status, value) Then
                _status = value
                OnPropertyChanged("Status")
            End If
        End Set
    End Property

	Private _creationUser As String
	<DataMember()>
	Public Property CreationUser() As String
        Get
            Return _creationUser
        End Get
        Set(ByVal value As String)
            If Not Equals(_creationUser, value) Then
                _creationUser = value
                OnPropertyChanged("CreationUser")
            End If
        End Set
    End Property

	Private _creationDate As Date
	<DataMember()>
	Public Property CreationDate() As Date
        Get
            Return _creationDate
        End Get
        Set(ByVal value As Date)
            If Not Equals(_creationDate, value) Then
                _creationDate = value
                OnPropertyChanged("CreationDate")
            End If
        End Set
    End Property

	Private _modificationUser As String
	<DataMember()>
	Public Property ModificationUser() As String
        Get
            Return _modificationUser
        End Get
        Set(ByVal value As String)
            If Not Equals(_modificationUser, value) Then
                _modificationUser = value
                OnPropertyChanged("ModificationUser")
            End If
        End Set
    End Property

	Private _modificationDate As Nullable(Of Date)
	<DataMember()>
	Public Property ModificationDate() As Nullable(Of Date)
        Get
            Return _modificationDate
        End Get
        Set(ByVal value As Nullable(Of Date))
            If Not Equals(_modificationDate, value) Then
                _modificationDate = value
                OnPropertyChanged("ModificationDate")
            End If
        End Set
    End Property

#End Region

#Region "Navigation Properties"

    <DataMember()>
    Public Property TraceabilityPaperwork() As TraceabilityPaperwork
        Get
            Return _traceabilityPaperwork
        End Get
        Set(ByVal value As TraceabilityPaperwork)
            If _traceabilityPaperwork IsNot value Then
                Dim previousValue As TraceabilityPaperwork = _traceabilityPaperwork
                _traceabilityPaperwork = value
                FixupTraceabilityPaperwork(previousValue)
                OnNavigationPropertyChanged("TraceabilityPaperwork")
            End If
        End Set
    End Property

    Private _traceabilityPaperwork As TraceabilityPaperwork


#End Region

#Region "ChangeTracking"

    Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
        If ChangeTracker.State <> ObjectState.Added AndAlso ChangeTracker.State <> ObjectState.Deleted Then
            ChangeTracker.State = ObjectState.Modified
        End If
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Protected Overridable Sub OnNavigationPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Private _changeTracker As ObjectChangeTracker

    <DataMember()>
    Public Property ChangeTracker() As ObjectChangeTracker Implements IObjectWithChangeTracker.ChangeTracker
        Get
            If _changeTracker Is Nothing Then
                _changeTracker = New ObjectChangeTracker()
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            Return _changeTracker
        End Get
        Set(ByVal value As ObjectChangeTracker)
            If _changeTracker IsNot Nothing Then
                RemoveHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            _changeTracker = value
            If _changeTracker IsNot Nothing Then
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
        End Set
    End Property

    Private Sub HandleObjectStateChanging(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.ClearNavigationProperties()
        End If
    End Sub

    Private _isDeserializing As Boolean
    Protected Property IsDeserializing() As Boolean
        Get
            Return _isDeserializing
        End Get
        Private Set(ByVal value As Boolean)
            _isDeserializing = value
        End Set
    End Property

    <OnDeserializing()>
    Public Sub OnDeserializingMethod(ByVal context As StreamingContext)
        IsDeserializing = True
    End Sub

    <OnDeserialized()>
    Public Sub OnDeserializedMethod(ByVal context As StreamingContext)
        IsDeserializing = False
        ChangeTracker.ChangeTrackingEnabled = True
    End Sub

    Protected Overridable Sub ClearNavigationProperties()
        TraceabilityPaperwork = Nothing
    End Sub

#End Region

#Region "Association Fixup"

    Private Sub FixupTraceabilityPaperwork(ByVal previousValue As TraceabilityPaperwork)
        If IsDeserializing Then
            Return
        End If

        If previousValue IsNot Nothing AndAlso previousValue.TraceabilityPaperworkAlert.Contains(Me) Then
            previousValue.TraceabilityPaperworkAlert.Remove(Me)
        End If

        If TraceabilityPaperwork IsNot Nothing Then
            TraceabilityPaperwork.TraceabilityPaperworkAlert.Add(Me)

            TraceabilityPaperworkId = TraceabilityPaperwork.Id
        End If
        If ChangeTracker.ChangeTrackingEnabled Then
            If ChangeTracker.OriginalValues.ContainsKey("TraceabilityPaperwork") AndAlso
                ChangeTracker.OriginalValues("TraceabilityPaperwork") Is TraceabilityPaperwork Then
                ChangeTracker.OriginalValues.Remove("TraceabilityPaperwork")
            Else
                ChangeTracker.RecordOriginalValue("TraceabilityPaperwork", previousValue)
            End If
            If TraceabilityPaperwork IsNot Nothing AndAlso Not TraceabilityPaperwork.ChangeTracker.ChangeTrackingEnabled Then
                TraceabilityPaperwork.StartTracking()
            End If
        End If
    End Sub

#End Region

End Class

