'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel
Imports System.Globalization
Imports System.IO
Imports System.Reflection
Imports System.Runtime.Serialization.Formatters.Binary
Imports System.Runtime.Serialization
Imports System.Runtime.CompilerServices
Imports Domain.Base.Entities
Imports System.Data.Entity.ModelConfiguration

<DataContract(IsReference:=True), Serializable(), KnownType(GetType(ViewListNoSurgical))>
Partial Public Class ViewListNoSurgical
	Inherits Entity(Of ViewListNoSurgical)
    Implements IObjectWithChangeTracker
    Implements INotifyPropertyChanged

#Region "Simple Properties"

	Private _serviceOrderDetailId As Integer
	<DataMember()>
	Public Property ServiceOrderDetailId() As Integer
        Get
            Return _serviceOrderDetailId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_serviceOrderDetailId, value) Then
                _serviceOrderDetailId = value
                OnPropertyChanged("ServiceOrderDetailId")
            End If
        End Set
    End Property

	Private _rateManualSalePrice As Decimal
	<DataMember()>
	Public Property RateManualSalePrice() As Decimal
        Get
            Return _rateManualSalePrice
        End Get
        Set(ByVal value As Decimal)
            If Not Equals(_rateManualSalePrice, value) Then
                _rateManualSalePrice = value
                OnPropertyChanged("RateManualSalePrice")
            End If
        End Set
    End Property

	Private _invoicedQuantity As Integer
	<DataMember()>
	Public Property InvoicedQuantity() As Integer
        Get
            Return _invoicedQuantity
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_invoicedQuantity, value) Then
                _invoicedQuantity = value
                OnPropertyChanged("InvoicedQuantity")
            End If
        End Set
    End Property

	Private _iPSServiceId As Integer
	<DataMember()>
	Public Property IPSServiceId() As Integer
        Get
            Return _iPSServiceId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_iPSServiceId, value) Then
                _iPSServiceId = value
                OnPropertyChanged("IPSServiceId")
            End If
        End Set
    End Property

	Private _iPSServiceDescription As String
	<DataMember()>
	Public Property IPSServiceDescription() As String
        Get
            Return _iPSServiceDescription
        End Get
        Set(ByVal value As String)
            If Not Equals(_iPSServiceDescription, value) Then
                _iPSServiceDescription = value
                OnPropertyChanged("IPSServiceDescription")
            End If
        End Set
    End Property

	Private _thirdPartyDescription As String
	<DataMember()>
	Public Property ThirdPartyDescription() As String
        Get
            Return _thirdPartyDescription
        End Get
        Set(ByVal value As String)
            If Not Equals(_thirdPartyDescription, value) Then
                _thirdPartyDescription = value
                OnPropertyChanged("ThirdPartyDescription")
            End If
        End Set
    End Property

	Private _invoiceId As Integer
	<DataMember()>
	Public Property InvoiceId() As Integer
        Get
            Return _invoiceId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_invoiceId, value) Then
                _invoiceId = value
                OnPropertyChanged("InvoiceId")
            End If
        End Set
    End Property

	Private _cupsEntityId As Integer
	<DataMember()>
	Public Property CupsEntityId() As Integer
        Get
            Return _cupsEntityId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_cupsEntityId, value) Then
                _cupsEntityId = value
                OnPropertyChanged("CupsEntityId")
            End If
        End Set
    End Property

	Private _cupsEntityDescription As String
	<DataMember()>
	Public Property CupsEntityDescription() As String
        Get
            Return _cupsEntityDescription
        End Get
        Set(ByVal value As String)
            If Not Equals(_cupsEntityDescription, value) Then
                _cupsEntityDescription = value
                OnPropertyChanged("CupsEntityDescription")
            End If
        End Set
    End Property

	Private _billingGroupId As Integer
	<DataMember()>
	Public Property BillingGroupId() As Integer
        Get
            Return _billingGroupId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_billingGroupId, value) Then
                _billingGroupId = value
                OnPropertyChanged("BillingGroupId")
            End If
        End Set
    End Property

	Private _billingGroupDescription As String
	<DataMember()>
	Public Property BillingGroupDescription() As String
        Get
            Return _billingGroupDescription
        End Get
        Set(ByVal value As String)
            If Not Equals(_billingGroupDescription, value) Then
                _billingGroupDescription = value
                OnPropertyChanged("BillingGroupDescription")
            End If
        End Set
    End Property

	Private _status As Byte
	<DataMember()>
	Public Property Status() As Byte
        Get
            Return _status
        End Get
        Set(ByVal value As Byte)
            If Not Equals(_status, value) Then
                _status = value
                OnPropertyChanged("Status")
            End If
        End Set
    End Property

	Private _selectOption As Nullable(Of Boolean)
	<DataMember()>
	Public Property SelectOption() As Nullable(Of Boolean)
        Get
            Return _selectOption
        End Get
        Set(ByVal value As Nullable(Of Boolean))
            If Not Equals(_selectOption, value) Then
                _selectOption = value
                OnPropertyChanged("SelectOption")
            End If
        End Set
    End Property

	Private _careGroupId As Integer
	<DataMember()>
	Public Property CareGroupId() As Integer
        Get
            Return _careGroupId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_careGroupId, value) Then
                _careGroupId = value
                OnPropertyChanged("CareGroupId")
            End If
        End Set
    End Property

	Private _rateManualId As Integer
	<DataMember()>
	Public Property RateManualId() As Integer
        Get
            Return _rateManualId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_rateManualId, value) Then
                _rateManualId = value
                OnPropertyChanged("RateManualId")
            End If
        End Set
    End Property

	Private _grandTotalSalesPrice As Decimal
	<DataMember()>
	Public Property GrandTotalSalesPrice() As Decimal
        Get
            Return _grandTotalSalesPrice
        End Get
        Set(ByVal value As Decimal)
            If Not Equals(_grandTotalSalesPrice, value) Then
                _grandTotalSalesPrice = value
                OnPropertyChanged("GrandTotalSalesPrice")
            End If
        End Set
    End Property

	Private _presentation As Nullable(Of Byte)
	<DataMember()>
	Public Property Presentation() As Nullable(Of Byte)
        Get
            Return _presentation
        End Get
        Set(ByVal value As Nullable(Of Byte))
            If Not Equals(_presentation, value) Then
                _presentation = value
                OnPropertyChanged("Presentation")
            End If
        End Set
    End Property

	Private _totalSalesPrice As Decimal
	<DataMember()>
	Public Property TotalSalesPrice() As Decimal
        Get
            Return _totalSalesPrice
        End Get
        Set(ByVal value As Decimal)
            If Not Equals(_totalSalesPrice, value) Then
                _totalSalesPrice = value
                OnPropertyChanged("TotalSalesPrice")
            End If
        End Set
    End Property

	Private _subTotalSalesPrice As Decimal
	<DataMember()>
	Public Property SubTotalSalesPrice() As Decimal
        Get
            Return _subTotalSalesPrice
        End Get
        Set(ByVal value As Decimal)
            If Not Equals(_subTotalSalesPrice, value) Then
                _subTotalSalesPrice = value
                OnPropertyChanged("SubTotalSalesPrice")
            End If
        End Set
    End Property

	Private _thirdPartyDiscountPercentage As Decimal
	<DataMember()>
	Public Property ThirdPartyDiscountPercentage() As Decimal
        Get
            Return _thirdPartyDiscountPercentage
        End Get
        Set(ByVal value As Decimal)
            If Not Equals(_thirdPartyDiscountPercentage, value) Then
                _thirdPartyDiscountPercentage = value
                OnPropertyChanged("ThirdPartyDiscountPercentage")
            End If
        End Set
    End Property

	Private _performsHealthProfessionalCode As String
	<DataMember()>
	Public Property PerformsHealthProfessionalCode() As String
        Get
            Return _performsHealthProfessionalCode
        End Get
        Set(ByVal value As String)
            If Not Equals(_performsHealthProfessionalCode, value) Then
                _performsHealthProfessionalCode = value
                OnPropertyChanged("PerformsHealthProfessionalCode")
            End If
        End Set
    End Property

	Private _thirdPartyId As Nullable(Of Integer)
	<DataMember()>
	Public Property ThirdPartyId() As Nullable(Of Integer)
        Get
            Return _thirdPartyId
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_thirdPartyId, value) Then
                _thirdPartyId = value
                OnPropertyChanged("ThirdPartyId")
            End If
        End Set
    End Property

	Private _serviceDate As Date
	<DataMember()>
	Public Property ServiceDate() As Date
        Get
            Return _serviceDate
        End Get
        Set(ByVal value As Date)
            If Not Equals(_serviceDate, value) Then
                _serviceDate = value
                OnPropertyChanged("ServiceDate")
            End If
        End Set
    End Property

	Private _liquidationType As Byte
	<DataMember()>
	Public Property LiquidationType() As Byte
        Get
            Return _liquidationType
        End Get
        Set(ByVal value As Byte)
            If Not Equals(_liquidationType, value) Then
                _liquidationType = value
                OnPropertyChanged("LiquidationType")
            End If
        End Set
    End Property

	Private _performsProfessionalSpecialty As String
	<DataMember()>
	Public Property PerformsProfessionalSpecialty() As String
        Get
            Return _performsProfessionalSpecialty
        End Get
        Set(ByVal value As String)
            If Not Equals(_performsProfessionalSpecialty, value) Then
                _performsProfessionalSpecialty = value
                OnPropertyChanged("PerformsProfessionalSpecialty")
            End If
        End Set
    End Property

	Private _rateManualType As Nullable(Of Byte)
	<DataMember()>
	Public Property RateManualType() As Nullable(Of Byte)
        Get
            Return _rateManualType
        End Get
        Set(ByVal value As Nullable(Of Byte))
            If Not Equals(_rateManualType, value) Then
                _rateManualType = value
                OnPropertyChanged("RateManualType")
            End If
        End Set
    End Property

	Private _medicalFeesContractId As Integer
	<DataMember()>
	Public Property MedicalFeesContractId() As Integer
        Get
            Return _medicalFeesContractId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_medicalFeesContractId, value) Then
                _medicalFeesContractId = value
                OnPropertyChanged("MedicalFeesContractId")
            End If
        End Set
    End Property

	Private _serviceOrderId As Integer
	<DataMember()>
	Public Property ServiceOrderId() As Integer
        Get
            Return _serviceOrderId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_serviceOrderId, value) Then
                _serviceOrderId = value
                OnPropertyChanged("ServiceOrderId")
            End If
        End Set
    End Property

	Private _amountPayable As Decimal
	<DataMember()>
	Public Property AmountPayable() As Decimal
        Get
            Return _amountPayable
        End Get
        Set(ByVal value As Decimal)
            If Not Equals(_amountPayable, value) Then
                _amountPayable = value
                OnPropertyChanged("AmountPayable")
            End If
        End Set
    End Property

	Private _totalAmountPayable As Decimal
	<DataMember()>
	Public Property TotalAmountPayable() As Decimal
        Get
            Return _totalAmountPayable
        End Get
        Set(ByVal value As Decimal)
            If Not Equals(_totalAmountPayable, value) Then
                _totalAmountPayable = value
                OnPropertyChanged("TotalAmountPayable")
            End If
        End Set
    End Property

	Private _medicalFeesCausationId As Integer
	<DataMember()>
	Public Property MedicalFeesCausationId() As Integer
        Get
            Return _medicalFeesCausationId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_medicalFeesCausationId, value) Then
                _medicalFeesCausationId = value
                OnPropertyChanged("MedicalFeesCausationId")
            End If
        End Set
    End Property

	Private _creationUser As String
	<DataMember()>
	Public Property CreationUser() As String
        Get
            Return _creationUser
        End Get
        Set(ByVal value As String)
            If Not Equals(_creationUser, value) Then
                _creationUser = value
                OnPropertyChanged("CreationUser")
            End If
        End Set
    End Property

	Private _creationDate As Nullable(Of Date)
	<DataMember()>
	Public Property CreationDate() As Nullable(Of Date)
        Get
            Return _creationDate
        End Get
        Set(ByVal value As Nullable(Of Date))
            If Not Equals(_creationDate, value) Then
                _creationDate = value
                OnPropertyChanged("CreationDate")
            End If
        End Set
    End Property

	Private _modificationUser As String
	<DataMember()>
	Public Property ModificationUser() As String
        Get
            Return _modificationUser
        End Get
        Set(ByVal value As String)
            If Not Equals(_modificationUser, value) Then
                _modificationUser = value
                OnPropertyChanged("ModificationUser")
            End If
        End Set
    End Property

	Private _modificationDate As Nullable(Of Date)
	<DataMember()>
	Public Property ModificationDate() As Nullable(Of Date)
        Get
            Return _modificationDate
        End Get
        Set(ByVal value As Nullable(Of Date))
            If Not Equals(_modificationDate, value) Then
                _modificationDate = value
                OnPropertyChanged("ModificationDate")
            End If
        End Set
    End Property

	Private _confirmationUser As String
	<DataMember()>
	Public Property ConfirmationUser() As String
        Get
            Return _confirmationUser
        End Get
        Set(ByVal value As String)
            If Not Equals(_confirmationUser, value) Then
                _confirmationUser = value
                OnPropertyChanged("ConfirmationUser")
            End If
        End Set
    End Property

	Private _confirmationDate As Nullable(Of Date)
	<DataMember()>
	Public Property ConfirmationDate() As Nullable(Of Date)
        Get
            Return _confirmationDate
        End Get
        Set(ByVal value As Nullable(Of Date))
            If Not Equals(_confirmationDate, value) Then
                _confirmationDate = value
                OnPropertyChanged("ConfirmationDate")
            End If
        End Set
    End Property

	Private _statusMedicalFeesCausation As Byte
	<DataMember()>
	Public Property StatusMedicalFeesCausation() As Byte
        Get
            Return _statusMedicalFeesCausation
        End Get
        Set(ByVal value As Byte)
            If Not Equals(_statusMedicalFeesCausation, value) Then
                _statusMedicalFeesCausation = value
                OnPropertyChanged("StatusMedicalFeesCausation")
            End If
        End Set
    End Property

	Private _totalAmountPayableReal As Decimal
	<DataMember()>
	Public Property TotalAmountPayableReal() As Decimal
        Get
            Return _totalAmountPayableReal
        End Get
        Set(ByVal value As Decimal)
            If Not Equals(_totalAmountPayableReal, value) Then
                _totalAmountPayableReal = value
                OnPropertyChanged("TotalAmountPayableReal")
            End If
        End Set
    End Property

	Private _percentageCashed As Decimal
	<DataMember()>
	Public Property PercentageCashed() As Decimal
        Get
            Return _percentageCashed
        End Get
        Set(ByVal value As Decimal)
            If Not Equals(_percentageCashed, value) Then
                _percentageCashed = value
                OnPropertyChanged("PercentageCashed")
            End If
        End Set
    End Property

	Private _invoiceDetailId As Integer
	<DataMember()>
	Public Property InvoiceDetailId() As Integer
        Get
            Return _invoiceDetailId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_invoiceDetailId, value) Then
                _invoiceDetailId = value
                OnPropertyChanged("InvoiceDetailId")
            End If
        End Set
    End Property

	Private _medicalFeesContractCodeName As String
	<DataMember()>
	Public Property MedicalFeesContractCodeName() As String
        Get
            Return _medicalFeesContractCodeName
        End Get
        Set(ByVal value As String)
            If Not Equals(_medicalFeesContractCodeName, value) Then
                _medicalFeesContractCodeName = value
                OnPropertyChanged("MedicalFeesContractCodeName")
            End If
        End Set
    End Property

	Private _incomeMainAccountId As Integer
	<DataMember()>
	Public Property IncomeMainAccountId() As Integer
        Get
            Return _incomeMainAccountId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_incomeMainAccountId, value) Then
                _incomeMainAccountId = value
                OnPropertyChanged("IncomeMainAccountId")
            End If
        End Set
    End Property

	Private _billingConceptId As Nullable(Of Integer)
	<DataMember()>
	Public Property BillingConceptId() As Nullable(Of Integer)
        Get
            Return _billingConceptId
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_billingConceptId, value) Then
                _billingConceptId = value
                OnPropertyChanged("BillingConceptId")
            End If
        End Set
    End Property

	Private _costCenterId As Integer
	<DataMember()>
	Public Property CostCenterId() As Integer
        Get
            Return _costCenterId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_costCenterId, value) Then
                _costCenterId = value
                OnPropertyChanged("CostCenterId")
            End If
        End Set
    End Property

	Private _rateManualDetailId As Integer
	<DataMember()>
	Public Property RateManualDetailId() As Integer
        Get
            Return _rateManualDetailId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_rateManualDetailId, value) Then
                _rateManualDetailId = value
                OnPropertyChanged("RateManualDetailId")
            End If
        End Set
    End Property

	Private _rateManualDetailSurgicalId As Nullable(Of Integer)
	<DataMember()>
	Public Property RateManualDetailSurgicalId() As Nullable(Of Integer)
        Get
            Return _rateManualDetailSurgicalId
        End Get
        Set(ByVal value As Nullable(Of Integer))
            If Not Equals(_rateManualDetailSurgicalId, value) Then
                _rateManualDetailSurgicalId = value
                OnPropertyChanged("RateManualDetailSurgicalId")
            End If
        End Set
    End Property

	Private _costValue As Decimal
	<DataMember()>
	Public Property CostValue() As Decimal
        Get
            Return _costValue
        End Get
        Set(ByVal value As Decimal)
            If Not Equals(_costValue, value) Then
                _costValue = value
                OnPropertyChanged("CostValue")
            End If
        End Set
    End Property

	Private _onlyMedicalFees As Integer
	<DataMember()>
	Public Property OnlyMedicalFees() As Integer
        Get
            Return _onlyMedicalFees
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_onlyMedicalFees, value) Then
                _onlyMedicalFees = value
                OnPropertyChanged("OnlyMedicalFees")
            End If
        End Set
    End Property

	Private _serviceOrderDetailSurgicalId As Integer
	<DataMember()>
	Public Property ServiceOrderDetailSurgicalId() As Integer
        Get
            Return _serviceOrderDetailSurgicalId
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_serviceOrderDetailSurgicalId, value) Then
                _serviceOrderDetailSurgicalId = value
                OnPropertyChanged("ServiceOrderDetailSurgicalId")
            End If
        End Set
    End Property

	Private _functionalUnitDescription As String
	<DataMember()>
	Public Property FunctionalUnitDescription() As String
        Get
            Return _functionalUnitDescription
        End Get
        Set(ByVal value As String)
            If Not Equals(_functionalUnitDescription, value) Then
                _functionalUnitDescription = value
                OnPropertyChanged("FunctionalUnitDescription")
            End If
        End Set
    End Property

	Private _creationUserServiceOrder As String
	<DataMember()>
	Public Property CreationUserServiceOrder() As String
        Get
            Return _creationUserServiceOrder
        End Get
        Set(ByVal value As String)
            If Not Equals(_creationUserServiceOrder, value) Then
                _creationUserServiceOrder = value
                OnPropertyChanged("CreationUserServiceOrder")
            End If
        End Set
    End Property

	Private _color As Integer
	<DataMember()>
	Public Property Color() As Integer
        Get
            Return _color
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_color, value) Then
                _color = value
                OnPropertyChanged("Color")
            End If
        End Set
    End Property

	Private _causationDate As Nullable(Of Date)
	<DataMember()>
	Public Property CausationDate() As Nullable(Of Date)
        Get
            Return _causationDate
        End Get
        Set(ByVal value As Nullable(Of Date))
            If Not Equals(_causationDate, value) Then
                _causationDate = value
                OnPropertyChanged("CausationDate")
            End If
        End Set
    End Property

	Private _admissionNumber As String
	<DataMember()>
	Public Property AdmissionNumber() As String
        Get
            Return _admissionNumber
        End Get
        Set(ByVal value As String)
            If Not Equals(_admissionNumber, value) Then
                _admissionNumber = value
                OnPropertyChanged("AdmissionNumber")
            End If
        End Set
    End Property

	Private _code As String
	<DataMember()>
	Public Property Code() As String
        Get
            Return _code
        End Get
        Set(ByVal value As String)
            If Not Equals(_code, value) Then
                _code = value
                OnPropertyChanged("Code")
            End If
        End Set
    End Property

	Private _serviceType As Byte
	<DataMember()>
	Public Property ServiceType() As Byte
        Get
            Return _serviceType
        End Get
        Set(ByVal value As Byte)
            If Not Equals(_serviceType, value) Then
                _serviceType = value
                OnPropertyChanged("ServiceType")
            End If
        End Set
    End Property

	Private _invoiceNumber As String
	<DataMember()>
	Public Property InvoiceNumber() As String
        Get
            Return _invoiceNumber
        End Get
        Set(ByVal value As String)
            If Not Equals(_invoiceNumber, value) Then
                _invoiceNumber = value
                OnPropertyChanged("InvoiceNumber")
            End If
        End Set
    End Property

	Private _patientCode As String
	<DataMember()>
	Public Property PatientCode() As String
        Get
            Return _patientCode
        End Get
        Set(ByVal value As String)
            If Not Equals(_patientCode, value) Then
                _patientCode = value
                OnPropertyChanged("PatientCode")
            End If
        End Set
    End Property

	Private _id As Integer
	<DataMember()>
	Public Property Id() As Integer
        Get
            Return _id
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_id, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'Id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _id = value
                OnPropertyChanged("Id")
            End If
        End Set
    End Property

#End Region

#Region "ChangeTracking"

    Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
        If ChangeTracker.State <> ObjectState.Added AndAlso ChangeTracker.State <> ObjectState.Deleted Then
            ChangeTracker.State = ObjectState.Modified
        End If
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Protected Overridable Sub OnNavigationPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Private _changeTracker As ObjectChangeTracker

    <DataMember()>
    Public Property ChangeTracker() As ObjectChangeTracker Implements IObjectWithChangeTracker.ChangeTracker
        Get
            If _changeTracker Is Nothing Then
                _changeTracker = New ObjectChangeTracker()
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            Return _changeTracker
        End Get
        Set(ByVal value As ObjectChangeTracker)
            If _changeTracker IsNot Nothing Then
                RemoveHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            _changeTracker = value
            If _changeTracker IsNot Nothing Then
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
        End Set
    End Property

    Private Sub HandleObjectStateChanging(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.ClearNavigationProperties()
        End If
    End Sub

    Private _isDeserializing As Boolean
    Protected Property IsDeserializing() As Boolean
        Get
            Return _isDeserializing
        End Get
        Private Set(ByVal value As Boolean)
            _isDeserializing = value
        End Set
    End Property

    <OnDeserializing()>
    Public Sub OnDeserializingMethod(ByVal context As StreamingContext)
        IsDeserializing = True
    End Sub

    <OnDeserialized()>
    Public Sub OnDeserializedMethod(ByVal context As StreamingContext)
        IsDeserializing = False
        ChangeTracker.ChangeTrackingEnabled = True
    End Sub

    Protected Overridable Sub ClearNavigationProperties()
    End Sub

#End Region

End Class

