'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Imports System
Imports DevExpress.Xpo
Imports DevExpress.Data.Filtering
Imports System.Collections.Generic
Imports System.ComponentModel
<Persistent("Portfolio.Circular030Detail")> _
Partial Public Class PortfolioCircular030DetailXpo
    Inherits XPLiteObject
    Dim fId As Integer
    <Key(True)> _
    Public Property Id() As Integer
        Get
            Return fId
        End Get
        Set(ByVal value As Integer)
            SetPropertyValue(Of Integer)("Id", fId, value)
        End Set
    End Property
    Dim fCircular030Id As PortfolioCircular030Xpo
    <Association("Portfolio_Circular030DetailReferencesPortfolio_Circular030")> _
    Public Property Circular030Id() As PortfolioCircular030Xpo
        Get
            Return fCircular030Id
        End Get
        Set(ByVal value As PortfolioCircular030Xpo)
            SetPropertyValue(Of PortfolioCircular030Xpo)("Circular030Id", fCircular030Id, value)
        End Set
    End Property
    Dim fConsecutive As Integer
    Public Property Consecutive() As Integer
        Get
            Return fConsecutive
        End Get
        Set(ByVal value As Integer)
            SetPropertyValue(Of Integer)("Consecutive", fConsecutive, value)
        End Set
    End Property
    Dim fAccountReceivableId As Integer
    Public Property AccountReceivableId() As Integer
        Get
            Return fAccountReceivableId
        End Get
        Set(ByVal value As Integer)
            SetPropertyValue(Of Integer)("AccountReceivableId", fAccountReceivableId, value)
        End Set
    End Property
    Dim fCollectionType As Byte
    Public Property CollectionType() As Byte
        Get
            Return fCollectionType
        End Get
        Set(ByVal value As Byte)
            SetPropertyValue(Of Byte)("CollectionType", fCollectionType, value)
        End Set
    End Property
    Dim fUpdatingIndicator As Char
    Public Property UpdatingIndicator() As Char
        Get
            Return fUpdatingIndicator
        End Get
        Set(ByVal value As Char)
            SetPropertyValue(Of Char)("UpdatingIndicator", fUpdatingIndicator, value)
        End Set
    End Property
    Dim fValue As Decimal
    Public Property Value() As Decimal
        Get
            Return fValue
        End Get
        Set(ByVal value As Decimal)
            SetPropertyValue(Of Decimal)("Value", fValue, value)
        End Set
    End Property
    Dim fBroadcastDate As DateTime
    Public Property BroadcastDate() As DateTime
        Get
            Return fBroadcastDate
        End Get
        Set(ByVal value As DateTime)
            SetPropertyValue(Of DateTime)("BroadcastDate", fBroadcastDate, value)
        End Set
    End Property
    Dim fPresentationDate As DateTime
    Public Property PresentationDate() As DateTime
        Get
            Return fPresentationDate
        End Get
        Set(ByVal value As DateTime)
            SetPropertyValue(Of DateTime)("PresentationDate", fPresentationDate, value)
        End Set
    End Property
    Dim fReturnDate As DateTime
    Public Property ReturnDate() As DateTime
        Get
            Return fReturnDate
        End Get
        Set(ByVal value As DateTime)
            SetPropertyValue(Of DateTime)("ReturnDate", fReturnDate, value)
        End Set
    End Property
    Dim fPaymentValue As Decimal
    Public Property PaymentValue() As Decimal
        Get
            Return fPaymentValue
        End Get
        Set(ByVal value As Decimal)
            SetPropertyValue(Of Decimal)("PaymentValue", fPaymentValue, value)
        End Set
    End Property
    Dim fGlosaValue As Decimal
    Public Property GlosaValue() As Decimal
        Get
            Return fGlosaValue
        End Get
        Set(ByVal value As Decimal)
            SetPropertyValue(Of Decimal)("GlosaValue", fGlosaValue, value)
        End Set
    End Property
    Dim fBalanceValue As Decimal
    Public Property BalanceValue() As Decimal
        Get
            Return fBalanceValue
        End Get
        Set(ByVal value As Decimal)
            SetPropertyValue(Of Decimal)("BalanceValue", fBalanceValue, value)
        End Set
    End Property
    Dim fLegalCollection As Boolean
    Public Property LegalCollection() As Boolean
        Get
            Return fLegalCollection
        End Get
        Set(ByVal value As Boolean)
            SetPropertyValue(Of Boolean)("LegalCollection", fLegalCollection, value)
        End Set
    End Property
    Dim fLegalCollectionState As Byte
    Public Property LegalCollectionState() As Byte
        Get
            Return fLegalCollectionState
        End Get
        Set(ByVal value As Byte)
            SetPropertyValue(Of Byte)("LegalCollectionState", fLegalCollectionState, value)
        End Set
    End Property
    Public Sub New(ByVal session As Session)
        MyBase.New(session)
    End Sub
End Class