CREATE TABLE [dbo].[NUsuariosAct] (
    [codigo]    NVARCHAR (255) NULL,
    [TERPRINOM] NVARCHAR (255) NULL,
    [TERSEGNOM] NVARCHAR (255) NULL,
    [TERPRIAPE] NVARCHAR (255) NULL,
    [TERSEGAPE] NVARCHAR (255) NULL,
    [Completo]  NVARCHAR (255) NULL
);

