Partial Public Class VReportInvoice
    Public Property Id As Integer
    Public Property OperatingUnitId As Integer
    Public Property InvoiceDate As Date
    Public Property InvoiceExpirationDate As Date
    Public Property InvoiceNumber As String
    Public Property CutType As Byte
    Public Property Observation As String
    Public Property Nit As String
    Public Property Name As String
    Public Property ThirdPartyAddress As String
    Public Property ThirdPartyPhone As String
    Public Property CareGroup As String
    Public Property CareGroupType As Byte
    Public Property HealthEntityCode As String
    Public Property DescriptionHealthAdministrator As String
    Public Property Contract As String
    Public Property PrintingMode As Byte?
    Public Property IdentificationTypeCode As String
    Public Property PatientCode As String
    Public Property PatientName As String
    Public Property PatientType As String
    Public Property PatientLevel As String
    Public Property PatientAddress As String
    Public Property PatientTelephoneNumber As String
    Public Property PatientPhoneMovil As String
    Public Property PatientAge As String
    Public Property TypeAdmission As Integer
    Public Property AdmissionNumber As String
    Public Property AdmissionDate As Date
    Public Property EgressDate As Date?
    Public Property AuthorizationNumber As String
    Public Property ProcessingDate As Date?
    Public Property ProcessLine As String
    Public Property PacientEntity As String
    Public Property PacientRegimen As String
    Public Property AffiliateType As Integer
    Public Property AffiliateStatus As String
    Public Property ERPConfirm As String
    Public Property IPSReport As String
    Public Property CODCENATE As String
    Public Property CenterAttentionName As String
    Public Property CenterAttentionCode As String
    Public Property CenterAttentionAddress As String
    Public Property CenterAttentionPhone As String
    Public Property UFUIGRMED As String
    Public Property UFUEGRMED As String
    Public Property InvoiceCategory As String
    Public Property DocumentType As Byte
    Public Property SubTotalService As Decimal?
    Public Property ThirdPartyDiscountValue As Decimal
    Public Property TotalPatientSalesPrice As Decimal
    Public Property PatientDiscount As Decimal
    Public Property TotalPatientAccountReceivable As Decimal?
    Public Property ThirdPartySalesValue As Decimal
    Public Property UserCode As String
    Public Property FullNameUser As String
    Public Property Status As Byte
    Public Property DocumentTypeName As String
    Public Property IdPay As Integer?
    Public Property ResolutionNumber As String
    Public Property ResolutionDate As Date?
    Public Property ResolutionInvoicePrefix As String
    Public Property ResolutionInitialInvoice As Long?
    Public Property ResolutionFinalInvoice As Long?
    Public Property ResolutionInitialDate As Date?
    Public Property ResolutionFinalDate As Date?
    Public Property Term As Integer?
    Public Property PaymentMeans As String
    Public Property PaymentMethodTypes As Byte
    Public Property PaymentMethod As String
    Public Property CUFE As String
    Public Property QR As String
    Public Property StatusDIAN As String
    Public Property ValidationDate As Date?
End Class
