CREATE TYPE [MixingStation].[PackageDetailType] AS TABLE (
    [Id]                    INT             NULL,
    [PackageId]             INT             NULL,
    [ProductId]             INT             NULL,
    [Quantity]              DECIMAL (18, 2) NULL,
    [MeasurementUnitId]     INT             NULL,
    [Volume]                NUMERIC (18, 2) NULL,
    [VolumeMeasureUnit]     INT             NULL,
    [Thinner]               BIT             NULL,
    [Vehicle]               BIT             NULL,
    [Osmolarity]            DECIMAL (5, 1)  NULL,
    [Density]               DECIMAL (6, 4)  NULL,
    [AtcId]                 INT             NULL,
    [SupplieId]             INT             NULL,
    [ComponentType]         TINYINT         NULL,
    [MainMedicine]          BIT             NULL,
    [PreparationType]       TINYINT         NULL,
    [Dilution]              DECIMAL (18, 4) NULL,
    [Concentration]         DECIMAL (18, 4) NULL,
    [AmountTime]            INT             NULL,
    [TimeUnit]              TINYINT         NULL,
    [VolumeTotal]           DECIMAL (18, 2) NULL,
    [NPTItemOrder]          TINYINT         NULL,
    [ComplementaryMedicine] BIT             NULL,
    [IsDelete]              BIT             NULL);

