'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic
Imports System.Collections.ObjectModel
Imports System.Collections.Specialized
Imports System.ComponentModel
Imports System.Globalization
Imports System.IO
Imports System.Reflection
Imports System.Runtime.Serialization.Formatters.Binary
Imports System.Runtime.Serialization
Imports System.Runtime.CompilerServices
Imports Domain.Base.Entities
Imports System.Data.Entity.ModelConfiguration

<DataContract(IsReference:=True), Serializable(), KnownType(GetType(ViewDashBoardPharmacyDevolution))>
Partial Public Class ViewDashBoardPharmacyDevolution
	Inherits Entity(Of ViewDashBoardPharmacyDevolution)
    Implements IObjectWithChangeTracker
    Implements INotifyPropertyChanged

#Region "Simple Properties"

	Private _row As Integer
	<DataMember()>
	Public Property Row() As Integer
        Get
            Return _row
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_row, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'Row' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _row = value
                OnPropertyChanged("Row")
            End If
        End Set
    End Property

	Private _selectOption As Integer
	<DataMember()>
	Public Property SelectOption() As Integer
        Get
            Return _selectOption
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_selectOption, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'SelectOption' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _selectOption = value
                OnPropertyChanged("SelectOption")
            End If
        End Set
    End Property

	Private _codigoCentroAtencion As String
	<DataMember()>
	Public Property CodigoCentroAtencion() As String
        Get
            Return _codigoCentroAtencion
        End Get
        Set(ByVal value As String)
            If Not Equals(_codigoCentroAtencion, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'CodigoCentroAtencion' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _codigoCentroAtencion = value
                OnPropertyChanged("CodigoCentroAtencion")
            End If
        End Set
    End Property

	Private _consecutivoDevoluciones As Integer
	<DataMember()>
	Public Property ConsecutivoDevoluciones() As Integer
        Get
            Return _consecutivoDevoluciones
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_consecutivoDevoluciones, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'ConsecutivoDevoluciones' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _consecutivoDevoluciones = value
                OnPropertyChanged("ConsecutivoDevoluciones")
            End If
        End Set
    End Property

	Private _fechaDevolucion As Date
	<DataMember()>
	Public Property FechaDevolucion() As Date
        Get
            Return _fechaDevolucion
        End Get
        Set(ByVal value As Date)
            If Not Equals(_fechaDevolucion, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'FechaDevolucion' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _fechaDevolucion = value
                OnPropertyChanged("FechaDevolucion")
            End If
        End Set
    End Property

	Private _codigoProfesional As String
	<DataMember()>
	Public Property CodigoProfesional() As String
        Get
            Return _codigoProfesional
        End Get
        Set(ByVal value As String)
            If Not Equals(_codigoProfesional, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'CodigoProfesional' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _codigoProfesional = value
                OnPropertyChanged("CodigoProfesional")
            End If
        End Set
    End Property

	Private _codigoPaciente As String
	<DataMember()>
	Public Property CodigoPaciente() As String
        Get
            Return _codigoPaciente
        End Get
        Set(ByVal value As String)
            If Not Equals(_codigoPaciente, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'CodigoPaciente' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _codigoPaciente = value
                OnPropertyChanged("CodigoPaciente")
            End If
        End Set
    End Property

	Private _ingreso As String
	<DataMember()>
	Public Property Ingreso() As String
        Get
            Return _ingreso
        End Get
        Set(ByVal value As String)
            If Not Equals(_ingreso, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'Ingreso' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _ingreso = value
                OnPropertyChanged("Ingreso")
            End If
        End Set
    End Property

	Private _centroAtencion As String
	<DataMember()>
	Public Property CentroAtencion() As String
        Get
            Return _centroAtencion
        End Get
        Set(ByVal value As String)
            If Not Equals(_centroAtencion, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'CentroAtencion' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _centroAtencion = value
                OnPropertyChanged("CentroAtencion")
            End If
        End Set
    End Property

	Private _uFUCODIGO As String
	<DataMember()>
	Public Property UFUCODIGO() As String
        Get
            Return _uFUCODIGO
        End Get
        Set(ByVal value As String)
            If Not Equals(_uFUCODIGO, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'UFUCODIGO' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _uFUCODIGO = value
                OnPropertyChanged("UFUCODIGO")
            End If
        End Set
    End Property

	Private _estado As String
	<DataMember()>
	Public Property Estado() As String
        Get
            Return _estado
        End Get
        Set(ByVal value As String)
            If Not Equals(_estado, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'Estado' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _estado = value
                OnPropertyChanged("Estado")
            End If
        End Set
    End Property

	Private _centroCostos As String
	<DataMember()>
	Public Property CentroCostos() As String
        Get
            Return _centroCostos
        End Get
        Set(ByVal value As String)
            If Not Equals(_centroCostos, value) Then
                ChangeTracker.RecordOriginalValue("CentroCostos", _centroCostos)
                _centroCostos = value
                OnPropertyChanged("CentroCostos")
            End If
        End Set
    End Property

	Private _oRIDEVMED As String
	<DataMember()>
	Public Property ORIDEVMED() As String
        Get
            Return _oRIDEVMED
        End Get
        Set(ByVal value As String)
            If Not Equals(_oRIDEVMED, value) Then
                ChangeTracker.RecordOriginalValue("ORIDEVMED", _oRIDEVMED)
                _oRIDEVMED = value
                OnPropertyChanged("ORIDEVMED")
            End If
        End Set
    End Property

	Private _fECREGISTR As Date
	<DataMember()>
	Public Property FECREGISTR() As Date
        Get
            Return _fECREGISTR
        End Get
        Set(ByVal value As Date)
            If Not Equals(_fECREGISTR, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'FECREGISTR' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _fECREGISTR = value
                OnPropertyChanged("FECREGISTR")
            End If
        End Set
    End Property

	Private _cODUSUARI As String
	<DataMember()>
	Public Property CODUSUARI() As String
        Get
            Return _cODUSUARI
        End Get
        Set(ByVal value As String)
            If Not Equals(_cODUSUARI, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'CODUSUARI' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _cODUSUARI = value
                OnPropertyChanged("CODUSUARI")
            End If
        End Set
    End Property

	Private _nombrePaciente As String
	<DataMember()>
	Public Property NombrePaciente() As String
        Get
            Return _nombrePaciente
        End Get
        Set(ByVal value As String)
            If Not Equals(_nombrePaciente, value) Then
                ChangeTracker.RecordOriginalValue("NombrePaciente", _nombrePaciente)
                _nombrePaciente = value
                OnPropertyChanged("NombrePaciente")
            End If
        End Set
    End Property

	Private _unidadFuncional As String
	<DataMember()>
	Public Property UnidadFuncional() As String
        Get
            Return _unidadFuncional
        End Get
        Set(ByVal value As String)
            If Not Equals(_unidadFuncional, value) Then
                ChangeTracker.RecordOriginalValue("UnidadFuncional", _unidadFuncional)
                _unidadFuncional = value
                OnPropertyChanged("UnidadFuncional")
            End If
        End Set
    End Property

	Private _nombreMedico As String
	<DataMember()>
	Public Property NombreMedico() As String
        Get
            Return _nombreMedico
        End Get
        Set(ByVal value As String)
            If Not Equals(_nombreMedico, value) Then
                ChangeTracker.RecordOriginalValue("NombreMedico", _nombreMedico)
                _nombreMedico = value
                OnPropertyChanged("NombreMedico")
            End If
        End Set
    End Property

	Private _bodega As String
	<DataMember()>
	Public Property Bodega() As String
        Get
            Return _bodega
        End Get
        Set(ByVal value As String)
            If Not Equals(_bodega, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'Bodega' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _bodega = value
                OnPropertyChanged("Bodega")
            End If
        End Set
    End Property

	Private _origenDevolutivo As String
	<DataMember()>
	Public Property OrigenDevolutivo() As String
        Get
            Return _origenDevolutivo
        End Get
        Set(ByVal value As String)
            If Not Equals(_origenDevolutivo, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'OrigenDevolutivo' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _origenDevolutivo = value
                OnPropertyChanged("OrigenDevolutivo")
            End If
        End Set
    End Property

	Private _impresionDev As Nullable(Of Boolean)
	<DataMember()>
	Public Property ImpresionDev() As Nullable(Of Boolean)
        Get
            Return _impresionDev
        End Get
        Set(ByVal value As Nullable(Of Boolean))
            If Not Equals(_impresionDev, value) Then
                ChangeTracker.RecordOriginalValue("ImpresionDev", _impresionDev)
                _impresionDev = value
                OnPropertyChanged("ImpresionDev")
            End If
        End Set
    End Property

	Private _codigoCama As String
	<DataMember()>
	Public Property CodigoCama() As String
        Get
            Return _codigoCama
        End Get
        Set(ByVal value As String)
            If Not Equals(_codigoCama, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'CodigoCama' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _codigoCama = value
                OnPropertyChanged("CodigoCama")
            End If
        End Set
    End Property

	Private _careCenterDescription As String
	<DataMember()>
	Public Property CareCenterDescription() As String
        Get
            Return _careCenterDescription
        End Get
        Set(ByVal value As String)
            If Not Equals(_careCenterDescription, value) Then
                ChangeTracker.RecordOriginalValue("CareCenterDescription", _careCenterDescription)
                _careCenterDescription = value
                OnPropertyChanged("CareCenterDescription")
            End If
        End Set
    End Property

	Private _profesion As String
	<DataMember()>
	Public Property Profesion() As String
        Get
            Return _profesion
        End Get
        Set(ByVal value As String)
            If Not Equals(_profesion, value) Then
                ChangeTracker.RecordOriginalValue("Profesion", _profesion)
                _profesion = value
                OnPropertyChanged("Profesion")
            End If
        End Set
    End Property

	Private _birthDay As Date
	<DataMember()>
	Public Property BirthDay() As Date
        Get
            Return _birthDay
        End Get
        Set(ByVal value As Date)
            If Not Equals(_birthDay, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'BirthDay' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _birthDay = value
                OnPropertyChanged("BirthDay")
            End If
        End Set
    End Property

	Private _mEDICAMENTO As Integer
	<DataMember()>
	Public Property MEDICAMENTO() As Integer
        Get
            Return _mEDICAMENTO
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_mEDICAMENTO, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'MEDICAMENTO' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _mEDICAMENTO = value
                OnPropertyChanged("MEDICAMENTO")
            End If
        End Set
    End Property

	Private _iNSUMOS As Integer
	<DataMember()>
	Public Property INSUMOS() As Integer
        Get
            Return _iNSUMOS
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_iNSUMOS, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'INSUMOS' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _iNSUMOS = value
                OnPropertyChanged("INSUMOS")
            End If
        End Set
    End Property

	Private _mEDICAMENTO_INSUMO As Integer
	<DataMember()>
	Public Property MEDICAMENTO_INSUMO() As Integer
        Get
            Return _mEDICAMENTO_INSUMO
        End Get
        Set(ByVal value As Integer)
            If Not Equals(_mEDICAMENTO_INSUMO, value) Then
                If ChangeTracker.ChangeTrackingEnabled AndAlso ChangeTracker.State <> ObjectState.Added Then
                    Throw New InvalidOperationException("The property 'MEDICAMENTO_INSUMO' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.")
                End If
                _mEDICAMENTO_INSUMO = value
                OnPropertyChanged("MEDICAMENTO_INSUMO")
            End If
        End Set
    End Property

#End Region

#Region "ChangeTracking"

    Protected Overridable Sub OnPropertyChanged(ByVal propertyName As String)
        If ChangeTracker.State <> ObjectState.Added AndAlso ChangeTracker.State <> ObjectState.Deleted Then
            ChangeTracker.State = ObjectState.Modified
        End If
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Protected Overridable Sub OnNavigationPropertyChanged(ByVal propertyName As String)
        RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
    End Sub

    Private Event PropertyChanged As PropertyChangedEventHandler Implements INotifyPropertyChanged.PropertyChanged
    Private _changeTracker As ObjectChangeTracker

    <DataMember()>
    Public Property ChangeTracker() As ObjectChangeTracker Implements IObjectWithChangeTracker.ChangeTracker
        Get
            If _changeTracker Is Nothing Then
                _changeTracker = New ObjectChangeTracker()
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            Return _changeTracker
        End Get
        Set(ByVal value As ObjectChangeTracker)
            If _changeTracker IsNot Nothing Then
                RemoveHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
            _changeTracker = value
            If _changeTracker IsNot Nothing Then
                AddHandler _changeTracker.ObjectStateChanging, AddressOf HandleObjectStateChanging
            End If
        End Set
    End Property

    Private Sub HandleObjectStateChanging(ByVal sender As Object, ByVal e As ObjectStateChangingEventArgs)
        If e.NewState = ObjectState.Deleted Then
            Me.ClearNavigationProperties()
        End If
    End Sub

    Private _isDeserializing As Boolean
    Protected Property IsDeserializing() As Boolean
        Get
            Return _isDeserializing
        End Get
        Private Set(ByVal value As Boolean)
            _isDeserializing = value
        End Set
    End Property

    <OnDeserializing()>
    Public Sub OnDeserializingMethod(ByVal context As StreamingContext)
        IsDeserializing = True
    End Sub

    <OnDeserialized()>
    Public Sub OnDeserializedMethod(ByVal context As StreamingContext)
        IsDeserializing = False
        ChangeTracker.ChangeTrackingEnabled = True
    End Sub

    Protected Overridable Sub ClearNavigationProperties()
    End Sub

#End Region

End Class

