CREATE EXTERNAL TABLE [Security].[Containers] (
    [Id] INT NOT NULL,
    [Code] VARCHAR (3) NOT NULL,
    [Name] VARCHAR (100) NOT NULL,
    [FoundationalContainer] VARCHAR (30) NOT NULL,
    [TransactionalContainer] VARCHAR (30) NOT NULL,
    [DocumentalContainer] VARCHAR (30) NOT NULL,
    [VituelContainer] VARCHAR (30) NOT NULL,
    [HISContainer] VARCHAR (30) NOT NULL,
    [InteropCostContainer] VARCHAR (30) NOT NULL,
    [HISIntegration] TINYINT NOT NULL,
    [GlossesIntegration] TINYINT NOT NULL,
    [PayrollIntegration] TINYINT NOT NULL,
    [CompanyType] TINYINT NOT NULL,
    [CompanyNit] VARCHAR (15) NOT NULL,
    [RepresentationLegal] VARCHAR (100) NOT NULL,
    [City] VARCHAR (50) NOT NULL,
    [Address] VARCHAR (50) NOT NULL,
    [Telephone] VARCHAR (20) NOT NULL,
    [ProductionCompany] BIT NOT NULL,
    [KeyCode] VARCHAR (20) NOT NULL,
    [LyncIntegration] BIT NOT NULL,
    [Version] VARCHAR (20) NOT NULL,
    [State] BIT NOT NULL,
    [DispensingIntegration] TINYINT NOT NULL,
    [HumanTalentIntegration] TINYINT NOT NULL,
    [VerificationDigitNit] VARCHAR (3) NOT NULL,
    [ArchitectureType] TINYINT NOT NULL,
    [CloudType] TINYINT NOT NULL,
    [Multitenant] BIT NOT NULL,
    [SuscriptionID] UNIQUEIDENTIFIER NOT NULL,
    [BranchOffices] TINYINT NOT NULL,
    [ServiceConfigurationId] TINYINT NOT NULL,
    [PublishEvent] BIT NULL,
    [UrlQueue] VARCHAR (MAX) NULL,
    [IsSynchronized] BIT NULL,
    [FootImage] VARCHAR (100) NULL,
    [DecimalSeparator] VARCHAR (1) NULL,
    [AzureFileShareRoute] VARCHAR (500) NULL,
    [ArchitectureQueue] TINYINT NULL,
    [NameQueue] VARCHAR (30) NULL,
    [ClientId] UNIQUEIDENTIFIER NULL
)
    WITH (
    DATA_SOURCE = [INDIGOSEC],
    SCHEMA_NAME = N'Security',
    OBJECT_NAME = N'Containers'
    );

GO