CREATE TABLE [dbo].[ChemotherapyOrders] (
    [ID_COMPANY]              VARCHAR (9)   NULL,
    [TIPO IDENTIFICACION]     VARCHAR (2)   NULL,
    [NRO IDENTIFICACION]      VARCHAR (25)  NOT NULL,
    [NOMBRE PACIENTE]         VARCHAR (250) NULL,
    [FECHA NACIMIENTO]        DATE          NULL,
    [EDAD]                    INT           NULL,
    [TELEFONO PRINCIPAL]      VARCHAR (MAX) NOT NULL,
    [TELEFONO ALTERNATIVO]    VARCHAR (MAX) NOT NULL,
    [DEPARTAMENTO]            CHAR (40)     NOT NULL,
    [MINICIPIO]               CHAR (40)     NOT NULL,
    [DIRECCION]               VARCHAR (MAX) NULL,
    [ENTIDAD]                 VARCHAR (300) NOT NULL,
    [GRUPO ATENCION]          VARCHAR (100) NOT NULL,
    [NRO DE INGRESO]          CHAR (10)     NOT NULL,
    [CENTRO DE ATENCION]      CHAR (100)    NOT NULL,
    [UNIDAD FUNCIONAL]        CHAR (60)     NOT NULL,
    [CIUDAD PROCEDIMIENTO]    VARCHAR (9)   NULL,
    [CODIGO ESQUEMA]          VARCHAR (20)  NOT NULL,
    [ESQUEMA]                 VARCHAR (250) NOT NULL,
    [TIPO ESQUEMA]            VARCHAR (22)  NULL,
    [SERVICIO ADMINISTRACION] VARCHAR (300) NULL,
    [ESTADO]                  VARCHAR (46)  NULL,
    [CODIGO DIAGNOSTICO]      CHAR (4)      NOT NULL,
    [DIAGNOSTICO]             CHAR (350)    NULL,
    [TIPO DIAGNOSTICO]        VARCHAR (21)  NULL,
    [FECHA PATOLOGIA]         VARCHAR (10)  NULL,
    [NRO CICLOS ESQUEMA]      CHAR (30)     NULL,
    [CICLO ACTUAL]            CHAR (30)     NULL,
    [DIA]                     CHAR (30)     NULL,
    [PROFESIONAL ORDENO]      CHAR (60)     NOT NULL,
    [PROFEIONAL ORDENO CICLO] CHAR (60)     NOT NULL,
    [FECHA ORDEN]             DATE          NULL,
    [FECHA ORDEN CICLO]       DATE          NULL,
    [ESTADO DIA]              VARCHAR (15)  NULL,
    [FECHA APLICACION]        DATE          NOT NULL,
    [NRO AUTORIZACION]        CHAR (15)     NULL,
    [CUPS]                    CHAR (20)     NULL,
    [DESCRIPCION]             VARCHAR (300) NULL,
    [CICLO ESQUEMA]           VARCHAR (34)  NOT NULL,
    [SALA]                    VARCHAR (100) NULL,
    [FECHA BUSQUEDA]          DATE          NULL,
    [AÑO CARGUE]              INT           NULL
);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Tabla de staging o reporte que consolida las órdenes de quimioterapia de pacientes, incluyendo datos demográficos (identificación, nombre, edad, contacto, ubicación), información del encuentro (número de ingreso, centro, unidad funcional, entidad aseguradora) y detalle clínico-administrativo del tratamiento oncológico (esquema, ciclo, día, diagnóstico CIE, profesional que ordenó, fecha de aplicación, autorización y código CUPS).', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'ChemotherapyOrders';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DescriptionSource', @value=N'ai_claude-sonnet-4-6_2026-05-05', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'ChemotherapyOrders';
GO
