CREATE TABLE [dbo].[ESE_HC_HISTORICO_PRIMERAINFANCIA] (
    [Ingreso]                                                                                              CHAR (10)        NOT NULL,
    [CodCentro]                                                                                            CHAR (10)        NOT NULL,
    [CentroAtencion]                                                                                       VARCHAR (100)    NULL,
    [1.PrimerNombre]                                                                                       VARCHAR (20)     NULL,
    [2.SegundoNombre]                                                                                      VARCHAR (20)     NULL,
    [3.PrimerApellido]                                                                                     VARCHAR (20)     NULL,
    [4.SegundoApellido]                                                                                    VARCHAR (20)     NULL,
    [5.TipoIdentificacion]                                                                                 VARCHAR (4)      NULL,
    [6.Identificacion]                                                                                     VARCHAR (15)     NULL,
    [7.FechaNacimiento]                                                                                    DATE             NULL,
    [Edad]                                                                                                 INT              NULL,
    [8.Sexo]                                                                                               VARCHAR (1)      NULL,
    [9.Regimen]                                                                                            VARCHAR (31)     NULL,
    [10.CodigoEPSEntidadTerritorial]                                                                       CHAR (9)         NOT NULL,
    [Entidad]                                                                                              CHAR (150)       NOT NULL,
    [11.GrupoEtnico]                                                                                       VARCHAR (3)      NULL,
    [12.PoblacionEspecial]                                                                                 VARCHAR (3)      NULL,
    [13.MunicipioResidencia]                                                                               VARCHAR (15)     NULL,
    [14.Telefono]                                                                                          VARCHAR (MAX)    NOT NULL,
    [Direccion]                                                                                            VARCHAR (MAX)    NOT NULL,
    [17.FechaHistoria]                                                                                     DATE             NULL,
    [CIE-10]                                                                                               CHAR (4)         NULL,
    [Diagnostico]                                                                                          CHAR (150)       NULL,
    [23.Peso]                                                                                              NUMERIC (23, 8)  NULL,
    [24.Talla]                                                                                             INT              NULL,
    [IMC]                                                                                                  NUMERIC (38, 18) NULL,
    [25.TAS]                                                                                               INT              NULL,
    [26.TAD]                                                                                               INT              NULL,
    [medico]                                                                                               CHAR (60)        NOT NULL,
    [PerimetroAbdominal]                                                                                   CHAR (30)        NULL,
    [MotivoConsulta]                                                                                       VARCHAR (MAX)    NULL,
    [IDMODELOHC]                                                                                           INT              NULL,
    [ID]                                                                                                   INT              NOT NULL,
    [Adinamia]                                                                                             VARCHAR (5000)   NULL,
    [Anorexia]                                                                                             VARCHAR (5000)   NULL,
    [Astenia]                                                                                              VARCHAR (5000)   NULL,
    [Escalofríos]                                                                                          VARCHAR (5000)   NULL,
    [Fiebre]                                                                                               VARCHAR (5000)   NULL,
    [Pérdida de peso]                                                                                      VARCHAR (5000)   NULL,
    [Sintomático respiratorio (tos y expectoración por 15 días o más)]                                     VARCHAR (5000)   NULL,
    [Sintomático piel (lesión no congénita de larga duración, sin respuesta a tratamientos)]               VARCHAR (5000)   NULL,
    [Aumento de peso]                                                                                      VARCHAR (5000)   NULL,
    [Otros síntomas ]                                                                                      VARCHAR (5000)   NULL,
    [Alteración de la agudeza visual]                                                                      VARCHAR (5000)   NULL,
    [Congestión ocular]                                                                                    VARCHAR (5000)   NULL,
    [Diplopía]                                                                                             VARCHAR (5000)   NULL,
    [Dolor en ojos]                                                                                        VARCHAR (5000)   NULL,
    [Fotofobia]                                                                                            VARCHAR (5000)   NULL,
    [Lagrimeo]                                                                                             VARCHAR (5000)   NULL,
    [Secreción en ojos]                                                                                    VARCHAR (5000)   NULL,
    [Sequedad]                                                                                             VARCHAR (5000)   NULL,
    [Visión borrosa]                                                                                       VARCHAR (5000)   NULL,
    [Edema palpebral]                                                                                      VARCHAR (5000)   NULL,
    [Otros ojos]                                                                                           VARCHAR (5000)   NULL,
    [Alteración de la agudeza auditiva]                                                                    VARCHAR (5000)   NULL,
    [Dolor en oídos]                                                                                       VARCHAR (5000)   NULL,
    [Secreción en oídos]                                                                                   VARCHAR (5000)   NULL,
    [Tinnitus]                                                                                             VARCHAR (5000)   NULL,
    [Otros oídos]                                                                                          VARCHAR (5000)   NULL,
    [Alteración de la agudeza olfatoria]                                                                   VARCHAR (5000)   NULL,
    [Epistaxis]                                                                                            VARCHAR (5000)   NULL,
    [Obstrucción]                                                                                          VARCHAR (5000)   NULL,
    [Secreción en nariz]                                                                                   VARCHAR (5000)   NULL,
    [Otros nariz]                                                                                          VARCHAR (5000)   NULL,
    [Afonía]                                                                                               VARCHAR (5000)   NULL,
    [Alteración del gusto]                                                                                 VARCHAR (5000)   NULL,
    [Disfagia]                                                                                             VARCHAR (5000)   NULL,
    [Disfonía]                                                                                             VARCHAR (5000)   NULL,
    [Gingivitis]                                                                                           VARCHAR (5000)   NULL,
    [Gingivorragia]                                                                                        VARCHAR (5000)   NULL,
    [Halitosis]                                                                                            VARCHAR (5000)   NULL,
    [Odontalgia]                                                                                           VARCHAR (5000)   NULL,
    [Úlceras en boca]                                                                                      VARCHAR (5000)   NULL,
    [Onicofagia]                                                                                           VARCHAR (5000)   NULL,
    [Respiración bucal]                                                                                    VARCHAR (5000)   NULL,
    [Otros cavidad oral]                                                                                   VARCHAR (5000)   NULL,
    [Adenopatías]                                                                                          VARCHAR (5000)   NULL,
    [Dolor en cuello]                                                                                      VARCHAR (5000)   NULL,
    [Espasmo en cuello]                                                                                    VARCHAR (5000)   NULL,
    [Masa]                                                                                                 VARCHAR (5000)   NULL,
    [Otros cuello]                                                                                         VARCHAR (5000)   NULL,
    [Arritmias]                                                                                            VARCHAR (5000)   NULL,
    [Disnea de esfuerzo]                                                                                   VARCHAR (5000)   NULL,
    [Dolor torácico]                                                                                       VARCHAR (5000)   NULL,
    [Ortopnea]                                                                                             VARCHAR (5000)   NULL,
    [Palpitaciones]                                                                                        VARCHAR (5000)   NULL,
    [Disnea paroxística nocturna]                                                                          VARCHAR (5000)   NULL,
    [Claudicación intermitente]                                                                            VARCHAR (5000)   NULL,
    [Otros cardiovascular]                                                                                 VARCHAR (5000)   NULL,
    [Dolor al respirar]                                                                                    VARCHAR (5000)   NULL,
    [Estertores]                                                                                           VARCHAR (5000)   NULL,
    [Expectoración]                                                                                        VARCHAR (5000)   NULL,
    [Hemoptisis]                                                                                           VARCHAR (5000)   NULL,
    [Sibilancias]                                                                                          VARCHAR (5000)   NULL,
    [Tos]                                                                                                  VARCHAR (5000)   NULL,
    [Otros respiratorio]                                                                                   VARCHAR (5000)   NULL,
    [Diarrea]                                                                                              VARCHAR (5000)   NULL,
    [Dolor abdominal]                                                                                      VARCHAR (5000)   NULL,
    [Estreñimiento]                                                                                        VARCHAR (5000)   NULL,
    [Pirosis]                                                                                              VARCHAR (5000)   NULL,
    [Hematemesis]                                                                                          VARCHAR (5000)   NULL,
    [Ictericia]                                                                                            VARCHAR (5000)   NULL,
    [Vomito]                                                                                               VARCHAR (5000)   NULL,
    [Polifagia]                                                                                            VARCHAR (5000)   NULL,
    [Polidipsia]                                                                                           VARCHAR (5000)   NULL,
    [Eructos]                                                                                              VARCHAR (5000)   NULL,
    [Flatulencia]                                                                                          VARCHAR (5000)   NULL,
    [Prurito anal]                                                                                         VARCHAR (5000)   NULL,
    [Hábito intestinal / día]                                                                              VARCHAR (5000)   NULL,
    [Incontinencia fecal]                                                                                  VARCHAR (5000)   NULL,
    [Otros gastrointestinal]                                                                               VARCHAR (5000)   NULL,
    [Anuria]                                                                                               VARCHAR (5000)   NULL,
    [Dolor genito-urinario]                                                                                VARCHAR (5000)   NULL,
    [Hematuria]                                                                                            VARCHAR (5000)   NULL,
    [Polaquiuria]                                                                                          VARCHAR (5000)   NULL,
    [Tenesmo urinario]                                                                                     VARCHAR (5000)   NULL,
    [Secreción]                                                                                            VARCHAR (5000)   NULL,
    [Poliuria]                                                                                             VARCHAR (5000)   NULL,
    [Incontinencia urinaria]                                                                               VARCHAR (5000)   NULL,
    [Nicturia]                                                                                             VARCHAR (5000)   NULL,
    [Oliguria]                                                                                             VARCHAR (5000)   NULL,
    [Prurito genital]                                                                                      VARCHAR (5000)   NULL,
    [Otros genito-urinario]                                                                                VARCHAR (5000)   NULL,
    [Afasia]                                                                                               VARCHAR (5000)   NULL,
    [Amnesia]                                                                                              VARCHAR (5000)   NULL,
    [Cefalea]                                                                                              VARCHAR (5000)   NULL,
    [Convulsiones]                                                                                         VARCHAR (5000)   NULL,
    [Desorientación]                                                                                       VARCHAR (5000)   NULL,
    [Parálisis]                                                                                            VARCHAR (5000)   NULL,
    [Parestesias]                                                                                          VARCHAR (5000)   NULL,
    [Vértigo]                                                                                              VARCHAR (5000)   NULL,
    [Síncope]                                                                                              VARCHAR (5000)   NULL,
    [Alucinaciones]                                                                                        VARCHAR (5000)   NULL,
    [Insomnio]                                                                                             VARCHAR (5000)   NULL,
    [Otros neurológico]                                                                                    VARCHAR (5000)   NULL,
    [Dolor articular]                                                                                      VARCHAR (5000)   NULL,
    [Dolor óseo]                                                                                           VARCHAR (5000)   NULL,
    [Edema en extremidades]                                                                                VARCHAR (5000)   NULL,
    [Espasmo muscular]                                                                                     VARCHAR (5000)   NULL,
    [Deformidad articular]                                                                                 VARCHAR (5000)   NULL,
    [Asimetrías]                                                                                           VARCHAR (5000)   NULL,
    [Otros osteo-muscular]                                                                                 VARCHAR (5000)   NULL,
    [Distribución anormal de la grasa]                                                                     VARCHAR (5000)   NULL,
    [Hirsutismo]                                                                                           VARCHAR (5000)   NULL,
    [Nerviosismo]                                                                                          VARCHAR (5000)   NULL,
    [Sed]                                                                                                  VARCHAR (5000)   NULL,
    [Sudoración]                                                                                           VARCHAR (5000)   NULL,
    [Otros endocrino]                                                                                      VARCHAR (5000)   NULL,
    [Alopecia]                                                                                             VARCHAR (5000)   NULL,
    [Alteración de la pigmentación]                                                                        VARCHAR (5000)   NULL,
    [Equimosis]                                                                                            VARCHAR (5000)   NULL,
    [Erupciones]                                                                                           VARCHAR (5000)   NULL,
    [Petequias]                                                                                            VARCHAR (5000)   NULL,
    [Prurito]                                                                                              VARCHAR (5000)   NULL,
    [Úlceras ]                                                                                             VARCHAR (5000)   NULL,
    [Alteraciones en las uñas]                                                                             VARCHAR (5000)   NULL,
    [Palidez]                                                                                              VARCHAR (5000)   NULL,
    [Otros piel y anexos]                                                                                  VARCHAR (5000)   NULL,
    [Otros sistemas]                                                                                       VARCHAR (5000)   NULL,
    [IDHCHISPACA_RES]                                                                                      INT              NULL,
    [Enfermedad cardíaca]                                                                                  VARCHAR (5000)   NULL,
    [Registre el tipo de enfermedad cardíaca]                                                              VARCHAR (5000)   NULL,
    [Fecha diagnóstico enfermedad cardíaca]                                                                VARCHAR (5000)   NULL,
    [Asma bronquial]                                                                                       VARCHAR (5000)   NULL,
    [Fecha diagnóstico asma]                                                                               VARCHAR (5000)   NULL,
    [Fibrosis quística]                                                                                    VARCHAR (5000)   NULL,
    [Fecha diagnóstico fibrosis quística]                                                                  VARCHAR (5000)   NULL,
    [Hepatitis B]                                                                                          VARCHAR (5000)   NULL,
    [Fecha diagnóstico Hepatitis B]                                                                        VARCHAR (5000)   NULL,
    [VIH]                                                                                                  VARCHAR (5000)   NULL,
    [Fecha diagnóstico VIH]                                                                                VARCHAR (5000)   NULL,
    [Tuberculosis]                                                                                         VARCHAR (5000)   NULL,
    [Fecha diagnóstico TB]                                                                                 VARCHAR (5000)   NULL,
    [Hemoglobinopatías o trastornos hematológicos]                                                         VARCHAR (5000)   NULL,
    [Fecha diagnóstico hemoglobinopatía]                                                                   VARCHAR (5000)   NULL,
    [Hipotiroidismo]                                                                                       VARCHAR (5000)   NULL,
    [Fecha diagnóstico hipotiroidismo]                                                                     VARCHAR (5000)   NULL,
    [Hipertiroidismo]                                                                                      VARCHAR (5000)   NULL,
    [Fecha diagnóstico hipertiroidismo]                                                                    VARCHAR (5000)   NULL,
    [Diabetes Mellitus tipo I]                                                                             VARCHAR (5000)   NULL,
    [Fecha diagnóstico DM I]                                                                               VARCHAR (5000)   NULL,
    [Epilepsia / Síndrome convulsivo]                                                                      VARCHAR (5000)   NULL,
    [Fecha diagnóstico síndrome convulsivo]                                                                VARCHAR (5000)   NULL,
    [Anomalías musculo esqueléticas]                                                                       VARCHAR (5000)   NULL,
    [Registre el tipo anomalía musculo esquelética]                                                        VARCHAR (5000)   NULL,
    [Fecha diagnóstico anomalía musculo esquelética]                                                       VARCHAR (5000)   NULL,
    [Anomalías neurológicas (déficit)]                                                                     VARCHAR (5000)   NULL,
    [Registre el tipo anomalía neurológica]                                                                VARCHAR (5000)   NULL,
    [Fecha diagnóstico anomalía neurológica]                                                               VARCHAR (5000)   NULL,
    [Cáncer en la mujer]                                                                                   VARCHAR (5000)   NULL,
    [Cual otro cáncer en la mujer?]                                                                        VARCHAR (5000)   NULL,
    [Registre el tratamiento recibido en la mujer]                                                         VARCHAR (5000)   NULL,
    [Fecha diagnóstico cáncer en la mujer]                                                                 VARCHAR (5000)   NULL,
    [Cáncer en el hombre]                                                                                  VARCHAR (5000)   NULL,
    [Cual  otro cáncer en el hombre?]                                                                      VARCHAR (5000)   NULL,
    [Registre el tratamiento recibido]                                                                     VARCHAR (5000)   NULL,
    [Fecha diagnóstico del cáncer]                                                                         VARCHAR (5000)   NULL,
    [Malformaciones congénitas]                                                                            VARCHAR (5000)   NULL,
    [Registre el tipo malformación congénita]                                                              VARCHAR (5000)   NULL,
    [Patología auditiva]                                                                                   VARCHAR (5000)   NULL,
    [Describa la patología auditiva y el plan de manejo]                                                   VARCHAR (5000)   NULL,
    [Patología visual]                                                                                     VARCHAR (5000)   NULL,
    [Describa la patología visual y el plan de manejo]                                                     VARCHAR (5000)   NULL,
    [Enfermedad genética]                                                                                  VARCHAR (5000)   NULL,
    [Describa la enfermedad genética y el plan de manejo]                                                  VARCHAR (5000)   NULL,
    [Rinitis]                                                                                              VARCHAR (5000)   NULL,
    [Fecha diagnóstico rinitis]                                                                            VARCHAR (5000)   NULL,
    [Hospitalizaciones]                                                                                    VARCHAR (5000)   NULL,
    [Registre el motivo de la(s) hospitalización (es)]                                                     VARCHAR (5000)   NULL,
    [Fecha de la última hospitalización]                                                                   VARCHAR (5000)   NULL,
    [Otros antecedentes médicos]                                                                           VARCHAR (5000)   NULL,
    [Apendicectomía]                                                                                       VARCHAR (5000)   NULL,
    [Fecha apendicectomía]                                                                                 VARCHAR (5000)   NULL,
    [Herniorrafia]                                                                                         VARCHAR (5000)   NULL,
    [Fecha herniorrafia]                                                                                   VARCHAR (5000)   NULL,
    [Cirugía cardiovascular]                                                                               VARCHAR (5000)   NULL,
    [Registre el tipo de cx cardiovascular]                                                                VARCHAR (5000)   NULL,
    [Fecha Cx]                                                                                             VARCHAR (5000)   NULL,
    [Otros antecedentes qx]                                                                                VARCHAR (5000)   NULL,
    [Anestesia general]                                                                                    VARCHAR (5000)   NULL,
    [Fecha última anestesia general]                                                                       VARCHAR (5000)   NULL,
    [Anestesia regional]                                                                                   VARCHAR (5000)   NULL,
    [Fecha última anestesia regional]                                                                      VARCHAR (5000)   NULL,
    [Anestesia general y regional]                                                                         VARCHAR (5000)   NULL,
    [Fecha última anestesia general y regional]                                                            VARCHAR (5000)   NULL,
    [Anestesia local]                                                                                      VARCHAR (5000)   NULL,
    [Fecha última anestesia local]                                                                         VARCHAR (5000)   NULL,
    [Otros / Observaciones]                                                                                VARCHAR (5000)   NULL,
    [Glóbulos rojos]                                                                                       VARCHAR (5000)   NULL,
    [Plasma]                                                                                               VARCHAR (5000)   NULL,
    [Plaquetas]                                                                                            VARCHAR (5000)   NULL,
    [Crioprecipitados]                                                                                     VARCHAR (5000)   NULL,
    [Sangre total]                                                                                         VARCHAR (5000)   NULL,
    [Otros]                                                                                                VARCHAR (5000)   NULL,
    [Fecha de la última transfusión ]                                                                      VARCHAR (5000)   NULL,
    [Reacciones transfusionales]                                                                           VARCHAR (5000)   NULL,
    [Otros antecedentes transfusionales]                                                                   VARCHAR (5000)   NULL,
    [Antecedentes Inmunológicos]                                                                           VARCHAR (5000)   NULL,
    [Fractura]                                                                                             VARCHAR (5000)   NULL,
    [Describa la fractura]                                                                                 VARCHAR (5000)   NULL,
    [Luxación]                                                                                             VARCHAR (5000)   NULL,
    [Describa la luxación]                                                                                 VARCHAR (5000)   NULL,
    [Esguince]                                                                                             VARCHAR (5000)   NULL,
    [Describa lel esguince]                                                                                VARCHAR (5000)   NULL,
    [Otros antecedentes traumáticos]                                                                       VARCHAR (5000)   NULL,
    [Esquizofrenia]                                                                                        VARCHAR (5000)   NULL,
    [Fecha diagnóstico de la esquizofrenia]                                                                VARCHAR (5000)   NULL,
    [Trastorno Bipolar]                                                                                    VARCHAR (5000)   NULL,
    [Fecha diagnóstico del trastorno bipolar]                                                              VARCHAR (5000)   NULL,
    [Trastorno del sueño]                                                                                  VARCHAR (5000)   NULL,
    [Depresión]                                                                                            VARCHAR (5000)   NULL,
    [Problemas afectivos]                                                                                  VARCHAR (5000)   NULL,
    [ansiedad]                                                                                             VARCHAR (5000)   NULL,
    [Fobias]                                                                                               VARCHAR (5000)   NULL,
    [Registre el tipo de fobia]                                                                            VARCHAR (5000)   NULL,
    [Trastornos del aprendizaje]                                                                           VARCHAR (5000)   NULL,
    [Déficit de atención e hiperactividad]                                                                 VARCHAR (5000)   NULL,
    [Trastorno negativista desafiante]                                                                     VARCHAR (5000)   NULL,
    [Trastorno disocial]                                                                                   VARCHAR (5000)   NULL,
    [Comportamiento perturbador no especificado]                                                           VARCHAR (5000)   NULL,
    [Trastorno de la conducta alimentaria]                                                                 VARCHAR (5000)   NULL,
    [Trastorno de la personalidad]                                                                         VARCHAR (5000)   NULL,
    [Trastorno por estrés postraumático]                                                                   VARCHAR (5000)   NULL,
    [Trastorno de la memoria]                                                                              VARCHAR (5000)   NULL,
    [Conducta suicida]                                                                                     VARCHAR (5000)   NULL,
    [Tratamiento recibido ante la conducta suicida]                                                        VARCHAR (5000)   NULL,
    [Exposición a violencia]                                                                               VARCHAR (5000)   NULL,
    [Maltrato fìsico, psicologico o ambos]                                                                 VARCHAR (5000)   NULL,
    [Matoneo]                                                                                              VARCHAR (5000)   NULL,
    [Abuso sexual]                                                                                         VARCHAR (5000)   NULL,
    [Violencia sexual]                                                                                     VARCHAR (5000)   NULL,
    [Abandono]                                                                                             VARCHAR (5000)   NULL,
    [Negligencia]                                                                                          VARCHAR (5000)   NULL,
    [Violencia intrafamiliar]                                                                              VARCHAR (5000)   NULL,
    [Victimas del conflicto armado]                                                                        VARCHAR (5000)   NULL,
    [Otros antecedentes psicológicos]                                                                      VARCHAR (5000)   NULL,
    [Estado civil de los padres]                                                                           VARCHAR (5000)   NULL,
    [Madre conocida]                                                                                       VARCHAR (5000)   NULL,
    [Nombre y apellido de la madre]                                                                        VARCHAR (5000)   NULL,
    [Edad de la madre (años)]                                                                              VARCHAR (5000)   NULL,
    [Nivel educativo de la madre]                                                                          VARCHAR (5000)   NULL,
    [Actividad / Cargo de la madre]                                                                        VARCHAR (5000)   NULL,
    [Tipo de relación de la madre con el (la) menor]                                                       VARCHAR (5000)   NULL,
    [¿Convive la madre con el (la) menor?]                                                                 VARCHAR (5000)   NULL,
    [Padre conocido]                                                                                       VARCHAR (5000)   NULL,
    [Nombre y apellido del padre]                                                                          VARCHAR (5000)   NULL,
    [Edad del padre (años)]                                                                                VARCHAR (5000)   NULL,
    [Nivel educativo del padre]                                                                            VARCHAR (5000)   NULL,
    [Actividad / Cargo del padre]                                                                          VARCHAR (5000)   NULL,
    [Tipo de relación del padre con el (la) menor]                                                         VARCHAR (5000)   NULL,
    [¿Convive el padre con el (la) menor?]                                                                 VARCHAR (5000)   NULL,
    [Tipo de relación entre los padres]                                                                    VARCHAR (5000)   NULL,
    [¿Existe apoyo económico?]                                                                             VARCHAR (5000)   NULL,
    [Los padres tienen una relación de consanguinidad]                                                     VARCHAR (5000)   NULL,
    [Tipo de parentesco entre los padres]                                                                  VARCHAR (5000)   NULL,
    [Hermano 1]                                                                                            VARCHAR (5000)   NULL,
    [Nombre y apellido del hermano 1]                                                                      VARCHAR (5000)   NULL,
    [Edad del hermano 1 (años)]                                                                            VARCHAR (5000)   NULL,
    [Género del hermano 1]                                                                                 VARCHAR (5000)   NULL,
    [Nivel educativo del hermano 1]                                                                        VARCHAR (5000)   NULL,
    [Actividad / Cargo del hermano 1]                                                                      VARCHAR (5000)   NULL,
    [Tipo de relación del hermano 1 con el (la) menor]                                                     VARCHAR (5000)   NULL,
    [¿Convive el hermano 1 con el (la) menor?]                                                             VARCHAR (5000)   NULL,
    [Hermano 2]                                                                                            VARCHAR (5000)   NULL,
    [Nombre y apellido del hermano 2]                                                                      VARCHAR (5000)   NULL,
    [Edad del hermano 2 (años)]                                                                            VARCHAR (5000)   NULL,
    [Género del hermano 2]                                                                                 VARCHAR (5000)   NULL,
    [Nivel educativo del hermano 2]                                                                        VARCHAR (5000)   NULL,
    [Actividad / Cargo del hermano 2]                                                                      VARCHAR (5000)   NULL,
    [Tipo de relación del hermano 2 con el (la) menor]                                                     VARCHAR (5000)   NULL,
    [¿Convive el hermano 2 con el (la) menor?]                                                             VARCHAR (5000)   NULL,
    [Hermano 3]                                                                                            VARCHAR (5000)   NULL,
    [Nombre y apellido del hermano 3]                                                                      VARCHAR (5000)   NULL,
    [Edad del hermano 3 (años)]                                                                            VARCHAR (5000)   NULL,
    [Género del hermano 3]                                                                                 VARCHAR (5000)   NULL,
    [Nivel educativo del hermano 3]                                                                        VARCHAR (5000)   NULL,
    [Actividad / Cargo del hermano 3]                                                                      VARCHAR (5000)   NULL,
    [Tipo de relación del hermano 3 con el (la) menor]                                                     VARCHAR (5000)   NULL,
    [¿Convive el hermano 3 con el (la) menor?]                                                             VARCHAR (5000)   NULL,
    [Registre información de otros hermanos]                                                               VARCHAR (5000)   NULL,
    [Pareja sentimental de la madre diferente al padre]                                                    VARCHAR (5000)   NULL,
    [Nombre y apellido de la pareja de la madre]                                                           VARCHAR (5000)   NULL,
    [Edad de la pareja de la madre]                                                                        VARCHAR (5000)   NULL,
    [Género de la pareja de la madre]                                                                      VARCHAR (5000)   NULL,
    [Tipo de relación de la pareja de la madre con el (la) menor]                                          VARCHAR (5000)   NULL,
    [¿Convive la pareja de la madre con el (la) menor?]                                                    VARCHAR (5000)   NULL,
    [Pareja sentimental del padre diferente a la madre]                                                    VARCHAR (5000)   NULL,
    [Nombre y apellido de la pareja del padre]                                                             VARCHAR (5000)   NULL,
    [Edad de la pareja del padre]                                                                          VARCHAR (5000)   NULL,
    [Género de la pareja del padre]                                                                        VARCHAR (5000)   NULL,
    [Tipo de relación de la pareja del padre con el (la) menor]                                            VARCHAR (5000)   NULL,
    [¿Convive la pareja del padre con el (la) menor?]                                                      VARCHAR (5000)   NULL,
    [¿El menor tiene a uno de sus padres privado de la libertad?]                                          VARCHAR (5000)   NULL,
    [¿Con quién convive el (la) menor en este momento?]                                                    VARCHAR (5000)   NULL,
    [¿Con quién ha convivido el (la) menor?]                                                               VARCHAR (5000)   NULL,
    [Existe relación armónica entre quienes conviven?]                                                     VARCHAR (5000)   NULL,
    [¿El menor es adoptado?]                                                                               VARCHAR (5000)   NULL,
    [¿Quién es el principal cuidador del niño (con quién pasa más del 50% de su tiempo cuando no está en ] VARCHAR (5000)   NULL,
    [Tipo de relación entre los padres, el cuidador y/o profesores y el (la) menor]                        VARCHAR (5000)   NULL,
    [Describa situaciones de conflicto o estrés por las que haya pasado la familia]                        VARCHAR (5000)   NULL,
    [Leucemia]                                                                                             VARCHAR (5000)   NULL,
    [Linfoma]                                                                                              VARCHAR (5000)   NULL,
    [Cáncer de colon y recto]                                                                              VARCHAR (5000)   NULL,
    [Cáncer de cuello uterino]                                                                             VARCHAR (5000)   NULL,
    [Cáncer de estomago]                                                                                   VARCHAR (5000)   NULL,
    [Cáncer de hígado y vías biliares]                                                                     VARCHAR (5000)   NULL,
    [Cáncer de mama]                                                                                       VARCHAR (5000)   NULL,
    [Cáncer de próstata]                                                                                   VARCHAR (5000)   NULL,
    [Cáncer de tiroides]                                                                                   VARCHAR (5000)   NULL,
    [Cáncer de tráquea, bronquios o pulmón]                                                                VARCHAR (5000)   NULL,
    [Otro tipo de cáncer ]                                                                                 VARCHAR (5000)   NULL,
    [Accidente cerebrovascular (ACV)]                                                                      VARCHAR (5000)   NULL,
    [Enfermedad coronaria]                                                                                 VARCHAR (5000)   NULL,
    [Diabetes mellitus]                                                                                    VARCHAR (5000)   NULL,
    [Hipertensión arterial (HTA)]                                                                          VARCHAR (5000)   NULL,
    [Hipertensión arterial y diabetes mellitus]                                                            VARCHAR (5000)   NULL,
    [Trastornos metabólicos]                                                                               VARCHAR (5000)   NULL,
    [Obesidad]                                                                                             VARCHAR (5000)   NULL,
    [EPOC]                                                                                                 VARCHAR (5000)   NULL,
    [Alergias]                                                                                             VARCHAR (5000)   NULL,
    [Patologías degenerativas]                                                                             VARCHAR (5000)   NULL,
    [Enfermedades genéticas]                                                                               VARCHAR (5000)   NULL,
    [Enfermedades mentales]                                                                                VARCHAR (5000)   NULL,
    [Epilepsia / Sínd. convulsivo]                                                                         VARCHAR (5000)   NULL,
    [Trastornos hematológicos]                                                                             VARCHAR (5000)   NULL,
    [Glaucoma]                                                                                             VARCHAR (5000)   NULL,
    [Anomalías congénitas]                                                                                 VARCHAR (5000)   NULL,
    [Osteoporosis]                                                                                         VARCHAR (5000)   NULL,
    [Tuberculosis (TB)]                                                                                    VARCHAR (5000)   NULL,
    [Lepra]                                                                                                VARCHAR (5000)   NULL,
    [Fumador]                                                                                              VARCHAR (5000)   NULL,
    [Alcoholismo]                                                                                          VARCHAR (5000)   NULL,
    [Farmacodependencia]                                                                                   VARCHAR (5000)   NULL,
    [Conductas suicidas]                                                                                   VARCHAR (5000)   NULL,
    [Maltrato y violencia intrafamiliar]                                                                   VARCHAR (5000)   NULL,
    [Registre otras enfermedades en familiares]                                                            VARCHAR (5000)   NULL,
    [Otros antecedentes familiares]                                                                        VARCHAR (5000)   NULL,
    [Otros antecedentes urológicos]                                                                        VARCHAR (5000)   NULL,
    [Accidentes toxicológicos]                                                                             VARCHAR (5000)   NULL,
    [Describa la sustancia o el agente tóxico y el plan de manejo recibido]                                VARCHAR (5000)   NULL,
    [Otros antecedentes tóxicos]                                                                           VARCHAR (5000)   NULL,
    [¿Por cuántos minutos realiza la actividad física vigorosa?  ]                                         VARCHAR (5000)   NULL,
    [¿Cuántas horas del tiempo libre al día, se sienta al frente de una pantalla (TV, computador, juego e] VARCHAR (5000)   NULL,
    [¿Que actividad recreativa realiza?]                                                                   VARCHAR (5000)   NULL,
    [Frecuencia del baño corporal]                                                                         VARCHAR (5000)   NULL,
    [Frecuencia del aseo de las uñas de manos y pies]                                                      VARCHAR (5000)   NULL,
    [¿En promedio cuantas horas duerme]                                                                    VARCHAR (5000)   NULL,
    [¿Tiene horarios regulares para acostarse?]                                                            VARCHAR (5000)   NULL,
    [¿Tiene horarios regulares para levantarse?]                                                           VARCHAR (5000)   NULL,
    [Otros antecedentes hábitos]                                                                           VARCHAR (5000)   NULL,
    [Edad de inicio escolar]                                                                               VARCHAR (5000)   NULL,
    [Tipo de escuela y/o colegio]                                                                          VARCHAR (5000)   NULL,
    [¿A cuántas escuelas y/o colegios ha asistido?]                                                        VARCHAR (5000)   NULL,
    [Rendimiento escolar]                                                                                  VARCHAR (5000)   NULL,
    [Disciplina escolar]                                                                                   VARCHAR (5000)   NULL,
    [¿Como es la relación con los compañeros de clase?]                                                    VARCHAR (5000)   NULL,
    [¿Como es la relación con los profesores?]                                                             VARCHAR (5000)   NULL,
    [Otros antecedentes escolares]                                                                         VARCHAR (5000)   NULL,
    [Recibió lactancia materna]                                                                            VARCHAR (5000)   NULL,
    [¿Por cuánto tiempo (meses) fue exclusiva?]                                                            VARCHAR (5000)   NULL,
    [Recibió leche de formula]                                                                             VARCHAR (5000)   NULL,
    [Edad de inicio de la leche de formula]                                                                VARCHAR (5000)   NULL,
    [Edad de inicio de la alimentación complementaria]                                                     VARCHAR (5000)   NULL,
    [¿Cuántas veces al día consume huevo?]                                                                 VARCHAR (5000)   NULL,
    [¿Cuántas veces al día consume leche y sus derivados?]                                                 VARCHAR (5000)   NULL,
    [¿Cuántas veces al día consume proteína animal (pollo, pescado, res, cerdo)?]                          VARCHAR (5000)   NULL,
    [¿Cuántas veces al día consume frutas?]                                                                VARCHAR (5000)   NULL,
    [¿Cuántas veces al día consume verduras?]                                                              VARCHAR (5000)   NULL,
    [¿Cuántas veces al día consume leguminosas?]                                                           VARCHAR (5000)   NULL,
    [¿Cuántas veces al día consume harinas o cereales?]                                                    VARCHAR (5000)   NULL,
    [¿Cuántas veces al día consume paquetes de fritos?]                                                    VARCHAR (5000)   NULL,
    [¿Cuántas veces al día consume dulces o azucares refinados?]                                           VARCHAR (5000)   NULL,
    [¿Cuántas veces al día consume fritos?]                                                                VARCHAR (5000)   NULL,
    [¿Es regular con los horarios de alimentación?]                                                        VARCHAR (5000)   NULL,
    [Otros antecedentes nutricionales]                                                                     VARCHAR (5000)   NULL,
    [¿Utiliza el cepillo dental?]                                                                          VARCHAR (5000)   NULL,
    [¿Utiliza la seda dental?]                                                                             VARCHAR (5000)   NULL,
    [No. de veces que realiza la higiene oral]                                                             VARCHAR (5000)   NULL,
    [Hábitos orales nocivos]                                                                               VARCHAR (5000)   NULL,
    [Enfermedades odontológicas]                                                                           VARCHAR (5000)   NULL,
    [Mal posición dentaria]                                                                                VARCHAR (5000)   NULL,
    [Morfología dentaria retentiva]                                                                        VARCHAR (5000)   NULL,
    [Xerostomía]                                                                                           VARCHAR (5000)   NULL,
    [Sinusitis]                                                                                            VARCHAR (5000)   NULL,
    [Irradiaciones]                                                                                        VARCHAR (5000)   NULL,
    [Fiebre reumática]                                                                                     VARCHAR (5000)   NULL,
    [Discapacidad física o mental]                                                                         VARCHAR (5000)   NULL,
    [Acceso a servicio odontológico en el último año]                                                      VARCHAR (5000)   NULL,
    [Urgencias]                                                                                            VARCHAR (5000)   NULL,
    [Revisión ]                                                                                            VARCHAR (5000)   NULL,
    [Uso diario de crema fluorada]                                                                         VARCHAR (5000)   NULL,
    [Otros antecedentes odontológicos]                                                                     VARCHAR (5000)   NULL,
    [Promedio de ingresos mensuales de la familia en los últimos 4 meses]                                  VARCHAR (5000)   NULL,
    [¿Cuantas personas de la familia viven con el ingreso mensual?]                                        VARCHAR (5000)   NULL,
    [¿La familia se encuentran en situación de desplazamiento forzado?]                                    VARCHAR (5000)   NULL,
    [¿Presenta dependencia económica?]                                                                     VARCHAR (5000)   NULL,
    [¿Tiene responsabilidad económica?]                                                                    VARCHAR (5000)   NULL,
    [Otros antecedentes socioeconómicos]                                                                   VARCHAR (5000)   NULL,
    [IDHCHISPACA_ANT]                                                                                      INT              NULL,
    [Descripción cabeza]                                                                                   VARCHAR (5000)   NULL,
    [Ojo derecho]                                                                                          VARCHAR (5000)   NULL,
    [Agudeza visual OD]                                                                                    VARCHAR (5000)   NULL,
    [Tamaño de la pupila OD]                                                                               VARCHAR (5000)   NULL,
    [Respuesta a la luz OD]                                                                                VARCHAR (5000)   NULL,
    [Ojo izquierdo]                                                                                        VARCHAR (5000)   NULL,
    [Agudeza visual OI]                                                                                    VARCHAR (5000)   NULL,
    [Tamaño de la pupila OI]                                                                               VARCHAR (5000)   NULL,
    [Respuesta a la luz OI]                                                                                VARCHAR (5000)   NULL,
    [Agudeza visual ambos ojos]                                                                            VARCHAR (5000)   NULL,
    [Relación entre las pupilas]                                                                           VARCHAR (5000)   NULL,
    [Reflejo corneal]                                                                                      VARCHAR (5000)   NULL,
    [Fondo de ojo]                                                                                         VARCHAR (5000)   NULL,
    [Descripción ojos]                                                                                     VARCHAR (5000)   NULL,
    [Otoscopia]                                                                                            VARCHAR (5000)   NULL,
    [Descripción ORL]                                                                                      VARCHAR (5000)   NULL,
    [Descripción cuello]                                                                                   VARCHAR (5000)   NULL,
    [Mamas]                                                                                                VARCHAR (5000)   NULL,
    [Descripción mamas]                                                                                    VARCHAR (5000)   NULL,
    [Cardiovascular]                                                                                       VARCHAR (5000)   NULL,
    [Descripción cardiovascular]                                                                           VARCHAR (5000)   NULL,
    [Pulmones]                                                                                             VARCHAR (5000)   NULL,
    [Descripción pulmones]                                                                                 VARCHAR (5000)   NULL,
    [Descripción tórax]                                                                                    VARCHAR (5000)   NULL,
    [Ruidos intestinales]                                                                                  VARCHAR (5000)   NULL,
    [Hepatomegalia]                                                                                        VARCHAR (5000)   NULL,
    [Esplenomegalia]                                                                                       VARCHAR (5000)   NULL,
    [Masa abdominal]                                                                                       VARCHAR (5000)   NULL,
    [Soplo abdominal]                                                                                      VARCHAR (5000)   NULL,
    [Descripción abdomen]                                                                                  VARCHAR (5000)   NULL,
    [Testículos]                                                                                           VARCHAR (5000)   NULL,
    [Pene]                                                                                                 VARCHAR (5000)   NULL,
    [Descripción genito urinario]                                                                          VARCHAR (5000)   NULL,
    [Descripción extremidades]                                                                             VARCHAR (5000)   NULL,
    [Fuerza muscular / 5]                                                                                  VARCHAR (5000)   NULL,
    [ROT / ++]                                                                                             VARCHAR (5000)   NULL,
    [Descripción neurológica]                                                                              VARCHAR (5000)   NULL,
    [Descripción piel]                                                                                     VARCHAR (5000)   NULL,
    [IDHCHISPACA_EXA]                                                                                      INT              NULL
);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Tabla histórica que almacena registros de historias clínicas del programa de Primera Infancia, consolidando datos demográficos del paciente (nombre, identificación, fecha de nacimiento, sexo, régimen, etnia), información del centro de atención, signos vitales y antropométricos (peso, talla, IMC, tensión arterial), diagnóstico CIE-10 y una extensa revisión por sistemas con síntomas detallados por aparato (general, visual, auditivo, respiratorio, cardiovascular, entre otros).', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'ESE_HC_HISTORICO_PRIMERAINFANCIA';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DescriptionSource', @value=N'ai_claude-sonnet-4-6_2026-05-05', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'ESE_HC_HISTORICO_PRIMERAINFANCIA';
GO
