CREATE TABLE [dbo].[ESE_HC_HISTORICO_ODONTOLOGIA] (
    [Ingreso]                                                                                CHAR (10)      NOT NULL,
    [Tipo de ID del paciente]                                                                VARCHAR (39)   NULL,
    [Numero de id del paciente]                                                              CHAR (15)      NOT NULL,
    [Apellido 1]                                                                             CHAR (20)      NOT NULL,
    [Apellido 2]                                                                             CHAR (20)      NOT NULL,
    [Nombre 1]                                                                               CHAR (20)      NOT NULL,
    [Nombre 2]                                                                               CHAR (20)      NOT NULL,
    [Fecha de nacieminto]                                                                    DATETIME       NOT NULL,
    [Edad en años]                                                                           INT            NULL,
    [Sexo]                                                                                   VARCHAR (9)    NULL,
    [Código Grupo de atención]                                                               VARCHAR (20)   NOT NULL,
    [Nombre Grupo de atención]                                                               VARCHAR (100)  NOT NULL,
    [Código Entidad]                                                                         CHAR (9)       NOT NULL,
    [Nombre entidad]                                                                         CHAR (150)     NOT NULL,
    [Tipo de entidad]                                                                        VARCHAR (27)   NULL,
    [Código del profesional]                                                                 CHAR (20)      NOT NULL,
    [Nombre del profesional]                                                                 CHAR (60)      NOT NULL,
    [Total dientes cariados]                                                                 TINYINT        NULL,
    [Total dientes perdidos-Extraidos]                                                       TINYINT        NULL,
    [Total dientes Obturados]                                                                TINYINT        NULL,
    [Suma de CEO]                                                                            TINYINT        NULL,
    [Suma de CPO]                                                                            TINYINT        NULL,
    [Fecha del folio]                                                                        DATETIME       NOT NULL,
    [Codigo Diagnostico]                                                                     CHAR (4)       NOT NULL,
    [Diagnostico principal]                                                                  CHAR (150)     NULL,
    [Estado Embarazo]                                                                        VARCHAR (18)   NULL,
    [Victima de maltrato]                                                                    VARCHAR (31)   NULL,
    [Victima Violencia sexual]                                                               VARCHAR (18)   NULL,
    [IDMODELOHC]                                                                             INT            NULL,
    [ID]                                                                                     INT            NOT NULL,
    [Adinamia]                                                                               VARCHAR (5000) NULL,
    [Anorexia]                                                                               VARCHAR (5000) NULL,
    [Astenia]                                                                                VARCHAR (5000) NULL,
    [Escalofríos]                                                                            VARCHAR (5000) NULL,
    [Fiebre]                                                                                 VARCHAR (5000) NULL,
    [Pérdida de peso]                                                                        VARCHAR (5000) NULL,
    [Sintomático respiratorio (tos y expectoración por 15 días o más)]                       VARCHAR (5000) NULL,
    [Sintomático piel (lesión no congénita de larga duración, sin respuesta a tratamientos)] VARCHAR (5000) NULL,
    [Aumento de peso]                                                                        VARCHAR (5000) NULL,
    [Otros síntomas ]                                                                        VARCHAR (5000) NULL,
    [Afonía]                                                                                 VARCHAR (5000) NULL,
    [Alteración del gusto]                                                                   VARCHAR (5000) NULL,
    [Disfagia]                                                                               VARCHAR (5000) NULL,
    [Disfonía]                                                                               VARCHAR (5000) NULL,
    [Gingivitis]                                                                             VARCHAR (5000) NULL,
    [Gingivorragia]                                                                          VARCHAR (5000) NULL,
    [Halitosis]                                                                              VARCHAR (5000) NULL,
    [Odontalgia]                                                                             VARCHAR (5000) NULL,
    [Úlceras en boca]                                                                        VARCHAR (5000) NULL,
    [Onicofagia]                                                                             VARCHAR (5000) NULL,
    [Respiración bucal]                                                                      VARCHAR (5000) NULL,
    [Otros cavidad oral]                                                                     VARCHAR (5000) NULL,
    [Adenopatías]                                                                            VARCHAR (5000) NULL,
    [Dolor en cuello]                                                                        VARCHAR (5000) NULL,
    [Espasmo en cuello]                                                                      VARCHAR (5000) NULL,
    [Masa]                                                                                   VARCHAR (5000) NULL,
    [Otros cuello]                                                                           VARCHAR (5000) NULL,
    [Otros sistemas]                                                                         VARCHAR (5000) NULL,
    [Tipo de Atencion]                                                                       VARCHAR (5000) NULL,
    [Tratamamiento Terminado]                                                                VARCHAR (5000) NULL,
    [IDHCHISPACA_RES]                                                                        INT            NULL,
    [Enfermedad cardíaca]                                                                    VARCHAR (5000) NULL,
    [Registre el tipo de enfermedad cardíaca]                                                VARCHAR (5000) NULL,
    [Fecha diagnóstico enfermedad cardíaca]                                                  VARCHAR (5000) NULL,
    [Hipertensión arterial]                                                                  VARCHAR (5000) NULL,
    [Fecha diagnóstico HTA]                                                                  VARCHAR (5000) NULL,
    [Asma bronquial]                                                                         VARCHAR (5000) NULL,
    [Fecha diagnóstico asma]                                                                 VARCHAR (5000) NULL,
    [Hepatitis B]                                                                            VARCHAR (5000) NULL,
    [Fecha diagnóstico Hepatitis B]                                                          VARCHAR (5000) NULL,
    [Hepatitis C]                                                                            VARCHAR (5000) NULL,
    [Fecha diagnóstico Hepatitis C]                                                          VARCHAR (5000) NULL,
    [VIH]                                                                                    VARCHAR (5000) NULL,
    [Fecha diagnóstico VIH]                                                                  VARCHAR (5000) NULL,
    [Tuberculosis]                                                                           VARCHAR (5000) NULL,
    [Fecha diagnóstico TB]                                                                   VARCHAR (5000) NULL,
    [Hemoglobinopatías o trastornos hematológicos]                                           VARCHAR (5000) NULL,
    [Fecha diagnóstico hemoglobinopatía]                                                     VARCHAR (5000) NULL,
    [Diabetes Mellitus tipo I]                                                               VARCHAR (5000) NULL,
    [Fecha diagnóstico DM I]                                                                 VARCHAR (5000) NULL,
    [Diabetes Mellitus Tipo II]                                                              VARCHAR (5000) NULL,
    [Fecha diagnóstico DM II]                                                                VARCHAR (5000) NULL,
    [Enfermedad renal crónica]                                                               VARCHAR (5000) NULL,
    [Fecha diagnóstico ERC]                                                                  VARCHAR (5000) NULL,
    [Enfermedad pulmonar obstructiva crónica]                                                VARCHAR (5000) NULL,
    [Fecha diagnóstico EPOC]                                                                 VARCHAR (5000) NULL,
    [Epilepsia / Síndrome convulsivo]                                                        VARCHAR (5000) NULL,
    [Fecha diagnóstico síndrome convulsivo]                                                  VARCHAR (5000) NULL,
    [Accidente cerebrovascular]                                                              VARCHAR (5000) NULL,
    [Fecha diagnóstico ACV]                                                                  VARCHAR (5000) NULL,
    [Anomalías musculo esqueléticas]                                                         VARCHAR (5000) NULL,
    [Registre el tipo anomalía musculo esquelética]                                          VARCHAR (5000) NULL,
    [Fecha diagnóstico anomalía musculo esquelética]                                         VARCHAR (5000) NULL,
    [Anomalías neurológicas (déficit)]                                                       VARCHAR (5000) NULL,
    [Registre el tipo anomalía neurológica]                                                  VARCHAR (5000) NULL,
    [Fecha diagnóstico anomalía neurológica]                                                 VARCHAR (5000) NULL,
    [Cáncer en la mujer]                                                                     VARCHAR (5000) NULL,
    [Cual otro cáncer en la mujer?]                                                          VARCHAR (5000) NULL,
    [Registre el tratamiento recibido en la mujer]                                           VARCHAR (5000) NULL,
    [Fecha diagnóstico cáncer en la mujer]                                                   VARCHAR (5000) NULL,
    [Cáncer en el hombre]                                                                    VARCHAR (5000) NULL,
    [Cual  otro cáncer en el hombre?]                                                        VARCHAR (5000) NULL,
    [Registre el tratamiento recibido]                                                       VARCHAR (5000) NULL,
    [Fecha diagnóstico del cáncer]                                                           VARCHAR (5000) NULL,
    [Rinitis]                                                                                VARCHAR (5000) NULL,
    [Síndrome geriátrico]                                                                    VARCHAR (5000) NULL,
    [Deterioro cognoscitivo]                                                                 VARCHAR (5000) NULL,
    [Inmovilidad]                                                                            VARCHAR (5000) NULL,
    [Inestabilidad y caídas]                                                                 VARCHAR (5000) NULL,
    [Fragilidad]                                                                             VARCHAR (5000) NULL,
    [Incontinencia]                                                                          VARCHAR (5000) NULL,
    [Depresión menor o mayor]                                                                VARCHAR (5000) NULL,
    [Iatrogenia medicamentosa]                                                               VARCHAR (5000) NULL,
    [Hospitalizaciones]                                                                      VARCHAR (5000) NULL,
    [Registre el motivo de la(s) hospitalización (es)]                                       VARCHAR (5000) NULL,
    [Fecha de la última hospitalización]                                                     VARCHAR (5000) NULL,
    [Otros antecedentes médicos]                                                             VARCHAR (5000) NULL,
    [Anestesia general]                                                                      VARCHAR (5000) NULL,
    [Fecha última anestesia general]                                                         VARCHAR (5000) NULL,
    [Anestesia regional]                                                                     VARCHAR (5000) NULL,
    [Fecha última anestesia regional]                                                        VARCHAR (5000) NULL,
    [Anestesia general y regional]                                                           VARCHAR (5000) NULL,
    [Fecha última anestesia general y regional]                                              VARCHAR (5000) NULL,
    [Anestesia local]                                                                        VARCHAR (5000) NULL,
    [Fecha última anestesia local]                                                           VARCHAR (5000) NULL,
    [Otros / Observaciones]                                                                  VARCHAR (5000) NULL,
    [Esquizofrenia]                                                                          VARCHAR (5000) NULL,
    [Fecha diagnóstico de la esquizofrenia]                                                  VARCHAR (5000) NULL,
    [Trastorno Bipolar]                                                                      VARCHAR (5000) NULL,
    [Fecha diagnóstico del trastorno bipolar]                                                VARCHAR (5000) NULL,
    [Depresión]                                                                              VARCHAR (5000) NULL,
    [Problemas afectivos]                                                                    VARCHAR (5000) NULL,
    [ansiedad]                                                                               VARCHAR (5000) NULL,
    [Fobias]                                                                                 VARCHAR (5000) NULL,
    [Registre el tipo de fobia]                                                              VARCHAR (5000) NULL,
    [Trastorno de la conducta alimentaria]                                                   VARCHAR (5000) NULL,
    [Conducta suicida]                                                                       VARCHAR (5000) NULL,
    [Tratamiento recibido ante la conducta suicida]                                          VARCHAR (5000) NULL,
    [Exposición a violencia]                                                                 VARCHAR (5000) NULL,
    [Maltrato fìsico, psicologico o ambos]                                                   VARCHAR (5000) NULL,
    [Matoneo]                                                                                VARCHAR (5000) NULL,
    [Abuso sexual]                                                                           VARCHAR (5000) NULL,
    [Violencia sexual]                                                                       VARCHAR (5000) NULL,
    [Abandono]                                                                               VARCHAR (5000) NULL,
    [Negligencia]                                                                            VARCHAR (5000) NULL,
    [Violencia intrafamiliar]                                                                VARCHAR (5000) NULL,
    [Victimas del conflicto armado]                                                          VARCHAR (5000) NULL,
    [Otros antecedentes psicológicos]                                                        VARCHAR (5000) NULL,
    [Leucemia]                                                                               VARCHAR (5000) NULL,
    [Linfoma]                                                                                VARCHAR (5000) NULL,
    [Cáncer de colon y recto]                                                                VARCHAR (5000) NULL,
    [Cáncer de cuello uterino]                                                               VARCHAR (5000) NULL,
    [Cáncer de estomago]                                                                     VARCHAR (5000) NULL,
    [Cáncer de hígado y vías biliares]                                                       VARCHAR (5000) NULL,
    [Cáncer de mama]                                                                         VARCHAR (5000) NULL,
    [Cáncer de próstata]                                                                     VARCHAR (5000) NULL,
    [Cáncer de tiroides]                                                                     VARCHAR (5000) NULL,
    [Cáncer de tráquea, bronquios o pulmón]                                                  VARCHAR (5000) NULL,
    [Otro tipo de cáncer ]                                                                   VARCHAR (5000) NULL,
    [Accidente cerebrovascular (ACV)]                                                        VARCHAR (5000) NULL,
    [Enfermedad coronaria]                                                                   VARCHAR (5000) NULL,
    [Diabetes mellitus]                                                                      VARCHAR (5000) NULL,
    [Hipertensión arterial (HTA)]                                                            VARCHAR (5000) NULL,
    [Hipertensión arterial y diabetes mellitus]                                              VARCHAR (5000) NULL,
    [Trastornos metabólicos]                                                                 VARCHAR (5000) NULL,
    [Obesidad]                                                                               VARCHAR (5000) NULL,
    [EPOC]                                                                                   VARCHAR (5000) NULL,
    [Alergias]                                                                               VARCHAR (5000) NULL,
    [Patologías degenerativas]                                                               VARCHAR (5000) NULL,
    [Enfermedades genéticas]                                                                 VARCHAR (5000) NULL,
    [Enfermedades mentales]                                                                  VARCHAR (5000) NULL,
    [Epilepsia / Sínd. convulsivo]                                                           VARCHAR (5000) NULL,
    [Trastornos hematológicos]                                                               VARCHAR (5000) NULL,
    [Glaucoma]                                                                               VARCHAR (5000) NULL,
    [Anomalías congénitas]                                                                   VARCHAR (5000) NULL,
    [Osteoporosis]                                                                           VARCHAR (5000) NULL,
    [Tuberculosis (TB)]                                                                      VARCHAR (5000) NULL,
    [Lepra]                                                                                  VARCHAR (5000) NULL,
    [Fumador]                                                                                VARCHAR (5000) NULL,
    [Alcoholismo]                                                                            VARCHAR (5000) NULL,
    [Farmacodependencia]                                                                     VARCHAR (5000) NULL,
    [Conductas suicidas]                                                                     VARCHAR (5000) NULL,
    [Maltrato y violencia intrafamiliar]                                                     VARCHAR (5000) NULL,
    [Registre otras enfermedades en familiares]                                              VARCHAR (5000) NULL,
    [Otros antecedentes familiares]                                                          VARCHAR (5000) NULL,
    [Fumador o exfumador (cigarrillo, puro, tabaco)]                                         VARCHAR (5000) NULL,
    [Edad de inicio de fumar]                                                                VARCHAR (5000) NULL,
    [No. fumado en el día]                                                                   VARCHAR (5000) NULL,
    [Años en los que fumo]                                                                   VARCHAR (5000) NULL,
    [índice paquetes/año]                                                                    VARCHAR (5000) NULL,
    [Exposición a humo de leña y/o carbon]                                                   VARCHAR (5000) NULL,
    [Consume alcohol]                                                                        VARCHAR (5000) NULL,
    [Edad de inicio del consumo de alcohol]                                                  VARCHAR (5000) NULL,
    [Frecuencia del consumo de alcohol]                                                      VARCHAR (5000) NULL,
    [Consume sustancia psicoactivas]                                                         VARCHAR (5000) NULL,
    [Edad de inicio del consumo de sustancias psicoactivas]                                  VARCHAR (5000) NULL,
    [Frecuencia del consumo de sustancias psicoactivas]                                      VARCHAR (5000) NULL,
    [¿Cuál sustancia psicoactiva consume?]                                                   VARCHAR (5000) NULL,
    [Accidentes toxicológicos]                                                               VARCHAR (5000) NULL,
    [Describa la sustancia o el agente tóxico y el plan de manejo recibido]                  VARCHAR (5000) NULL,
    [Otros antecedentes tóxicos]                                                             VARCHAR (5000) NULL,
    [Recibió lactancia materna]                                                              VARCHAR (5000) NULL,
    [¿Por cuánto tiempo (meses) fue exclusiva?]                                              VARCHAR (5000) NULL,
    [Recibió leche de formula]                                                               VARCHAR (5000) NULL,
    [Edad de inicio de la leche de formula]                                                  VARCHAR (5000) NULL,
    [Edad de inicio de la alimentación complementaria]                                       VARCHAR (5000) NULL,
    [¿Cuántas veces al día consume huevo?]                                                   VARCHAR (5000) NULL,
    [¿Cuántas veces al día consume leche y sus derivados?]                                   VARCHAR (5000) NULL,
    [¿Cuántas veces al día consume proteína animal (pollo, pescado, res, cerdo)?]            VARCHAR (5000) NULL,
    [¿Cuántas veces al día consume frutas?]                                                  VARCHAR (5000) NULL,
    [¿Cuántas veces al día consume verduras?]                                                VARCHAR (5000) NULL,
    [¿Cuántas veces al día consume leguminosas?]                                             VARCHAR (5000) NULL,
    [¿Cuántas veces al día consume harinas o cereales?]                                      VARCHAR (5000) NULL,
    [¿Cuántas veces al día consume paquetes de fritos?]                                      VARCHAR (5000) NULL,
    [¿Cuántas veces al día consume dulces o azucares refinados?]                             VARCHAR (5000) NULL,
    [¿Cuántas veces al día consume fritos?]                                                  VARCHAR (5000) NULL,
    [¿Con que frecuencia consume ponqués, galletas, postres o helados?]                      VARCHAR (5000) NULL,
    [¿Con que frecuencia consume bebidas azucaradas?]                                        VARCHAR (5000) NULL,
    [¿Con que frecuencia consume fritos (grasas saturadas)?]                                 VARCHAR (5000) NULL,
    [¿Con que frecuencia consume comidas rápidas y/o embutidos?]                             VARCHAR (5000) NULL,
    [¿Con que frecuencia consume frutas, verduras y hortalizas?]                             VARCHAR (5000) NULL,
    [¿Con que frecuencia consume proteína animal (pollo, pescado, res, cerdo)?]              VARCHAR (5000) NULL,
    [Agrega sal a la comida ya servida]                                                      VARCHAR (5000) NULL,
    [¿Es regular con los horarios de alimentación?]                                          VARCHAR (5000) NULL,
    [Otros antecedentes nutricionales]                                                       VARCHAR (5000) NULL,
    [¿Utiliza el cepillo dental?]                                                            VARCHAR (5000) NULL,
    [¿Utiliza la seda dental?]                                                               VARCHAR (5000) NULL,
    [No. de veces que realiza la higiene oral]                                               VARCHAR (5000) NULL,
    [Hábitos orales nocivos]                                                                 VARCHAR (5000) NULL,
    [Uso de prótesis o aparatología oral]                                                    VARCHAR (5000) NULL,
    [Describa la condición del dispositivo]                                                  VARCHAR (5000) NULL,
    [Enfermedades odontológicas]                                                             VARCHAR (5000) NULL,
    [Mal posición dentaria]                                                                  VARCHAR (5000) NULL,
    [Morfología dentaria retentiva]                                                          VARCHAR (5000) NULL,
    [Xerostomía]                                                                             VARCHAR (5000) NULL,
    [Sinusitis]                                                                              VARCHAR (5000) NULL,
    [Irradiaciones]                                                                          VARCHAR (5000) NULL,
    [Fiebre reumática]                                                                       VARCHAR (5000) NULL,
    [Discapacidad física o mental]                                                           VARCHAR (5000) NULL,
    [Acceso a servicio odontológico en el último año]                                        VARCHAR (5000) NULL,
    [Urgencias]                                                                              VARCHAR (5000) NULL,
    [Revisión ]                                                                              VARCHAR (5000) NULL,
    [Uso diario de crema fluorada]                                                           VARCHAR (5000) NULL,
    [Otros antecedentes odontológicos]                                                       VARCHAR (5000) NULL,
    [IDHCHISPACA_ANT]                                                                        INT            NULL,
    [Descripción cabeza]                                                                     VARCHAR (5000) NULL,
    [Labio superior]                                                                         VARCHAR (5000) NULL,
    [Labio inferior]                                                                         VARCHAR (5000) NULL,
    [Comisura]                                                                               VARCHAR (5000) NULL,
    [Mucosa oral]                                                                            VARCHAR (5000) NULL,
    [Proceso alveolar]                                                                       VARCHAR (5000) NULL,
    [Mejillas]                                                                               VARCHAR (5000) NULL,
    [Paladar]                                                                                VARCHAR (5000) NULL,
    [Piso de boca]                                                                           VARCHAR (5000) NULL,
    [Lengua]                                                                                 VARCHAR (5000) NULL,
    [Glandulas]                                                                              VARCHAR (5000) NULL,
    [Maxilar superior]                                                                       VARCHAR (5000) NULL,
    [Maxilar inferior]                                                                       VARCHAR (5000) NULL,
    [Alteraciones de la articulación temporo maxilar]                                        VARCHAR (5000) NULL,
    [Dolor ATM]                                                                              VARCHAR (5000) NULL,
    [Facetas de desgaste]                                                                    VARCHAR (5000) NULL,
    [Ruidos articulares]                                                                     VARCHAR (5000) NULL,
    [Desviación mandibular]                                                                  VARCHAR (5000) NULL,
    [Deformaciones de contorno]                                                              VARCHAR (5000) NULL,
    [Limitación apertura]                                                                    VARCHAR (5000) NULL,
    [Mala oclusión]                                                                          VARCHAR (5000) NULL,
    [Alteraciones periodontales]                                                             VARCHAR (5000) NULL,
    [Sangrado]                                                                               VARCHAR (5000) NULL,
    [Retracciones]                                                                           VARCHAR (5000) NULL,
    [Movilidad]                                                                              VARCHAR (5000) NULL,
    [Bolsa]                                                                                  VARCHAR (5000) NULL,
    [Placa blanda]                                                                           VARCHAR (5000) NULL,
    [Calculos]                                                                               VARCHAR (5000) NULL,
    [Alteraciones pulpares y periapicales]                                                   VARCHAR (5000) NULL,
    [Pulpitis reversible]                                                                    VARCHAR (5000) NULL,
    [Pulpitis irreversible]                                                                  VARCHAR (5000) NULL,
    [Periodontitis apical aguda]                                                             VARCHAR (5000) NULL,
    [Periodontitis apical crónica]                                                           VARCHAR (5000) NULL,
    [Necrosis pulpar]                                                                        VARCHAR (5000) NULL,
    [Fluorosis]                                                                              VARCHAR (5000) NULL,
    [Descripción ORL]                                                                        VARCHAR (5000) NULL,
    [Descripción cuello]                                                                     VARCHAR (5000) NULL,
    [IDHCHISPACA_EXA]                                                                        INT            NULL
);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Tabla histórica que almacena registros de historia clínica odontológica por paciente y atención. Consolida datos demográficos del paciente, información del profesional tratante, índices epidemiológicos dentales (CEO/CPO, caries, dientes perdidos y obturados), diagnóstico principal con código, síntomas bucales y sistémicos, y antecedentes patológicos relevantes (enfermedades crónicas, infecciosas y oncológicas) registrados en cada folio de consulta odontológica.', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'ESE_HC_HISTORICO_ODONTOLOGIA';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DescriptionSource', @value=N'ai_claude-sonnet-4-6_2026-05-05', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'ESE_HC_HISTORICO_ODONTOLOGIA';
GO
