
CREATE TABLE [dbo].[HCHISPACA_HISTORICA](
	[IDETIPHIS] [char](9) NOT NULL,
	[NUMEFOLIO] [nchar](10) NOT NULL,
	[CONSFOLIO] [char](10) NULL,
	[IPCODPACI] [varchar](25) NOT NULL,
	[NUMINGRES] [char](10) NOT NULL,
	[CODCENATE] [char](10) NOT NULL,
	[UFUCODIGO] [char](10) NOT NULL,
	[CODPROSAL] [char](20) NOT NULL,
	[FECHISPAC] [datetime] NOT NULL,
	[TIPHISPAC] [char](2) NOT NULL,
	[INDICAPAC] [char](2) NOT NULL,
	[INDICAMED] [varchar](max) NULL,
	[TRAINTUNI] [bit] NOT NULL,
	[MOTTRAINT] [varchar](2000) NULL,
	[ESTHISPAC] [char](1) NOT NULL,
	[CODDIAGNO] [char](4) NULL,
	[DATSUBJET] [varchar](max) NULL,
	[DATOBJETI] [varchar](max) NULL,
	[DATPRONOS] [varchar](max) NULL,
	[DATTRATAM] [varchar](max) NULL,
	[INDAUDFOR] [numeric](18, 0) NOT NULL,
	[CODUSUARI] [char](20) NULL,
	[FECVISREG] [datetime] NULL,
	[MOSEPICRI] [bit] NULL,
	[ESTAFOLIO] [bit] NULL,
	[CODESPTRA] [char](3) NULL,
	[GENCONEXT] [bit] NULL,
	[PLAINDMED] [varchar](max) NULL,
	[HCIRENAL] [int] NULL,
	[HCIRENALPERI] [int] NULL,
	[ID] [int] NOT NULL,
	[IDMODELOHC] [int] NULL,
	[GENSERVICEORDER] [int] NULL,
	[CONCILIACIONMED] [bit] NULL,
	[JUNTAMEDICA] [bit] NULL,
	[RECORDANESTESIA] [bit] NULL,
	[REAPERTURAHC] [bit] NULL,
	[HCTELEFONICA] [bit] NULL,
	[MEDSOLHCTELEF] [char](20) NULL,
	[ESPMEDSOLHCTELEF] [char](3) NULL,
	[CAUSAEXTERNA] [int] NULL,
	[FINALIDAD] [int] NULL,
	[HCOTROSPROC] [int] NULL,
	[AssistedConsultationProfessional] [char](20) NULL,
	[Reformulation] [bit] NULL,
	[PendingValidationHCTelephone] [bit] NULL,
	[DateValidationHCTelephone] [datetime] NULL,
	[INDICATION] [int] NULL,
	[StoryType] [int] NULL,
	[ReportCreatedID] [varchar](255) NULL,
	[OmitsElectronicSignature] [int] NULL,
	[ReasonOmitsElectronicSignature] [char](4) NULL,
	[ObservationsOmitsElectronicSignature] [varchar](200) NULL,
	[IdClinicalHistoryFormats] [int] NULL,
	[ReportVersionType] [int] NULL,
	[Container] [varchar](4) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


