

CREATE TABLE [dbo].[HCNOSERFA_HISTORICA](
	[AUTO] [int] IDENTITY(1,1) NOT NULL,
	[NUMEFOLIO] [nchar](10) NOT NULL,
	[IDETIPHIS] [char](9) NOT NULL,
	[IPCODPACI] [varchar](25) MASKED WITH (FUNCTION = 'partial(0, "Identification_Ofuscado", 0)') NOT NULL,
	[NUMINGRES] [char](10) NOT NULL,
	[CODCENATE] [char](10) NOT NULL,
	[UFUCODIGO] [char](10) NOT NULL,
	[CODPROSAL] [char](20) MASKED WITH (FUNCTION = 'partial(0, "Identification_Ofuscado", 0)') NOT NULL,
	[FECHISPAC] [datetime] NOT NULL,
	[OBSERVACI] [varchar](max) NULL,
	[CONSFOLIO] [char](10) NULL,
	[Container] [varchar](4) NULL,
 CONSTRAINT [PK_HCNOSERFA_HISTORICA] PRIMARY KEY CLUSTERED 
(
	[AUTO] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


