CREATE TABLE [dbo].[HCONCOPREG_DATOS_2022] (
    [Id]                       INT           IDENTITY (1, 1) NOT NULL,
    [CODDIAGNO]                CHAR (4)      NOT NULL,
    [IDEntidadVIE]             INT           NULL,
    [1]                        VARCHAR (20)  NULL,
    [2]                        VARCHAR (30)  NULL,
    [3]                        VARCHAR (20)  NULL,
    [4]                        VARCHAR (30)  NULL,
    [5]                        VARCHAR (2)   NULL,
    [6]                        CHAR (15)     NOT NULL,
    [7]                        DATE          NULL,
    [8]                        VARCHAR (1)   NULL,
    [9]                        VARCHAR (4)   NULL,
    [10]                       VARCHAR (1)   NULL,
    [11]                       VARCHAR (9)   NULL,
    [12]                       INT           NULL,
    [13]                       INT           NULL,
    [14]                       VARCHAR (5)   NULL,
    [15]                       VARCHAR (MAX) NULL,
    [16]                       DATE          NULL,
    [17]                       VARCHAR (4)   NULL,
    [18]                       DATE          NULL,
    [19]                       DATE          NULL,
    [20]                       DATE          NULL,
    [21]                       INT           NULL,
    [22]                       INT           NULL,
    [23]                       DATE          NULL,
    [24]                       DATE          NULL,
    [25]                       VARCHAR (12)  NULL,
    [26]                       DATE          NULL,
    [27]                       INT           NULL,
    [28]                       INT           NULL,
    [29]                       INT           NULL,
    [30]                       DATE          NULL,
    [31]                       INT           NULL,
    [32]                       DATE          NULL,
    [33]                       INT           NULL,
    [34]                       INT           NULL,
    [35]                       DATE          NULL,
    [36]                       INT           NULL,
    [37]                       INT           NULL,
    [38]                       INT           NULL,
    [39]                       DATE          NULL,
    [40]                       INT           NULL,
    [41]                       INT           NULL,
    [42]                       INT           NULL,
    [43]                       DATE          NULL,
    [44]                       VARCHAR (4)   NULL,
    [45]                       INT           NULL,
    [46]                       INT           NULL,
    [46.1]                     VARCHAR (2)   NULL,
    [46.2]                     VARCHAR (2)   NULL,
    [46.3]                     VARCHAR (2)   NULL,
    [46.4]                     VARCHAR (2)   NULL,
    [46.5]                     VARCHAR (2)   NULL,
    [46.6]                     VARCHAR (2)   NULL,
    [46.7]                     VARCHAR (2)   NULL,
    [46.8]                     VARCHAR (2)   NULL,
    [47]                       INT           NULL,
    [48]                       INT           NULL,
    [49]                       DATE          NULL,
    [50]                       INT           NULL,
    [51]                       VARCHAR (12)  NULL,
    [52]                       VARCHAR (12)  NULL,
    [53]                       INT           NULL,
    [53.1]                     VARCHAR (20)  NULL,
    [53.2]                     VARCHAR (20)  NULL,
    [53.3]                     VARCHAR (20)  NULL,
    [53.4]                     VARCHAR (20)  NULL,
    [53.5]                     VARCHAR (20)  NULL,
    [53.6]                     VARCHAR (20)  NULL,
    [53.7]                     VARCHAR (20)  NULL,
    [53.8]                     VARCHAR (20)  NULL,
    [53.9]                     VARCHAR (20)  NULL,
    [IDHCORDQUIMIO49]          INT           NULL,
    [IDHCRADORDEN88]           INT           NULL,
    [54]                       VARCHAR (20)  NULL,
    [55]                       VARCHAR (20)  NULL,
    [56]                       VARCHAR (20)  NULL,
    [57]                       INT           NULL,
    [58]                       DATE          NULL,
    [59]                       INT           NULL,
    [60]                       INT           NULL,
    [61]                       INT           NULL,
    [62]                       DATE          NULL,
    [63]                       INT           NULL,
    [64]                       VARCHAR (12)  NULL,
    [65]                       VARCHAR (12)  NULL,
    [66]                       INT           NULL,
    [66.1]                     VARCHAR (20)  NULL,
    [66.2]                     VARCHAR (20)  NULL,
    [66.3]                     VARCHAR (20)  NULL,
    [66.4]                     VARCHAR (20)  NULL,
    [66.5]                     VARCHAR (20)  NULL,
    [66.6]                     VARCHAR (20)  NULL,
    [66.7]                     VARCHAR (20)  NULL,
    [66.8]                     VARCHAR (20)  NULL,
    [66.9]                     VARCHAR (20)  NULL,
    [IDHCORDQUIMIO62]          INT           NULL,
    [IDHCRADORDEN97]           INT           NULL,
    [67]                       VARCHAR (20)  NULL,
    [68]                       VARCHAR (20)  NULL,
    [69]                       VARCHAR (20)  NULL,
    [70]                       INT           NULL,
    [71]                       DATE          NULL,
    [72]                       INT           NULL,
    [73]                       INT           NULL,
    [74]                       INT           NULL,
    [75]                       INT           NULL,
    [76]                       DATE          NULL,
    [77]                       VARCHAR (100) NULL,
    [78]                       VARCHAR (20)  NULL,
    [79]                       INT           NULL,
    [80]                       DATE          NULL,
    [81]                       INT           NULL,
    [82]                       VARCHAR (100) NULL,
    [83]                       VARCHAR (20)  NULL,
    [84]                       INT           NULL,
    [85]                       INT           NULL,
    [86]                       INT           NULL,
    [87]                       INT           NULL,
    [88]                       DATE          NULL,
    [89]                       INT           NULL,
    [90]                       VARCHAR (20)  NULL,
    [91]                       INT           NULL,
    [92]                       VARCHAR (12)  NULL,
    [93]                       VARCHAR (12)  NULL,
    [94]                       DATE          NULL,
    [95]                       INT           NULL,
    [96]                       INT           NULL,
    [97]                       DATE          NULL,
    [98]                       INT           NULL,
    [99]                       VARCHAR (20)  NULL,
    [100]                      INT           NULL,
    [101]                      VARCHAR (12)  NULL,
    [102]                      VARCHAR (12)  NULL,
    [103]                      DATE          NULL,
    [104]                      INT           NULL,
    [105]                      INT           NULL,
    [106]                      INT           NULL,
    [107]                      INT           NULL,
    [108]                      INT           NULL,
    [109]                      DATE          NULL,
    [110]                      VARCHAR (12)  NULL,
    [111]                      INT           NULL,
    [112]                      DATE          NULL,
    [113]                      VARCHAR (12)  NULL,
    [114]                      INT           NULL,
    [114.1]                    INT           NULL,
    [114.2]                    INT           NULL,
    [114.3]                    INT           NULL,
    [114.4]                    INT           NULL,
    [114.5]                    INT           NULL,
    [114.6]                    INT           NULL,
    [115]                      DATE          NULL,
    [116]                      VARCHAR (12)  NULL,
    [117]                      INT           NULL,
    [118]                      DATE          NULL,
    [119]                      VARCHAR (12)  NULL,
    [120]                      INT           NULL,
    [121]                      DATE          NULL,
    [122]                      VARCHAR (12)  NULL,
    [123]                      INT           NULL,
    [124]                      INT           NULL,
    [125]                      INT           NULL,
    [126]                      INT           NULL,
    [127]                      INT           NULL,
    [128]                      INT           NULL,
    [129]                      INT           NULL,
    [130]                      DATE          NULL,
    [131]                      DATE          NULL,
    [132]                      INT           NULL,
    [133]                      INT           NULL,
    [134]                      DATE          NULL,
    [AdicionalCAC30]           INT           NULL,
    [AdicionalCAC31]           INT           NULL,
    [AdicionalCAC1]            INT           NULL,
    [AdicionalCAC2]            INT           NULL,
    [AdicionalCAC3]            INT           NULL,
    [AdicionalCAC4]            INT           NULL,
    [AdicionalCAC14]           INT           NULL,
    [AdicionalCAC27]           INT           NULL,
    [AdicionalCAC6]            VARCHAR (5)   NULL,
    [AdicionalCAC8]            INT           NULL,
    [AdicionalCAC5]            VARCHAR (5)   NULL,
    [AdicionalCAC10]           INT           NULL,
    [AdicionalCAC35]           INT           NULL,
    [AdicionalCAC12]           INT           NULL,
    [AdicionalCAC13]           INT           NULL,
    [AdicionalCAC9]            VARCHAR (5)   NULL,
    [AdicionalODO5]            INT           NULL,
    [AdicionalCAC17]           INT           NULL,
    [AdicionalCAC19]           DATE          NULL,
    [AdicionalODO6]            INT           NULL,
    [AdicionalCAC21]           DATE          NULL,
    [AdicionalCAC7]            INT           NULL,
    [AdicionalCAC28]           INT           NULL,
    [AdicionalCAC20]           INT           NULL,
    [AdicionalCAC18]           INT           NULL,
    [AdicionalCAC26]           INT           NULL,
    [AdicionalCAC11]           VARCHAR (5)   NULL,
    [AdicionalCAC33]           INT           NULL,
    [AdicionalCAC34]           INT           NULL,
    [AdicionalODO1]            INT           NULL,
    [AdicionalCAC16]           VARCHAR (5)   NULL,
    [AdicionalODO8]            INT           NULL,
    [AdicionalCAC29]           INT           NULL,
    [AdicionalODO4]            INT           NULL,
    [AdicionalODO2]            INT           NULL,
    [AdicionalCAC32]           INT           NULL,
    [CONFIRMARESTADIO36]       BIT           NULL,
    [CONFIRMARESTADIO38]       BIT           NULL,
    [AdicionalCAC25]           CHAR (10)     NULL,
    [AdicionalODO3]            VARCHAR (5)   NULL,
    [AdicionalODO7]            VARCHAR (5)   NULL,
    [AdicionalODO9]            INT           NULL,
    [AdicionalODO10]           INT           NULL,
    [AdicionalODO11]           INT           NULL,
    [GeneroSoporteCAC]         BIT           NULL,
    [IDHCRADESQAdicionalCAC14] INT           NULL,
    [GeneroSoporteCAC2]        INT           NULL,
    [FECHACREACION]            DATETIME      NULL,
    [FECHAMODIFICACION]        DATETIME      NULL
);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Tabla que almacena los registros del formulario de seguimiento oncológico para el año 2022, vinculada a un diagnóstico (CODDIAGNO, 4 caracteres, compatible con CIE-O o CIE-10) y a una entidad/sede (IDEntidadVIE). Contiene más de 130 campos numerados que representan ítems de un formulario estructurado de registro de cáncer (HCONCOPREG), incluyendo fechas de tratamiento, órdenes de quimioterapia (IDHCORDQUIMIO) y radioterapia (IDHCRADORDEN), campos adicionales para programas CAC y ODO, y confirmación de estadio tumoral.', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'HCONCOPREG_DATOS_2022';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DescriptionSource', @value=N'ai_claude-sonnet-4-6_2026-05-05', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'HCONCOPREG_DATOS_2022';
GO
