CREATE TABLE [dbo].[homifs_imp_1] (
    [ORIGEN_INDIGO036]           VARCHAR (50) NULL,
    [FILESHARE_PRINCIPAL]        VARCHAR (50) NULL,
    [FILESHARE_BK16FEB]          VARCHAR (50) NULL,
    [TOTAL_RECUPERADOS]          VARCHAR (50) NULL,
    [PACIENTES_ADJUNTOS_13FA12M] VARCHAR (50) NULL
);

