CREATE TABLE [dbo].[INTANTIBI_HISTORICA](
	[AUTO] [int] NOT NULL,
	[ORDEN_INDIGO] [int] NOT NULL,
	[CODSERIPS] [char](20) NOT NULL,
	[NOMUESTRA] [varchar](50) NOT NULL,
	[NOMMICROR] [varchar](150) NULL,
	[NOMANTIBI] [varchar](150) NOT NULL,
	[CMI] [varchar](50) NOT NULL,
	[RESULTADO] [varchar](max) NULL,
	[NUMMUESTRA] [int] NULL,
	[IDINTERCTRL] [int] NULL,
	[MICROBIOLOGIA] [bit] NULL,
	[TIPORESULTADO] [bit] NULL,
 CONSTRAINT [PK_INTANTIBI_HISTORICA] PRIMARY KEY CLUSTERED 
(
	[AUTO] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]