CREATE TABLE [dbo].[Invoices] (
    [Id]                               INT             IDENTITY (1, 1) NOT NULL,
    [OperatingUnitId]                  INT             NOT NULL,
    [DocumentType]                     TINYINT         NOT NULL,
    [InvoiceNumber]                    NVARCHAR (MAX)  NULL,
    [RevenueControlDetailId]           INT             NULL,
    [AdmissionNumber]                  NVARCHAR (MAX)  NULL,
    [HealthAdministratorId]            INT             NULL,
    [ThirdPartyId]                     INT             NOT NULL,
    [PatientCode]                      NVARCHAR (MAX)  NULL,
    [CareGroupId]                      INT             NULL,
    [InvoiceDate]                      DATETIME        NOT NULL,
    [InvoiceExpirationDate]            DATETIME        NOT NULL,
    [TotalInvoice]                     DECIMAL (18, 2) NOT NULL,
    [CapitationInitialDate]            DATETIME        NULL,
    [CapitationEndDate]                DATETIME        NULL,
    [CapitationlPatientsAmount]        INT             NULL,
    [CapitationPatientValue]           DECIMAL (18, 2) NOT NULL,
    [ThirdPartySalesValue]             DECIMAL (18, 2) NOT NULL,
    [ThirdPartyDiscountValue]          DECIMAL (18, 2) NOT NULL,
    [ResponsibleRecoveryFee]           TINYINT         NOT NULL,
    [TotalPatientSalesPrice]           DECIMAL (18, 2) NOT NULL,
    [PatientDiscount]                  DECIMAL (18, 2) NOT NULL,
    [PatientDiscountPercentage]        DECIMAL (18, 2) NOT NULL,
    [TotalPatientWithDiscount]         DECIMAL (18, 2) NOT NULL,
    [ValueVoucher]                     DECIMAL (18, 2) NOT NULL,
    [CashReceiptId]                    INT             NULL,
    [JournalVoucherId]                 INT             NULL,
    [PatientPaidValue]                 DECIMAL (18, 2) NOT NULL,
    [ThirdPartyAccountReceivableValue] DECIMAL (18, 2) NOT NULL,
    [PatientAccountReceivableValue]    DECIMAL (18, 2) NOT NULL,
    [PatientAccountReceivableId]       INT             NULL,
    [PatientType]                      INT             NULL,
    [PatientAffiliatedType]            INT             NULL,
    [PatientPaidAbility]               INT             NULL,
    [PatientSocialClass]               NVARCHAR (MAX)  NULL,
    [CREETaxRetentionValue]            DECIMAL (18, 2) NOT NULL,
    [CREETaxRetentionBaseValue]        DECIMAL (18, 2) NOT NULL,
    [Observation]                      NVARCHAR (MAX)  NULL,
    [InvoiceCategoryId]                INT             NULL,
    [IsCutAccount]                     BIT             NOT NULL,
    [OutputDiagnosis]                  NVARCHAR (MAX)  NULL,
    [Status]                           TINYINT         NOT NULL,
    [InvoicedUser]                     NVARCHAR (MAX)  NULL,
    [InvoicedDate]                     DATETIME        NOT NULL,
    [ReversalReasonId]                 INT             NULL,
    [DescriptionReversal]              NVARCHAR (MAX)  NULL,
    [TimeStamp]                        VARBINARY (MAX) NULL,
    [OutputDate]                       DATETIME        NOT NULL,
    [InitialDate]                      DATETIME        NOT NULL,
    [CutType]                          TINYINT         NOT NULL,
    [AnnulmentUser]                    NVARCHAR (MAX)  NULL,
    [AnnulmentDate]                    DATETIME        NULL,
    [BillingAuthorizationId]           INT             NULL,
    [CUFE]                             NVARCHAR (MAX)  NULL,
    [QR]                               NVARCHAR (MAX)  NULL,
    [ContractId]                       INT             NULL,
    [InvoiceValue]                     DECIMAL (18, 2) NOT NULL,
    [ValueTax]                         DECIMAL (18, 2) NOT NULL,
    [TotalValue]                       DECIMAL (18, 2) NOT NULL,
    [CurrencyId]                       INT             NULL,
    [TRMValue]                         DECIMAL (18, 2) NULL,
    [TaxDevolutionValue]               DECIMAL (18, 2) NOT NULL,
    [ElectronicInvoiceNumber]          NVARCHAR (MAX)  NULL,
    CONSTRAINT [PK_dbo.Invoices] PRIMARY KEY CLUSTERED ([Id] ASC)
);
GO
EXEC sys.sp_addextendedproperty @name=N'MS_Description', @value=N'Tabla central de facturación en un sistema de salud que registra facturas emitidas a terceros (aseguradoras, administradoras de salud) y pacientes por servicios de atención. Almacena los valores de venta, descuentos, retenciones CREE, cuentas por cobrar diferenciadas por tercero y paciente, y datos de capitación. Soporta facturación electrónica mediante CUFE y código QR, e incluye control de estado, anulación y reversión de documentos por unidad operativa y contrato.', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'Invoices';
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DescriptionSource', @value=N'ai_claude-sonnet-4-6_2026-05-05', @level0type=N'SCHEMA', @level0name=N'dbo', @level1type=N'TABLE', @level1name=N'Invoices';
GO
